### ISSUE TITLE
full query in error report

### ISSUE THREAD

**Issue by paulstam** [mysqljs/mysql#1217]
Hi,
sometimes if a query throws an error it will be very hard to debug in production as only a part of the query is reported on. It would be very nice to also have the full query available in the error report to see where things go wrong (especially when working with placeholders to see which query you end up with)

**Comment by dougwilson** [comment]
Sorry this issue didn't get closed when we added `err.sql` (https://github.com/mysqljs/mysql#error-handling) to get the full SQL when an error occurs. This is supported now 🎉
