### ISSUE TITLE
Tracking used connections from a pool

### ISSUE THREAD

**Issue by samholmes** [mysqljs/mysql#1366]
Is there a way to track where my connections are being consumed from a pool for debugging purposes? Obviously, if one connection doesn't get released  back into the pool, then this will cause a connection leak. In order to spot these connection leaks, I need a way to track where the connections are being used  in my code base. Right now I'm rolling my own way to do this, but it doesn't work very well and I'm wondering if there's already a solution to this.

**Comment by samholmes** [comment]
Here's my own solution: https://gist.github.com/samholmes/513df4a7f0b47b409904

The `connectionLogs` can be exposed by an HTTP route for example, and it should contain the connections that haven't been released. This way if a connection hasn't been released, I can figure out from the log where the connection was pulled. However, it has issues because my logs should only show ever 10 connections at a time when a connection leak occurs, but it looks like my logs show 700+ connections.

**Comment by samholmes** [comment]
Is there an event I can hook into that will trigger when the connection is released back into the pool? This would be better than hijacking the release method.

**Comment by monken** [comment]
`pool._freeConnections` hold the available connections. Since it's not documented I wouldn't recommend using it. An event could be implemented with little effort in this function: https://github.com/felixge/node-mysql/blob/f867e85c7a349b7ab8463629c6d517fc679002bc/lib/Pool.js#L114
