### ISSUE TITLE
How to get generated SQL statement after an error?

### ISSUE THREAD

**Issue by Synchro** [mysqljs/mysql#1420]
Say I have code like this:

```javascript
db.query('INSERT INTO ?? SET ?', [table, data], function(err, inserted) {
  if(err) return callback(err);
  ...
}
```
If that throws an error, I end up with a structure like this in `err`:

```json
{
  "err": {
    "code": "WARN_DATA_TRUNCATED",
    "errno": 1265,
    "sqlState": "01000",
    "index": 0
  },
  "n": "\n",
  "stack": "Error: WARN_DATA_TRUNCATED: Data truncated for column 'mime' at row 1...
```
While it's clear what the error is, it would be helpful to get hold of the query it ran (particularly when using the `?` placeholder that can expand enormously) so it can be logged, but I can't see how to do that without changing to code where I render the query in advance. I can see that [inside the `query` method it renders the query](https://github.com/felixge/node-mysql/blob/master/lib/Connection.js#L198), but I don't see how to get at that from outside. Perhaps something like:

```javascript
if(err) {
  err.query = this.query;
  return callback(err);
}
```

**Comment by visualfanatic** [comment]
Inside your callback function you should be able to get the `this.sql` value, this is generated SQL.
https://github.com/mysqljs/mysql/blob/5372bf0896630bc683ac8a8b528468e54ddcf06c/lib/protocol/sequences/Query.js#L14

**Comment by dougwilson** [comment]
Hi @Synchro the answer gave by @visualfanatic seems right, and since there has not been a response in months, I'm going to close the issue.
