### ISSUE TITLE
how to use query result (single row or multiple row) data from node-mysql

### ISSUE THREAD

**Issue by shihabmi7** [mysqljs/mysql#1444]
I have successfully get data by performing query with node-mysql. But i cant use the query result.

My query result is

```
    {
  user_id: 'joy',
  user_name: 'joy',
  email: 'joy@gmail.com',
  socket_id: '/#glVfkRwTqKrlBETiAAAH',
  status: 1 }

```
To use this from i wrote code like :

 ```
var value= [];
    value = connection.query('SELECT * FROM socket_users WHERE email = ?',[receiver_email], function (error, results,fields) {
        // Neat!
        if (error) throw error;

        console.log(results[0]);

        if (results[0].status == 0) {


        }else {
            console.log("User is online......");
        }

        //console.log("select one user sql: "+is_Exists.sql);
    });

```
But i got errors at results[0].status line. It says

> TypeError: Cannot read property 'status' of undefined

**Comment by dougwilson** [comment]
If you are getting the error `TypeError: Cannot read property 'status' of undefined` on the line `results[0].status == 0`, that means your query returned zero results. Your code is assuming it always gets at least one row, which, from the error, looks like it not always the case. I suggest adding some code to handle when you get zero results for the query.

**Comment by shihabmi7** [comment]
thanks mate ; i got an empty results array , that's why i can't access **results[0].status**  value and getting an error.
