### ISSUE TITLE
Steam bot error on sell.js TypeError: Cannot read property 'ban' of undefined

### ISSUE THREAD

**Issue by DanteSparda3556** [mysqljs/mysql#1446]
```
handshake complete
Logged in!
[SERVER] Trade offer incoming
/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Cannot read property 'ban' of undefined
    at Query._callback (/var/www/bot/sell.js:589:21)
    at Query.Sequence.end (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:85:24)
    at Query._handleFinalResultPacket (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/var/www/bot/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/var/www/bot/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/var/www/bot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/var/www/bot/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
```
In line 589 have :

								var ban;
								mysqlConnection.query('SELECT ban FROM `users` WHERE `steamid`=\''+offer.steamid_other+'\'', function(err, row, fields)
								{
								-> Line 589	ban= row[0].ban;
									if(ban==1)
									{
										offers.declineOffer({tradeOfferId: offer.tradeofferid});
										offer.items_to_receive = [];
										mysqlConnection.query('INSERT INTO `messages` (`userid`,`msg`,`from`, `win`, `system`, `time`) VALUES (\''+offer.steamid_other+'\',\'You are banned.\',\'System\', \'0\', \'1\', \''+unixtime+'\')', function(err, row, fields) {});
										console.log('[SERVER] Declined offer #'+offer.tradeofferid+' - Sent by: '+offer.steamid_other+' - Reason: User is banned');
										
										return;
									}

**Comment by DanteSparda3556** [comment]
Resolve this problem what should I change this line?

**Comment by dougwilson** [comment]
Hi @DanteSparda3556, this error is not related to this module, rather you have an error in your file `/var/www/bot/sell.js` on line 589, where you have an undefined variable and are trying to access the `ban` property on it.

I see in your code piece, that you are not handling the `err` object, which you need to do. You also assume that there is at least one row. This means that you have to do two things to fix this:

1. Handle the `err` in some fashion.
2. Handle the case if you don't have result rows.

**Comment by DanteSparda3556** [comment]
var ban;
								mysqlConnection.query('SELECT ban FROM `users` WHERE `steamid`=\''+offer.steamid_other+'\'', function(err, row, fields)
								{
									ban= row[0].ban;
									if(ban==1)
									{
										offers.declineOffer({tradeOfferId: offer.tradeofferid});
										offer.items_to_receive = [];
										mysqlConnection.query('INSERT INTO `messages` (`userid`,`msg`,`from`, `win`, `system`, `time`) VALUES (\''+offer.steamid_other+'\',\'You are banned.\',\'System\', \'0\', \'1\', \''+unixtime+'\')', function(err, row, fields) {});
										console.log('[SERVER] Declined offer #'+offer.tradeofferid+' - Sent by: '+offer.steamid_other+' - Reason: User is banned');
										
										return;
									}

Arrume este codigo para mim porfavor
