### ISSUE TITLE
Man fix this code to my plsss

### ISSUE THREAD

**Issue by DanteSparda3556** [mysqljs/mysql#1447]
var ban;
                            mysqlConnection.query('SELECT ban FROM `users` WHERE `steamid`=\''+offer.steamid_other+'\'', function(err, row, fields)
                            {
                                ban= row[0].ban;
                                if(ban==1)
                                {
                                    offers.declineOffer({tradeOfferId: offer.tradeofferid});
                                    offer.items_to_receive = [];
                                    mysqlConnection.query('INSERT INTO `messages` (`userid`,`msg`,`from`, `win`, `system`, `time`) VALUES (\''+offer.steamid_other+'\',\'You are banned.\',\'System\', \'0\', \'1\', \''+unixtime+'\')', function(err, row, fields) {});
                                    console.log('[SERVER] Declined offer #'+offer.tradeofferid+' - Sent by: '+offer.steamid_other+' - Reason: User is banned');

                                    return;
                                }

**Comment by dougwilson** [comment]
@DanteSparda3556 it is impossible to fix your code without the full context. How to handle errors or what to do when there are no result rows would have to be decided by someone who knows the full context, use cases, and more of your server, which I do not know. Please stop spamming this issue board.
