### ISSUE TITLE
How to escape table schemas?

### ISSUE THREAD

**Issue by surerob-rob-mullins** [mysqljs/mysql#1455]
I've ran into an issue when I attempt to escape a table schema, in that the escape feature is invalidating the schema text.

Specifically the escape feature places single quotes around the schema text like so:
```CREATE TABLE IF NOT EXISTS `shipments` ('id INT(7), product_id INT(7), order_address_id INT(7), data LONGTEXT, date INT(10)')```

Where the original statement might look like either:
`var sql = 'CREATE TABLE IF NOT EXISTS  ' +connection.escape(table_name) +' (' +connection.escape(table_schema) +')';`
OR
`connection.query('CREATE TABLE IF NOT EXISTS ?? (?)', [table_name, table_schema], function(err, res) { ... });`

So the way to work around this would be to separately escape the table_schema, and then perform a `string.replace()` to remove the single quotes. 

However I wanted to see if perhaps I am going about this the wrong way, or we can implement support for escaping table schemas. Thanks in advance!

**Comment by dougwilson** [comment]
Hi! I believe you misunderstand the purpose of escaping. DDL, DML, and other actual SQL needs to be literal, you cannot escape it, as that does not make sense. What escaping does is take a value and allows you to use it where a value belongs.

**Comment by surerob-rob-mullins** [comment]
Hi, thanks for the response. Not sure I understand though, as my understanding of escaping might be similar to what `mysql_real_escape_string()` would do in PHP.

**Comment by dougwilson** [comment]
Hi @surerob-rob-mullins, no, it is not quite the same as `mysql_real_escape_string`, and even then, your example cannot be used with `mysql_real_escape_string` for any actual purpose--the only reason it would even work with `mysql_real_escape_string` is that it is not actually performing any escaping (only returning the input string). As soon as your input caused `mysql_real_escape_string` to actually escape something, you'd have a SQL error in your examples.
