### ISSUE TITLE
Use of node-mysql with generators

### ISSUE THREAD

**Issue by TomBZombie** [mysqljs/mysql#1463]
Would it be possible for `connection.query()` to also return the resultset? This should allow the following code to work:

```php

function getResults*() {
yield connection.query('SELECT * FROM user', []);
}

var results = getResults().next().value();
```

At the moment, it's impossible (please correct me if I'm wrong!) to use generators to prevent chaining of callbacks.

**Comment by dougwilson** [comment]
Use a wrapper. This is a low-level module that just gives you the basics. Besides, we already return a value.
