### ISSUE TITLE
Using mysql and Meteor Session

### ISSUE THREAD

**Issue by acefxlabs** [mysqljs/mysql#1466]
Hello 
I am using Meteor with Mysqljs and have been able to achieve quite a number of things which i am gonna write a tutorial on. 
The issue i am having is I want to be able to keep user session, if user logs in, I want to create a session that is not MongoDB dependent and use it both on client and server side.
Please any idea on how to achieve this

Thanks

**Comment by dougwilson** [comment]
Hi @acefxlabs, I'm not sure this is the most appropriate forum for your question, as the audience here is unlikely to be able to help. Generally this is an issue tracker for the `mysql` module, as in if you're having a specific issue, bug, or providing an enhancement, then it's going to be a wash if someone is going to be able to assist.

In this case, I have never used MongoDB or Meteor, and really have no idea. Your question, in the general sense, does not have a simple answer and could be a project in itself. I suggest probably going to Stackoverflow.com and asked over there.
