### ISSUE TITLE
Mysql insert statement with functions

### ISSUE THREAD

**Issue by ashishkhanna** [mysqljs/mysql#1470]
Can you please help me to generate mentioned below insert statement in node syntax , I want to use md5 while inserting into database
insert into `user`(`user_id`,`username`,`password`) values ( NULL,'f',**md5('t')**).

connection.query('INSERT INTO user SET ?', user, function(err, result) {}

**Comment by uribes78** [comment]
I recommend to set the query string before, something like:

```javascript
var query = 'INSERT INTO user SET password=MD5(?), ?';
connection.query(query, ['supersecret', user], function (err, result) {});
```
where 'user' can be a json object without password key, to avoid error
hope this can help you!

**Comment by dougwilson** [comment]
Hi @ashishkhanna , I hope @uribes78 was able to help you :) If you are looking for a library that provides advanced SQL constructing, a good one is the https://hiddentao.com/squel/ library.

**Comment by ashishkhanna** [comment]
Thanks a ton for your help

Thanks & regards,

Ashish Khanna
