### ISSUE TITLE
npm quick start documentation missing require("mysql")

### ISSUE THREAD

**Issue by 1mike12** [mysqljs/mysql#1472]
This is probably really obvious to a lot of people, but I think if someone comes alone and copies the Usage word for word, it should run. 

right under "And in your code..." maybe add the `require("mysql")` ?

**Comment by dougwilson** [comment]
Hi @1mike12, can you point to where you are referring to? I can't find the string "And in your code" any where within our README. We also have no section called "Usage".

**Comment by 1mike12** [comment]
I don't even remember what I was refering to either :) Maybe it got fixed or I was very confused. Either way looks like the documentation is totally fine.
