### ISSUE TITLE
Cannot perform a bulk update

### ISSUE THREAD

**Issue by wecodeingit** [mysqljs/mysql#1475]
May be this can be an enhancement, just like bulk insert, if bulk update can be implemented, it would be really helpful.

**Comment by dougwilson** [comment]
As far as I know, there is no such thing as a bulk update in MySQL.

**Comment by dougwilson** [comment]
Hi @wecodeingit I'm going to close this issue since I don't think there is such a ting and there's been no reply to state otherwise.
