### ISSUE TITLE
mysql connection does not require connection closing

### ISSUE THREAD

**Issue by piyushsf** [mysqljs/mysql#1476]
I am using in mysql npm in two projects. In one project, it requires me to release connection after using it. And in another project, if I put `connection.release()` in code, then it says connection already released. I am not able to understand this different behavior. 

P.S I am using mysql pooling.

Any help would be appreciated.

**Comment by dougwilson** [comment]
Hi @piyushsf , the error connection already released means that you're accidentally calling `.release()` more than once on the same connection. This is typically due to a logic error in the code path. Would you be able to show the code you wrote that is having the issue?

**Comment by dougwilson** [comment]
Hi @piyushsf I'm going to close this issue since I haven't heard anything back.
