### ISSUE TITLE
OkPacket parse fieldCount first?

### ISSUE THREAD

**Issue by daleoooo** [mysqljs/mysql#1479]
In [mysql document](https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html), there is no field count definition, but [OkPacket](https://github.com/mysqljs/mysql/blob/1aa486e6e0dd6938569949509de6fe66433cc228/lib/protocol/packets/OkPacket.js#L15) parse the fieldCount in the first, this is wired, can you give the reason about that? 

thanks

**Comment by sidorares** [comment]
field count is part of Resultset packet

https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response

> The query-response packet is a meta packet which can be one of
- a ERR_Packet
- a OK_Packet
- a Protocol::LOCAL_INFILE_Request
- a ProtocolText::Resultset

**Comment by dougwilson** [comment]
The JS property is named incorrectly; it should be `header`, not `fieldCount`. Not sure if we can really change that at this point (and we don't use it, so it really doesn't even matter).

**Comment by daleoooo** [comment]
Thanks, @sidorares @dougwilson, I found insert ... on duplicate return 1 rows effect if set a row to its current values. I think this is wired, so I search it and found this:

With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values. If you specify the CLIENT_FOUND_ROWS flag to mysql_real_connect() when connecting to mysqld, the affected-rows value is 1 (not 0) if an existing row is set to its current values.

so, I must set CLIENT_FOUND_ROWS in some where.

**Comment by daleoooo** [comment]
I have found CLIENT_FOUND_ROWS is the default connection flag, document [here](https://github.com/mysqljs/mysql#connection-flags).
