### ISSUE TITLE
Support for null values in where clauses?

### ISSUE THREAD

**Issue by macias** [mysqljs/mysql#1483]
Once again thank you for excellent library :-).

Would it be possible to add support for null values for where clauses? Maybe something like this:

`... "where a == ? AND b == ?", [a,b] ...`

Since there is no such operator as `==` in SQL it could be safely used. The effect would be for regular values as writing `= ?`, but if the data provided is NULL it would be translated to `IS NULL`.

**Comment by dougwilson** [comment]
Hi @macias, the replacement `?` we provide is very basic, akin to actual SQL prepared statement, which wouldn't do that, either. You may want to consider using a more full-featured module like https://hiddentao.com/squel/

I'm not sure if that particular module does what you are looking for, but it is the kind of full-featured SQL generator that would add something like that :)
