### ISSUE TITLE
Bigint is Rounded

### ISSUE THREAD

**Issue by Lolums** [mysqljs/mysql#1487]
When I try to select a BIGINT value in Node, it is truncated to a lower precision.

207570943474794506 may become 207570943474794500, for example.

This is due to javascript's number precision.

Do var a = 207570943474794506;
Then check the value of a. You'll get back 207570943474794500.

However, one should still be able to select BIGINTs.

One fix for this would be to return BIGINT values as strings. Please do this!

**Comment by AdriVanHoudt** [comment]
see the `supportBigNumbers` option under https://github.com/mysqljs/mysql#connection-options

**Comment by dougwilson** [comment]
I'm going to close this, and @AdriVanHoudt answered it and there hasn't been any other comments :)

**Comment by dougwilson** [comment]
And for people coming by, here is the excerpt from the README:

> bigNumberStrings: Enabling both supportBigNumbers and bigNumberStrings forces big numbers (BIGINT and DECIMAL columns) to be always returned as JavaScript String objects (Default: false). Enabling supportBigNumbers but leaving bigNumberStrings disabled will return big numbers as String objects only when they cannot be accurately represented with JavaScript Number objects (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects. This option is ignored if supportBigNumbers is disabled.
