### ISSUE TITLE
Database won`t get connection from pool after some time

### ISSUE THREAD

**Issue by Rellfy** [mysqljs/mysql#1488]
Hello

I have always been using this module with no problems, until this new project I started to develop. After a few minutes/connections made, I've noticed that `database.getConnection()` just won't be executed (not executed at all, so I can't check for errors) and because of this I can't debug it. I really don't feel like it's my code the problem, since it executes with no problem before a few connections are made to the database. I have checked if I was releasing all the connections to the pool after executing queries, and apparently I was, so this might not be the problem...

Has anyone else came across the same problem?

**Comment by dougwilson** [comment]
Hi @Rellfy, I'm not sure why I didn't get an email when you opened this issue, but I did get an email when you closed it. Did you get your issue resolved?

Reading through it, my first thought is that that only occurs if you are not releasing every connection back to the pool on accident or there is a bug somewhere in our code. I just spent a bit poking at it, but didn't find a bug. Can you provide the version of Node.js, the version of this module, and code that reproduces the issue?

**Comment by Rellfy** [comment]
Hello Douglas!

First of all, thanks for the reply.

I think it was indeed the fact that I wasn't returning the connection in
some parts of the code (I guess I can blame "callback hell", or actually
blame myself and organize the code lol), but now it seems to be fixed.
Thanks! :)
