### ISSUE TITLE
Unable to execute database query-Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by nirmalgoswami** [mysqljs/mysql#1491]
Hello,

I know this error is reported so many time here but none of them are working for me.

here its my code

`database.js`

```
var mysql      = require('mysql');

var connection = mysql.createConnection({
    host     : 'hostname',
    user     : 'user',
    password : 'password',
    database : 'dbname',
    dateStrings :true
});
connection.connect(function(err) {

    if (err) {
        console.error('error connecting: ' + err.stack);
    }
    console.log('connected as id ' + connection.threadId);

});
module.exports = connection;
```

`main.js`

```
'use strict';
var connection = require("../lib/database.js");
var lib = require("../lib");


module.exports.handler = function (event, context) {

  try {
   
    var q = "query here " ;
    connection.query(q, function (err, rows) {
....
....
```
Problem is i am getting following error sometime
`unable to execute database query-Error: Cannot enqueue Query after fatal error.` 

`Possible Answer`
1. Use pool but i dont think it will solve.
2. Remove `connection.connect` but i dont think it will solve.

i am giving you possible answer because i want to show what is in my mind :)

I am using `V2.10.2` of this module and `v6.3.0` of node

Thank you,
Nirmal Goswami

**Comment by dougwilson** [comment]
Hi @nirmalgoswami, please see the conversation / responses in #1492
