### ISSUE TITLE
Connection acquired always success although input wrong value

### ISSUE THREAD

**Issue by SanhNX** [mysqljs/mysql#1495]
I have api to update todo list through "PUT" Method as below:

```js
var connection = require('../connection');
connection.acquire(function(err, con) {
      con.query('update todo_list set ? where id = ?', [todo, todo.id], function(err, result) {
        con.release();
        if (err) {
          res.send({status: 1, message: 'TODO update failed'});
        } else {
          res.send({status: 0, message: 'TODO updated successfully'});
        }
      });
    });
```

But when i am trying to call this API through Postman and assign one value does not exist in the db(Ex: id= 100000). My result always return success without error.

Please help me resolve this issue. Thank you so much

**Comment by sidorares** [comment]
you not getting error because `update todo_list set (...) where id = 100000` is valid sql. Check `result.affectedRows` if you need to know if there was a match for that id

**Comment by SanhNX** [comment]
Thank @sidorares , It work well.
