### ISSUE TITLE
How to handle access token for each "GET "request to prevent hacker use direct link to fetch data.

### ISSUE THREAD

**Issue by SanhNX** [mysqljs/mysql#1497]
How to handle access token for each "GET" request to prevent hacker use direct link to fetch data.
it mean that you can not enter directly into the browser API to get information, you must get access token through first, then transfer that value to execute query commands.

**Comment by dougwilson** [comment]
Hi @SanhNX, I'm sorry you may have asked in the wrong repository. This is a MySQL driver, and doesn't have any mechanism to interact with HTTP. You may want to post a question against whatever HTTP server you are using if you're not sure how to do that.
