### ISSUE TITLE
Remote host closed connection during handshake

### ISSUE THREAD

**Issue by nirmalgoswami** [mysqljs/mysql#1500]
Hello,

I am using [jmeter](http://jmeter.apache.org/) to test api.i am getting expected result till low users i.e. `100` but when i set `500` or `1000` user than i am getting following error in some call not all.

`Remote host closed connection during handshake`

**Comment by sidorares** [comment]
Hi @nirmalgoswami ! Are you using pool? Whats your pool connection limit and mysql server [max_connections](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_max_connections) settings?

**Comment by nirmalgoswami** [comment]
@sidorares Yes i am using pool and i did not set any limit and max_connections.i am using default value.

**Comment by sidorares** [comment]
It's usually very easy to hit default limit ( I think it's 100 ) but I would expect different error ( server rejects handshake and closes connection, but error should be like "Max number of connections reached" ). Try to set your pool [connectionLimit](https://github.com/mysqljs/mysql#pool-options) to some low value ( say, 20 ) and see if error persist

**Comment by dougwilson** [comment]
Hi @nirmalgoswami, do you have any further information? I'm not quite sure if there is anything this module can do, and you didn't provide enough information for us to really understand what is happening to be able to look into the issue ourselves.

**Comment by nirmalgoswami** [comment]
hello,thanks for reply.i have tested my apis without use of this module i.e. mysql and still i am getting that error with more call/per second so that means issue is not related to this module but it is related to the network connection and my sever is not handling more traffic.so i am closing this.
