### ISSUE TITLE
Binary row stream? (Buffer objects)

### ISSUE THREAD

**Issue by Simran-B** [mysqljs/mysql#1503]
Is it possible to avoid processing the raw MySQL protocol packets and just hand the content over as Buffers? My assumption is that if I want to forward the data via a binary protocol anyway, then converting back and forth is unnecessary and could be a bottleneck.

**Comment by dougwilson** [comment]
HI @Simran-B, no, it's not possible to do that currently with this module, and I've never really thought about it before. It would be interesting to hear your thoughts on what we could do to support this feature.

**Comment by sidorares** [comment]
@Simran-B which parts of this library would you use? De-framing parser ( raw data chunks -> [mysql header + raw payload] ) ?

**Comment by dougwilson** [comment]
Hi @Simran-B I hope it's OK if I close this issue. Without more information, it's hard to know where we should even start on this.
