### ISSUE TITLE
Connection Uri String giving a URI malformed error if password contains %

### ISSUE THREAD

**Issue by saswatds** [mysqljs/mysql#1513]
``url.js:275
      this.auth = decodeURIComponent(rest.slice(0, atSign));
                  ^

URIError: URI malformed
    at decodeURIComponent (native)
    at Url.parse (url.js:275:19)
    at urlParse _(url.js:81:5)___``

**Comment by sidorares** [comment]
@saswatds if you build your URI manually you should use `encodeURIComponent` on password value:

```
> encodeURIComponent("%@^4")
'%25%40%5E4
```

**Comment by dougwilson** [comment]
Because in URI, the % character is the start of an escape sequence. You need to escape characters in URI that are not allowed. For example, a literal % needs to be %25 in the URI
