### ISSUE TITLE
TypeError: mysql.createConnection is not a function

### ISSUE THREAD

**Issue by aznaLee** [mysqljs/mysql#1514]
please help this error... 

this is my code
![image](https://cloud.githubusercontent.com/assets/22021011/18263752/2ed399ca-7447-11e6-80a8-0ca90b837d0d.png)

this is my error
![image](https://cloud.githubusercontent.com/assets/22021011/18263764/3fe7d6a4-7447-11e6-9c5e-97fc078b197f.png)

this is my project window
![image](https://cloud.githubusercontent.com/assets/22021011/18263774/4e7d3f10-7447-11e6-948c-188784de8dad.png)

**Comment by sidorares** [comment]
could you paste the above code as text @aznaLee ?

**Comment by dougwilson** [comment]
The project window screenshot doesn't look right, as the `mysql` folder should have an `index.js` file in it. I wonder if the installation is corrupted? Can you paste the output of `npm ls` from that project directory as well?

**Comment by aznaLee** [comment]
@dougwilson  mysql folder have an index.js ... i try paste the output of npm ls project directory, no problem..

@sidorares hmm...?

**Comment by sidorares** [comment]
@aznaLee first picture - could you copy/paste this text as text, not image?

**Comment by aznaLee** [comment]
@sidorares ah.. 

var mysql = require('mysql');
var connection = mysql.createConnection({
	host : '127.0.0.1',
	user : 'root',
	password : 'mysql'
});

connection.connect();

connection.query('SELECT "Hello World"', function(err, results, fields){
	if(err)
	{
		throw err;
	}
	
	console.log(results);
	console.log(fields);
});

connection.end();

like this?

**Comment by sidorares** [comment]
yes. just wanted to check if you have any special chars in `createConnection`

**Comment by dougwilson** [comment]
In your screenshot, the mysql folder looks very wrong; it does nit have an index.js file, it is missing the Changes.md file, and there should not be a test folder.

**Comment by dougwilson** [comment]
I'm closing this issue since we gave a couple suggestions but haven't heard back in 20 days so far. Let us know if you're still having issues and we can re-open the issue :)

**Comment by gullman99** [comment]
I have this issue
