### ISSUE TITLE
unexpected error when idle

### ISSUE THREAD

**Issue by superhero** [mysqljs/mysql#1515]
Ran a long job, 8h in to it, it through an error... what I think is strange is that I only made 1 sql query. So I don't know if I misunderstood something, but to me that seems very strange that the mysql module would through an error at all. After the result has been returned I expected the mysql module to stay quite. How could I catch this exception?

**`app/main`**
```
require('app/wrapper/mysql')((error, connection) => // see below for file content
{
  if (error)
    throw error;

  connection.query(query, (error, rows) =>
  {
    if (error)
      throw error;

    // bunch of logic, none mysql related, just looping through the result `rows`
```

**`app/wrapper/mysql`**
```
'use strict';

const connection = require('mysql').createConnection(
{
  host     : '...',
  user     : '...',
  password : '...',
  database : '...'
});

module.exports = callback =>
  connection.state == 'connected'
  ? callback(null, connection)
  : connection.connect(error => callback(error, connection));
```

**`output`**
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/opt/bot/node_modules/mysql/lib/protocol/Protocol.js:109:13)
    at Socket.<anonymous> (/opt/bot/node_modules/mysql/lib/Connection.js:115:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm info lifecycle credit-limit-bot@1.0.0~start: Failed to exec start script
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! credit-limit-bot@1.0.0 start: `npm install && npm update && node node_modules/app/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the credit-limit-bot@1.0.0 start script 'npm install && npm update && node node_modules/app/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the credit-limit-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm update && node node_modules/app/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs credit-limit-bot
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls credit-limit-bot
npm ERR! There is likely additional logging output above.
```

**Comment by sidorares** [comment]
> How could I catch this exception?

you need to listen for `error` events on connection object:

```js
connection.on('error', function(err) {
  // ...
});
```
note that there is no way to "re-connect" after error - you have to create new connection. For long running process it probably makes sense to use built-in connection pool, it'll manage all this for you.

**Comment by superhero** [comment]
@sidorares ty for fast response. As you can see in my code, the rows are already returned. So I don't see why an exception is even disrupting the process. After a new query or connection is requested I would understand if there would be an exception though.

To prevent this behavior, if I understand you correctly, I could write re-write my wrapper like so?:

```
'use strict';

const connection = require('mysql').createConnection(
{
  host     : '...',
  user     : '...',
  password : '...',
  database : '...'
});

// preventing system crash when the connection is droped
connection.on('error', error =>  console.log(error));

module.exports = callback =>
  connection.state == 'connected'
  ? callback(null, connection)
  : connection.connect(error => callback(error, connection));
```

**Comment by sidorares** [comment]
The server forcibly disconnected tcp socket due to inactivity. Client re-emits network error and if there is no listener it crashes process ( `error` events are special in that regard and cannot be ignored ).

**Comment by superhero** [comment]
@sidorares Again thank you, but I'm a bit confused. Is it possible to overwrite that error listener that throws an error as suggested above? or do I need to do something else to prevent this crash.

**Comment by sidorares** [comment]
no, connect callback only gives you connect time errors. Your query callback gives you query errors. What happens in between ( you are not sending any command but remote server closed connection is only available as connection `error` event.

If you want to wrap all this in a single call and export from module - do something like this:

```js
module.exports = (connectParams, onError) => {
   const connection = require('mysql').createConnection(connectParams);
   connection.on('error', onError);
   return connection;
}
```

Alternatively just use pool:

```js
module.exports = (connectParams) => {
   const pool = require('mysql').createPool(connectParams);
   return pool;
}
```

`pool.query('select 1+1', callback)` - when server kills connection due to idle inactivity pool automatically removes it from list of "good" connection, next time you do query it gives you one of idle good connections or creates new if all connections busy

**Comment by sidorares** [comment]
no, connect callback only gives you connect time errors. Your query callback gives you query errors. What happens in between ( you are not sending any command but remote server closed connection is only available as connection `error` event.

If you want to wrap all this in a single call and export from module - do something like this:

```js
module.exports = (connectParams, onError) => {
   const connection = require('mysql').createConnection(connectParams);
   connection.on('error', onError);
   return connection;
}
```

Alternatively just use pool:

```js
module.exports = (connectParams) => {
   const pool = require('mysql').createPool(connectParams);
   return pool;
}
```

`pool.query('select 1+1', callback)` - when server kills connection due to idle inactivity pool automatically removes it from list of "good" connection, next time you do query it gives you one of idle good connections or creates new if all connections busy
