### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by plouc** [mysqljs/mysql#1516]
Hi,

I'm playing with streams and MySQL, I have a script which run a query, stream it to multiple transforms and finally exit.

My problem is that if an error happens in one of the transform streams, I want to be able to close the created readable stream and release the connection, (I think it's the `localStream` in `Query.prototype._sendLocalDataFile`), but I didn't figured out how to achieve this.

When the error is emitted, the underlying stream get unpiped and the connection stay active, so I cannot exit the program, I've tried to call `pool.end()` but it didn't changed anything.

Perhaps there's something I have missed or my approach is wrong, if you have any advice, I'll be very grateful (even if you don't in fact, thanks a lot for this lib :)).

**Comment by plouc** [comment]
Unpiping the stream and re-piping it to a PassThrough fixed my problem, but perhaps there's another approach.

**Comment by ZJONSSON** [comment]
Is the error happening in your own transforms or the mysql internals?

Errors do not propagage in node stream `.pipe` pipeline so you might need to include `.on('error', () => connection.close())` after each custom transform that might error.

**Comment by plouc** [comment]
@ZJONSSON, thank you for your feedback.

I'm aware of this, I have a small helper which propagate the error on the last transform which handle the error event:

``` javascript
const fwd = (source, ...destinations) => {
    const last  = destinations[destinations.length - 1];
    let current = source;
    destinations.forEach(dest => {
        current.on('error', last.emit.bind(last, 'error'));
        current = current.pipe(dest);
    });
    return current;
};
```

The project I'm working on also use Knex, which makes impossible to get the specific connection when using a pool, that why I tried `pool.end()` in the first place.

**Comment by ZJONSSON** [comment]
Sound good - I use a small helper myself to propagate errors in those situations https://www.npmjs.com/package/streamz from within the pipeline.  It also allows me to end a pipeline with `.promise().then( successFn, errorFn)`

**Comment by plouc** [comment]
Interesting, I have something similar for concurrency, a simple transform with an internal buffer and the usage of `Promise.all()` to provide concurrency, after it push resolved promise results.

``` javascript
/**
 * Takes items from buffer and promisify them, clear the current buffer,
 * and push data for each resolved promise.
 *
 * @private
 * @param {Function} callback - The transform callback
 * @returns {void}
 */
processBuffer(callback) {
    let promises;

    // used to skip pushing for rejected promises,
    // only apply when loose mode is true
    const rejectedIndices = [];

    if (this.options.looseMode === true) {
        // Ensure we're dealing with a Promise, Promise.all does this automatically,
        // but we want to catch error for each promise to be able to partially
        // process chunks, instead of the `all or nothing` behaviour of Promise.all
        promises = this.buffer.map((chunk, index) => {
            return Promise.resolve(this.promiseFn(chunk))
                .catch(err => {
                    rejectedIndices.push(index);
                    this.emit('error', err);
                })
            ;
        });
    } else {
        promises = this.buffer.map(this.promiseFn);
    }

    Promise.all(promises).then(values => {
        values
            .filter((v, index) => !rejectedIndices.includes(index))
            .forEach(this.push.bind(this))
        ;
    })
        .catch(err => {
            this.emit('error', err);
        })
        .then(() => {
            callback();
        })
    ;

    this.buffer = [];
}
```

**Comment by ZJONSSON** [comment]
Yeah it seems the objectives are very similar. One reason for my approach is that I wanted to be able to create super-simple pipelines where the components where self-contained but provided full error propagation such as https://github.com/ZJONSSON/node-etl

**Comment by AlexandreAWE** [comment]
Mysql driver, you right. I just point that is not clear in TypeORM documentation that event name for retrieve data is called "result" and not "data".
eg: http://typeorm.io/#/select-query-builder/streaming-result-data
