### ISSUE TITLE
Pooling - Too many connections error

### ISSUE THREAD

**Issue by glavince** [mysqljs/mysql#1518]
hey everyone,

When I use pool, I am getting "To many connections" error after connections reach the MySql server maximum connections limit. Currently the limit is 150. I don't have issues when I use "mysql.createConnection" and use "connection.end()" after query execution, but I have when use "mysql.createPool" and "mysql.createPoolCluster" with "connection.release()".

This code works without problems:
```js
function execute(mysql_server, sql, params, cb) {
  var connection = mysql.createConnection({
    host            : mysql_server.host,
    user            : mysql_server.user,
    password        : mysql_server.password,
    database        : mysql_server.database
  });
  connection.query(sql, params, function(err, rows, fields) {
    if(err) console.log(err);
    connection.end();
    cb(err, rows, fields);
  });
}
```
This code returns error when the server reach the max connections limit (150) even if "connectionLimit" is set to 20.
```js
function execute(mysql_server, sql, params, cb) {
  var pool  = mysql.createPool({
    connectionLimit : 20,
    host            : mysql_server.host,
    user            : mysql_server.user,
    password        : mysql_server.password,
    database        : mysql_server.database
  });
  pool.getConnection(function(err, connection) {
    if(err) console.log(err);
    connection.query(sql, params, function(err, rows, fields) {
      if(err) console.log(err);
      connection.release();
      cb(err, rows, fields);
    });
  });
}
```
Same thing here:
```js
function execute(mysql_server, sql, params, cb) {
  var poolCluster = mysql.createPoolCluster({
    connectionLimit : 20
  });
  poolCluster.add('master', config.mysql_master);
  poolCluster.add('slaveAdmin', config.mysql_slave_admin);
  poolCluster.add('slave1', config.mysql_slave_1);
  poolCluster.getConnection(server, function (err, connection) {
    if(err) console.log(err)
    connection.query(sql, params, function(err, rows, fields) {
      if(err) console.log(err)
      connection.release();
      cb(err, rows, fields);
    });
  });
}
```

thanks!!!

**Comment by sidorares** [comment]
@glavince  ( I added fence blocks for you - you can just use "\`\`\`js" at start and triple "`" at end )

is this the only process connecting to db? With `connectionLimit` there should be no more than 20 connections

**Comment by dougwilson** [comment]
Taking a look as well, are you calling execute function for every SQL? That would mean you are actually making an entire pool every time you perform a query. A pool is meant to be re-used. A fix for you could be as simple as moving the

    var pool  = mysql.createPool

Outside of your exectute function (though you would have to refactor how that server variable would work).

**Comment by glavince** [comment]
Yeah, that was the issue. I was calling mysql.createPool on each query.
Thank you very much for your EXPRESS replay with solution!!!

**Comment by dougwilson** [comment]
Awesome, glad that was the issue, @glavince ! Feel free to open new issues here if you have anything else :)
