### ISSUE TITLE
Question, timeout when pause stream

### ISSUE THREAD

**Issue by uribes78** [mysqljs/mysql#1520]
Hi, I'm working on a process that must use the stream feature, but on every result I need to process an extra process, those extra process can take a long time, 3 to 5 mins aprox.

This is my code:
```javascript
		this.myPool.getConnection(function (err, cnn) {
			if (err) {
				self.log && self.log.error("Getting connection to process items.", err);
				mainCallback(false);
			} else {
				var result = cnn.query("SELECT * FROM importer;"), cnf = null, totalItems = 0;

				result.on('result', function (result) {
					if (result.item) {
						totalItems++;
						cnn.pause(); 

						try {
							cnf = JSON.parse(result.json);

							doItem(result.item, cnf, function (err, rt) {
								if (err)
									self.log && self.log.error("For '%s' failed execution.", result.item, err.message || err);
								else {
									rt.total && self.log && self.log.debug("%s data", result.item, rt);
								}
								cnn.resume();
							});
						} catch (e) {
							self.log && self.warn("Item '%s' has incorrect configuration.", result.item, e);
							cnn.resume();
						}
					}
				}).on('error', function (err) {
					self.log && self.log.error("MySQL items query.", err);
				}).on('end', function () {
					if (cnn) cnn.destroy();
					self.log && self.log.info("%d item(s) found to process.", totalItems);
					mainCallback( (totalItems !== 0) );
				});
			}
		});
```

Is it possible to keep a connection paused that long time without not loosing the connection? or I should look for a different method to achieve my needs?

Thanks any way to read.

**Comment by ZJONSSON** [comment]
Have you tried the [streams2](https://github.com/mysqljs/mysql#piping-results-with-streams2) functionality of the mysql package yet?  It uses the built-in backpressure management of node streams to pause and resume when buffers get full ([detail](https://github.com/mysqljs/mysql/blob/5372bf0896630bc683ac8a8b528468e54ddcf06c/lib/protocol/sequences/Query.js#L188-L224)).  Your code would look something like this:

```js
    cnn.query("SELECT * FROM importer;")
      .stream({highWaterMark:10})  // buffer up to 10 records
      .pipe(require('Stream'),Transform({
        transform: function(result,encoding,cb) {
          var cnf = JSON.parse(result.json);

          doItem(result.item, cnf, function (err, rt) {
            if (err)
              self.log && self.log.error("For '%s' failed execution.", result.item, err.message || err);
            else {
              rt.total && self.log && self.log.debug("%s data", result.item, rt);
            }
            cnn.resume();
          });
        } catch (e) {
          self.log && self.warn("Item '%s' has incorrect configuration.", result.item, e);
          cnn.resume();
        }
      });
```

A standard stream will only process one record at a time and the output order will reflect the input order.  If order doesn't matter and `doItem` is async you can multiply throughput by using userland streams that allow concurrency, such as [streamz](https://github.com/ZJONSSON/streamz) .

**Comment by uribes78** [comment]
@ZJONSSON thanks for the advice, I will try the stream2. Thanks a lot
