### ISSUE TITLE
ER_CON_COUNT_ERROR: Too many connections

### ISSUE THREAD

**Issue by Rellfy** [mysqljs/mysql#1521]
Hi, I have been using this module for a long time, and it works pretty well. However, I have been coming across a problem recently, this "ER_CON_COUNT_ERROR: Too many connections". 

I am using pool to create/release connections, and I have already changed the limits to about 10.000 (on the module and mysql server). I had a problem with not releasing connections before, so I think that's not the issue here (but still, might be, I have no idea what's causing this). But everytime I access my app (it has to make mysql connections) and I execute the MySQL query `show status where 'variable_name' = 'Threads_connected';` I can notice that the value increases by 1 every time I reload the page, and it might keep increasing till it reaches the limit (10k) and returns the error. But, is it normal for this value to keep increasing? Shouldn`t it decrease after when the connection is released?

When I turn the node server off, the number of threads connected go back to 1. Has anyone experienced anything simillar?

**Comment by sidorares** [comment]
> Shouldn`t it decrease after when the connection is released?

No, releasing connection only marks it as "idle" and ready to be re-used later. Unless you explicitly call `.end()` on pool connection it remains open. The fact that number of opened connection is growing likely indicates that you age not always releasing them back to pool

10.000 number is really big for open connections - mysql server creates full os thread to handle active connection, which means that it needs at least 2mb per connection, and 10000 would need 2000GB of ram (+ huge cpu overhead on switching context)

**Comment by merarischroeder** [comment]
@sidorares "you are not always releasing them back to pool". So does `release` release or not? Your spiel earlier talks about idle vs closed, but you didn't say `release` isn't releasing back to the pool. Some clarification would be handy.

**Comment by dougwilson** [comment]
Hi @merarischroeder what that quote means is that it's possible there is a code path that is missing the `.release()` call all together. This is way more common than you would think; almost every single time a question like this comes across, it turns out there is some ransom code path that is just not calling `.release()`. If you or @Rellfy can share the full code that reproduces this issue, we can dig into this issue better together. Right now, without any code being offered up or a pull request to fix the issue, everything is simply speculation.

**Comment by merarischroeder** [comment]
@dougwilson I understand the missing .release() issue, this is why I'm lurking here at the moment, I'm about to put forward a feature request with a particular design in mind. But while I'm here, I'm checking for duplicates.

The problem with @sidorares response, is that he went on a tangent, which made his final answer in the last paragraph ambiguous. 

Shouldn`t it decrease after when the connection is released?

The opening statement "No, releasing..." is actually wrong. 

Correct way of answering:

Yes. BTW it doesn't close the underlying connection, it will remain idle, which is probably what you want. But you might need to reset the connection manually, or manually clear any variables left behind.

I'm not trying to be a pest, I just imagine that someone else might get confused if they come by.

**Comment by sidorares** [comment]
@merarischroeder my "No" was referring to original `Threads_connected` count after doing `poolConnection.release()`, as in original question. No, it does not decrease after you release connection, because it remains connected.

> But everytime I access my app (it has to make mysql connections) and I execute the MySQL query show status where 'variable_name' = 'Threads_connected'; I can notice that the value increases by 1 every time I reload the page, and it might keep increasing till it reaches the limit (10k) and returns the error. But, is it normal for this value to keep increasing? Shouldn`t it decrease after when the connection is released?

**Comment by merarischroeder** [comment]
@sidorares My bad. I read the title "too many connections" and assumed they were referring to the _freeConnections variable.

**Comment by Rellfy** [comment]
Oh I see now. It must be some path that isn't really releasing the connection. So, if I have two paths for example, which I call 300 times, and one of them is not releasing the connection back to the pool, instead of having only 2 threads connected (since I`m going to call them asynchronously, but only call the 2 again when they`re both finished, for example), I would have 150 connected because the second DB call is missing the conn release?

 If that`s it, the problem should be fixed. Thank you all for making it clear. I might just need to check my code (which isn`t just a few lines btw) for missing connection releases.
