### ISSUE TITLE
pool getConnection stalling

### ISSUE THREAD

**Issue by kumangdeal** [mysqljs/mysql#1522]
Hi,

sometimes, the getConnection method from the pool stalled, no error returned, no connection returned, the callback was not even called.

any idea why this happen ? i always release my connection after i'm done with it.

thanks!

**Comment by dougwilson** [comment]
Hi @kumangdeal, I know you said "i always release my connection after i'm done with it" but are you sure there isn't some code path that is accidentally not always doing that? The only things that I know of that fit your description are (1) you are accidentally not always releasing every connection you get or (2) there is a bug in this module.

If you are thinking (2), I would love to investigate the issue! Would you be able to provide all the following information?

1. The version of Node.js you are using.
2. The version of this module you are using.
3. Complete code that reproduces the issue. We should be able to copy and paste it and run the code (i.e. it needs to be complete code, not partial snippets).
4. Instructions for how to run the code to reproduce the issue.

Thank you!

**Comment by kumangdeal** [comment]
hi @dougwilson , thanks for the response.

firstly, i'm newbie in node js (backend dev) thing, so i'm sorry if i asked any noob question :D 

i'm pretty sure that i released my connections,
i tried to test it by calling the release() before running any query and it crashed, telling the connection already released.

1. My node js version is 5.1.0
2. the module version is 2.11.1
3. this is how i obtain my connections : 

mysqlHelper.js
http://pastebin.com/6jWNiZeC

implementation in any controllers 
http://pastebin.com/u1RbA01N

4. I don't know how to reproduce it. The app works fine first, after several time ( i think the more request is sent to server, the sooner it will stall ). But if i just restart the app, it will work fine again. (then it will stall again).

**Comment by sidorares** [comment]
@kumangdeal can you show your `model.doSomething` implementation? If callback is not called for some reason ( code logic error or exception prevents from reaching ) then `conn.release()` is not called as well

**Comment by kumangdeal** [comment]
@sidorares 

here's how i use the connection in a model.
http://pastebin.com/MQRYrdKt

are you suggesting that if an error or exception happened in the model class, that could be the reason for the callback not being called ?

so far i didn't see any crash or error logged.

**Comment by kumangdeal** [comment]
hi all,

so if there is a connection that is not released, can that eventually lead to this ?

turns out there's a function that use a connection but it doesn't release it after everything is done.
the function called rarely, but after some time it eventually passed the pool limit. 
So if my limit is 30, and the functions is called 30 times already, there will be 30 unreleased connection. Is this situation can make the getConnection function stall ? if so, then i'll just mark this thread as solved, because that would be my mistake 🙇 .

thanks :D

**Comment by sidorares** [comment]
> so if there is a connection that is not released, can that eventually lead to this ?

yes

> Is this situation can make the getConnection function stall ? 

yes. if you have `queueLimit` set then `getConnection` would return error as soon as there is more then a limit waiting, but default `queueLimit` value is 0 ( no limit ), that is your `getConnection` request sits in the queue forever ( until connection is released, but when there is a code failing to do `.release()` this might never happen )

**Comment by kumangdeal** [comment]
@sidorares thanks for the explanation.

**Comment by forenheith** [comment]
Hi all, I have the almost the same issue with getConnetion() method. I just get the example code from documentation and filling in my credentials and nothing works. Here is my code.

`function getFreeConnection() {
    pool = getConnectionsPool();
    try {
        pool.getConnection(function cb(err, connection) {

            if (err) {
                console.error(`error getting connection from pool; ${err}`);
                throw  err;
            }

            if (!connection) {
                console.error(`error getting connection from pool`);
                return null;
            }
        });
    } catch (e) {
        console.error(e);
    }
}

function getConnectionsPool() {
    pool = pool ?
        pool :
        mysql.createPool({
            host: process.env.MYSQL_HOST,
            user: process.env.MYSQL_USER,
            password: process.env.MYSQL_PASSWORD,
            database: process.env.MYSQL_DB
        });

    if (!pool) {
        console.error(`error getting connections pool`);
        return null;
    }
    return pool;
}`

Callback is never called. Any ideas? How can I debug this issue?
