### ISSUE TITLE
Export Query and packet classes

### ISSUE THREAD

**Issue by felixfbecker** [mysqljs/mysql#1524]
The Query and packet classes (OkPacket, RowDataPacket) should be exported in the index.js. Especially for RowDataPacket and OkPacket it should be possible to check if the result is an OkPacket (from an UPDATE/INSERT) or a RowDataPacket (from a SELECT) with `instanceof`. Currently we can only check with `.constructor.name`, which is of course error-prone. See https://github.com/sequelize/sequelize/pull/6475/files/8de5d3f895c6c15aece62f65710176137034a6bb#r75575249

Additionally, this would also allow us to type the parameter in TypeScript correctly because we can get a reference to the classes. Currently I export these in the typings even though they are not _actually_ exported, which can cause runtime bugs if users try to use them with `instanceof`.

**Comment by sidorares** [comment]
It's possible to do now, but I guess exporting from main entry point and documenting is more reliable

```js
  var RowDataPacket  = require('mysql/lib/protocol/packets/RowDataPacket.js');
  var OkPacket  = require('mysql/lib/protocol/packets/OkPacket.js');
```

**Comment by felixfbecker** [comment]
that feels like going into library internals :/
also adds two lines of boilerplate

**Comment by sidorares** [comment]
and won't work if reference to module is passed from outside

**Comment by dougwilson** [comment]
Hi @felixfbecker I can't figure out your use-case from that link you gave me, as it's not clear how this module is being used. Can you provide come code examples of how one would use that? Also, we don't use `instanceof` in our own codebase, so using that is no guarantee it will work; we only guarantee `.constructor.name` to work currently. Also, those packets are not public API, so I don't want to actually export them unless they get a API that we can support as public.

**Comment by sidorares** [comment]
I assume this is to differentiate select results ( where we return array of `RowDataPacket` ) from insert/update/delete where `OkPacket` is returned

If we factor in multiple statements it gets even more complicated - the result is can be 1) OkPacket or 2) array of `RowDataPacket` or 3) mixed array of 1 or 2 if number of results is more than one

**Comment by dougwilson** [comment]
So ideally whatever we implement here is usable with `mysql2` as well, so exporting the classes doesn't seem like a good way to make the two modules compatible. What if those packets had some kind of method on them that provided that information? I'm not sure, brainstorming right now.

**Comment by felixfbecker** [comment]
Yes, that is the use case. `OkPaket` and `RowDataPacket` _are_ public API, they are passed as arguments to callbacks after all. The PR I linked was another example, I don't remember why, but there was a reason we had to check if some variable was a `ResultSetHeader` and had to resort to `.constructor.name`. That feels very fragile, it could be any object from any library, and if you get an object that inherits from `ResultSetHeader` the constructor name can be different even though it is still an instance of `ResultSetHeader`.

For the TypeScript use case: I am converting the TypeScript typings from DT to @types and all the callback arguments are simply typed `...args: any[]`, which sucks of course. So I typed the packets and changed it to `(err: QueryError, result: RowDataPacket[] | OkPacket, fields: FieldPacket)`. The problem now is, if a user uses these callbacks, he needs to type the `result` parameter depending on if he did an INSERT or UPDATE. But he cant, because there is not reference exported from the module.

> So ideally whatever we implement here is usable with mysql2 as well, so exporting the classes doesn't seem like a good way to make the two modules compatible. What if those packets had some kind of method on them that provided that information? I'm not sure, brainstorming right now.

I guess @sidorares could export them aswell :)
As I said they are public API already, they are passed to the user. Changing them would already be a breaking change. The only thing you can change are private methods, which I would consider anything with an underscore or anything not documented. That doesn't really change if you export the class or not.

**Comment by sidorares** [comment]
> What if those packets had some kind of method on them that provided that information?

yes, I'm thinking in same direction. I don't like current api in that regard (I wish we always return rows array and ok packet) but I guess this is very difficult to change now

**Comment by dougwilson** [comment]
> As I said they are public API already, they are passed to the user. Changing them would already be a breaking change. The only thing you can change are private methods, which I would consider anything with an underscore or anything not documented. That doesn't really change if you export the class or not.

I guess I didn't fully explain :) What isn't public API is the actual construction of those objects outside of this module. Exporting the references adds construction of them to the public API. How would a user use that API?

I also took a look at the `mysql2` module and the packet objects have a different constructor API, causing a simple export right now to diverge the public API between the two.

**Comment by dougwilson** [comment]
Of course, it's weird to even talk about having "classes" in JavaScript, because that is weird. As far as our API is concerned, we are building those from a raw `{}`, and the underlying prototype structure does not matter. That's why I think providing a method or some property to get this information is probably a better JavaScript API. It would also help since the `mysql2` module has different prototypes for is the result set was from the text protocol or the binary protocol, which the end user library of course doesn't care about.

**Comment by felixfbecker** [comment]
Good point. Many libraries add another `name` type to instances to indicate the type, like an error that also has the property `name: 'ValidationError'` even though you could also use `instanceof` to check that. For `RowDataPacket` that would of course not work because it contains all the columns and a `name` column is quite common. So maybe `.constructor.name` is not that bad after all.

I will change the TypeScript classes to interface then.

**Comment by felixfbecker** [comment]
> Of course, it's weird to even talk about having "classes" in JavaScript, because that is weird. 

Btw need to disagree here, we have classes in JavaScript now, and they are the same as writing a function, just different syntax. So I use the word class to refer to the functions here, as they are invoked with `new`

**Comment by dougwilson** [comment]
> Btw need to disagree here, we have classes in JavaScript now

I assume in a version of JavaScript that this module is not using ?? At least for the JavaScript version this module is using, it only promises that the `.query` function returns objects, it does not promise what `instanceof` will be, what the prototype chain is, etc.

I think having some property to determine the type of the response would be useful. `.name` is common, as you pointed out, but adding something like `.mysqlResultType()` may be unlikely to collide, etc. Of course, mixing in the column names directly into these objects is itself questionable, for a tagent discussion :)

**Comment by dougwilson** [comment]
> Could you take a quick look if the API is typed correctly? http://typed-mysql.surge.sh/

I'm taking a look, and it's definitely a lot to look through :) So far nothing is jumping out as wrong, though I've seen a few missing things: (a) `Connection.prototype.query` takes the result from `Connection.prototype.createQuery`, for example, and I don't think the typings are describing that? (I could be wrong as I'm seeing this type of docs for the first time from TS :) ). and (b) I'm not sure if it matters to your typings, but the `Pool.prototoype.getConnection` returns an object created from the main `PoolConnection` function, which is one more prototype level from `Connection` function and has extra methods available, like `.release()`.

**Comment by dougwilson** [comment]
>  (b) I'm not sure if it matters to your typings, but the Pool.prototoype.getConnection returns an object created from the main PoolConnection function, which is one more prototype level from Connection function and has extra methods available, like .release().

I see now that `.release()` is declared on the `Connection` class that is made in there, but of course there is no `.release()` method on the objects returned from `mysql.createConnection`, which I'm guessing the typings currently wouldn't catch that code mistake without the distinction between `Connection` and `PoolConnection`.

**Comment by felixfbecker** [comment]
You might wanna uncheck "Inherited" or it will show you all the stuff from EventEmitter etc aswell :)

> Connection.prototype.query takes the result from Connection.prototype.createQuery, for example, and I don't think the typings are describing that

It's not possible to describe such a relationship, it's only about return types. If you prefer to browse the declarations: https://github.com/types/npm-mysql

> I'm not sure if it matters to your typings, but the Pool.prototoype.getConnection returns an object created from the main PoolConnection function, which is one more prototype level from Connection function and has extra methods available, like .release().

That does matter! thanks! copied that from the original typings

**Comment by felixfbecker** [comment]
Closing this as you 2 convinced me this is not a good idea :)
