### ISSUE TITLE
ER_ACCESS_DENIED_ERROR on Amazon RDS, from a remote host

### ISSUE THREAD

**Issue by cyberjoac** [mysqljs/mysql#1525]
Hi, I'm trying to connect to a remote MySQL instance on Amazon RDS from a **remote host**, that is also on Amazon.

I get the error message: 
`ER_ACCESS_DENIED_ERROR: Access denied for user 'integration_test'@'ec2-xx-xx-xx-xxx.us-west-2.compute.amazonaws.com'`

What is very weird is that I can successfully run the same code from my local computer, with same credentials exactly and it works.
It is also possible to connect from the command line.

I don't have any idea how to solve this issue, any help ?

**Comment by danielpacak** [comment]
I'm using this module successfully on Amazon AWS. Would you mind sharing your JS code for establishing connection? Also make sure you have a proper security group configured for the inbout traffic.

![image](https://cloud.githubusercontent.com/assets/1322923/18745194/a783544c-80c1-11e6-9bd5-441aed997689.png)

Below is the piece of code that works for me:

```js
'use strict';

// TODO Set connectionLimit as an environment variable `RDS_POOL_CONNECTION_LIMIT`.
module.exports = require('mysql').createPool({
  connectionLimit: 10,
  host: process.env.RDS_HOSTNAME,
  user: process.env.RDS_USERNAME,
  password: process.env.RDS_PASSWORD,
  port: process.env.RDS_PORT,
  database: process.env.RDS_DB_NAME
});
```

**Comment by sidorares** [comment]
"Access denied for user" is a message from mysql server, so there is tcp connection - it's definitely not a firewall/security group issue.

@cyberjoac make sure that 1) `integration_test` user is allowed to connect from `ec2-xx-xx-xx-xxx.us-west-2.compute.amazonaws.com` 2) db used (it's part of permissions same way as host) is allowed 3) auth plugin / old_auth vs mysql_42 configured

**Comment by cyberjoac** [comment]
```
var execsql = require('execsql'),
    config = require('../../../../config/config'),
    dbConfig = {
        host: 'aws-mysql.xxxxxxxxxxxxxxx.us-west-2.rds.amazonaws.com',
        port: 3306,
        user: 'integration_test',
        password: 'integration_test'
    },
'''
This is the connection string I am using...
Inbound rules are working fine.

I allowed connection from % which is supposed to mean 'all hosts', isn't it ? 
I allowed the db...

**Comment by cyberjoac** [comment]
Should I mention as well that my node code for connecting to MySql is running inside Docker.
And it's not working as well on my local environment, while running inside Docker...
Should I open any ports ?

**Comment by danielpacak** [comment]
@cyberjoac Can you try specifying the database name explicitly, i.e. the `database` property in your connection config object?

**Comment by cyberjoac** [comment]
And I'm also using execsql,
I found that the issue is happening only with execsql, which is a wrapper of mysql.
It seems the issue is coming from there.
Source code is here: https://github.com/node-fun/execsql/blob/master/index.js
Now I'll solve the issue by using directly mysql but I would be happy to understand what is it that execsql is doing wrong...
Sorry to have bothered you anyway..

**Comment by femto113** [comment]
This is just a guess but the problem is likely with the code below--the port and database parameters are not being passed through when creating the connection.  These may be needed for RDS.

exports.config = function (options) {
	_.extend(config, _.pick(options, ['host', 'user', 'password']));
	conn = mysql.createConnection(config);
	conn.connect();

**Comment by dougwilson** [comment]
@cyberjoac if you remove the use of the `execsql` module and use this module directly and it works, then you may want to report the issue there. I think @femto113 is right on what the issue would be if it works with this module but not `execsql`.

**Comment by ERama035** [comment]
can any body help me how to solve the same problem , but i am able to login into the mysql , but when i try to run the application using "node app.js" , it shows the below error ?...

![image](https://user-images.githubusercontent.com/12675170/41174024-7dafde1c-6b1e-11e8-86ca-4f088d897dc3.png)
