### ISSUE TITLE
TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by fadeaway** [mysqljs/mysql#1529]
```js
connection.query(sql, params, function (err, rows)
{
    //how is connection undefined here? err is null
    connection.destroy();
});
```

**Comment by dougwilson** [comment]
Weird. I've never seen that before, and almost every test case we have as `connection.destroy()` in the code. Would you be able to provide all the following:

1. The version of Node.js you are using.
2. The version of this module you are using.
3. Complete code that reproduces the issue. Snippets pretty much never work, because it's hard to understand how variables are getting set. I should be able to copy and paste your code into a file and run it without making assumptions on the rest of the code.
4. Complete instructions on how to case the error. It may be as simple as "run the JavaScript" provided. Please note what I see when the error occurs and what you are expecting to see on a successful run.

Thank you!

**Comment by fadeaway** [comment]
Sorry the actual error is TypeError: Cannot read property 'destroy' of undefined

I am trying to close a connection after the query finishes and get property 'destroy' of connection is undefined. This is with https://github.com/mysqljs/mysql

Node: v0.12.7 
Mysql: 2.9.0

the function being called that has the mysql code in it is a step in an async waterfall. Hopefully this gives some more information. the below code is done inside the async waterfall function.

var connection = mysql.createConnection( data.dbConfig //db info );
connection.connect();

connection.query( sql, params, function(err, result) {
  console.log(err); // this is null
  connection.destroy();
});

**Comment by dougwilson** [comment]
Thanks for the information, @fadeaway ! So For the past 10 minutes I've been running the code
```js
var connection = mysql.createConnection( data.dbConfig //db info );
connection.connect();

connection.query( sql, params, function(err, result) {
  console.log(err); // this is null
  connection.destroy();
});
```
in a loop and no error. Can you give more detailed instructions on exactly how I am supposed to reproduce the error?

**Comment by fadeaway** [comment]
Here is some more code that will hopefully help. This is in a function that is called by a loop. func1,func2,func3 has the above code that I sent you. the async version im using is 1.4.2 if that helps.

    `var dbConfig =  {
        "host": "localhost",
        "user": "root",
        "password": "",
        "database": "db"
    };
    data.dbConfig = dbConfig;

    async.waterfall( [
      this.proxy( 'func1', data ),
      this.proxy( 'func2', data ),
      this.proxy( 'func3', data )
    ], function( err ) {
      if ( err ) {
        console.error( 'Error', err );
      }
    } );`

**Comment by dougwilson** [comment]
Ok, I tried, but I still cannot reproduce. There is nothing I can do if you cannot provide the information I asked for inhttps://github.com/mysqljs/mysql/issues/1529#issuecomment-249997136

Specifically you need to provide all the code I can copy and paste into the file and run. Please stop providing snippets, which I asked to not get. If you need to create a GIT repo to host full code I can run and link to that along with instructions, please do.

At this point, the only help I can give based on the provided information is to ask you to submit a pull request that fixes the bug you're reporting.

**Comment by dougwilson** [comment]
Here is the log from another console session I just did where I tried again. Please tell me what I'm doing wrong and why I'm not able to reproduce the issue:
```
$ npm i async@1.4.2
async@1.4.2 node_modules\async

$ npm i mysql@2.9.0
mysql@2.9.0 node_modules\mysql
├── bignumber.js@2.0.7
└── readable-stream@1.1.14 (inherits@2.0.3, string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2)

$ cat ex.js
var async = require('async');
var mysql = require('mysql');

var data = {};
var dbConfig =  {
    "host": "localhost",
    "user": "root",
    "password": "",
    "database": "db"
};
data.dbConfig = dbConfig;

async.waterfall( [
  function (cb) { func1(data); cb(); },
  function (cb) { func1(data); cb(); },
  function (cb) { func1(data); cb(); }
], function( err ) {
  if ( err ) {
    console.error( 'Error', err );
  }

  console.log('done');
} );

function func1 (data) {
  var connection = mysql.createConnection( data.dbConfig /* db info */ );
  var sql = 'SELECT 1';
  var params = [];
  connection.connect();

  connection.query( sql, params, function(err, result) {
    console.log(err); // this is null
    connection.destroy();
  });
}

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done

$ node ex.js
done
```

**Comment by fadeaway** [comment]
This project can't be shared it is proprietary.

**Comment by dougwilson** [comment]
Hi @fadeaway please let me know what next steps I should take :)

**Comment by fadeaway** [comment]
I'm looking to reproduce the issue now in a smaller project.

**Comment by fadeaway** [comment]
The issue here is you won't be able to run the code because it is talking to a xml rpc server that you wouldn't be able to bounce off of. I can post the code for the whole module but like i said you wouldn't be able to run it and this is what you are wanting. It's possible you could spot the issue with just seeing the code but you didn't seem to want that.

**Comment by dougwilson** [comment]
Hi @fadeaway, what do you think the next steps are here?

**Comment by fadeaway** [comment]
I'm not sure. I feel like this is a issue on my end but beating my head on where the breakdown is happening. I've used this method in plenty of other places and never seen connection just be undefined in  the query callback.

**Comment by dougwilson** [comment]
Yea, it does seem really, really odd, and there isn't enough information to say it _isn't_ a bug in this module. What is actually happening to the `connection` variable is really hard to tell with the snippets, since at least so far, all of them, taken as they are, have no logic or any other errors I can see :(

**Comment by fadeaway** [comment]
If you care to look this over and see if there is some kinda glaring issue here, if not no big deal ill keep debugging on it. http://pastebin.com/Z6AcUfZt - handleSuccess is the only function I am dealing with at this point and only function that is being hit. I posted the debug output at the bottom as well.

**Comment by dougwilson** [comment]
Looks like the issue is your variable scoping. In JavaScript, all variables are function-scoped; there is no such thing as block scope. That means that once you enter your callback function on line 151, the `connection` variable is referring to the one that is declared on line 158. It won't be until line 158 runs that the value will be set, so when it hits line 152, the variable is still undefined.

**Comment by fadeaway** [comment]
ah, this makes sense. I'm used to dealing with C based languages that are block scoped. Thanks for the help Doug. In my other parts of code i have separate functions and not nested callbacks is probably why i haven't seen this behavior before.

**Comment by dougwilson** [comment]
No problem, glad we were able to figure it out :) That's why snippets are hard, because sometimes, it's hard to know which parts of the code are important to see or not :S and yes, JavaScript var scoping is... weird.
