### ISSUE TITLE
Connecting to Google Cloud SQL using Cloud SQL Proxy on Heroku produces ENOENT error

### ISSUE THREAD

**Issue by mm-wang** [mysqljs/mysql#1530]
I'm having a similar problem to #1464 with connecting to a socket. The socket I would like to connect to is a google cloud proxy for a google sql server. 

According to [Google Cloud SQL's help page](https://cloud.google.com/sql/docs/external#proxy) for external connections, the UNIX socket follows the syntax `<PROXY_PATH>/<INSTANCE_CONNECTION_NAME>` which I am using as the socketPath in Node. I am using the correct username and password, since I can connect using MySQL Workbench. I can also connect if I use the node command you provided in the issue referenced above.

On the Google SQL Cloud Proxy side, I'm starting up the proxy from a Windows command window:

```
cloud_sql_proxy.exe -dir=/cloudsql -instances=[instance-connection-name]=tcp:3306 
& mysql -u [username] -p [password] -h 127.0.0.1
```

On the Node.js side:

```
var connection = mysql.createConnection({
    user: "username",
    password: "password",
    port: 3306,
     socketPath: "/cloudsql/[instance-connection-name]"
});
```

where I replace [...] with the correct values.

In the connection, I get:

```
_connection: [Circular]
...
_fatalError: {[ Error: connect ENOENT /cloudsql/[instance-connection-name] ] 
code: 'ENOENT',
errno: 'ENOENT',
syscall: 'connect',
address: '/cloudsql/[instance-connection-name]'
fatal: true},
```

and Heroku also spits out a similar error:

```
Error: Cannot enqueue Query after fatal error.]
code: 'PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR', 
fatal: false
```

I realize that there are many different parts to this, so it could be another portion that is throwing an error.  However, since the proxy is open and I can access it with node, I believe that it could be the way I am using this package. Any help would be appreciated.

**Comment by dougwilson** [comment]
Hm. I'm not very familiar with that setup, and the most I can say from the errors is that `Error: connect ENOENT /cloudsql/[instance-connection-name]` is coming from Node.js core code, and I'm not familiar with that that means on a UNIX socket. Is there any way you can help me reproduce the issue to take a closer look?

**Comment by mm-wang** [comment]
I'm not sure that I can reproduce this error outside of Heroku, unfortunately. It's specific to the dynamic IP address assigned by Heroku to an application, which is what prompted my connection.

The best way to reproduce the error is to set up a SQL database that can only be accessed by a certain username and password through a proxy. The way I created this is the following.

Is this enough information? Or do you need the specific connection that I am setting up? I have a dummy database that I could provide you with information for, although I'd rather not do so publicly on Github.

### Steps
1. Create a project
2. Create an instance for a server

  - ID: skipper_sql
  - Region - us-east1
  - Machine Type - SSD
  - Storage Capacity - start at 10GB
  - Create backups and set automated ones

3. [Optional] Add your public IP to the authorized networks to see the database. Remove to test proxy.

4. Create a cloud SQL Proxy: <https://cloud.google.com/sql/docs/sql-proxy>

  1. Enable Cloud SQL Administration API - <https://cloud.google.com/sql/docs/external#proxy> <https://cloud.google.com/appengine/docs/flexible/nodejs/using-cloud-sql#before_you_begin>
  2. Install and Initialize Cloud SDK - <https://cloud.google.com/sdk/docs/>
  3. Set the instance password - <https://cloud.google.com/shell/docs/examples#manage_cloud_sql_data>

    ```
    gcloud sql instances set-root-password [YOUR_INSTANCE_NAME]
    --password [YOUR_INSTANCE_ROOT_PASSWORD]
    ```

    Instance is from gcloud, password generated from KeePass, use whenever asking for root user

  4. Use Google Cloud SDK to create a user for proxy connections - <https://cloud.google.com/sql/docs/mysql-client#cloud-shell> <https://cloud.google.com/sql/docs/sql-proxy#invocations>

    ```
    gcloud beta sql connect my-instance --user=root
    CREATE USER '[USER_NAME]'@'%' IDENTIFIED BY '[PASSWORD]';
    ```

    Check user is there - <https://cloud.google.com/sql/docs/create-manage-user-mysql>

    ```
    SELECT user, host FROM mysql.user;
    ```

   Create a specific cloud sql proxy user and password:

   ```
   CREATE USER '[USER_NAME]'@'cloudsqlproxy~%' IDENTIFIED BY '[PASSWORD]'
   ```

    Verify connection to databases

    ```
    mysql --host=[INSTANCE_IP] --user=root --password
    ```

  5. Set up a service account - <https://console.cloud.google.com/iam-admin/serviceaccounts/serviceaccounts-zero>

5. **Run SQL Proxy on local machine and keep it running**

  On Windows:

  ```
   cloud_sql_proxy.exe -instances=[instance-connection-name]=tcp:3306 & mysql -u [username] -p [password] -h 127.0.0.1
  ```

  Can add credential file as well, however won't allow MySQL Workbench to work then.

  ```
   ... -instances=[instance] -credential_file=[file] & mysql...
  ```

6. Create socketPath with username and password on npm

  ```
   {
      “username”: “dev”,
      “password”: “devpwd”,
      “database”: “dev-db”,
      “host”: “localhost”,
      “dialect”: “mysql”,
      “dialectOptions”: {
      “socketPath”: “/cloudsql/{projectName}:{zone}:{instance-name}”
   }
  ```

  ```
   socketPath: "/cloudsql/t-computer-144617:us-east1:skipper-sql"
  ```

  from <https://medium.com/google-cloud/node-js-on-app-engine-with-cloud-sql-proxy-43f56279a56b#.szvu84x7k>

7. Use in application in Node using Express

   ```
var connection = mysql.createConnection({
    user: "[username]",
    password: "[password]",
    port: 3306,
   
     socketPath: "/cloudsql/[instance-connection-name]"
});

router.post("/get-result", function(req, res) {


    var query = "INSERT INTO `test_schema`.`test_table` (`name`, `date`, `number`) VALUES ('name', '2016/9/27', '3');";

    console.log("MYSQL CONN: ", connection);

    connection.query(query, function(err, rows, fields) {
        if (err) {
            console.log("ERROR: ", err);
            return res.status(500).send("Could not connect on query");
        }
        var results = {
            "rows": rows,
            "fields": fields,
        };
        console.log(results.rows);

        connection.end();
        res.json(results);
    });

});
```

**Comment by dougwilson** [comment]
I'm confused just at step number 1. Where do i make a new project? Sorry if it should be obvious, but I can't figure it out.

For for additional steps, are those free things I can just make? Where do I sign up?

**Comment by dougwilson** [comment]
Would it be easier if you could submit a pull request with a fix?

**Comment by mm-wang** [comment]
Ah, this was referring to the [Google Platform Cloud SQL](https://cloud.google.com/sql/docs/). I'm sorry it was not clear before. There is a free trial available with Google Cloud SQL, you can click the Try It Free button in the corner.

![image](https://cloud.githubusercontent.com/assets/1688790/18914867/d45c7d1e-855c-11e6-929d-f3d72aacb858.png)

After you click Try It Free, you can go through the trial setup. You get 60 days free and $300 worth of credit.

Once you have gone there, you can follow the prompts for setting up a project.

**Comment by mm-wang** [comment]
If you have any examples of connecting with a UNIX or TCP socketPath, that would be great to have.

**Comment by mm-wang** [comment]
I have another update. I've been tinkering on this with a local host connecting to the Google Cloud SQL server, and I have some new error logs, in case that can maybe help?

```
Err connecting: Error: Cannot enqueue Handshake after fatal error.
    at Protocol._validateEnqueue (C:\Users\[user]\Documents\GitHub\CORE.TypicalBa
ys\node_modules\mysql\lib\protocol\Protocol.js:199:16)
    at Protocol._enqueue (C:\Users\[user]\Documents\GitHub\[repo]\node_
modules\mysql\lib\protocol\Protocol.js:135:13)
    at Protocol.handshake (C:\Users\[user]\Documents\GitHub\[repo]\node
_modules\mysql\lib\protocol\Protocol.js:52:41)
    at Connection.connect (C:\Users\[user]\Documents\GitHub\[repo]\node
_modules\mysql\lib\Connection.js:136:18)

```

**Comment by penghuiliusc** [comment]
Hi, do you have any update about this issue?

**Comment by dougwilson** [comment]
Sorry for not updating (I thought I did). I was able to connect to the Google Cloud SQL just fine, so not sure what the issue is. Without being able to reproduce and no PR fix offered up, I'm not sure there is any action I can take here.

**Comment by penghuiliusc** [comment]
@dougwilson Thanks so much! Can you give an example on successfully connecting to Google Cloud SQL?

**Comment by dougwilson** [comment]
All I did was follow the instructions at https://cloud.google.com/sql/docs/external#proxy ; I tried both TCP and UNIX socket proxies with this module and they both worked.

**Comment by bwoodlt** [comment]
How do you manage this if connecting via a docker container? Kinda struggling with this.
