### ISSUE TITLE
escapeId() and period '.' issue

### ISSUE THREAD

**Issue by siddo420** [mysqljs/mysql#1533]
Thanks for the module.

I amy trying to escape table names in this format: ti_g.n5, which is a correct MySQL table name identifier. 

```
CREATE TABLE `ti_g.n5` (id INT);
Query OK, 0 rows affected (0.43 sec)

mysql> SELECT * FROM `ti_g.n5`;
Empty set (0.02 sec)

mysql> SHOW TABLES LIKE 'ti_g%';
+------------------------+
| Tables_in_test (ti_g%) |
+------------------------+
| ti_g.n5                |
+------------------------+
1 row in set (0.00 sec)

```
However, when I used escapeId() on it, it returns `ti_g`.`n5` instead, which I think assumes a db name.tbl_name combination but this is not what I want. 

Is this is a bug? If yes, any workarounds available atm?

**Comment by dougwilson** [comment]
Hi @siddo420 this is how the `escapeId()` function is documented to work (https://github.com/mysqljs/mysql#escaping-query-identifiers) so it isn't a bug :)

Now, the `escapeId()` function actually accepts a second argument to control the behavior you are seeing. You can use `mysql.escapeId('ti_g.n5', true)` to achieve the desired functionality.

I also see that this is not documented on the README by accident. If you would like to make a pull request to add documentation around this, that would be a good first contribution :)

**Comment by dougwilson** [comment]
I hope I was able to answer your question, since I haven't heard back. I also noticed that the second argument to `escapeId` was not documented, so added documentation to the README.
