### ISSUE TITLE
Multiple statement question

### ISSUE THREAD

**Issue by beturs** [mysqljs/mysql#1535]
When I do a multiple statement query, can I assume that the _results_ array is in the order of my statements ?
```js
connection.query('INSERT car; INSERT plane', function(err, results) {
  if (err) throw err;

  console.log(results[0].insertId); // can I assume this will return the id for the inserted car ?
  console.log(results[1].insertId); // can I assume this will return the id for the inserted plane ?
});
```

**Comment by dougwilson** [comment]
Technically they simply are in the order that the MySQL server sends them to this module. I'm not 100% sure if there is some kind of guaranteed order, as that may be a better question towards the MySQL server itself. This module just presents them in the same order as the MySQL server sent them back, if that helps.

**Comment by beturs** [comment]
Thank you @dougwilson 👍

**Comment by dougwilson** [comment]
So I took a quick read through the protocol and as far as I can tell, the answer is yes:  you're guaranteed to get that behavior as far as I can tell.
