### ISSUE TITLE
pool.end prevents the script from finishing

### ISSUE THREAD

**Issue by dgonzalez** [mysqljs/mysql#1536]
not sure if I am doing something wrong but this is a very simple use case:
```
const config = require('./config')
const mysql = require('mysql')


const pool = mysql.createPool({
  host: config.mysqlHost,
  port: config.mysqlPort,
  user: config.mysqlUser,
  password: config.mysqlPassword,
  database: config.mysqlDatabase,
  timezone: 'gmt',
  dateStrings: true,
  connectionLimit: config.mysqlConnectionLimit,
  waitForConnections: false,
})

pool.getConnection((err, conn) => {
  conn.release()
})

pool.end(() => {
  console.log('Pool closed')
})

```

This outputs:
```
pool closed
```

but the script never finishes which is what I would expect with pool.end.

The version I am using is `2.11.1`

**Comment by dougwilson** [comment]
I tried your script out and the script exited just fine (which matches what our tests show as well). There are a couple things you didn't provide, which may help here:

1. I don't know what `require('./config')` does, which could be important to the issue. Either provide the exact contents of that file or post a new example that does not `require` anything other than this module.
2. I don't know the version of Node.js you are using, so just assumed Node.js 4.6.0

**Comment by dgonzalez** [comment]
Node 6.6.0

```
//const config = require('./config')
const mysql = require('mysql')


const pool = mysql.createPool({
  host: 'localhost',
  port: '8889',
  user: 'root',
  password: 'root',
  database: 'the-db',
  timezone: 'gmt',
  dateStrings: true,
  connectionLimit: 10,
  waitForConnections: false,
})

pool.getConnection((err, conn) => {
  conn.release()
})

pool.end(() => {
  console.log('Pool closed')
})
```

same behaviour.

**Comment by dougwilson** [comment]
Weird, I still cannot replicate. Can you attach a debugger and figure out what is keeping the event loop open? I've never done that before, so I'm not 100% sure how to do it, but clearly there is something keeping it open and that basic test for me on Node.js 6.6.0 ends the process successfully. I did change the port to 3306, since that's where my MySQL is listening. I assume that you were able to connect just fine in your example (i.e. `err` is `null` in your callback, right?).

**Comment by sidorares** [comment]
@dgonzalez this is a great tool to help with issues like yours: https://github.com/mafintosh/why-is-node-running

or just do `console.log(process._getActiveHandles(), process._getActiveRequests())` at interval

**Comment by dougwilson** [comment]
Awesome, good to know, @sidorares 👍 @dgonzalez were you able to use that module on your code to see what is holding the process open?

**Comment by dgonzalez** [comment]
not yet. I will try over the weekend.

**Comment by dougwilson** [comment]
Hi @dgonzalez, I hope it's OK if I close this issue, as I haven't heard anything back in 20 days. If you do have some more information, please feel free to post here and I can re-open the issue :) !
