### ISSUE TITLE
Querying the same value against multiple fields

### ISSUE THREAD

**Issue by dankell** [mysqljs/mysql#1538]
I may be missing it in the docs, but is there an easy way to use escape to query the same value against multiple fields without having to repeat it multiple times in the array?

For instance

```
var myDate = new Date();
connection.query('SELECT * FROM users WHERE date_1 >= ? AND date_2 <= ?', [myDate, myDate], function(err, results) {
  // ...
});
```

(I have a query where I am using the same date against 8 date fields)

**Comment by dougwilson** [comment]
Because `?` is a positional replacement, there is no other way to do it using that replacement style.
