### ISSUE TITLE
App crashes when on MySQL error

### ISSUE THREAD

**Issue by hohozhao** [mysqljs/mysql#1539]
Hi team,

I am quite new to nodejs.
I searched the issues and not found the same, hence come to create a new issue.

I already added on 'error' function, like this:

``` js
con.on('error', function(err){
    console.log(err.code);
});
```

But whenever MySQL error happens like selecting non-exists table, my App always crashes.

``` sql
select * from not_exists_table
```

```
/home/user/my-project/node_modules/mysql/lib/protocol/Parser.js:78
        throw err; // Rethrow non-MySQL errors
        ^
Error:
 ER_NO_SUCH_TABLE: Table 'my-database.not_exists_table' doesn't exist
```

Don't know how to make App don't crash when MySQL error happens. 

Thanks,
HoHo

**Comment by dougwilson** [comment]
Hi @hohozhao can you share your Node.js code? It looks like you may have a `throw error` in your code, which is crashing your app.

**Comment by hohozhao** [comment]
Hi @dougwilson ,
Thanks for quick reply. 

YOU ARE CORRECT! 
I did use throw err, and thinking it just "throw" out error message and continue, but instead it dies.
Now I remove "throw err" and "use console.log(err)" and my App continues. 

You can close this issues now. I am young to mysqljs but love it!
Cheers,
HoHo

**Comment by EyeOfThReindeer** [comment]
Hello,
Is there a way to catch the thrown error without ending the application? 

I have the server component written in way that allows me to throw errors which are then handled by the server. Server logs the exception in console and responds the client with "Internal server error" message WITHOUT ending the application for all other clients.

Once mysql is included, however, thrown errors forces the entire application to stop. (in /mysql/lib/protocol/Parser.js:79)

My code of Model module:

```
var mysql = null;
var connection = null;

exports.connect = function (callback) {
    if (connection == null) {
        mysql = require("mysql");

        var conf = global.config.database;
        connection = mysql.createConnection({
            host: conf.host,
            user: conf.username,
            password: conf.password,
            database: conf.dbname
        });

        connection.connect(function (err) {
            if (err) {
                throw createMessage(0, 'Error connecting to database' + err.stack);
            } else {
                console.log("Database connection established");
            }
            callback();
        });
    } else {
        callback();
    }
};

executeQuery = function (sql, variables, callback, success, fail) {
    fail = (typeof (fail) !== "undefined") ? fail : "Fail";
    success = (typeof (success) !== "undefined") ? success : "Success";
    try {
        exports.connect(function () {
            var query = connection.query(sql, variables);
            var results = [];
            var error = null;
            query.on('error', function (err) {
                error = err;
            });

            query.on('result', function (queryResult) {
                results.push(queryResult);
            });

            query.on('end', function () {
                if (error === null) {
                    callback(createMessage(1, success, results));
                } else {
                    callback(createMessage(0, fail, {'error': error}));
                }
            });
        });
    } catch (exception) {
        callback(createMessage(0, fail, {'error': exception}));
    }
};

exports.checkLoginCredentials = function (username, password, callback) {
    var sql = "SELECT * FROM users WHERE ausername = ?";
    var variables = [username];
    executeQuery(sql, variables, function (message) {
        if (message.response === 0 && message.response_http !== 404) {
            throw message;
        }
        callback(message);
    });
};
```

**Comment by wisetc** [comment]
@hohozhao How do you fix it?

**Comment by wisetc** [comment]
```javascript
    var slug = req.params.slug;
    connection.query(`SELECT * FROM posts WHERE slug="${slug}"`, (err, post) => {
        if (err) throw err;
        if (post.length) {
            res.render('post', { post: md.render(post[0].content) });
        } else {
            res.send('404');
        }
    });
```

Solved it. If slug is wrong, then no error catches, but length of the result will be zero. And when in this case, you have to return a response.

**Comment by numberend** [comment]
Sequence.js is buggy! if table or data not found sequence cannot not return a stack! 
The code is no checking it, therefore parser.js is exceptional. 

Otherwise i not understand the logic on parser.js line 79, it's directly bypasing error statement!

Sequence.js
    Buggy    115. if (err.stack.indexOf(LONG_STACK_DELIMITER) !== -1) 
   Correct   115. if (!err.stack || err.stack.indexOf(LONG_STACK_DELIMITER) !== -1) 

Thanks.

**Comment by dougwilson** [comment]
Hi @numberend please feel free to submit a pull request. Be sure to include a new test that fails without your fix and passes with it :)

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-111230~2](https://user-images.githubusercontent.com/68846734/88573598-e6f84e00-d038-11ea-8c17-3e4374bf04a3.png)

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-111323~2](https://user-images.githubusercontent.com/68846734/88573654-f5df0080-d038-11ea-94ef-a6f11f360a3d.png)

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-111338~2](https://user-images.githubusercontent.com/68846734/88573684-02fbef80-d039-11ea-89db-d0cf7dd2ce6a.png)

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-093404](https://user-images.githubusercontent.com/68846734/88573728-1313cf00-d039-11ea-8e4e-e2416d9ae3f0.png)
Contact,for sale.

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-111234~2](https://user-images.githubusercontent.com/68846734/88573795-32126100-d039-11ea-97dc-498da7cb9a41.png)
Contact,for buy.

**Comment by jacksmithloreenanderson** [comment]
![Screenshot_20200727-093419](https://user-images.githubusercontent.com/68846734/88573840-49e9e500-d039-11ea-9436-85ed31d7cd34.png)
Contact,for chipping.
