### ISSUE TITLE
Modify LastInsert id

### ISSUE THREAD

**Issue by Hamiid** [mysqljs/mysql#1544]
Is this possible to get last inserted id after inserting row with specific function?
I save primary key in my table with uuid and I need get them with HEX function.

**Comment by dougwilson** [comment]
The MySQL protocol and functions only work when your primary key is an integer. This is a limitation of the MySQL protocol itself and something this module is bound to (simply being a client library). In order to do what you are trying to do, you'd need to use a stored procedure

**Comment by Hamiid** [comment]
@dougwilson Thank you for your reply
