### ISSUE TITLE
Multiple Statements, throwing ER_PARSE_ERROR on Valid Query

### ISSUE THREAD

**Issue by clement360** [mysqljs/mysql#1545]
I have added "multipleStatements": true to my node-mysql options and run the following upon app startup:
```
this.connection.query('SELECT 1; SELECT 2', function(err, results) {
      if (err) {
        console.log("$$$ Error testing database: " + JSON.stringify(err));
      } else {
        // results is an array with one element for every statement in the query:
        console.log(results[0]); // [{1: 1}]
        console.log(results[1]); // [{2: 2}]
      }
 });
```
This is what I get in the logs: $$$ Error testing database: {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","index":0}

What's going on the sql must be valid, I copied it straight from the docs

**Comment by clement360** [comment]
of course I solved it immediately after posting. A config file was overriding the db options for local environments...

**Comment by wangfengyuan** [comment]
How to solve this？ I have the same problem

**Comment by sidorares** [comment]
@wangfengyuan double check that `multipleStatements` config option is actually set
