### ISSUE TITLE
Process crash: Cannot read property 'eofPackets' of null

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [mysqljs/mysql#1547]
mysql version 2.6.1
node version 4.5.0
maria db version 10.1.18

```
TypeError: Cannot read property \'eofPackets\' of null',
at Query.EofPacket (node_modules/mysql/lib/protocol/sequences/Query.js:111:18)',
at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:271:23)',
at Parser.write (node_modules/mysql/lib/protocol/Parser.js:77:12)',
at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:39:16)',
at Socket.<anonymous> (node_modules/mysql/lib/Connection.js:82:28)',
at emitOne (events.js:77:13)',
at Socket.emit (events.js:169:7)',
at readableAddChunk (_stream_readable.js:153:18)',
at Socket.Readable.push (_stream_readable.js:111:10)',
at TCP.onread (net.js:536:20)' ] }
```

Seen twice in quick succession.
Unfortunately we don't know what query if any was running at the time.
Any idea what could cause this?

**Comment by dougwilson** [comment]
Perhaps some kind of weird issue, not sure. Can you add `debug: true` to your pool/connection options and then post the output generated before that error occurs? That will help us figure out what is going on.

**Comment by liam-goodacre-hpe** [comment]
Sorry about the long delay.
Here are the logs around when this happens, we have hidden potentially sensitive parts with `...`.
Let me know if you need more info.  Thanks.

```
<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: 46,
  length: 200,
  type: 253,
  flags: 16388,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }

<-- EofPacket
EofPacket {
  fieldCount: 254,
  warningCount: 0,
  serverStatus: 43,
  protocol41: true }

<-- RowDataPacket
RowDataPacket ...

<-- EofPacket
EofPacket {
  fieldCount: 254,
  warningCount: 0,
  serverStatus: 43,
  protocol41: true }

<-- ResultSetHeaderPacket
ResultSetHeaderPacket { fieldCount: 8, extra: 49 }

<-- FieldPacket
FieldPacket {
  catalog: ...,
  db: ...,
  table: ...,
  orgTable: ...,
  name: ...,
  orgName: ...,
  charsetNr: undefined,
  length: undefined,
  type: undefined,
  flags: undefined,
  decimals: undefined,
  default: undefined,
  zeroFill: undefined,
  protocol41: true }

--> ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: ... }

<-- EofPacket
EofPacket {
  fieldCount: 254,
  warningCount: 0,
  serverStatus: 43,
  protocol41: true }

TypeError: Cannot read property 'eofPackets' of null
at Query.EofPacket (.../node_modules/mysql/lib/protocol/sequences/Query.js:111:18)
at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:271:23)
at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:77:12)
at Protocol.write (.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
at Socket.<anonymous> (.../node_modules/mysql/lib/Connection.js:82:28)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at readableAddChunk (_stream_readable.js:153:18)
at Socket.Readable.push (_stream_readable.js:111:10)
at TCP.onread (net.js:536:20)
```

**Comment by dougwilson** [comment]
Thanks, that helps a lot! What is the query in that last ComQueryPacket? Looks like that is what is causing the issue, so would be awesome to understand what query is making the server start off with a EOF packet so we can program in what to do under that condition.

**Comment by dougwilson** [comment]
Hi @liam-goodacre-hpe after investigating, I'm fairly certain I know what is causing your issue, but with no information provided here for how I can reproduce your particular issue, I have no way to know if I have resolved your issue or not for sure. Are you able to install a version of this module from this repository and test to see if your issue is resolved? Install the https://github.com/mysqljs/mysql/tree/new-qdp branch:
```
npm install mysqljs/mysql#new-qdp
```

**Comment by dougwilson** [comment]
Hi @liam-goodacre-hpe since I haven't heard back I'm going to assume this has resolved your issue. Please open a new issue if this does not turn out to be the case.

**Comment by liam-goodacre-hpe** [comment]
Thanks @dougwilson - I didn't see your previous messages; we will try this and get back to you with the results.

**Comment by dougwilson** [comment]
Thanks, that would be awesome if you could confirm / deny the changes :) !

**Comment by LiamGoodacre** [comment]
We haven't updated yet.  However we noticed something strange in the `RowDataPacket`.  It is supposed to be returning the results of a stored procedure which contains the results of two `SELECT` statements.  But we received the data from the first `SELECT` as though they were from the second.  Due to the differing number of columns between the two `SELECT`s and different types we found some strange data such as values being `NaN` and the last column having the value of `\u0000\u0000\u001d�\u0000`.

**Comment by liam-goodacre-hpe** [comment]
We haven't updated yet. However we noticed something strange in the RowDataPacket. It is supposed to be returning the results of a stored procedure which contains the results of two SELECT statements. But we received the data from the first SELECT as though they were from the second. Due to the differing number of columns between the two SELECTs and different types we found some strange data such as values being NaN and the last column having the value of \u0000\u0000\u001d�\u0000.

**Comment by dougwilson** [comment]
It's hard to say what is going on unless you can provide some ay I can reproduce the issue or maybe provide a PR with a fix. It's also possible that is a symptom of the same error and this resolves that, but you'll need to test it to be sure, as I am unable to validate without reproduction steps.

**Comment by liam-goodacre-hpe** [comment]
Agreed; however, unfortunately we are also unable to reliably reproduce this. :(

**Comment by dougwilson** [comment]
Right. That's why I think you should try out the proposed fix, because I think I fixed the issue, so continuing to talk about the prefix state is probably not moving anything forward, because it doesn't tell me if I need to even investigate further :)
