### ISSUE TITLE
PROTOCOL_SEQUENCE_TIMEOUT when getConnection

### ISSUE THREAD

**Issue by Duncan00** [mysqljs/mysql#1549]
We got `PROTOCOL_SEQUENCE_TIMEOUT` when `getConnection` from Pool in `promise-mysql`.
The stack shows `Error: Handshake inactivity timeout`.

It is one time issue, wondering whether it is really connection problem suddenly occurred once or we have some incorrect handling in the connection pool.

As it is `Handshake inactivity timeout`, so we expect it is not related to specific queries or any deadlock timeout problems.

MySQL server: `AWS aurora5.6`

**Comment by dougwilson** [comment]
So when using the connection pool, it will re-use existing connections. If there are no connections available for re-use, it will try to connect to the server as a new connection. A failure to connect to the server is considered fatal to the pool, though you're welcome to try again in your code with some kind of back off and should probably program it to understand if the connection issue is transient (timeout) vs permanent (wrong username).

**Comment by dougwilson** [comment]
I hope it's OK @Duncan00 if I close this issue, as I think I answered everything and there hasn't been any response, so I don't think there is anything further to do on my end.
