### ISSUE TITLE
 Cannot find module './lib/protocol/SqlString' on escape fn

### ISSUE THREAD

**Issue by ShaharLevy** [mysqljs/mysql#1551]
Hi,
Couldn't find any issue regarding this...

it's been happening inconsistently in my proccessess sometimes it's been working fine, 
yet throws this error on other times..
Using your module inside a lib i created , when using the escape function this is thrown.

> Error: Cannot find module './lib/protocol/SqlString' stack: Error: Cannot find module './lib/protocol/SqlString'
>     at Function.Module._resolveFilename (module.js:337:15)
>     at Function.Module._load (module.js:287:25)
>     at Module.require (module.js:366:17)
>     at require (module.js:385:17)
>     at loadClass (/home/ec2-user/git/my-repo/node_modules/my-lib/node_modules/mysql/index.js:136:15)
>     at Object.escape (/home/ec2-user/git/my-repo/node_modules/my-lib/node_modules/mysql/index.js:64:19)
>     at Pool.escape (/home/ec2-user/git/my-repo/node_modules/my-lib/node_modules/mysql/lib/Pool.js:279:16)

Thanks for the great Module :).

**Comment by dougwilson** [comment]
Weird, I've never seen that issue before. Perhaps your installation is corrupted somehow? I would expect that error to show up on Travis CI, at least. The current versions of this module do not have a `./lib/protocol/SqlString` module, so maybe somehow you have files on your disk that correspond to two different versions at the same time?

**Comment by dougwilson** [comment]
Sorry, this module does have that file, sorry! I still don't understand what your issue is, and since I haven't heard anything back, I'm going to close this issue. If you can provide some additional context here, I'd be happy to re-open.

**Comment by AdriVanHoudt** [comment]
Only thing I can imagine is a npm install gone wrong. @ShaharLevy try removing your node_modules folder and running `npm install` again

**Comment by ShaharLevy** [comment]
@dougwilson Thanks for the help and sorry I didn't answer probably missed the first notification ...
@AdriVanHoudt Thanks ! it was probably a bad install as you said, I don't quite understand how it happened..
This can stay closed sorry for the trouble and thanks again. :)
