### ISSUE TITLE
[Q] How to use mysql functions?

### ISSUE THREAD

**Issue by trzyrazyzero** [mysqljs/mysql#1552]
I have code like this:
`connection.query('INSERT INTO``test_table``SET ?', {user: 'test_user', uuid: 'UNHEX(REPLACE(uuid(), "-",""))' }, function(err, rows, fields) {
     console.log(err);   
});
`
How to make that unhex, replace etc. will work when inserting into?

**Comment by dougwilson** [comment]
You just can't use that escaping, as it assumes all the object values are u trusted (i.e. it has no way to tell if that value came from a user or something you typed, so it is always escaped). You'll probably want to use a more full-featured SQL builder.

**Comment by trex005** [comment]
I'm building a library that will allow users to specify HAVING conditions.  Is there a way to escape these?  If not can you point me to a "more full-featured SQL builder" that could?
