### ISSUE TITLE
If I call  stored procedures  which has out @totalpage what should I do

### ISSUE THREAD

**Issue by Messilimeng** [mysqljs/mysql#1553]
set @totalpage = 0;
call xiaoya.sp_common_pager('suppliers', 'name, logo, innerid', 'createdtime desc', '', '', 10, 1, '1000', 1, @totalpage);
select @totalpage;

**Comment by dresende** [comment]
You gave the correct response. The only issue you might face is trying to run those 3 queries in 1 call. You need to enable `multipleStatements` [(docs)](https://github.com/mysqljs/mysql#multiple-statement-queries) or make 3 separate queries.
