### ISSUE TITLE
connection.query  incompatible with sleep function?

### ISSUE THREAD

**Issue by JTorresConsulta** [mysqljs/mysql#1555]
connection.query doesnt work when i set a sleep() function as it:

```js
connection.query('UPDATE......')
sleepFor(2000);

function sleepFor( sleepDuration ){
    var now = new Date().getTime();
    while(new Date().getTime() < now + sleepDuration){ /* do nothing */ } 
}
```

**Comment by erikdubbelboer** [comment]
That's because sleep is blocking the main thread preventing it from doing anything else, such as handling the query.

I'm not sure what you are trying to accomplish. Maybe try something like:
```js
connection.query('UPDATE......');
setTimeout(function() {
  // Do what you wanted to do after the sleep.
}, 2000);
```

**Comment by JTorresConsulta** [comment]
Hi erikdubbelboer, thanks for your message.

I cant use setTimeout because i need 2 different  "threads" 
I solved with several setInterval() in main

Thank you again : )

**Comment by dougwilson** [comment]
@JTorresConsulta I'm going to close this issue has @erikdubbelboer was able to answer it. The `node-sleep` module's readme has the following disclaimer:

> These calls will block execution of all JavaScript by halting Node.js' event loop!

Since the event loop is blocked by your example, this module is unable to write the query to the network socket.
