### ISSUE TITLE
there is an error on placeholder(?)  not to be replace

### ISSUE THREAD

**Issue by javalivepeng** [mysqljs/mysql#1558]
code:  connection.query('insert xxxx set ? on duplicate key update ?', [entity, entity])

For a period of time can't replace the ? restart the system and  go to work. this is a bug?

**Comment by dougwilson** [comment]
I have never ran into this issue before, so it could be. We would love to take a look into to, but unfortunately there is not enough information provided for us to look. Can you please provide all the following information?

1. Version of Node.js you are using.
2. Version of this module you are using.
3. Complete code I can copy and paste and run that reproduces the issue.
4. Instructions for how to run the code with a description of what happens with the issue and what you are expecting to happen.

Thank you!

**Comment by dougwilson** [comment]
Hi @javalivepeng I'm going to close this issue due to lack of response.
