### ISSUE TITLE
ER_LOCK_WAIT_TIMEOUT in transaction when using connection pool

### ISSUE THREAD

**Issue by janoskaz** [mysqljs/mysql#1561]
When I use connection created using `createConnection` statement to run several SQL statemenst in a transaction, it works fine. When I use `var pool  = mysql.createPool` and then `pool.query`, I get `ER_LOCK_WAIT_TIMEOUT` errors from the database (when using transactions). This occurs only with some data and does not occur when using connection created by `createConnection`.

**Comment by dougwilson** [comment]
Are your running several transactions in parallel? For example, if you add `connectionLimit: 1` in your pool options, does the issue go away?

**Comment by janoskaz** [comment]
Thanks for the tip, I have found the problem. I need to create specific connection and use it or each statement in transaction, like this:

```
pool.getConnection(function(err, connection) {
  connection.query( 'START TRANSACTION', function(err, rows) {
    // do all sql statements with connection and then
    connection.query( 'COMMIT', function(err, rows) {
       connection.release();
    }       
  });
});
```

I would think that is a feature, not a bug:)

**Comment by dougwilson** [comment]
Hi @janoskaz what you posted above is exactly how you use transactions with the pool. What was your code like before?

**Comment by janoskaz** [comment]
I was using it like this:

```
var pool  = mysql.createPool({ opts });

pool.query( 'START TRANSACTION', function(err, rows) {
    // do all sql statements with connection and then
    pool.query( 'COMMIT', function(err, rows) {
    }       
  });
```

**Comment by dougwilson** [comment]
Ah, gotcha. @janoskaz that makes a lot of sense why you were having issues, then :) Yes, your change is definitely the correct way to do it :)
