### ISSUE TITLE
A lot of querys colapse my server 

### ISSUE THREAD

**Issue by JTorresConsulta** [mysqljs/mysql#1562]
Hi !

I am trying to make simple updates each second in my db from node with mysql and mySQL service are using 70% and every second more CPU usage.

I think the loop  is accumulating querys and not releasing the old.

This is my code. **All works correctly except** the accumulative high CPU usage in my server. 

I amvery gratefull if anybody can tell me a clue.  Maybe i can close, remove or release the query once used ...

Thanks!

```
var connection  = mysql.createPool({
    host: 'localhost',
    user: 'xxxxxxxxx',
    password: 'xxxxxxxxx',
    database: 'xxxxxxxxxxx',
    port: 3306
});

//Loop every second//
     connection.query("UPDATE myfield WHERE etc... ", function(error, rows){ if (error) throw error; });
//End Loop//
```

**Comment by JTorresConsulta** [comment]
is it the correct thread ...?

**Comment by JTorresConsulta** [comment]
Could someone help me? 
I do not want to go back to prehistory and write my data intxt  archives  ^_^

**Comment by dougwilson** [comment]
Hi @JTorresConsulta sorry I have been very busy :) Typically this area of GitHub is for issues, but I'm not sure if your report is an issue with the module, rather perhaps an issue with your code or that you are issuing queries at a rate faster than your MySQL server has the capacity to respond to.

Ultimately, there is not enough information here to really go off. Can you provide all the following information:

1. The version of Node.js you are using.
2. The version of this module you are using.
3. The full code you are using that has the issue (what you posted above has the important bits missing).
4. Help me reproduce your issue so I can dig in to it.

Thanks :) !

**Comment by JTorresConsulta** [comment]
Hi dougwilson!  Dont worry  ;)

1. I had this problem working with NODE v6.4 and v7.0
2. The version of this module is "mysql": "2.11.1",
3. Its very easy. My script open a connection, and after that launch a new update query every second or every 500ms. Sorry its difficult to write you my code because its connect with my server and the updated data comes from a http petition.

You can reproduce creating a  `connection.query("UPDATE yourfields WHERE etc... ` and calling every 500ms for ex with a setInterval like:

`setInterval(function() {  /*here your query*/ }, 500); `


I dont think its a problem in my server because I created the same script with PHP and mySQL server doesnt colapse. 

Thank you !

**Comment by dougwilson** [comment]
Hi @JTorresConsulta I believe the issue is that you misunderstand what the differences between the Node.js environment and PHP are; PHP does not actually execute it every 1s or 500ms, as it is a blocking environment, such that the second query won't execute until the first is completed. Node.js is a non-blocking environment, which means that if your query does not actually complete on the server within the 1s / 500ms you are doing, then you'll absolutely overwhelm your MySQL server. How long does your query take to complete?

If you are not satisified with my guess above, I can't do much else but simply guess unless you complete steps 3 & 4 above, otherwise I have no way to do anything else but throw random guessing at you until one sticks ;)

**Comment by JTorresConsulta** [comment]
Hi dougwilson !
Yes, I understand you. 

I dont know how can I know the time the query take to complete, but both my NODE script and PHP script complete the queries into the 500 ms required. I know because i am monitoring sending the result to a client with sockets and the client are receiving each 500 ms.

I cant copy/paste my script code becasue you dont understand it and I dont want you losse your time. I am goint to create a new simple script that create the same problem for you.

Thanks

**Comment by dougwilson** [comment]
Even better, if you can put together a pull request that fixes your issue, that would be the best way to get your issue addressed :) I'd be happy to merge.

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard back.
