### ISSUE TITLE
Need an example of Streaming mySql module with Node & Express

### ISSUE THREAD

**Issue by Andriy-Kulak** [mysqljs/mysql#1566]
Can someone provide an example of streaming large data sets ([based on this documentation](https://github.com/mysqljs/mysql#streaming-query-rows)) with 'mysql' module, node and express? There is documentation, but I don't understand how to query the data in smaller segments properly because I don't see any good examples. Any help would be greatly appreciated. The query works, it just takes to long time because the table I am referencing is huge so I want to break it down to render 1,000 rows at a time.

Here is my code:

```
const mysql = require('mysql');
const express = require('express');
const app = express();

const connection = mysql.createConnection({
    host: 'us-cdbr-azure-east-a.cloudapp.net',
    database: 'eagertobp',
    user: ******,
    password: *******,
    port: '3306'
});

connection.connect(function(err) {
if(err) {
    console.log('error')
} else {
    console.log('Connected');
}
});

app.get('/', function(req,resp) {

connection.query("SELECT * FROM submissionanalytics");
console.log('test');
connection
    .on('error', function(err) {
        console.log('err', err);
        // Handle error, an 'end' event will be emitted after this as well
    })
    .on('fields', function(fields) {
        console.log('fields hit');
        // the field packets for the rows to follow
    })
    .on('result', function(row) {
        console.log('result hit');
        // Pausing the connnection is useful if your processing involves I/O
        connection.pause();

        processRow(row, function() {
            console.log(row);
        connection.resume();
        });
    })
    .on('end', function() {
        // all rows have been received
    });
})

app.listen(1337);
```

**Comment by dougwilson** [comment]
Hi! This is a good idea, so any contribution to add an example would be neat! You probably don't really find any example of how to use `LIMIT` and `OFFSET` because that is not specific to this module and just a general "how to use SQL" type of thing, which there are many, many resources online for how to construct better SQL statements, including doing chunking / streaming with them.

**Comment by zeing** [comment]
`
const   mysql = require('mysql');

const dbInfo = {
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'test',
    charset: 'utf8_unicode_ci',
    typeCast: function (field, next) {
        if (field.type == 'JSON') {
            return (JSON.parse(field.string()));
        }
        return next();
    }
}

var connection = mysql.createConnection(dbInfo);


function createRequest(command, callback,opt) {
    var query = connection.query(command,opt),
        contentStream=[];

    query
        .on('error', function(err) {
            // Handle error, an 'end' event will be emitted after this as well
            callback(err,{});
        })
        .on('fields', function(fields) {
            // the field packets for the rows to follow
        })
        .on('result', function(row) {
            // Pausing the connnection is useful if your processing involves I/O
            connection.pause();
            processRow(row, function() {
                connection.resume();
            });
        })
        .on('end', function() {
            // all rows have been received
            if(typeof callback == "function") {
                callback(null,contentStream);
            } else
                return contentStream;
        });

    function processRow(row,callback) {
        var dataString=JSON.stringify(row);
        var dataObj=JSON.parse(dataString);
        contentStream.push(dataObj);
        callback();
    }

}


module.exports = {
    createRequest : createRequest
};

`

**Comment by dougwilson** [comment]
Closing as no PR has materialized.
