### ISSUE TITLE
how do I find out which PoolCluster group was selected?

### ISSUE THREAD

**Issue by siddo420** [mysqljs/mysql#1569]
This is regarding the poolcluster feature https://github.com/mysqljs/mysql#pooling-connections .

For functions like the following, is it possible (inside the callback ) to find the exact group name that was selected ?
```
poolCluster.getConnection('SLAVE*', 'ORDER', function (err, connection) {}); // SLAVE1 or SLAVE2??
poolCluster.of('*').getConnection(function (err, connection) {});
```
Is the following valid and possible?
```
poolCluster.of('*').query( ... )
```

**Comment by dougwilson** [comment]
> For functions like the following, is it possible (inside the callback ) to find the exact group name that was selected ?

Hm, I don't think there is a way, so that would be a good feature to add!

> Is the following valid and possible?

Yes, it was just added in version 2.12.0 of this module (https://github.com/mysqljs/mysql/blob/master/Changes.md#v2120-2016-11-02) so you may just need to upgrade if you're getting an error trying to do that :)

**Comment by siddo420** [comment]
It would be helpful when you need to know which database/pool an object is being stored in.

Do you have an ETA for it?

**Comment by dougwilson** [comment]
> Do you have an ETA for it?

Whenever you make a pull request to add it :)

**Comment by siddo420** [comment]
figured it out 
```
connection._clusterId
```
contains the selector
