### ISSUE TITLE
selector wildcard support for Pool Cluster

### ISSUE THREAD

**Issue by siddo420** [mysqljs/mysql#1570]
Pool cluster throws errors when wildcard selector is used as prefix or in the middle of selector string.

For example, I have the following setup:
``` 
> var mysql = require('mysql'  )
> var poolCluster = mysql.createPoolCluster();
> var config = { user: 'root', host:'127.0.0.1', password: '....', database: 'test' }
> poolCluster.add('MASTER', config);
```

The following throw errors:
```
> poolCluster.getConnection('*ER', function (err, connection) { console.log( err ) });
{ [Error: Pool does not exist.] code: 'POOL_NOEXIST' }
> poolCluster.getConnection('MA*ER', function (err, connection) { console.log( err ) });
{ [Error: Pool does not exist.] code: 'POOL_NOEXIST' }
```
Although, this works
```
> poolCluster.getConnection('MA*', function (err, connection) { console.log( err ) });
```

I think, all of selectors match MASTER, so they should technically work.

**Comment by dougwilson** [comment]
Hi @siddo420 I removed the "[Bug]" from the issue title because this is not a bug :) You're just asking for a feature that does not exist. You're welcome to make a pull request to add this new feature, though :) ! Please include the use-cases and proposal for why this should be a feature as well.

**Comment by siddo420** [comment]
A better of way doing this is to support regex in patterns but that can break existing code.

Would you be OK with that?

**Comment by dougwilson** [comment]
@ifsnow added support for regular expressions and I added support for the wildcard to be anywhere in the string, so I think all the bases with this request should be covered now :)

**Comment by siddo420** [comment]
when will this be included in main branch? 

I've tried 2.13.0.

**Comment by siddo420** [comment]
seems to work now ..thanks
