### ISSUE TITLE
insert/update of a column which is of type JSON

### ISSUE THREAD

**Issue by o1lab** [mysqljs/mysql#1573]
Im inserting/updating javascript objects using JSON.stringify() when a column is of type JSON.

While querying them back - typeCast suggestion made in #1267 comes as handy.

Is there a way I could use something similar to typeCast while inserting/updating javascript objects. So that I don't have to manually do a JSON.stringify( ).

**Comment by dougwilson** [comment]
Yes, the queryFormat option.

**Comment by o1lab** [comment]
@dougwilson : how to use queryFormat when inserting/updating JSON ? I see queryFormat use in select [here].(https://github.com/mysqljs/mysql/blob/96fdd0566b654436624e2375c7b6604b1f50f825/test/unit/connection/test-custom-query-format.js)

**Comment by dougwilson** [comment]
The queryFormat is run against all queries, not just SELECT. Just add your JSON.stringify in there similar to how you added the JSON.parse in the typeCast.
