### ISSUE TITLE
getting executed sql string using bluebird promise

### ISSUE THREAD

**Issue by yosiweinreb** [mysqljs/mysql#1575]
using promise the `conn.queryAsync` returns a promise, and does not return an object which i can get the executed sql string with the key `sql`

what is the way to get that string?

**Comment by dougwilson** [comment]
Hi @yosiweinreb this module has no `.queryAsync` method, so I'm not sure. Can you provide the code you are using? Our `.query` method returns the `Query` object you can get the SQL string from.

**Comment by yosiweinreb** [comment]
using :
 
     const Promise = require('bluebird')
     const mysql = require('mysql');
     Promise.promisifyAll(mysql);
     Promise.promisifyAll(require("mysql/lib/Connection").prototype);
     Promise.promisifyAll(require("mysql/lib/Pool").prototype);

You get a new method `queryAsync` on a connection, which returns a promise
Not sure if this related to bluebird or to this module

**Comment by dougwilson** [comment]
Yea, this is an issue with Bluebird; when it does the callback style function wrapping, it doesn't expose what the original function returned in any way.
