### ISSUE TITLE
Sequelize MySql Insert (using node mysql): Node js vs Django

### ISSUE THREAD

**Issue by anuranjit** [mysqljs/mysql#1576]
DB inserts from Sequelize take minimum thrice the time as compared to inserts by Django. Sometimes node is around 8- 10 times slower than python. (According to newrelic) The SQL fired by Django: Time ~2ms

```sql
INSERT INTO `table` (`created_on`, `updated_on`, `field2`, `field3`, `field1`, `field4`, `field5`, `field6`, `field7`, `fiedl8`) VALUES ('2016-11-03 14:52:31', '2016-11-03 14:52:31', NULL, NULL, 100617299, '68.00', '75.00', '75.00', 0, '1.00')
```

The SQL fired by Node: Time ~20ms
 ```sql
INSERT INTO `table` (`id`,`field`,`field2`,`field3`,`field4`,`field5`,`field6`,`field7`,`field8`) VALUES (DEFAULT,'68.00','75.00','75.00',0,1,'2016-11-03 09:46:05','2016-11-03 09:46:05',100617299)
```
Is the performance of node mysql less than of python driver? or are there any tuning params that can help optimize this ?

**Comment by dougwilson** [comment]
Is the performance of node mysql less than of python driver?

I have honestly never used python, so I have no idea. If you are seeing performance issues, it would be awesome if you could make pull requests to address them for us :)

or are there any tuning params that can help optimize this ?

There are no tuning parameters, but if you think there should be any, please let us know :) !

**Comment by dineshjoshi** [comment]
@anuranjit how did you measure the latency / time taken?
