### ISSUE TITLE
clarification on timezones

### ISSUE THREAD

**Issue by diginfo** [mysqljs/mysql#1579]
I am having problems getting to grips with timezones and would appreciate some clarification.

If I set a timezone in the connection setting, then it appears that this setting only converts the date / time in the database by the offset specified in this setting during a database read, however when you save a date, it does NOT adjust the date to match the timezone offset ?

    timezone: '+6:00',

If I execute the following, then dates ARE saved using the timezone specified in the sql statement:

     SET time_zone = '+6:00';

is it possible to configure the connection to write dates using the timezone setting without having to prepend every sql statement with SET time_zone = '+6:00'; ?

Many Thanks

**Comment by dougwilson** [comment]
> however when you save a date, it does NOT adjust the date to match the timezone offset ?

It should be. I just tried and it is being converted and all our tests for this pass. Can you please provide the version of this module you're using with complete code that has this issue along with instructions on how to run your code so we can take a look?

**Comment by diginfo** [comment]
Hi;

The version is 2.10.2

It's pretty impossible to show the code as it part of a huge app, but here's the testing procedure:

1 - Using Connection timezone
--
1.a - Change timezone in connection to be 1 hour before your localtime zone & restart
1.b - using the connection write a date into the database
1.c - using MYSQL CONSOLE or WORKBENCH or similar, query the table / field
1.d - In our tests, the date read back is the same as the local time and not 1 hour before.

2 - Using SET time_zone
--
1.a - Change timezone in connection to be 'utc' & restart
1.b - execute SET time_zone = '+/-X:XX'; 
1.c - using the connection write a date into the database
1.c - using MYSQL CONSOLE or WORKBENCH or similar, query the table / field
1.d - In our tests, the date read back is 1 hour before.

**Comment by dougwilson** [comment]
Thanks, but unfortunately your instructions are too ambiguous to look into. I have no issue converting even following your instructions, so there must be something wrong with your code. Since you don't have any code to share, I'm going to close this issue. If you can figure out your issue, please feel free to make a PR to fix it :)

**Comment by diginfo** [comment]
What I am doing is creating a transaction using the mysql nodejs connection and then verifying using a non nodejs connection that the date was saved correctly.

Sorry, but I don't understand what is ambiguous about that.

In my tests, if you connect to the database with any other utility or console application and query a transaction created using nodejs, the date that is returned is not -1 hour.

Can you let me know what is ambiguous and I wil try and clarify ?

**Comment by dougwilson** [comment]
What do your tables look like? What types are the columns? What exactly does your SQL look like when you do the query? How are you using this module in your code? I need the exact code you are using so I can understand how you are inputting dates: is it with a Date object? A string? Are there other parts of your code interfering with the conversion (this happens a lot, where people never share their code, and in the end, they realized the issue with somewhere in their code).

Unless you can just give me code to run, there is nothing I can attach a debugger to to figure it out.  You're the only one in the position that can debug the issue, so please if you can attach a debugger and debug it and send a PR or share your code.
