### ISSUE TITLE
query result cannot be store in node redis hmset, have to transform the rawdatapacket to pure object

### ISSUE THREAD

**Issue by Nomia** [mysqljs/mysql#1580]
* **Version**:  redis: ^2.6.3   mysql: ^2.12.0
* **Platform**: Mac OS Sierra
* **Description**: 
the problem was redis hmset(key, obj, callback). The obj can only be pure object. But the node mysql's query result was not a pure object. But being wrapped by something (RawDataPacket):
![image](https://cloud.githubusercontent.com/assets/1707818/20586304/bfb73e9a-b23d-11e6-8eb6-9527076bb467.png)

When I try to: 
`hmset(key, aRawDataPacket, callback)`

Redis will throw me some warning, saying that there are some value is null in my data. But it just don't save them.

When I try to: 
`hmset(key, pureobj, callback)`
It's OK. saved perfectly.

Could node redis and node mysql be in harmony with each other?

redis:
link: https://github.com/NodeRedis/node_redis

**Comment by sidorares** [comment]
@Nomia could you post exactly what error/warning redis gives?

**Comment by dougwilson** [comment]
I assume it is `Deprecated: The HMSET command contains a "null" argument` warning, which makes sense because the object in the screenshot has `pass`, `salt`, and `signature` all with the value `null`.

**Comment by dougwilson** [comment]
> The obj can only be pure object.

I just tested `node_redis` and this is not the case. I was not able to reproduce any issue. @Nomia please provided the complete code you are using with instructions on exactly how to reproduce the issue.

**Comment by Nomia** [comment]
Thank u for the quick reply. @dougwilson @sidorares 

It was my fault, my mocha test delete that key afterwards, sorry man :>

As I try to reproduce the issue, I found out that in my mocha test, I test every method, including the update method. When data was updated, I'll delete the key.

**Comment by dougwilson** [comment]
It's no problem! Happy to hear your issue is resolved :)
