### ISSUE TITLE
How to append new object property name  in a result row data packet query???

### ISSUE THREAD

**Issue by dreweird** [mysqljs/mysql#1581]
```js
var data = {
   "data"={}
}
 connection.query("SELECT * FROM table",function(err, rows, fields){
       if(rows.length != 0){
            rows['new'] = [1,2,3];
             data["data"]=rows
           console.log(data);
            res.json(data);
      }
})
```
In console log the rows['new'] is not included...I want to append the new object to the result row and the output will be like this....
```js
{
    "data": [
        {
            "id": 1,
            "name": "name",
            "new": [
                1, 2, 3
               ]
        } and so on
   ]
}
``

Somebody help me with this??

**Comment by ifsnow** [comment]
`rows` is an array.
```
[
  RowDataPacket { field1: value1, field2: 'value2' },
  RowDataPacket { field1: value1, field2: 'value2' }
  ....
]
```

so, you need to add a new object to each of array.
I think it's the way you want.

```
connection.query("SELECT * FROM table",function(err, rows, fields){
    rows.map(function(row) {
        row['new'] = [1, 2, 3];
    });

    data['data'] = rows;    
    console.log(data);
    res.json(data);    
});
```

**Comment by dougwilson** [comment]
Hi @dreweird this is a general how to write JavaScript question, rather than something to do with this module specifically. You'll get a lot faster answers if you ask on a site like Stackoverflow instead of the bug tracker of this module.

I believe @ifsnow has a decent example of how to accomplish your task: iterate over all the `rows` elements and set the `new` property on them, one by one.

**Comment by sidorares** [comment]
@dreweird ideally you should avoid mutating values returned by 3rd party library, in JS it's very easy to make a copy:

```js
   connection.query("SELECT * FROM table", (err, rows) => {
      data.data = rows.map((r) => Object.assign({}, r, {"new": [1, 2, 3]}))
      res.json(data)
   })
```
