### ISSUE TITLE
Is it a good choice to backup big data with this node mysql client?

### ISSUE THREAD

**Issue by calebeaires** [mysqljs/mysql#1583]
I want to understand how this plugin works to understand how its operation has impact on execution performance on a Electron.io Node app.

For example: I have to make some backup from a table with **2m (Million) lines** to another database. First i tried to do it with [node child_process](https://nodejs.org/api/child_process.html) on a Electron.io app. It works on development (``# electrion main.js `` ), but it don`t work on a  asar package since it has it own child process restrictions.

Here is what I have to do:

### Prepare the output database
```
DROP TABLE IF EXISTS MY_SECOND_DATABASE.BACKUP_TABLE;
CREATE TABLE MY_SECOND_DATABASE.BACKUP_TABLE (
 `NumberField` int(11) NOT NULL
 );
```
### Backup from database source
``mysql -h 127.0.0.1 -u root -proot MY_FIRST_DATABASE -e “SELECT NumberField FROM MY_TABLE” > /User/MacBook/Downloads/sql_output_content.txt``
### Then copy to another database
`` mysql -h 127.0.0.1 -u root -proot MY_SECOND_DATABASE -e "LOAD DATA LOCAL INFILE ‘/User/MacBook/Downloads/sql_output_content.txt’ INTO TABLE BACKUP_TABLE FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n'"``

### Doubts that have arisen

- Would be a better approach **if I use this node mysql plugin** to do the same operation since it does the same task I have doing on a spawn children process?
- Is there an alternative to accomplish more efficiently this task?

**Comment by dougwilson** [comment]
I'm sorry I didn't respond, but when I originally read your message I didn't understand your question(s) and meant to respond later (I didn't). I still don't exactly understand what you're asking though, can you elaborate?

**Comment by dougwilson** [comment]
Hi @calebeaires I'm going to close this issue since I never heard back.
