### ISSUE TITLE
Improve documentation for insert statement 

### ISSUE THREAD

**Issue by avmadhukiran** [mysqljs/mysql#1585]
in the insert statement connection.query( 'insert into table set ? ',obj,function(){}) if all the fields of obj is not matched it not showing up any error it just doesnt insert .

**Comment by dougwilson** [comment]
Hi @avmadhukiran I don't see that line anywhere in our README. Can you point to where it is?

**Comment by avmadhukiran** [comment]
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function(err, result) {
  // Neat! 
});
console.log(query.sql);

this part

**Comment by dougwilson** [comment]
Gotcha :) So you're asking that I add a `if (err) throw err;` line inside the function like all the others, correct? Would you be willing to make a pull request?

**Comment by avmadhukiran** [comment]
yes
