### ISSUE TITLE
Data losing in select query

### ISSUE THREAD

**Issue by bigearsenal** [mysqljs/mysql#1586]
Every time i refresh my site, i got different number of records in result even though the query was not changed. (Sometimes i got 25, some times got 33 records with the same query, the total number of records in db is 36). Some records are missing.
Here is the video clip
[https://youtu.be/myPizNIGMxo](https://youtu.be/myPizNIGMxo)

I use mysql pool
DB.js

```js
// Database connection
var config = require('../config')();
var mysql      = require('mysql');
var pool = mysql.createPool(config.db);

module.exports = {
    getConnection: function(callback){
        var self = this;
        pool.getConnection(function(err, connection){
            if (err) {
                console.log(err);
                callback(err, null);
                return;
            }
            callback(null, connection);
            connection.on('error', function(err){
                console.log(err);
                throw err;
                // self.getConnection(function(err, connection){
                //     callback(err, connection);
                // });
            });
        });
    }
};
```

query.js
```js
query: function(options, callback){
        ...
        var DB = require('./DB');
        DB.getConnection(function(err, connection){
            if (err) {
                callback(null);
                return;
            }
            connection.query(sql, function(err, result){
                if (err) {
                    console.log('Error ' + err.code + 'in ' + sql);
                    if (callback) {
                        callback(null);
                    }
                    return;
                }
                if (callback) {
                    callback(result);
                }
            });
            connection.release();
        });


    }
```
Do u know why? Thank you!

**Comment by ifsnow** [comment]
I don't know exactly why it works wrong.
but, I'm sure the position of `connection.release()` is incorrect.
This should be moved into the `connection.query()`.


Please check out the document below.
```
When you are done with a connection, just call connection.release() and the connection will return to the pool, ready to be used again by someone else.
```

Modified source below.
```
DB.getConnection(function(err, connection){
    if (err) {
        callback(null);
        return;
    }
    connection.query(sql, function(err, result){
        connection.release(); // This is the correct position.
        
        if (err) {
            console.log('Error ' + err.code + 'in ' + sql);
            if (callback) {
                callback(null);
            }
            return;
        }
        if (callback) {
            callback(result);
        }
    });    
});
```

**Comment by bigearsenal** [comment]
Thanks for replying.
But i had tried putting it in block first, then I tried putting outside, the result was the same.
So strange

**Comment by ifsnow** [comment]
You can turn on the debug setting to check the progress.

```
mysql.createPool({
    ....
    ....,
    debug : true
});
```

then, you can see protocol details. I hope you get a clue to the problem.

**Comment by bigearsenal** [comment]
Hi there, I tried debuging but it didn't help.
Maybe the problem caused because I got and released connection for each query. Should I do that? Or i should keep the connection for multiple queries?
If yes, so when should I release the connection? Before rendering?

**Comment by ifsnow** [comment]
I'm sorry you didn't find a clue.

I think it depends on your structure.

For one thing, You should release used connections as soon as possible.
That's because the connection is not returned to the pool until `release` is called.

```
pool.getConnection(err, conn) {
    conn.query(...., function(err, results) {
        conn.release(); // Good
        process(results);
        render(results);
        conn.release(); // Bad
    }
}
```

**Comment by bigearsenal** [comment]
So I have to release the connection after each query?
It seems not working perfectly.
For example, i have table authors, books and bookAuthors(bookID, authorID for many-to-many relationship). Then I retrieve bookID, then foreach bookID, i retrieve book detail.
Sometimes some books are missing.
I get connection and release it after each query

**Comment by dougwilson** [comment]
There has not been enough information provided to really say. In order to figure out what the issue is, we'll need you to help us setup your environment on our side so we can debug. This means we need to understand what your database looks like what your code is, and how you run your code to reproduce the issue. Once we can reproduce, we can debug the issue.

**Comment by dougwilson** [comment]
I'm going to close since I haven't heard anything back.
