### ISSUE TITLE
throws TypeError when inserting string

### ISSUE THREAD

**Issue by konstantinkrassmann** [mysqljs/mysql#1589]
Hi, 

As i try to execute the following query: 

``` sql
UPDATE tasks set _configuration='{\"name\":\"`Nightly\",\"description\":\"ABC: ??/??\\r\\nDEF: ??/??\\r\\nPumpe: ?\\r\\nDruck: ?\",\"recurringTime\":{\"transfer_recurr\":\"1\",\"recurring_once\":\"\",\"recurring_day\":\"01\",\"recurring_month\":\"01\",\"transfer_time_h\":\"22\",\"transfer_time_m\":\"00\",\"editable\":\"1\",\"editable_before\":\"0\",\"editable_after\":\"300\",\"start\":\"31.01.2014\",\"end\":\"31.08.2014\",\"action\":\"save\",\"type\":\"3\"}}', checked=1 where id=2
```

The sql throws the following error: 

```
TypeError: val.replace is not a function
        at Object.escapeId (C:\Development\api\node_modules\mysql\node_modules\sqlstring\lib\SqlString.js:30:20)
        at Object.format (C:\Development\api\node_modules\mysql\node_modules\sqlstring\lib\SqlString.js:91:21)
        at PoolConnection.Connection.format (C:\Development\api\node_modules\mysql\lib\Connection.js:287:20)
        at PoolConnection.query (C:\Development\api\node_modules\mysql\lib\Connection.js:209:22)
```

It seems like the framework doesnt like the "?" within the string, even if the string was escaped with `$connection.escape`.

I expect the framework to ignore such placeholder, if i dont pass any statement values.

**Comment by RzeszowPL** [comment]
i have the same error

**Comment by konstantinkrassmann** [comment]
Seems like a bug in SQLString itself. 
I end up overwriting the default queryFormat function, as suggested in the readme

``` javascript
  connection.config.queryFormat = function (query, values) {
             return query.replace(/\:(\w+)/g, function (txt, key) {
                    if (values.hasOwnProperty(key)) {
                        return this.escape(values[key]);
                    }
                    return txt;
                }.bind(this));
            };
```

And place my variables into the query like this
``` javascript
DatabaseAdapter.query( "Select * from users where id=:id", {id: 2});

**Comment by dougwilson** [comment]
You need to upgrade to version 2.12.0

**Comment by konstantinkrassmann** [comment]
@dougwilson I'm working with the lastest version (2.12.0), if query contains "?" it will throw errors.

**Comment by dougwilson** [comment]
The stack trace you provided is not from 2.12.0. I was not able to reproduce either. Perhaps can you either (1) provide the exact JavaScript code for me to run to reproduce the error or (2) make a PR to fix the error?

I don't know what to do if I can't reproduce and the only thing I see is a stack trace from an old version that did have this issue before a fix.

**Comment by konstantinkrassmann** [comment]
It's closed for me, but you should be able to reproduce, when executing something like

``` javascript
connection.query('UPDATE users SET foo = "??, ?", WHERE id = 1', [], function(err, results) {
  // ...
});
```

**Comment by ifsnow** [comment]
@konstantinkrassmann It seems like your query is incorrect. You must remove comma(,) after `foo = "??,?"

```sql
UPDATE users SET foo = "??, ?" WHERE id = 1
```

**Comment by dougwilson** [comment]
@konstantinkrassmann I still cannot reproduce. I think there is really only open option left: please make a PR to fix the issue.
