### ISSUE TITLE
Issue with "UPDATE"

### ISSUE THREAD

**Issue by RzeszowPL** [mysqljs/mysql#1595]
I have a problem with UPDATE. The problem is that the data is not uploaded to the database.

DB:
user_id = BIGINT(20) (76561198000000000)
user_name = VARCHAR(255) (Rzeszow)
numbers = INT(10) (5)

`connection.query('UPDATE users SET numbers = ? WHERE user_id = ?', [5, user_id], function(err, results, fields) {});`
This above does not work.
`connection.query('UPDATE users SET numbers = ? WHERE user_name = ?', [5, user_name], function(err, results, fields) {});`
But it's work.

How do you think user_id is the large number or is it an error?
I checked everywhere they work user_id and user_name, and run everywhere, even in the INSERT, but here user_id has a problem.

**Comment by RzeszowPL** [comment]
I must add it here ?
```
var connection = mysql.createConnection({
  host     : 'MyHost',
  user     : 'MyUser',
  password : 'MyPass',
  database : 'MyDB',
  supportBigNumbers : 'True'
});
```

**Comment by ifsnow** [comment]
@RzeszowPL 

```
supportBigNumbers : 'True'
```
It's not coreect. This value should be set to Boolean format.
```
supportBigNumbers : true
```

**Comment by RzeszowPL** [comment]
```
var connection = mysql.createConnection({
  host     : 'MyHost',
  user     : 'MyUser',
  password : 'MyPass',
  database : 'MyDB',
  supportBigNumbers : true,
  bigNumberStrings : true
});
```
Did't work :(
