### ISSUE TITLE
When to start a Pool connection and when to end one? Can I have many Pool at one time?

### ISSUE THREAD

**Issue by hz0324** [mysqljs/mysql#1597]
I am a little confused of using Pool.
The demo shows how to use it at once. 
But in real production environment, when should I create a connection pool and when should I close it.

Should I create a connection pool and use it forever until the shutdown of the app server? Or should I create a connection pool once recieving a request and close the pool after finishing the request?

Thanks

**Comment by ifsnow** [comment]
@hz0324 
In my experience, I prefer to keep the pool while the server is running.
I think this is why we use the pool.

**Comment by hz0324** [comment]
@ifsnow yeah, it sounds reasonable, but I don't know whether it is good for a production environment. You know, teacher used to tell us : release anything after IO process. 

So I am really confused

**Comment by ifsnow** [comment]
@hz0324 

I'm sure the pool should be kept in the production environment.

An important thing is that you should release used connections as soon as possible.
That's because the connection is not returned to the pool until release is called.

```js
pool.getConnection(err, conn) {
    conn.query(...., function(err, results) {
        conn.release(); // Good
        process(results);
        render(results);
        conn.release(); // Bad. Other jobs cann't use this connection while process, render function are running.
    }
}
```

Your teacher seems to have told you about this.

**Comment by hz0324** [comment]
@ifsnow Ok, thanks you. I will give it a try. Hope everything works fine.

**Comment by dougwilson** [comment]
> Should I create a connection pool and use it forever until the shutdown of the app server?

Yes, this is exactly how you should run it. Just like you open the listening port for the HTTP server and don't keep closing it after each request, you open the pool at the start of the program and then don't close down the pool until the same time you're closing down your HTTP server. They have the same lifecycle.

**Comment by hz0324** [comment]
@dougwilson Thanks you very much. It really helps. One more question, do I need to worry about dealing with the errors when using pool? Or this lib will take care of them?

**Comment by dougwilson** [comment]
Hi @hz0324 it really depends on which type of errors you're referring to. The most generic answer is that if you use the pool and always provide a callback function to the `connection` methods, then there is no additional handling you need to do besides responding to the `error` argument in your callback methods.
