### ISSUE TITLE
Driver doesn't allow process to exit

### ISSUE THREAD

**Issue by acarstoiu** [mysqljs/mysql#1599]
Somehow it looks like after a connection is established (and a query is performed, if it matters) the Node.js process won't be allowed to exit naturally as nothing else must be executed. The connection is a simple one (no pooling).

The behaviour is identical to what happens when `setTimeout()` or `setInterval()` is called without `unref()`ing the created timer.

**Comment by dougwilson** [comment]
Did you call connection.end() to end the connection?

**Comment by acarstoiu** [comment]
Nope. But still, this shouldn't prevent the process from exiting. I'm using several other drivers (for other storage technologies) written in pure JS and they behave as expected.

**Comment by dougwilson** [comment]
So if you don't end the connection, there will be an open connection from Node.js to your server, and open TCP connections keep the event loop open. I haven't experienced the issue your having before. Can you please provide all the following information for me to look into this?

1. The version of this module you're using.
2. The version of Node.js you are using.
3. The complete source code of the script you are using that you see this occur.
4. Complete instructions on how to run the script, including a description of what you see happen when the issue occurs and explain what you think should happen.

Thanks!

**Comment by dougwilson** [comment]
I'm going to close since I haven't heard anything back.

**Comment by acarstoiu** [comment]
Well, fair enough, you were right to do so.
But not anymore. Being forced to wait for something, I had the time to put together the simplest test that reproduces the issue:
```javascript
'use strict';

var mySqlClient = require('mysql');

var connection = mySqlClient.createConnection({
    host: 'localhost',
    port: 3306,
    user: "xxxxx",
    password: "yyyyy",
    database: "test"
});

connection.query("SELECT 1;", function(error, rows) {
    if (error)
        console.log("Error occured:", error);
    else console.log("Result:", rows);
});
```
It runs indefinitely, after outputting the result:
```bash
# node sql
Result: [ RowDataPacket { '1': 1 } ]
^C
```
The expected behaviour is for the program to end. Node.js version is _6.9.4_ (but I doubt it matters too much), while the `mysql` driver is version _2.12.0_.

**Comment by dougwilson** [comment]
Thanks, but running your example shows the reason the process is alive is because the Node.js socket is still active on the event loop. Using require('net').createConnection directly from core had the same behavior. If you're expecting it not to keep the loop open, then you should report the bug to Node.js core.

**Comment by dougwilson** [comment]
If you think there is a way this module can solve this, please make a PR, because I really don't know, so help would be awesome!

**Comment by acarstoiu** [comment]
More than one year later, here is the solution (and it's been there since always :blush: ): https://nodejs.org/api/net.html#net_socket_unref
