### ISSUE TITLE
Do I have to use end() method of connection?

### ISSUE THREAD

**Issue by lugrugzo** [mysqljs/mysql#1600]
I'm `require`'ing this db.js module from other modules.

```
var mysql      = require('mysql')

var db_config = {
  host     : '127.0.0.1',
  user     : 'root',
  database : '',
  password : ''
}

var connection
	connection = mysql.createConnection(db_config)
	connection.connect(function(err) {
		if(err) {
			console.log('Database connection error:', err)
		}
	})

/* to prevent losing connection */
setInterval(function () {
    connection.query('SELECT 1', [], function () {})
}, 10000)

module.exports = connection
```
But in other examples I'm seeing like this. They are connecting mysql before query and ending connection after query:

```
conn.connect()
conn.query(...., funciton(err, result) {
    conn.end()
})

```

I'd like to know if my approach is wrong.

**Comment by dougwilson** [comment]
You're approach is OK. You only need to call `conn.end()` if you want to close the connection. Based on you using `setInterval`, it looks like you are not intending to close the connection, so you don't need to call `.end()`.
