### ISSUE TITLE
is it possible to access aws redshift ? currently im using node-redshift npm. 

### ISSUE THREAD

**Issue by kalitas** [mysqljs/mysql#1601]
but its written that its not stable...and this git much more reliable..

**Comment by dougwilson** [comment]
I have never heard of aws redshift before, so don't know off-hand. This module will work with any service that uses the MySQL wire protocol, if it uses that.

**Comment by kalitas** [comment]
is it possible to add aws driver to this lib?

**Comment by dougwilson** [comment]
I'm not familiar with aws red
shift. This module will work with any service that uses the MySQL wire protocol, if it uses that.

**Comment by femto113** [comment]
Redshift has its own custom protocol, for which Amazon provides ODBC and JDBC drivers for use by BI and data warehouse tools.  I believe behind the scenes it's really a flavor of Postgres, not MySQL.  Take a look at https://www.npmjs.com/package/node-redshift, which uses the pg module to connect.

**Comment by dougwilson** [comment]
Thanks, @femto113 . Then yea, it wouldn't be added to this module, since this module is to provide the MySQL protocol.

**Comment by kalitas** [comment]
@femto113 thanks, I finally use node-redshift...it seem to be much less reliable than odbc..but easier for me, maybe when delivery is done and time to breath will come :), i will deep dive into it.
