### ISSUE TITLE
timezone configuration option ignored or overwritten when using createPool

### ISSUE THREAD

**Issue by RobiFerentz** [mysqljs/mysql#1602]
As the title suggests, when using createPool (as opposed to createConnection) queries ignore the timezone configuration (e.g: 'utc') . The readme suggests this should not happen as a pool merely passes the config object to each connection it creates, but testing a time sensitive (i.e: getting data for last ten minutes of a predetermined hour) query shows this to be the case.

**Comment by RobiFerentz** [comment]
This seems to be happening due to using a queryFormat function, but if I format the query with the timezone passed into the format function, I still get the incorrect data.

**Comment by RobiFerentz** [comment]
Nevermind, my bad. I used msql.format incorrectly inside my queryFormat function

**Comment by dougwilson** [comment]
Hi @RobiFerentz sorry I wasn't able to respond before you closed the issue :) It sounds like your issue has been self-resolved, but let us know if you're having any additional issues :) !
