### ISSUE TITLE
Errors not rethrown? (Using Bluebird)

### ISSUE THREAD

**Issue by SenshiSentou** [mysqljs/mysql#1604]
Hi,

I experienced something interesting using node-mysql in conjunction with Bluebird. Not sure what's causing this or if it's even improper behaviour, but it struck me as odd that inner errors are not rethrown, but consumed (though at least logged, thankfully). I think the code speaks for itself:

```js
return db.newConnection(conn => {
    return conn.queryAsync("SELECT col1, col2 FROM `table` WHERE col3 = ?", [param])
    .then(results => {
        if(results.length > 5){
            throw "I am an error";
        }
    });
})
.then(() => {
    console.log("Awesome stuff!");
})
.catch(e => {
    console.log("Exception caught: " + e);
})
```

**Expected output:**
`Exception caught: I am an error!`

**Actual output:**
`I am an error!`
`Awesome stuff!`

**Comment by dougwilson** [comment]
I have never used Bluebird and this module doesn't do any promises by default. Unless you have a fix, then I'm not sure if there is anything we can do.

**Comment by dougwilson** [comment]
I'm going to close since I haven't heard anything further.
