### ISSUE TITLE
MYSQL createPool not creating pool

### ISSUE THREAD

**Issue by nmeri17** [mysqljs/mysql#1606]
I make a call to Mysql.createPool and it simply returns nothing. Every instance I have attempted using it either lies dormant or gets skipped in favour of processes that do not require it during their execution. The server itself returns no errors so I cannot tell what the cause is. It just crashes after some time with the message:

>   throw err;
>    ^
>
> Error: Connection lost: The server closed the connection.

on this line

    myPool.getConnection(function(err, connection) {
		if (err) {
			throw err;
		}

I have already read the docs, issues returning that crash report, a gazillion online tutorials on combining Node.js/Connect with the mysql module but none seems to be beneficial to anyone else but companies that sell pain relievers since I have had to patronise them so often from when I began trying to achieve this. Below is my full code:

```
          var http = require("http"), connect = require("./node_modules/connect"),    static = require("./node_modules/serve-static"),
    mysql = require("./node_modules/mysql"), bodyParser =   require("./node_modules/body-parser").urlencoded({limit: "20kb", extended:   true}), cookieSession = require("./node_modules/cookie-session"), app = connect(),
      myPool = mysql.createPool({host: "localhost", port: 1717, user: "root", pass: "", multipleStatements: true, acquireTimeout: Number.POSITIVE_INFINITY})
      .on("connection", function(connection) {console.log("new connect");});


     myPool.getConnection(function(err, connection) {
		if (err) {
			throw err;
		}
		connection.query("CREATE DATABASE IF NOT EXISTS db DEFAULT CHARACTER SET utf8 COLLATE utf8_general_mysql500_ci;USE db; CREATE TABLE IF NOT EXISTS users (email VARCHAR(150) NOT NULL , password VARCHAR(50) NOT NULL ) ENGINE = MyISAM;INSERT INTO users (email, password) VALUES ('email@gmail.com', '1717')",
			function(err, result) {
				if (err) throw err;
				else {
					console.log("created myPool");
					connection.release();
				}
		});
	});


    app = app.use(bodyParser)
    .use(cookieSession({secret: "mmay1717", maxAge: this.maxAge + (60 * 60 * 24 * 1000)}))
    .use("/login", login)
    .use(static(__dirname + "/public"));


        function login (req, res, next) {

	if (req.method == "POST") {
		var params = req.body, resObj = {errText: "", sessName: ""}; console.log("received post request");
		
		myPool.getConnection(function(err, connection) {
			if (err) {
				throw err;
			}
			connection.query("USE db; SELECT COUNT(*) FROM users WHERE email=? AND password=?", [params.email, params.pwd], function(err, numrows, rowInfo) {
				if (err) {
					throw err;
  				}

				else if (numrows/*.length >= 1*/) {
  					console.log(numrows);
					req.session.name = params.email.split("@")[0];
					resObj.sessName = req.session.name;
					res.end(JSON.stringify(resObj));
					connection.release();
				}
				else {
					resObj.errText = "Incorrect email or password";
					res.end(JSON.stringify(resObj));
					connection.release();
				}
			});
		});
	}
	else 
		res.end("output login page here");
		next();
    }

    http = http.createServer(app).listen(1717);
```

When I make a post request, it completely skips the mysql parts and affirms it received a post request. I've tried using "127.0.0.1" instead of localhost, tried my hands on the indiscrepancy of throwing errors vs using console.error, even tried passing the pool as a middleware to connect. When that did not work, I wrapped the pool in a middleware and passed it to `use`, ultimately, I reinstalled mysql just to be sure. The boulder still stands. Please help!

**Comment by dougwilson** [comment]
Hi @nmeri17 I'm sadly not really able to reproduce. Can you say what versions of all those modules you're using so I can install the same ones? Also the version of Node.js.

**Comment by nmeri17** [comment]
A whole month later? Oh Doug! The `package.json` looks so unrecognisable from the one I had when submitting this issue. But I installed them all around Dec 8-10 so they are all fairly up to date. The Node version is 6.3.1.

I eventually tried [Sequelize](http://sequelize.readthedocs.org/en/latest/) too and that did not pan out well either. I currently use Mongoose to store and retrieve records though so it's OK if you think the issue should be closed.

In hindsight, if I could go back in time to collaborate with myself, I would suggest commenting out that line invoking the next middleware. The application's current `use` stack does not call the `next` function even once and like I said, there are no issues with making POST requests anymore.

One last thing: I understand you've been too busy attending to the numerous issues associated with your many modules. If only there was a way to bring me under your wings, I could help with writing your modules and who knows, replying issues a lot quicker than a month plus.

**Comment by dougwilson** [comment]
Actually, I had just realized I made a mistake when I reformatted your issue above. Your `else` in your middleware is missing brackets, causing the `next()` to get invoked for even `POST`, which I accidentally didn't notice.

Changing
```
	else 
		res.end("output login page here");
		next();
```

to
```
	else  {
		res.end("output login page here");
		next();
        }
```

Is what seems to fix the issue for me, at least.

**Comment by dougwilson** [comment]
> If only there was a way to bring me under your wings, I could help with writing your modules and who knows, replying issues a lot quicker than a month plus.

Absolutely! The biggest help I really need is help answering and digging into issues just like this one. If you can help dig into these kinds of issues and either determine they are not an issue with the module or determine the fix that the module needs and make a PR, then we can get you joined into the organization to start just directly committing the fixes :) Let me know if this sounds agreeable!

**Comment by nmeri17** [comment]
I'm in. Let's see how it goes.
