### ISSUE TITLE
Boolean returned as Object Buffer

### ISSUE THREAD

**Issue by lviggiani** [mysqljs/mysql#1607]
Hi this is my first attempt with this node module, so perhaps I'm doing something wrong.

My query, returns boolean fields like this `{"type":"Buffer","data":[1]}` instead of `true` or `false`

This is how I do the query:

```
connection.query("SELECT * FROM Projects;", function(err, rows) {
...
```

**Comment by dougwilson** [comment]
Hi @lviggiani MySQL has no boolean type that I am aware of. Are you trying to emulate it with some other type? What does the `CREATE TABLE` look like for that `Projects` table?

**Comment by lviggiani** [comment]
You're right... it's actually not boolean. Here is the create table spec for that field:

**`exist` bit(1) NOT NULL**

**Comment by dougwilson** [comment]
Yea, I have seen that being used as a fill int (though usually `TINYINT(1)` is more common, imo). You can use our type casting definitions to do the conversations automatically (https://github.com/mysqljs/mysql#type-casting). There is an example in that section for `TINYINT(1)`, but you should be able to change the `field.type` in the example to `BIT` for your use-case.
