### ISSUE TITLE
How mysql with 'like' or 'where'?

### ISSUE THREAD

**Issue by wangwenjie1314** [mysqljs/mysql#1608]
I want to make my sql:

```sql
select uuid,name,age from user where name='www' limit 1,10;
```

and i write code:
```js
connection.query('select ?? from user where ? limit ?,?', [
	['uuid', 'name', 'age'], {
		name: 'www'
	}, (page.currPage - 1) * page.pageSize, page.pageSize
], function(err, result) {
       //some code
})
```

But, if i want this sql:

```sql
select uuid,name,age from user where name like 'www' limit 1,10;
```
I donot know how to write ；

——————————————

and more，

if i want this sql:

it Support
```
select uuid,name,age from user where name like 'www' limit 1,10;
```
At the same time，it Support：

```
select uuid,name,age from user  limit 1,10;
```

I donot know how to write ；

————————————————
Thank you looking forward to answer

**Comment by wangwenjie1314** [comment]
I Used sequelize to solve the problem

**Comment by dougwilson** [comment]
Hi @wangwenjie1314 since this is just a simple substitution, you would have to write `select ?? from user where name like ? limit ?,?` as the query. If you're looking for a full-features sql builder, sequalize can do it :)
