### ISSUE TITLE
Proper API reference

### ISSUE THREAD

**Issue by lucasprus** [mysqljs/mysql#1617]
Does this thing have a proper API reference like this one: 
https://github.com/kriskowal/q/wiki/API-Reference ?

I am looking at `connection.rollback` in the examples on the main page but don't know exactly when its callback argument is called.

**Comment by dougwilson** [comment]
The only documentation in the README. It would be awesome if you could contribute something you feel is a proper API reference or at least help us understand how we can improve the current docs such that you feel it is a proper API reference.

**Comment by dougwilson** [comment]
I'm going to close since I haven't heard back.
