### ISSUE TITLE
Gets the stored procedure output parameters

### ISSUE THREAD

**Issue by zymapp** [mysqljs/mysql#1618]
How to get stored procedure output parameters，
eg:
```sql
CALL selectUser(@code, @msg, ?);
```
Need to get `@code` `@msg` return value

**Comment by dougwilson** [comment]
You'll need to make at least two queries: one that makes the `CALL` and the other that `SELECT` the variables. Example: perform `CALL selectUser(@code, @msg, ?);` then do `SELECT @code, @msg;`.

**Comment by newlukai** [comment]
Also stumbled upon this. And I must admit I'm thinking it's madness to open the door to SQL injections (i. e. activate multiple statements) in order to get the return values of a Stored Procedure call, isn't it?

**Comment by dougwilson** [comment]
No, just make two different query calls (one with the `CALL` and a second with the `SELECT`).
