### ISSUE TITLE
collection does not turn into bulk insters

### ISSUE THREAD

**Issue by superhero** [mysqljs/mysql#1621]
From the documentation:

> Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')

This does ofc not state that the feature is supported, and I don't believe it is; so this should be considered a feature request in that case :) But I think the documentation indicates an expected behavior.

```
require('mysql').createPool(opt).query('INSERT INTO `db`.`tbl` SET ?', [{foo:'bar'}, {foo:'baz'}]);
```

```
INSERT INTO `db`.`tbl` SET `foo` = ('bar', 'baz');
```

**Comment by dougwilson** [comment]
Thanks for the suggestion! Last time it was tried, no one was successful at adding that syntax you showed. You're welcome to make a PR to add it!

**Comment by dougwilson** [comment]
As for the docs, it does not make reference or even imply the syntax you are showing in your code example. I don't understand how you would have come to that conclusion :)

**Comment by dougwilson** [comment]
Lol, as an additional note, your code example has the wrong argument. You are providing an array of two values, not an array of one value that is an array itself.your second argument needs to have another set of [] around it.

**Comment by superhero** [comment]
>Thanks for the suggestion! Last time it was tried, no one was successful at adding that syntax you showed. You're welcome to make a PR to add it!

Interesting! I will look it over and see if this challenge can be accepted ;)

>As for the docs, it does not make reference or even imply the syntax you are showing in your code example. I don't understand how you would have come to that conclusion :)

As I stated, **I think it indicates** an expected behavior. This does not mean that there is an error in the documentation. How I came to that conclusion; if nested arrays turns into a bulk insert, then I would assume that others also thought of the syntax I explained. I'm not proposing a change in the documentation, I'm implying it's expected because of other great functionality that already exists. Others seems to have touched the subject as you say, so I guess I'm not completely wrong here. I could probably have formulated myself better.

>Lol, as an additional note, your code example has the wrong argument. You are providing an array of two values, not an array of one value that is an array itself.your second argument needs to have another set of [] around it.

I was typing it up a bit to fast it seems, an additional wrapper would ofc be needed :)

**Comment by AlexKvazos** [comment]
I think you want to read #1189. Bulk inserts work, but you need an array to encapsulate your two-level collection.

**Comment by superhero** [comment]
@AlexKvazos idk how this is related to bulk inserts by object though. Did you misunderstand me? or am I missing something?

--- 

also, I solved the problem I had with the following code (if it could help someone else stumbling upon this) I could not follow the code enough to make PR, and the code is probably to dirty anyway...

```
      // parsing a bulk INSERT query
      const
      query    = 'INSERT INTO `db`.`tbl` SET ?',
      parts   = [],
      mapped  = {},
      iface   = collection.shift(),
      compose = value =>
      {
        switch(typeof value)
        {
          case 'object':
            value = value.toString();
            break;

          case 'undefined':
            value = null;
            break;

          case 'function':
          case 'symbol':
            throw `no support for the type: "${typeof value}" in collection`;
        }

        return typeof value == 'string'
          ? /* escape */ `'${value}'`
          : value;
      };

      for(let key in iface)
        mapped[key] = [compose(iface[key])];

      collection.forEach((item) =>
      {
        for(let key in iface)
          mapped[key].push(key in item ? compose(item[key]) : null);
      });

      for(let key in iface)
        parts.push('`' + key + '`=(' + mapped[key].join(',') + ')');

      console.log(query.replace('?', parts.join(',')));
```
