### ISSUE TITLE
Issue with asynchronus functions

### ISSUE THREAD

**Issue by akosijoy** [mysqljs/mysql#1624]
Not sure if I should call this an issue or I just don't know how to do it. I have a simple SQL select function and another function that uses the output of the select. But the second function keeps running before the sql select gets a value.

```js
var data = sqlConnect();
filterData(data); // ends up running before sqlConnec() finishes 
                  // so data is always empty when it runs.
```

Is there a way to make the code wait until data has value before making filterData() run?

I also tried a callback:

```js
sqlConnect(function(data){
    filterData(data);
});

function sqlConnect(callback){
    //sql connect code
    callback(data);
}
```

But I think since technically the sqlConnect 'function' finished it went to continue to the filterData function even though it was the sql connection that still didn't finish. Any help would be appreciated. Thank you

**Comment by sidorares** [comment]
your second approach is the way to go. Can you post more info why you think it does not work?

**Comment by dougwilson** [comment]
It would probably be useful to understand what `//sql connect code` actually is doing, because if that is something asynchronus then you'll still end up in the situation as the first. It may also be of interest to go through some general Node.js tutorials on writing asynchronus Node.js code since it can be quite the concept to first get started with if you're not used to writing the pattern.

**Comment by akosijoy** [comment]
Thank you for the fast replies.

A little more explanation, I'm editing an open source code that uses Meteor called OHIF. It has it's own database in Mongo and I need to connect it to another sql DB and compare the results of the two to make a filter. 
```

function sqlConnect(callback){
  var ownerFilter = [];
  var mysql = require('mysql');
  var connection = mysql.createConnection({
    host      : 'localhost',
    user      : 'root',
    password  : 'P@ssword*1',
    database  : 'study_owners'
  });

  connection.connect();

  connection.query('select * from studies where owner_id = \''+Accounts.userId()+'\'', function(error, results, fields){

    if(error) throw error;
    console.log("RESULTS OF SQL: ")
    console.log(results);

    results.forEach(function(result){
      ownerFilter.push(result['study_id']);
    });
    console.log("owner filter");
    console.log(ownerFilter);
  });

  connection.end();

  callback(ownerFilter);
}
```

This is the function that calls both sqlConnect() and filterData().

```
function resultDataToStudies(resultData) {

    var ownerFilter;
    var fd;
    sqlConnect(function(ownerFilter){
      return fd = filterData(resultData, ownerFilter);
    })
}
```

and this is the output: 
**I20170118-10:58:01.672(8)? went here ->console.log() in filterData
I20170118-10:58:01.673(8)? []              ->console.log() in filterData (value of ownerFilter var)
I20170118-10:58:01.673(8)? 3964225  ->console.log() in filterData(value of a studyId to be compared)
I20170118-10:58:01.674(8)? 4238399  ->console.log() in filterData(value of a studyId to be compared)
I20170118-10:58:01.674(8)? 738          ->console.log() in filterData(value of a studyId to be compared)
I20170118-10:58:01.675(8)? 1              ->console.log() in filterData(value of a studyId to be compared)
I20170118-10:58:01.873(8)? RESULTS OF SQL: ->console.log() in sqlConnect()
I20170118-10:58:01.874(8)? [ RowDataPacket {  ->console.log() in sqlConnect()
I20170118-10:58:01.875(8)?     p_id: 1,                
I20170118-10:58:01.875(8)?     study_id: '3964225', 
I20170118-10:58:01.876(8)?     owner_id: 'fNv7ZcTpiQ7PWwv72',
I20170118-10:58:01.876(8)?     owner_name: 'admin' },
I20170118-10:58:01.877(8)?   RowDataPacket {
I20170118-10:58:01.877(8)?     p_id: 3,
I20170118-10:58:01.878(8)?     study_id: '738',
I20170118-10:58:01.879(8)?     owner_id: 'fNv7ZcTpiQ7PWwv72',
I20170118-10:58:01.879(8)?     owner_name: 'admin' } ]
I20170118-10:58:01.880(8)? owner filter                         ->console.log() in sqlConnect()
I20170118-10:58:01.880(8)? [ '3964225', '738' ]            ->console.log() in sqlConnect()**

It's true I'm not used to asynchronous functions and while I've tried looking into them (I also tried making use of a promise). I can't seem to figure it out, so I just thought I'd ask for help. Thank you for the quick replies and any help you can give.

**Comment by dougwilson** [comment]
You just need to move the `callback(ownerFilter);` up into the function above it, probably right after the last `console.log`. Example:
```
function sqlConnect(callback){
  var ownerFilter = [];
  var mysql = require('mysql');
  var connection = mysql.createConnection({
    host      : 'localhost',
    user      : 'root',
    password  : 'P@ssword*1',
    database  : 'study_owners'
  });

  connection.connect();

  connection.query('select * from studies where owner_id = \''+Accounts.userId()+'\'', function(error, results, fields){

    if(error) throw error;
    console.log("RESULTS OF SQL: ")
    console.log(results);

    results.forEach(function(result){
      ownerFilter.push(result['study_id']);
    });
    console.log("owner filter");
    console.log(ownerFilter);
    callback(ownerFilter);
  });

  connection.end();
}
```

**Comment by akosijoy** [comment]
WOW it worked! thank you very much! I'm now confused on whether I should feel happy that it's working or sad that I feel stupid... but thank you very much!

**Comment by dougwilson** [comment]
It's no problem, glad we could help :) I used to be the same way, and there was definitely a beginning learning curve for callbacks :)
