### ISSUE TITLE
How to specify custom query format for a pool?

### ISSUE THREAD

**Issue by CLGitDev** [mysqljs/mysql#1626]
In the documentation, I've come across the statement "Pools accept all the same options as a connection." However, when I change my code from mysql.createConnection to mysql.createPool and fire a query, I'm getting ER_PARSE_ERROR.

I'm sure the syntax of my SQL is correct and it runs perfectly fine under a connection created via mysql.createConnection. Just want to double check what is the correct way of defining a custom query format for a connetion pool?

**Comment by dougwilson** [comment]
Since the pool config inherits from the connection config, everything available in the connection config is also available in the pool config.

**Comment by CLGitDev** [comment]
@dougwilson 

Below is the code snippet I'm using. It works perfectly for the createConnection function, but once I replace it with createPool, i'm getting parsing error. Could you please shed some light on what I might have done wrong?

```
var db = mysql.createConnection({
	host: <host>,
	user: <username>,
	password: <password>,
	database: <database>,
	debug: false
});

db.config.queryFormat = function (query, values) {
  return query.replace(/\:(\w+)/g, function (txt, key) {
    if (values.hasOwnProperty(key)) {
      return this.escape(values[key]);
    }
    return txt;
  }.bind(this));
};

var sql = 'SELECT * FROM table WHERE value1 = :value1 AND value2 = :value2';

db.query(sql, {value1: 'foo', value2: 'bar'}, function (error, rows, fields) {
  if (error)
    throw error;
  else
    console.log(rows);
});
```

**Comment by dougwilson** [comment]
@CLGitDev you need to define your `queryFormat` in the constructor; the property `db.config` is a different object between pool and connection.

**Comment by CLGitDev** [comment]
@dougwilson Thanks a lot for your help! It works well after the queryFormat is defined in the constructor.

**Comment by Telokis** [comment]
Hey @dougwilson !
I'm using a custom queryFormat and would like to do something like `pool.format` to have a look at my query before sending it. How would I do it without instantiating a connection?

Thanks!
