### ISSUE TITLE
Big integer returned +1.

### ISSUE THREAD

**Issue by lluiscab** [mysqljs/mysql#1627]
So I'm doing a query to my database but for some reason, the returned data is higher than the actual data on the mysql server.
[Picture](https://twitter.com/lluiscabCat/status/822814044658823170)

**Comment by dougwilson** [comment]
Hi @lluiscab this is a limitation of JavaScript itself: it cannot represent big numbers. You can try it yourself by even trying to `console.log` a number you typed in manually:
```
$ node -e 'console.log(147798296306515969)'
147798296306515970
```

This modules provides a bunch of connection options to help deal with big numbers when you need to, by either allowing you to get the numbers back as strings or as objects from the `bignumber.js` library.

See the https://github.com/mysqljs/mysql#connection-options for more information :)
