### ISSUE TITLE
package-json-validator returns validation errors for valid field values

### ISSUE THREAD

**Issue by lkisac** [mysqljs/mysql#1631]
Validating [package.json](https://github.com/mysqljs/mysql/blob/master/package.json) through http://package-json-validator.com returns invalid for repository shortcut syntax and npm auto-populated fields.

**Results:**
```
{
  "valid": false,
  "errors": [
    "Url not valid for repository: mysqljs/mysql"
  ],
  "warnings": [
    "Missing recommended field: keywords",
    "Missing recommended field: bugs"
  ],
  "recommendations": [
    "Missing optional field: homepage"
  ]
}
```

From pull request [#1630](https://github.com/mysqljs/mysql/pull/1630)

**Comment by dougwilson** [comment]
Right, I know, we already talked about it :) I'm not sure why you're opening an issue about it here, I don't run that validator web site.
