### ISSUE TITLE
Default Log-Warning on Pool Enqueue

### ISSUE THREAD

**Issue by sebastian48** [mysqljs/mysql#1632]
The default settings of a pool is to enqueue all new connection requests without logging any message to the console. So if somewhere in your code you forgot a connection.release(), at some point, nothing will work anymore and callbacks won't get triggered anymore.  What is more, this problem will probably not occur before you are already in production. And because there's no debugging message, finding what's wrong will get really though. 

So I would by default log a warning at the pool#enqueue event. Something like "mysql: # connections are waiting for available connection slot."

**Comment by dougwilson** [comment]
No module should log messages by default. Simply add a log on the event and you're done :) ! Then you can use whatever logging library you are already using.

**Comment by sebastian48** [comment]
Yes, as soon as you know where to look it is really easy.
To forget a connection.release() is rather likely, in my case it was a simple if (user.length <0) return; But everything worked fine, until last week. It appeared that every once in a while, the server had a meltdown. It is pretty hard to find a bug that occurs only days after starting the server and not leaving any error messages.
