### ISSUE TITLE
How to set Default Timezone with createPool() method.

### ISSUE THREAD

**Issue by 2505rathod** [mysqljs/mysql#1634]
How to set Default Timezone with createPool() method.
how to set Asia/Kolkata local time.

**Comment by ifsnow** [comment]
@2505rathod 

You can see `timezone` option in [this link](https://github.com/mysqljs/mysql#connection-options)

```js
var pool  = mysql.createPool({
  .....,
  timezone : '+0530' // Asia/Kolkata
});
```

I hope this helps.
