### ISSUE TITLE
make this package dependency-less

### ISSUE THREAD

**Issue by kaizhu256** [mysqljs/mysql#1636]
this is a nice-too-have feature to simplify npm-install (given how unreliable npm-install has become lately).

the simple-way to do this is to simply statically include the current npm-dependencies.  i provided an example @ https://www.npmjs.com/package/mysql-lite

![screen shot 2017-01-31 at 21 11 22](https://cloud.githubusercontent.com/assets/280571/22466139/ddc99332-e7f9-11e6-9366-d10a14a926a0.png)

![image](https://cloud.githubusercontent.com/assets/280571/22466058/7c70b2d2-e7f9-11e6-8ce8-bf8a30b73389.png)

**Comment by dougwilson** [comment]
I think having your separate module is the best way to approach this, because this module is not going to drop it's dependencies, especially as we continue to strip code out into the `mysqljs` organization as separate modules on GitHub to share with packages like `mysql2`.
