### ISSUE TITLE
Setting value to generated column produce UNKNOWN_CODE_PLEASE_REPORT

### ISSUE THREAD

**Issue by Akxe** [mysqljs/mysql#1639]
Setting value to generated column produce UNKNOWN_CODE_PLEASE_REPORT...
Not much to say, I am sorry I cant find the error number there

**Comment by dougwilson** [comment]
Hi @Akxe thanks for the report! Can you provide the following information as well?

The version of this module you were running when you got that error and the version of your MySQL server.

**Comment by dougwilson** [comment]
Hi @Akxe I'm not sure what to get added without some more information. Please feel free to add anything more at any time and I can always re-open :)

**Comment by Akxe** [comment]
Sorry I accidentally logged out of account.

MySQL: 5.7.17
mysqljs: ^2.8.0

**Comment by dougwilson** [comment]
So all the error codes for 5.7.17 were added in version 2.13.0 of this module. Perhaps you just need to upgrade?
