### ISSUE TITLE
Trigger - Phpmyadmin

### ISSUE THREAD

**Issue by MertOtrk** [mysqljs/mysql#1641]
How i can listen a trigger in node.js ? İ added on phpmyadmin, Trigger page. How i can listen changes like to postgresql ?

**Comment by dougwilson** [comment]
Hi @MertOtrk I'm not very familiar with phpMyAdmin or PostgreSQL, so I don't really understand what your question is. Perhaps you can make a PR to add the feature if that is a thing?

**Comment by MertOtrk** [comment]
Hello @dougwilson i need to listen changes. İ have a game, i trying to listen all changes in user table. İ cant check in every second, so i will use "trigger" feature. İts same to PostgreSQL. İn postgresql, i create a trigger function and type in node.js like this, "function.listen("LISTEN triggername")" and if will a changes, postgresql is call your function. How i can do this in mysql ?

**Comment by dougwilson** [comment]
I don't think it is part of the MySQL protocol.
