### ISSUE TITLE
Stored Procedure

### ISSUE THREAD

**Issue by nivoset** [mysqljs/mysql#1642]
So i have a mysql server running on a beaglebone green wireless.
Node: 5.12.0
node mysql: 2.13
mysql: 14.14 (dist 5.5.52)

when i run a procedure to give me a list of faults (i will say i have 5700 entries in it) on mysql workbench, it takes at most 10 seconds, however, when i use it in node, it takes a few minutes if it reports them at all (no error, just sits idle) sometimes it has taken 20 minutes to return the results to the console.

i tried to set the timeout setting for it, and i still dont get an error showing up. (set to 60000, so 60 seconds)

```sql
SELECT 	
   faultHistory.tableIndex,	 
   faultHistory.unixTime,	    
   FaultLookup.text as title,	    
   FaultLookup.type 
FROM 		
   `Monitoring`.`faultHistory`, 	    
   `FaultLookup`.`FaultLookup`,            
   `FaultLookup`.`FaultType`	
WHERE  
   faultHistory.faultIndex=FaultLookup.faultIndex 
AND FaultLookup.type = FaultType.id 
group by faultHistory.tableIndex 
order by FaultType.id desc limit 50;
```

this is the code inside the procedure

**Comment by dougwilson** [comment]
Hi @nivoset that is definitely weird :) Is it possible you can share the following to help me reproduce and dig into the issue: (a) a simple script that performs the query that has the behavior you mentioned above and (b) the schema of the tables used in the query above so I can reconstruct them?

**Comment by nivoset** [comment]
create statements below.


CREATE TABLE `FaultLookup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `versionIndex` int(11) DEFAULT '0',
  `alarmIndex` int(11) NOT NULL DEFAULT '-1',
  `faultIndex` int(11) NOT NULL DEFAULT '-1',
  `type` char(45) DEFAULT 'Unknown',
  `text` char(45) DEFAULT 'Unknown',
  `description` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=latin1;


CREATE TABLE `faultHistory` (
  `tableIndex` int(11) NOT NULL AUTO_INCREMENT,
  `carIndex` int(10) unsigned NOT NULL,
  `CPU` int(10) unsigned DEFAULT NULL,
  `faultIndex` int(11) DEFAULT NULL,
  `alarmIndex` int(11) DEFAULT NULL,
  `additionalData1` int(11) unsigned DEFAULT NULL,
  `additionalData2` int(11) unsigned DEFAULT NULL,
  `destination` int(11) unsigned DEFAULT NULL,
  `height` int(11) unsigned DEFAULT NULL,
  `fpm` int(11) DEFAULT NULL,
  `odometer` int(11) unsigned DEFAULT '0',
  `runCounter` int(11) unsigned DEFAULT '0',
  `unixTime` int(11) unsigned NOT NULL,
  PRIMARY KEY (`tableIndex`,`carIndex`,`unixTime`)
) ENGINE=InnoDB AUTO_INCREMENT=5738 DEFAULT CHARSET=latin1;

**Comment by nivoset** [comment]
this is the code that is ran. i replaced the function call with a direct call of it, though it doesn't seem to have changed how long it took.

`      //var query = 'call FaultLookup.GetAllFaults();';
      
      var query = "SELECT 	faultHistory.tableIndex, faultHistory.carIndex as carIndex, faultHistory.unixTime, FaultLookup.text as title, FaultLookup.type FROM `WebMRM`.`faultHistory`, `FaultLookup`.`FaultLookup`, `FaultLookup`.`FaultType` WHERE (WebMRM.faultHistory.faultIndex=FaultLookup.faultIndex AND WebMRM.faultHistory.alarmIndex=FaultLookup.alarmIndex) AND FaultLookup.type = FaultType.id group by faultHistory.tableIndex order by FaultType.id desc limit 500;";
      mysql.query({
            sql: query,
            timeout: 60000
         }, function (err, rows) {
         if (err) {
            console.log('error with call FaultLookup.GetAllFaults()' + " : " + socket.id);
            console.log(err);
         } else {
            console.log('got faultLog ' + new Date() + " length: " + rows.length + " " + socket.id);
            var sendNextChunk = function () {
               var howManyLeft = rows.length-1;
               console.log('send chunk ' + howManyLeft  + " : " + socket.id);
               var send = 25;
               if (howManyLeft < send) {
                  send = howManyLeft;
               }
               var tempArray = rows.splice(0, (send+1) );
               
               io.emit('faultLog', tempArray);
               //socket.emit('log', 'Sent Fault chuck: ' + send);
               
               if (socket.connected && rows.length) {
                  setTimeout(sendNextChunk, 150);
               }
            };
            setTimeout(sendNextChunk, 50);
         }
      });`

**Comment by nivoset** [comment]
i forgot i put in some code (as a test) to spit it out in smaller chunks, but it doesn't get the the got faultlog thing half the time, or if it does it takes forever.

i also changed it from a socket.emit to io.emit to make it not as bad for now (so any return would give the data)

**Comment by nivoset** [comment]
So i did find the issue, a test bit of code was running i forgot about (was hammering the mysql server since it wasn't for this stage, this bogged it down horribly).

This threw me off since the procedure ran instantly in workbench, but lagged on the server call for some reason. So it looks like its fine.

**Comment by dougwilson** [comment]
Ah, I see. Sorry I didn't get to investigate your issue before you were able to figure it out, though :(

**Comment by nivoset** [comment]
Thats fine, i was looking all over, this was odd. happy to stop you before
going into it
