### ISSUE TITLE
Charset utf8 not working

### ISSUE THREAD

**Issue by hieuandree** [mysqljs/mysql#1648]
Value in databse is `Hiáº¿u NgÃ´ Trung`. I use option charset : utf8 when create connection but result return same value in database. 

```js
var mysql      = require('mysql');
var connection = mysql.createConnection({
    host     : 'localhost',
    user     : 'name',
    password : 'password',
    database : 'db',
    port     : '3360',
    charset  : 'utf8'
});

connection.connect();

connection.query('SELECT * FROM `user_comment` WHERE `id` = "27"', function (error, results, fields) {
    if (error) throw error;
    console.log(results);
});

connection.end();
```

**Comment by dougwilson** [comment]
Hi @hieuandree I'm not sure I understand your question. It sounds like you're saying that you're already getting the same value back that is in the database, so I'm not sure what you're expecting, exactly.

Can you show the create table statement for the table you're using?

**Comment by hieuandree** [comment]
`CREATE TABLE `user_comment` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `uniqid` varchar(100) DEFAULT NULL,
  `id_vid` int(10) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `mobile` varchar(100) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `fullname` varchar(100) DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `extend` varchar(100) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;`

I use php insert fullname with value "Hiếu Ngô Trung", and i see value in DB is "Hiáº¿u NgÃ´ Trung".
I use nodejs mysql with setting charset utf8 in connection but result fullname return is "Hiáº¿u NgÃ´ Trung". I expect result is "Hiếu Ngô Trung"

**Comment by dougwilson** [comment]
If you see it as `Hiáº¿u NgÃ´ Trung` in the DB, how can Node.js return it any differently? Are you sure that php didn't mess up the value somehow?

**Comment by dougwilson** [comment]
I can certainly investigate it, but I need to understand exactly how to reproduce the issue in order to diagnose it, unless you have a PR in mind to fix.

**Comment by hieuandree** [comment]
When insert fullname with value "Hiếu Ngô Trung" , value in DB will is encode with charset utf8.
I think when get value from DB , result return will decode with utf8.

**Comment by dougwilson** [comment]
But we do decode the value with utf8, that's what I'm not understanding. Without a better understanding, I have no idea what I'm supposed to change here. Please submit a PR if you have an idea of what we're not doing.
