### ISSUE TITLE
Does node mysql allows updating multiple rows through one query

### ISSUE THREAD

**Issue by eMahtab** [mysqljs/mysql#1652]
I have to update multiple rows and I want to do it with one single query. I was able to insert multiple rows but I'm not able to update multiple rows, below is the code snippet 

```
var update_tasks="UPDATE tasks SET phy_1_id=? , phy_2_id=? where id=?";
                  db.query(update_tasks,[[-1,-1,10086],[-1,-1,10087]],function (er, results, fields){
                      if (er) {console.log("Error "+JSON.stringify(er));return res.status(500).send(er);}
                      else{
                        return res.status(200).json(results);
                      }
                  })
```

Can you tell what should I do.

**Comment by dougwilson** [comment]
This module should work find with any MySQL query. Is the above the query you are having an issue with? Are you getting an error running it, or something else?

**Comment by eMahtab** [comment]
Yes I'm using above query to update multiple rows, I'm getting below error

Error {"code":"ER_PARSE_ERROR","errno":1064,"sqlState":"42000","index":0}

Seems to be some parsing error but not sure whats wrong.

**Comment by dougwilson** [comment]
I'm not sure what you're trying to do in the values array--you're only supplying two values even though you have three question marks, and the values for the first two don't really make sense.

**Comment by eMahtab** [comment]
Yes I have three ? and I'm passing three values one for phy_1_id , other one for phy_2_id and the last one for id column of the row , that is the id of the where clause
 [[-1,-1,10086],[-1,-1,10087]]

**Comment by dougwilson** [comment]
That's just _two_ values. Check this out:
```
var values = [[-1,-1,10086],[-1,-1,10087]]
console.log(values.length)
```

That shows 2

**Comment by eMahtab** [comment]
Yes length of the array is two, because I'm trying to update two rows.

**Comment by eMahtab** [comment]
From the mysql package docs for updating a single row

```
connection.query('UPDATE users SET foo = ?, bar = ?, baz = ? WHERE id = ?', ['a', 'b', 'c', userId], function (error, results, fields) {
  if (error) throw error;
  // ...
});
```

But I'm trying to update multiple rows that's why I'm passing arrays of arrays 
[[-1,-1,10086],[-1,-1,10087]]

**Comment by dougwilson** [comment]
Gotcha. That's not possible to do. You're welcome to make a PR if you want to add that feature.

**Comment by dougwilson** [comment]
The way it works is each question mark (`?`) is replaced with each element in the array, so the README example
```
connection.query('UPDATE users SET foo = ?, bar = ?, baz = ? WHERE id = ?', ['a', 'b', 'c', userId])
```
 Is identical to the following:
```
connection.query('UPDATE users SET foo = ' + connection.escape('a') + ', bar = ' + connection.escape('b') + ', baz = ' + connection.escape('c') + ' WHERE id = ' + connection.escape(userId))
```

In your code above, you are doing
```
connection.query('UPDATE tasks SET phy_1_id=? , phy_2_id=? where id=?',[[-1,-1,10086],[-1,-1,10087]])
```

Which results in the following:
```
connection.query('UPDATE tasks SET phy_1_id=' + connection.escape([-1,-1,10086]) + ' , phy_2_id=' + connection.escape([-1,-1,10087]) + ' where id=?')
```

Which is not valid SQL

**Comment by eMahtab** [comment]
So I have to fire multiple update queries for updating multiple rows. Will this be good, considering performance. Or is there something else I can use to achieve this

**Comment by dougwilson** [comment]
We support any SQL query that MySQL supports. What is the raw SQL query you are trying to send?

**Comment by sidorares** [comment]
@eMahtab from performance point of view (especially if you have large number of rows to insert) probably best way to use `LOAD DATA INFILE` - see example here https://github.com/mysqljs/mysql/blob/eeca1326c5f4d67725a486ddf1ef12c3f12d2187/test/integration/connection/test-load-data-infile.js

**Comment by eMahtab** [comment]
I have a requirement in my application to update multiple rows in the table, thats it. 

update tasks 
set phy_1_id=342,phy_2_id=762
where task_id=878

update tasks
set phy_1_id=234,phy_2_id=763
where task_id=879

update tasks
set phy_1_id=235,phy_2_id=764
where task_id=880

.....

Basically I'm assigning records to multiple physicians and trying to update the rows in the tasks table.

**Comment by eMahtab** [comment]
I was able to insert multiple rows 

 ```
 var query = "INSERT INTO phase_physician(phase_name,physician_id,physician_name,physician_email,role) VALUES ?";
          var phase_physicians=[];
          body.selectedPhysicians.forEach(function(item){
                 var phy=[];
                 phy[0]=body.phase;
                 phy[1]=item.id;
                 phy[2]=item.name;
                 phy[3]=item.email;
                 phy[4]=item.role;
                 phase_physicians.push(phy);
          });

          db.query(query,[phase_physicians], function(er,data) {
              if (er) return res.status(500).send(er);
              return res.status(200).json(data);
          });
```

and I thought I can update multiple rows also like that. I am able to update single row but I'm looking to update multiple rows.

**Comment by dougwilson** [comment]
I don't believe MySQL has a syntax for bulk row updates in general, so I suppose MySQL would need to add syntax for that and then you could use it.

**Comment by dougwilson** [comment]
The closest you're going to get is either what @sidorares suggested or `REPLACE INTO`, though they're not exactly the same as `UPDATE`.
