### ISSUE TITLE
Execute external file or DELIMITER support

### ISSUE THREAD

**Issue by Deathangel908** [mysqljs/mysql#1653]
Is it possible to execute sql file ? 

Like an option I can read this file and pass its string content to `connection.query`, but it will fail because of lack of `DELIMITER` support.

Is there anything I can do to execute content of a file using mysqljs?

**Comment by dougwilson** [comment]
This module just implements the MySQL protocol, passing the data to your MySQL server instance. I don't think DELIMITER is a valid MySQL statement so the server probably rejects it.

**Comment by Deathangel908** [comment]
I didn't find if mysqljs supports executing external files. So to summarize there's no way to resolve `my use-case`?

**Comment by dougwilson** [comment]
Not unless you want to put a PR together.
