### ISSUE TITLE
When to release connection in a transaction?

### ISSUE THREAD

**Issue by bravecat** [mysqljs/mysql#1656]
``` javascript
mysqlPool.getConnection((err0, conn) => {
  if (err0) {
    throw err0
  }
  async.series([(cb) => {
        conn.beginTransaction((err) => {
          cb(err)
        })
      }, (cb) => {
        conn.query('insert into app_test(col) values (1)', (err, result) => {
          cb(err, result)
        })
      }, (cb) => {
        conn.query('insert into app_test(col) values (1)', (err, result) => {
          cb(err, result)
        })
      }, (cb) => {
        conn.commit((err) => {
          cb(err)
        })
      }
    ], (err, result) => {
    // position A 
    if (err) {
      conn.rollback(() => {
        connsole.error(err)
      })
    } else {
      connsole.log('success')
    }
  })
  // position B
})
```

Where should I put `conn.release()` , at position A or B? If at position A, will `conn.rollback()`  be called?
Thanks.

**Comment by ifsnow** [comment]
@bravecat It's just my opinion.

```js
if (err) {
  conn.rollback(() => {
    conn.release();
    connsole.error(err)
  })
} else {
  conn.release();
  connsole.log('success')
}
```

**Comment by bravecat** [comment]
@ifsnow Please Look at https://github.com/mysqljs/mysql#transactions, which does not call `conn.release()` in the rollback, why not?

And in my code above, if I put `conn.release()` at position A, mysql could still rollback. Why?

**Comment by dougwilson** [comment]
Hi @bravecat the response from @ifsnow is the correct solution. The link to the section in the README is how to use the transactions, but outside of the context of the pool altogether. You want to release back to the pool after your last operation on the connection, which would be within the release callback.

**Comment by bravecat** [comment]
@dougwilson Got it!
