### ISSUE TITLE
date query between escape values not working 

### ISSUE THREAD

**Issue by code-smith** [mysqljs/mysql#1657]
select * from tPayments where createdAt between ? and ? order by createdAt desc 
im passing values startdate,endDate in params but i get error. It works with hard coded values in db but not this way. any help ?

<img width="1240" alt="screen shot 2017-03-11 at 7 30 29 am" src="https://cloud.githubusercontent.com/assets/9841589/23819473/a2a12e22-062c-11e7-9377-e2ddf2b7d76a.png">

I'm using node 6+ so i managed to send date as string using date_var.slice(0,19).replace("T"," ")

**Comment by dougwilson** [comment]
Hi @code-smith can you show the full code that you are using? Hard to really know what is wrong with the code without seeing it, unfortunately.

**Comment by dougwilson** [comment]
Hi @code-smith I'm closing this since I never heard back.

**Comment by code-smith** [comment]
sorry, i dint notice this. But issues is solved. It was an error in my code. thanks a lot and  also sorry!!
