### ISSUE TITLE
SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user

### ISSUE THREAD

**Issue by runhwguo** [mysqljs/mysql#1660]
but i can connect to mysql from console,mysql version is the lastest 2.13.0, os is linux,in and my mac is ok,

`let sequelize = new Sequelize(config.db.database, config.db.username, config.db.password, {
  host: config.db.host,
  dialect: config.db.dialect,
  pool: {
    max: 5,
    min: 0,
    idle: 10000
  },
  dialectOptions: {
    charset: 'utf8'
  }
});`

`db: {
    dialect: 'mysql',
    database: 'avlab',
    username: 'avlab',
    password: 'av_lab_!@#',
    host: '10.189.30.34',
    port: 4029
  },`

**Comment by dougwilson** [comment]
Hmm, that seems weird indeed. Any idea what we can change or any instructions you can provide on how we cab reproduce the issue to debug it?

**Comment by runhwguo** [comment]
@dougwilson Thank you for your enthusiastic answer, I have solved the problem, when I was in the initialization Sequelize, forget to configure the port, and mysql default is 3306,so it denies!

**Comment by raahul1912** [comment]
I am facing same error. I am passing all necessary params into the function

`const DB_HOST: any = process.env.DB_HOST;
const DB_NAME: any = process.env.DB_NAME;
const DB_USER: any = process.env.DB_USER;
const DB_PASSWORD: any = process.env.DB_PASSWORD;
const DB_PORT: any = process.env.DB_PORT;

const sequelize = new Sequelize(DB_NAME, DB_USER, DB_PASSWORD, {
  host: DB_HOST,
  port: DB_PORT,
  dialect: 'mariadb',
  pool: {
    max: 10,
    min: 0,
    acquire: 30000,
    idle: 10000
  },
  define: {
    underscored: true
  }
});`
