### ISSUE TITLE
Incorrect row value returned, due to precision, particularly for 64bit values.

### ISSUE THREAD

**Issue by AJauntyShark** [mysqljs/mysql#1661]
I'm storing a value let's just say `801902278743625728`. This value is large and is stored as a `bigint(20)`. I noticed the return value loses precision and will look like `801902278743625700`, note the two last digits.

As a work around I'm doing this in my query.

`SELECT CONVERT(bigvalue USING utf8) as bigvalue ...`

This issue sounds like a limitation of Javascript, see [here](https://dev.twitter.com/overview/api/twitter-ids-json-and-snowflake). It was an odd case, so thought I would share!

**Comment by dougwilson** [comment]
Yep, it is a limitation of JavaScript. This module has multiple different options to deal with this, from using BigNumber objects to returning the numbers as strings. Just select the option that best fits your need :)

**Comment by dougwilson** [comment]
The full list of options can be found in our readme: https://github.com/mysqljs/mysql/blob/master/Readme.md#connection-options

**Comment by AJauntyShark** [comment]
@dougwilson sounds good, thanks for the quick response! :)
