### ISSUE TITLE
NPM pages needs typo fixed

### ISSUE THREAD

**Issue by sjfricke** [mysqljs/mysql#1664]
The `Getting the id of an inserted row` section of the [NPM pages](https://www.npmjs.com/package/mysql) has a typo in the code snippets

```
connection.query('INSERT INTO posts SET ?', {title: 'test'}, function (error, results, fields) {
  if (error) throw error;
  console.log(result.insertId);
});
```

should be `console.log(results.insertId);`

It is correct on the GitHub markdown page, but a novice user will waste time finding that bug due to a simple little typo

Is the NPM pages not linked up with the GitHub Markdown?

**Comment by dougwilson** [comment]
npm doesn't provide a way to update the NPM page without publishing a new version. It'll get updated when the next version is published :)
