### ISSUE TITLE
Weird stream pause behaviour with loads of rows

### ISSUE THREAD

**Issue by hendricha** [mysqljs/mysql#1670]
```js
var mysql = require('mysql');

var connection = mysql.createConnection('mysql://root@localhost/some_database');

var s = connection.query('SELECT * FROM some_table_with_lot_of_rows').stream();

s.on('data', function(data) {
  console.log(data);
  return s.pause();
});

s.on('error', function(err) {
  return console.log(err);
});
```
The expected behaviour would be, I think, that node would not exit indefinitely, since there is a query still paused. (Or there would be an eventual timeout.) However when the select returns significantly lots of rows (our table contained around 300 000) node exists directly after pause is called. Did I miss some mysql or node-mysql quirk, or is this a bug?

**Comment by dougwilson** [comment]
H @hendricha what exit code does the Node.js process exit with when this happens? Can you provide the version of this module, version of Node.js, and the data I can run this against to reproduce?

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard anything back.
