### ISSUE TITLE
Support for ECMAScript 6's Internationalization & Localization Date/Time Formatting

### ISSUE THREAD

**Issue by Faegy** [mysqljs/mysql#1673]
It would be useful to add a connection option like `IntlDate: true` that would make all queried dates return as `Intl` objects (ECMA6) rather than the current `Date` objects.

This would allow us to achieve a more internationalized code.

**Comment by dougwilson** [comment]
I would suggest just defining your own custom type cast for this prupose: https://github.com/mysqljs/mysql#type-casting
