### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by jesperlandmer** [mysqljs/mysql#1675]
I can't connect to the MySQL-database. I've googled some solutions, but none seems to work, or perhaps I haven't understood them. This is the setup:
```js
let express = require("express");
let mysql      = require("mysql");
let http = require("http");

let app  = express();
http.createServer(app).listen(8000, function() {
    console.log("Listening on http://localhost:" + port)
});

var connection = mysql.createConnection({
    host: "127.0.0.1",
    user: "root",
    password: process.env.DB_PASSWORD,
    database: "users",
    port: 8000
});

connection.connect();

connection.query("SELECT * FROM user", function(err, rows, fields)
{
    if (err) {
        console.error("error connecting: " + err.stack);
        return;
    }

    console.log(rows[0]);
});

connection.end();
```
Tried to setup the connection with "socketPath" and with another port, but they both returned error:

```
Error: connect ECONNREFUSED 127.0.0.1:3306
at Object.exports._errnoException (util.js:1034:11)
at exports._exceptionWithHostPort (util.js:1057:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
--------------------
at Protocol._enqueue (/vagrant/node_modules/mysql/lib/protocol/Protocol.js:141:48)
at Protocol.handshake (/vagrant/node_modules/mysql/lib/protocol/Protocol.js:52:41)
at Connection.connect (/vagrant/node_modules/mysql/lib/Connection.js:130:18)
at Object.<anonymous> (/vagrant/app.js:12:12)
at Module._compile (module.js:571:32)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
```
When the connection and listen listens on same port, it doesn't return any errors, but the connection doesn't seem to initialize.
`console.log(connection.connect()); // -> undefined`
I'm very new to using MySQL to node so I'm probably doing this all wrong, but can't figure out what the problem is

**Comment by yleshchuk** [comment]
Are you creating webserver at 8000 port and then trying to connect to it with mysql client?

**Comment by dresende** [comment]
1. You have to write async code, you cannot call `.end()` on the last line;
2. `.connect()` is useless in this case, it will be called automatically on `.query`;

Please reply with more information if the problem still persists.

- Can you access using mysql client or any other software?
- What node version? Server version?

**Comment by valterh4ck3r** [comment]
Same problem...

**Comment by valterh4ck3r** [comment]
Usin this tutorial : 
https://cloud.google.com/nodejs/getting-started/using-cloud-sql?hl=pt-br

I have same problem

**Comment by Koala-dev** [comment]
try to start mysql server first. it would get connected without server running.

**Comment by dontito94** [comment]
Same problem
