### ISSUE TITLE
How can I use this package with .my.cnf?

### ISSUE THREAD

**Issue by StephanBijzitter** [mysqljs/mysql#1676]
About `.my.cnf`: https://easyengine.io/tutorials/mysql/mycnf-preference/
I have this file in my user directory, and when running mysql (the real one, not this package) through the command line, it takes my config file and allows me to use it without providing a user or a password, as they are present in the config.

However, the following code does not work:
```js
mysql.createPool({
                connectionLimit: 100,
                //user: 'root',
                //password: 'password',
                database: schema,
                debug: false
});
```

`message: 'Access denied for user \'\'@\'localhost\' (using password: NO)' `

Specifying only the user does not work either, while specifying both does work correctly.
I'd love to be able to use my config file, but how?

**Comment by dougwilson** [comment]
Hi @StephanBijzitter sorry if you misunderstood what this module is. This is just a MySQL driver, not something designed to replicate everything the `mysql` command line tool does. There may be a module on `npm` that can parse the `.my.cnf` file and if so, you could combine this module with that one to load your config to get the behavior you desire.

**Comment by StephanBijzitter** [comment]
@dougwilson But that would essentially add `-p mypassword` to the command sent to mysql, right? In which case the password would show up in all kinds of logs on a server.

I'm not too familiar with mysql, but afaik _not_ providing `-u` and `-p` should be enough for mysql to load and parse the config file on its own.

**Comment by dougwilson** [comment]
Hi @StephanBijzitter I'm not 100% clear on what you're suggesting, because this is a Node.js module, not a command line client, so there are no `-p mypassword` options, for example.

**Comment by dougwilson** [comment]
There may be a module on `npm` that can parse the `.my.cnf` file and if so, you could combine this module with that one to load your config to get the behavior you desire.

**Comment by dougwilson** [comment]
The module https://www.npmjs.com/package/node-ini looks like a candidate. Here is an example you could use:
```js
var ini = require('node-ini');
var mysql= require('mysql');

var config = ini.parseSync('/path/to/your/.my.cnf');

mysql.createPool({
                connectionLimit: 100,
                user: config.client.user,
                password: config.client.password,
                database: schema,
                debug: false
});
```

**Comment by StephanBijzitter** [comment]
Yeah parsing .ini files is not a problem, i'd use `node-file-parser` for that though.

I thought this package (mysql) was just a wrapper around the CLI. If that is not the case, parsing a file and using the values would be perfectly fine. As that would indeed not make the password show up in any log files on the server.

Thanks :-)

**Comment by dougwilson** [comment]
Gotcha. No, this is actually a pure node.js JavaScript Client implementing the MySql protocol.

**Comment by ishmam999** [comment]
@dougwilson about the solution you gave what should be the directory of the .my.cnf file.
In my case I have the .my.cnf file in a different directory(not home). So ini.parseSync() throw an error saying that there is no such file.
