### ISSUE TITLE
Why matadata come with resultset in case of stored procedure

### ISSUE THREAD

**Issue by sapkal-manish** [mysqljs/mysql#1678]
Why matadata come with resultset, If we call stored procedure? explaining in details:

### If I write code as follows : 
```
 connection.query("SELECT userid, email, roleid from usertbl where userid = 1;", function(err, rows, fields) { 
    console.log(rows);
})
```
### Result is :
`[ { userid: 1, email: 'a@b.com', roleid: 1 } ]`

### but same query called within stored procedure like as follows:
```
 connection.query("CALL sp_getuser(1);", function(err, rows, fields) { 
    console.log(rows);
})
```
### Result is :
```
[
[ { userid: 1, email: 'a@b.com', roleid: 1 } ],
{ fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 34,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 } ]
```

why matadata come like fieldcount, affectedRows etc..

And How to prevent it?

**Comment by dougwilson** [comment]
Hi @sapkal-manish this is MySQL server protocol behavior. The call of `SELECT` is a single result set over the MySQL protocol, but the `CALL` is a multi-result-set over the MySQL protocol.

When the server sends back a multi result set, you get in the callback `err, results` and `results` is an array of the `results`, meaning that `results[0]` is the first result of that (which would be the `SELECT` if that is the first result-generating statement in the procedure).

I hope that helps!
