### ISSUE TITLE
SIGNAL SQLSTATE with MYSQL_ERRNO not recognized as error

### ISSUE THREAD

**Issue by elaith9** [mysqljs/mysql#1679]
When executing a mysql procedure which contains following line: 	
SIGNAL SQLSTATE '45001' SET MESSAGE_TEXT = 'message', MYSQL_ERRNO = 1001; error is set to null and there are no row data packets in response. I was expecting message text and errno to be somehow returned. Im I missing something?

**Comment by dougwilson** [comment]
Hi @elaith9 is it possible to share the following?

1. Version of the MySQL server.
2. Version of this module.
3. The complete procedure I can load into a MySQL server and any necessary DDL to get it to run.
4. The query to invoke to see the issue.

Thank you!

**Comment by dougwilson** [comment]
I'm closing this issue since I never heard anything back.
