### ISSUE TITLE
pending pool connections

### ISSUE THREAD

**Issue by uribes78** [mysqljs/mysql#1682]
Hi, I have been using the pool feature, and is working very good. But I need to have a process checking how many connection are left on the pool. I use the "destroy" method on the connection to release them, so I need to know where there is no more connection active to close everything and finish the process.

It is that possible to do it? How do I know the process has finished all the SQL statement on the process.

Hope you can help me to achivie this.

**Comment by dougwilson** [comment]
Hi @uribes78 the `pool.end` (https://github.com/mysqljs/mysql#closing-all-the-connections-in-a-pool) is probably what you are looking for--after you have made all your queries from your code, you would call `pool.end` which will wait for them to complete and then invoke your supplied callback when everything is done and disconnected.

**Comment by dresende** [comment]
As @dougwilson wrote, `.end()` is the way to go. You can also check [Pool Events](https://github.com/mysqljs/mysql#pool-events).
