### ISSUE TITLE
CPU usage while waiting for query

### ISSUE THREAD

**Issue by kpetrow** [mysqljs/mysql#1684]
I'm running a complex query on some spatial data over 4 millionish rows and streaming the data back.  Everything is going ok except while node is waiting for the query to return data it uses about 10 percent of the CPU.  This is while mysql is doing its thing and i think node should be just sitting idle.  The wait time is expected given the query but the high cpu usage is not.  I just saw that maybe its due to "trace".  I have yet to test this but am doubtful.  Thanks.

**Comment by dougwilson** [comment]
Hi @kpetrow I haven't seen that myself, but would love to take a look. There is really no information to really work with here, so would at least need some starting information to work on, like the following:

1. The version of MySQL server.
2. The version of Node.js
3. The version of this module
4. A complete code that reproduces the issue so I can run and debug the issue

**Comment by kpetrow** [comment]
My bad, this was due to something else.  I did discover :
`select sleep (x)`

so not complete waste of time.
