### ISSUE TITLE
Dose this mysql driver support MariaDB 10.1 ?

### ISSUE THREAD

**Issue by XiaohuChen** [mysqljs/mysql#1685]
First, Thanks to your hard work !  I'm new to Nodejs , I just want to know if this mysql driver support MariaDB 10.1 ? 
           Thanks !

**Comment by dougwilson** [comment]
Hi @XiaohuChen yes, all MySQL drivers by default support MariaDB, since it uses the same protocol. We also specifically test against MariaDB 10.1 just to be sure :)

**Comment by XiaohuChen** [comment]
@dougwilson  Thanks very much!
