### ISSUE TITLE
Mysql disconnection after passed some hours

### ISSUE THREAD

**Issue by sdantuoni** [mysqljs/mysql#1688]
Error PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR

Hi, I have a REST API made in NodeJS and ExpressJS and the problem I am having is that when I spend several hours without making any requests, the connection to MYSQL is closed, then when I make a request again the connection is closed, I throw that Error and even though the API keeps running it does not work any query to the db that you want to do until you restart it. I saw some handleDisconnect and pool but I have not managed anything to work, besides this I would also like that if intentionally or for anything the mysql server closes also crashee the API by connect ECONNREFUSED 127.0.0.1:3306. Just try to connect silently until the MYSQL server is available again and connect. You could even log in a message but not the API to drop.

Server.js

```
REST.prototype.connectMysql = function() {
    var self = this;
    var pool      =    mysql.createPool({
        connectionLimit : 100,
        waitForConnections : true,
        host     : process.env.RDS_HOSTNAME,
        user     : process.env.RDS_USERNAME,
        password : process.env.RDS_PASSWORD,
        database : process.env.RDS_DB_NAME,
        debug    :  false,
        wait_timeout : 28800,
        connect_timeout :10
    });

    pool.getConnection(function(err,connection){
        if(err) {
          self.stop(err);
        } else {
          self.configureExpress(connection);
        }
    });
}

REST.prototype.configureExpress = function(connection) {
      var self = this;
      app.use(bodyParser.urlencoded({ extended: true }));
      app.use(bodyParser.json());
      var router = express.Router();
      app.use('/api', router);
      var rest_router = new rest(router,connection,md5);
      self.startServer();
}

REST.prototype.startServer = function() {
      app.listen(3000,function(){
          console.log("All right ! I am alive at Port 3000.");
      });
}

REST.prototype.stop = function(err) {
    console.log("ISSUE WITH MYSQL n" + err);
    process.exit(1);
}

new REST();

```

A simple endpoint of my API

```
router.get("/users/one/:id", function(req,res){
        var query = "SELECT * FROM ?? WHERE ?? = ?";
        var table = ["users", "id", req.params.id];
        query = mysql.format(query, table);
        connection.query(query,function(err,rows){
            if(err) {
                console.log(err)
                res.json(err);
            } else {
                res.json(rows);
            }
        });
    });
```

**Comment by dougwilson** [comment]
This question has come up multiple times, and whatever tutorial you're following really needs to be updated. I have no idea where it comes from. You can find a good discussion on this here: https://github.com/mysqljs/mysql/issues/1360#issuecomment-189091033
