### ISSUE TITLE
use like question

### ISSUE THREAD

**Issue by adminparry** [mysqljs/mysql#1690]
Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'where xxxxx like '%'xxx'%'' at line 1

however 
x 👎  "SELECT * FROM card WHERE name LIKE '%" + connection.escape(req.body.search) + "%'"
x 👎 'SELECT * FROM card WHERE name LIKE \'%\'hello\'%\''
x 👎 connection.query("SELECT * FROM card WHERE name LIKE ?", '%' + req.body.search + '%', function () {});
x 👎 connection.query("SELECT * FROM card WHERE name LIKE '%?%'", req.body.search, function () {});

**Comment by ifsnow** [comment]
@adminparry 

It seems that you're using the LIKE statement incorrectly.

This is a correct query.

```sql
SELECT * FROM card WHERE name LIKE %xxx%
```

You can use this as follows.

```js
const sql = 'SELECT * FROM card WHERE name LIKE ?';
const params = ['%' + req.body.search + '%'];

connection.query(sql, params, (err, rows) => {
  // logic
});
```
