### ISSUE TITLE
DATETIME and TIMESTAMP in the same way

### ISSUE THREAD

**Issue by lecosas** [mysqljs/mysql#1693]
Let me try to explain my problem.

I use a DB with some field's type TIMESTAMP and others DATETIME. In TIMESTAMP fields I store datetimes data in UTC (00:00), but in DATETIME I store data in local time (-03:00). 

As far as I realized, mysql module treat the same way TIMESTAMP and DATETIME converting them to my local time.

I put (+03:00) to my connection's option. So the timestamp works well, but the module adds +03:00 to datetime too. 

My options: 

var connectionPool = mysql.createPool({ 
  host :            '127.0.0.1',
  user :            'XXXXX',
  password :        'XXXX',
  database :        'XXXX',
  port :            3306,
  timezone:         '+03:00'
});

**Comment by dougwilson** [comment]
That's correct, they are both treated the same because that is the most common configuration. You can create a custom type cast function (https://github.com/mysqljs/mysql#type-casting) to change the behavior to perform however you which, though.

**Comment by lecosas** [comment]
Thanks a lot @dougwilson

**Comment by riwu** [comment]
@dougwilson I tried:

    if (field.type === 'TIMESTAMP') {
      console.log(field.string());
    }

It prints some weird characters, why? Works fine for `DATETIME`.
