### ISSUE TITLE
TypeError: val.slice is not a function

### ISSUE THREAD

**Issue by Ekzer** [mysqljs/mysql#1697]
Hi,
I'm getting an exception in this case:
The query : `"SELECT id FROM accounts WHERE dn = ?;"`
Where dn = 'sn=JB,dc=test,dc=test,dc=fr'
The call : `mysql.query("SELECT id FROM accounts WHERE dn = ?;", dn, callback);`

And here is the Stacktrace :

> error: uncaughtException: val.slice is not a function date=Tue Apr 18 2017 12:05:35 GMT+0200 (CEST), pid=31200, uid=501, gid=20, cwd=/Users/Documents/Acretion/common/acretion_www_common, execPath=/usr/local/Cellar/node/7.8.0/bin/node, version=v7.8.0, argv=[/usr/local/Cellar/node/7.8.0/bin/node, /Users/Documents/Acretion/common/acretion_www_common/app.js], rss=108945408, heapTotal=75468800, heapUsed=50643008, external=89838, loadavg=[2.20166015625, 2.0703125, 2.04443359375], uptime=478030
> TypeError: val.slice is not a function
>     at escapeString (/Users/Documents/Acretion/common/acretion_www_common/node_modules/sqlstring/lib/SqlString.js:183:23)
>     at Object.escape (/Users/Documents/Acretion/common/acretion_www_common/node_modules/sqlstring/lib/SqlString.js:53:21)
>     at Object.format (/Users/Documents/Acretion/common/acretion_www_common/node_modules/sqlstring/lib/SqlString.js:91:21)
>     at PoolConnection.Connection.format (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/Connection.js:281:20)
>     at PoolConnection.query (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/Connection.js:203:22)
>     at /Users/Documents/Acretion/common/acretion_www_common_modelAccess/mysql/mysqlClient.js:73:16
>     at Ping.onOperationComplete [as _callback] (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/Pool.js:110:5)
>     at Ping.Sequence.end (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
>     at Ping.Sequence.OkPacket (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/protocol/sequences/Sequence.js:95:8)
>     at Protocol._parsePacket (/Users/Documents/Acretion/common/acretion_www_common/node_modules/mysql/lib/protocol/Protocol.js:280:23)

Thank you in advance.

**Comment by dougwilson** [comment]
Hi @Ekzer thanks for the report! I tried out the code you provided, but could not reproduce the error. Here is what I'm doing:
```js
var dn = 'sn=JB,dc=test,dc=test,dc=fr';
conn.query("SELECT `id` FROM `accounts` WHERE `dn` = ?;", dn, function (err) {
  console.dir(err);
});
```

Can you help me figure out how this code is different from your code? Perhaps what version of this module, and complete code to run with instructions?

**Comment by Ekzer** [comment]
Hello @dougwilson,
I'm really sorry, it was a stupid error of mine... I passed the callback function as a query... Thanks to tiredness... I close the ticket,
Really sorry again and thank you for your help :)
