### ISSUE TITLE
column alias

### ISSUE THREAD

**Issue by p0d3r** [mysqljs/mysql#1699]
```
var userId = 1;
var columns = ['username', 'email'];
var query = connection.query('SELECT ?? FROM ?? WHERE id = ?', [columns, 'users', userId], function (error, results, fields) {
  if (error) throw error;
  // ...
});

console.log(query.sql); // SELECT `username`, `email` FROM `users` WHERE id = 1
```

Is there any way to set aliases for columns in this usage case?

For example I want to set an alias to `username` as `account_name`

**Comment by dougwilson** [comment]
Hi @p0d3r that is not possible. The substitution syntax is very limited to provide basic query building. You may be interesting in using a full query building module to construct the queries like https://hiddentao.com/squel/
