### ISSUE TITLE
How to escape a whole sql string instead of escaping each arguments?

### ISSUE THREAD

**Issue by aflext** [mysqljs/mysql#1701]
I have a mysql db query architecture in which i can not modify the sql quey file one by one to escape each arguments for there has too many files, but all the sql queries will call the `query` method of a same base mysql instance, so i wonder if i can escape the eventual sql string in the base mysql `query` mthod.

**Comment by dougwilson** [comment]
Hi! I'm not sure I understand your question. Can you provide additional details of what you're trying go do? Perhaps some kind of example of what the SQL string looks like and what you are trying to change it to?

**Comment by aflext** [comment]
@dougwilson 
I want to escape the whole  sql string  like `select * from tableA where name = 'foo'bar'` to `select * from tableA where name = 'foo\'bar'` with some function like `mysql_escape("select * from tableA where name = 'foo'bar'")` instead of doing this using `Preparing Queries` or concating escaped strings

**Comment by dougwilson** [comment]
Ah, I see, thanks for the information, @aflext ! This module does not have such functionality currently, so you (or someone) would need to implement it and can make a pull request adding the feature :)

**Comment by aflext** [comment]
@dougwilson well,i will try to fix it..Thanks a lot anyway.
