### ISSUE TITLE
release connection back to the Pool

### ISSUE THREAD

**Issue by mind84** [mysqljs/mysql#1703]
Hi, first of all, thanks for this library!

I would need clarifications about pooling connection and how it works. This is my basic code, it's a little script that I wrote just to understand and test the behavior of the pool function

```js
var mysql = require("mysql");


obConnection = {database: "myDevDb", user: "mySelf", password: "cript"};
obConnection.connectionLimit = 99;

var pool = mysql.createPool(obConnection);

pool.getConnection(function(err, connection){//getting the connection
	
	connection.query("select * from myTable", function(err, res){//perform query
		connection.release();//release connection
		
		if(err) console.info(err);
		else console.info(connection.threadId);
		
		connection.query("select * from anotherTable", function(err, res){
			if (err) console.info(err)//error expected here? connection has been released..
			else console.info(connection.threadId);
		})
	})
});

pool.on('release', function (connection) {
  console.info('Connection %d released', connection.threadId);
});

pool.on('acquire', function (connection) {
  console.info('Connection acquired', connection.threadId);
});

pool.on('connection', function (connection) {
  console.info("conn established")
});
```

and this is the output:

![output](https://cloud.githubusercontent.com/assets/20710470/25268749/382d15d8-267a-11e7-9e96-7aa50bd5feac.PNG)

What I would expect is an error on the second query ("anotherTable", just to be clare) because connection has already been released. 

Did i miss something? 

Thanks

**Comment by ifsnow** [comment]
@mind84 Unfortunately this module does not raise an error when you use the connection that has already been released, so make sure you're careful for using it.

**Comment by mind84** [comment]
@ifsnow Fine, thanks for the reply.

This means that the script fails to release connection? 

If not, what's the rule of `.release()` in the pool's "workflow?" It seems to me that the command is totally ignored.
Wondering if i'm missing the point here!

Again, thanks for yuor work!

**Comment by ifsnow** [comment]
@mind84 

```js
connection.query("select * from myTable", function(err, res) {
    // (1)
    connection.release();
    
    // (2)
    connection.query("select * from anotherTable", function(err, res) {    
    })
});
```

(1) This connection is added to the queue of free connections. It can now be used by other requests(`pool.getConnection`)
    
(2) It works well without error you expect. That's because the connection is still valid after `release`, but you should not use this connection because it can be used in other requests.

I think the following approach is good.

```js
connection.query("select * from myTable", function(err, res) {
    // logics
    connection.query("select * from anotherTable", function(err, res) {
        connection.release();
    })
});
```

or

```js
connection.query("select * from myTable", function(err, res) {
    connection.release();
    
    // long running complex logics
    
    pool.getConnection(function(err, connection) {
        connection.query("select * from anotherTable", function(err, res) {
            connection.release();
        })
    });
});
```

**Comment by mind84** [comment]
@ifsnow 
got it, thanks
