### ISSUE TITLE
not work LIMIT ? and OFFSET ? ..

### ISSUE THREAD

**Issue by XOneto9** [mysqljs/mysql#1705]
Hi,

AS syntax, I use LIMIT ? OFFSET 10,
full string of query is that "select * from placeReview where spotName = ? limit ? offset 10"

in above sentence, placReview is table name, and spotName is my one of columns name.
anyway, if I play query in nodejs.. then I get a error

Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'limit '20'' at line 1

like this,

also, I can not see anything else related of LIMIT and OFFSET information in the Code example..

**Comment by XOneto9** [comment]
I have still above problems.....


`var sql = "select * from placeReview where spotName=? limit ?,10"
    pool.getConnection((err, connection) => {
        if (err) {
            console.log(err);
            callback(true);
            return;
        }
        connection.query(sql, [qspotName, qpage], (err, results, field) => {
            connection.release();
            if (err) {
                console.log(err);
                callback(true);
                return;
            };
        console.log(results);
            callback(false, results);
        });
    });`

**Comment by XOneto9** [comment]
I have still problems.... T^T

`
var sql = "select * from placeReview where spotName=? limit ?,10"
    pool.getConnection((err, connection) => {
        if (err) {
            console.log(err);
            callback(true);
            return;
        }
        connection.query(sql, [qspotName, qpage], (err, results, field) => {
            connection.release();
            if (err) {
                console.log(err);
                callback(true);
                return;
            };
        console.log(results);
            callback(false, results);
        });
    });

`

**Comment by XOneto9** [comment]
I have still problems...

```
var sql = "select * from placeReview where spotName=? limit ?,10"
    pool.getConnection((err, connection) => {
        if (err) {
            console.log(err);
            callback(true);
            return;
        }
        connection.query(sql, [qspotName, qpage], (err, results, field) => {
            connection.release();
            if (err) {
                console.log(err);
                callback(true);
                return;
            };
        console.log(results);
            callback(false, results);
        });
    });
```

that is my whole code..
I don't know where I get error,

**Comment by dougwilson** [comment]
Hi @XOneto9 the error is occurring because your `qpage` variable is a string and not a number. You can convert it to a number using `parseInt` or similar: `qpage = parseInt(qpage, 10)`.

**Comment by XOneto9** [comment]
@dougwilson Thank you so much your answer! 
I will do to use your solution :) Thanks!
