### ISSUE TITLE
Why is query execution time so high ?

### ISSUE THREAD

**Issue by matt212** [mysqljs/mysql#1706]
Why does same query take around 300 ms more than actual execution time when using Mysql native driver for Nodejs , even with or without using "create pool" options?

Please refer highlighted section in below attached screenshot
![mysql](https://cloud.githubusercontent.com/assets/1698139/25308356/d064cbba-27cf-11e7-95fc-687999fc42a6.png)

Also for native driver execution time, please see below attached screenshot:

![native driver](https://cloud.githubusercontent.com/assets/1698139/25308358/db76b8a6-27cf-11e7-9d5a-7e0924271f71.png)

Codebase for node.js Mysql Native driver

db.js
```js

var mysql = require('mysql');
var connectionpool = mysql.createPool({
    connectionLimit: 100, //important
    host: 'localhost',
    user: "your user name",
    password: "your password",
    database: "your database",
    multipleStatements: true,
});

    exports.getConnection = function(callback) {
        connectionpool.getConnection(callback);
    };
```
emp.js
```js
var connections = require('../db');
     var pre_query = new Date().getTime();
        var sqlstatements = "select  * from employees where recordstate<>'raw'and  DATE(createdAt) " + "between ('1982-03-24') and ('2017-04-23')    order by employeesID desc limit 20 offset 0;" + "select COUNT(*) as count   from employees where recordstate<>'raw'and  " + "DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc";
        connections.getConnection(function(err, c) {
            console.log(sqlstatements)
            c.query(sqlstatements, function(err, projects) {


                console.log(err);
                if (!err) {
                    c.release();

                    var red = new Object();
                    red.rows = JSON.parse(JSON.stringify(projects[0]));
                    red.count = JSON.parse(JSON.stringify(projects[1]))[0].count;
                    var post_query = new Date().getTime();
                    // calculate the duration in seconds
                    var duration = (post_query - pre_query) / 1000;
                    console.log(duration)
                        // console.log(red);
                  

                }
            })
        })
```

**Comment by dougwilson** [comment]
Interesting, I'm not sure. Unless you can track down where exactly in the code the time is being taken, I can do it, but need to get enough information to set up the same thing you have there, if you can provide the details.

**Comment by matt212** [comment]
Hi @dougwilson ,
thanks for response and i think the setup would be any node.js version and  provided code  is decoupled , which in this scenario makes it pretty straight forword .
 make two files db config.js and emp.js and place the  provided code according and only thing missing is mysql table dump which i am providing right now.
please refer below gdrive link for the same 
https://drive.google.com/file/d/0B_sJE1z-87iTVXpISGFxZmlrRTA/view?usp=sharing

**Comment by dougwilson** [comment]
Thanks, @matt212 ! I don't have anything to open `.rar` files, can you provide in a more common format? Perhaps just a `.zip`?

**Comment by matt212** [comment]
@dougwilson ,
Sure , please refer below zip containing employee data for evaluation purpose

https://drive.google.com/file/d/0B_sJE1z-87iTM0ViZTRWVjFaN1E/view?usp=sharing

**Comment by dougwilson** [comment]
Thanks! While I was waiting, I did as you instructed and created a `db.js` with your code and a `emp.js` with the code. I tried to run `emp.js` and got the following error. What am I doing wrong?
```
$ node emp
module.js:471
    throw err;
    ^

Error: Cannot find module '../config/db'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mysql-1706/emp.js:1:81)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by matt212** [comment]
it require path of config db.js thats it !
make config folder or place where-ever one would seems fit and place the path in "require" statement ! 
 please refer db.js code snippet

**Comment by dougwilson** [comment]
Ok, so I changed the first line of `emp.js` to `var connections = require('./db');` and then I installed `npm install mysql`, but now I get the following error:
```
$ node emp
/mysql-1706/db.js:5
    user: config.development.username,
          ^

ReferenceError: config is not defined
    at Object.<anonymous> (/mysql-1706/db.js:5:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/mysql-1706/emp.js:1:81)
    at Module._compile (module.js:570:32)
```

**Comment by matt212** [comment]
hi @dougwilson  , 

you need to put your mysql credentials  there in place of "config.development" part of db.js code snippet !

**Comment by dougwilson** [comment]
Yes, I see now. I don't really have a lot of time right now, I thought it would be simple to run, but seems like I have to struggle to run, get error, fix error, run, get error, fix error, over and over. I'm happy to take a look, but please just provide the necessary instructions with complete, runnable code and when you do that, I'll come back another day and take a look. Thanks!

**Comment by dougwilson** [comment]
I tried messing around a little more before heading out, and got it to run, but I'm seeing an execution time of 0.177 (177 ms), which is way less than 300ms. I'm a bit unclear on what I'm supposed to be looking for, can you explain a bit more on what I'm supposed to be seeing when running your code / what you're trying to figure out? Here is the output of running the `emp.js` file against the dump you provided:
```
$ node emp
select  * from employees where recordstate<>'raw'and  DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc limit 20 offset 0;select COUNT(*) as count   from employees where recordstate<>'raw'and  DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc
null
0.177
/mysql-1706/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

ReferenceError: res is not defined
    at Query._callback (/mysql-1706/emp.js:21:21)
    at Query.Sequence.end (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.EofPacket (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
    at Protocol._parsePacket (/mysql-1706/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/mysql-1706/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/mysql-1706/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/mysql-1706/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by dougwilson** [comment]
And if I move the `var pre_query = new Date().getTime();` line down so it doesn't include the time setting up the TCP connection, handshaking with the MySQL sever, and performing the authentication and setting setup, I get that the query took 0.013 seconds. Here is the `emp.js` file I'm using for that:
```js
var connections = require('./db');
        var sqlstatements = "select  * from employees where recordstate<>'raw'and  DATE(createdAt) " + "between ('1982-03-24') and ('2017-04-23')    order by employeesID desc limit 20 offset 0;" + "select COUNT(*) as count   from employees where recordstate<>'raw'and  " + "DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc";
        connections.getConnection(function(err, c) {
     var pre_query = new Date().getTime();
            console.log(sqlstatements)
            c.query(sqlstatements, function(err, projects) {


                console.log(err);
                if (!err) {
                    c.release();

                    var red = new Object();
                    red.rows = JSON.parse(JSON.stringify(projects[0]));
                    red.count = JSON.parse(JSON.stringify(projects[1]))[0].count;
                    var post_query = new Date().getTime();
                    // calculate the duration in seconds
                    var duration = (post_query - pre_query) / 1000;
                    console.log(duration)
                        // console.log(red);
                    res.json(red);

                }
            })
        })
```

And it's output:
```
$ node emp
select  * from employees where recordstate<>'raw'and  DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc limit 20 offset 0;select COUNT(*) as count   from employees where recordstate<>'raw'and  DATE(createdAt) between ('1982-03-24') and ('2017-04-23')    order by employeesID desc
null
0.013
/mysql-1706/node_modules/mysql/lib/protocol/Parser.js:79
        throw err; // Rethrow non-MySQL errors
        ^

ReferenceError: res is not defined
    at Query._callback (/mysql-1706/emp.js:21:21)
    at Query.Sequence.end (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query._handleFinalResultPacket (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Query.js:137:8)
    at Query.EofPacket (/mysql-1706/node_modules/mysql/lib/protocol/sequences/Query.js:121:8)
    at Protocol._parsePacket (/mysql-1706/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/mysql-1706/node_modules/mysql/lib/protocol/Parser.js:75:12)
    at Protocol.write (/mysql-1706/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/mysql-1706/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

**Comment by matt212** [comment]
@dougwilson , 

if you refer mysql workbench query it is zero ms in nodejs object it is coming to near 285 to 300 ms in my machine ,
![machine](https://cloud.githubusercontent.com/assets/1698139/25309975/bd65659c-27f7-11e7-94f9-2b174af166d6.png)
another note
thanks for pointing out below 
a. time setting up the TCP connection
b. handshaking with the MySQL sever 
c. performing the authentication and setting setup
what is tentative ratio of query execution in mysql database and nodejs object  including aforementioned factors 
ratio example :-   1ms in mysql database then 2 ms in nodejs object

**Comment by dougwilson** [comment]
I don't have MySQL workbench, so in order to compare the times, can you explain exactly what they are including in their times? In the 0.013 seconds I posted above, that includes allocating memory in Node.js, then constructing the packet buffers to send to the MySQL server, then the network transfer time of sending the packet, then the query execution time, then the time of the results transfer back, then more memory allocation in Node.js, then trying to parse the received packets, then the time to cast the types into native JavaScript types, and the overheads with executing in a non-compiled language. It's not clear to me what you're trying to compare, unless you're asking where the 13 ms of overhead is coming from, but to do all of that in 13 milliseconds seems good to me. Do you have any suggestions of where to optimize out the 13 milliseconds from the Node.js code? From timing on my machine, 10ms of that was the network transfer time, leaving only 3 milliseconds within Node.js itself.

**Comment by dougwilson** [comment]
As for why you're getting near 285 to 300 ms on your machine, I really have no idea. I asked if you could explain how to get the same setup, but you said it didn't matter, so I just used what I had at hand. Without being able to reproduce the near 285 to 300 ms or get access to your machine, I don't really have a good way to determine where that time is coming from. I just ran the code you provided.

**Comment by matt212** [comment]
what is query is in a nutshell 
a.why is native driver for node.js slower as compared to query execution in database.
b.what would be tentative ratio of query execution in mysql database and nodejs native driver  including below factors 
1. time setting up the TCP connection
2. handshaking with the MySQL sever
3. performing the authentication and setting setup
4.allocating memory in Node.js, 
5.then constructing the packet buffers to send to the MySQL server,
6. then the network transfer time of sending the packet,
7. then the query execution time, then the time of the results transfer back,
8. then more memory allocation in Node.js, 
9.then trying to parse the received packets, 
10.then the time to cast the types into native JavaScript types,
if I had any pointers, i would have mentioned in post !
like 1 ms in mysql server and 2 ms in nodejs object due to above afoementioned factors 
Kinda curious , there has to be some standard ratio !

**Comment by dougwilson** [comment]
I already provided the details. If you're looking for the specific time on your machine, you'll need to run a profiler on your Node.js application. Here is the answers for all those on my machine from my run of 117ms which included all the steps you mentioned:

1. 30ms
2. 12ms
3. 62ms
4. <1ms (anything taking les than 1ms just shows as 0ms)
5. <1ms
6. 4ms
7. <1ms then 6ms
8. <1ms
9. <1ms
10. <1ms

Since all those <1ms added up into 3ms total, it's a bunch of fractions spread around.

I hope this helped!

**Comment by matt212** [comment]
Another aspect which i have observed when query execution after idle time it takes more time , then 
after it executes like seamlessly any pointers.

**Comment by dougwilson** [comment]
> Another aspect which i have observed when query execution after idle time it takes more time , then after it executes like seamlessly any pointers.

Hm, I'm not sure. If you can provide some code to run with details instructions so I can reproduce, I can then see where the time is being used.

> plus config of your machine and OS ?

![image](https://cloud.githubusercontent.com/assets/67512/25310223/ad8ff3fc-27ad-11e7-914a-b14b50e54944.png)

**Comment by matt212** [comment]
Woah , that is some **Heavy Rig**,  Kudos , but also  thanks for taking out time for explaining the intricate details of functional aspect of native driver !
Sure give me  a day or two will share across project via bitbucket , case in point you can provide me with your   bitbucket username or emailid in order for me to share the repo !

**Comment by dougwilson** [comment]
Hi @matt212 yea, just whatever I was issued for work. Unfortunately I do not have a bitbucket account, I'm just here on GitHub.

**Comment by matt212** [comment]
shoot, no worries will share it through gdrive in  .zip archive mode .
