### ISSUE TITLE
null variable is converted to 'null' instead of NULL

### ISSUE THREAD

**Issue by dekelev** [mysqljs/mysql#1707]
The docs states this: **undefined / null are converted to NULL**

I'm using v2.13.0 of this plugin and only undefined values are converted to NULL.
null values are converted to 'null' string, which seems to be a bug, according to the docs.

**Comment by sidorares** [comment]
hi @dekelev the conversion is done via https://github.com/mysqljs/sqlstring library. Can you reduce example to `SqlString.format()` call and post issue there?

**Comment by dekelev** [comment]
hi @sidorares the issue does not reproduce with a pure example using the **sqlstring** or **mysql** modules.
I'll debug the original code tomorrow and will either post the results or close this issue.

**Comment by dekelev** [comment]
@sidorares sorry, my mistake, the variable was wrapped in _JSON.stringify_ before it was added to the query.
