### ISSUE TITLE
Maybe add a way to make sure multipleStatements "result order" is always the same

### ISSUE THREAD

**Issue by dumpsters** [mysqljs/mysql#1709]
Just something I thought about... Recently I found out about `multipleStatements: true` and I've been using it alot, works great but I'm worried that a future update might change how the result order is returned, currently as far as I understand it returns the results in the same order as the queries order, all the time. If something changed it might break alot of programs that use this functionality.

Example:

```js
const DB = require('./db.js');

[...]

let qry = '';

for (let i = 0, len = json_request.length; i < len; i++) {
	let user = json_request[i];
	qry += 'SELECT user_id,user_name,user_email FROM users WHERE user_id = "' + user.id + '" LIMIT 1;';
}

DB.query(qry, null, (err, results) => {
	if (err) return cb(err);

	async.each(results, (user_db, cb) => {

		let user_found = json_request[results.indexOf(user_db)];
[...]
```

the `user_found` would return the wrong object. What are your thoughts on this? thanks in advance.

**Comment by dougwilson** [comment]
Hi @dumpsters I'm not sure I understand the question / request. This module does not provide any ordering of the results; it doesn't even understand if there are multiple queries or not. All this module does is talk the MySQL protocol to the MySQL server. If the SQL string happens to have multiple queries in it, the MySQL server will parse that, execute it, and return it in whatever order the MySQL server does. This module guarantees that you'll always get the results in the exact same order the MySQL server sends them back, which it guarantees is the exact order you wrote them in your SQL string.

**Comment by dumpsters** [comment]
Oh I was under the impression that when the query string had multiple queries, it was this module itself that ordered the results in the same order as the queries were typed in the string and not the mysql server itself that did the ordering, I guess you can close it then. Thanks
