### ISSUE TITLE
Multiple insertion in mysql database, You have an error in your SQL syntax; check the manual that corresponds to your MySQL

### ISSUE THREAD

**Issue by MagSag** [mysqljs/mysql#1712]
I want to insert multiple record at the same time in the database and for that here is my sql instruction :

  `  insert into tabo (fee,doo,ple,idur) values (?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?) ON duplicate key update tabo.doo=values(doo),tabo.fee=values(fee);`

Whe I am executing it, it is bringing this error:

> You have an error in your SQL syntax; check the manual that
> corresponds to your MySQL server version for the right syntax to use near  '?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?) ON duplicate key update tabo.doo=values(doo),tabo.fee=values(fee);

I am not able to know where exactly I have an error. I need help to know what is wrong with my query.

Here is my table tabo structure:
```sql
  CREATE TABLE tabo (
    fee varchar(100),
    doo time,
    ple time,
    idu int(11),
    PRIMARY KEY(idu,fee)
    ) engine=innodb;
```

I am using nodejs but even in mysql the query is not running and the package(module) I am using is mysqljs/mysql :

Here is my code:

```js
    connection.query('insert into tabo (fee,doo,ple,idur) values (?,?,?,?),(?,?,?,?),(?,?,?,?),(?,?,?,?) ON duplicate key update tabo.doo=values(doo),tabo.fee=values(fee)' ,['Good','12:00','14:00','Bad','18:00','20:00','best','02:00','04:00','worst','06:00','08:00'], function (error, results, fields) {
    if(error){
    console.log(error);
    }else{
    console.log("success");
    }
    }
```

**Comment by dougwilson** [comment]
Hi @MagSag it looks like in your JavaScript code you provided, you are not providing enough values to fill in the number of `?` characters in your query. You have 16 question marks but only 12 values.

**Comment by MagSag** [comment]
Thanks @dougwilson that's true.
