### ISSUE TITLE
Is there a way to get the inserted record?

### ISSUE THREAD

**Issue by maximedupre** [mysqljs/mysql#1721]
Is there a way to get all the values of a row that has just been inserted, without making another query? I know it is possible to get the id of the row that has been inserted, but I need all the values, as my DB not only has auto-incrementing ids, but also dates that are being generated automatically with "CURRENT_TIMESTAMP".

Thanks!

**Comment by dougwilson** [comment]
This module just implements the MySQL protocol. As far as I know, it is not possible to do this in MySQL, unless you can point me to some information on this in the MySQL manual.

**Comment by maximedupre** [comment]
I have just started learning SQL today, so you're probably right. I'm making a REST api and on a POST it is standard to return the created resource in the response, which is why I need to get the inserted row.

**Comment by RickBollinger** [comment]
Using Node/Express I write server code. It accepts a request object with a 'body' property that has all the incoming columns and updated values. After applying the updates to MySQL it is the server's job to send the body back to the client in the response object.

At least that seems to be what works.

**Comment by dougwilson** [comment]
Yea, I can only think of two ways:

1. Do a `SELECT` after your `INSERT` to get the values.
2. Remove calculated values from the db all together and calculate them in Node.js so you don't need the extra `SELECT`.

**Comment by maximedupre** [comment]
@dougwilson Right, those seems to be the only two options. Thanks for the help guys.

**Comment by sidorares** [comment]
@maximedupre @dougwilson there might be a way to do this in one query / roundtrip using stored procedure (which would internally do insert + select )

**Comment by dougwilson** [comment]
Right, you can absolutely use a stored procedure, which would still be an insert + a select within the server.

**Comment by sidorares** [comment]
something like this ( haven't tested )

```sql
CREATE PROCEDURE insert_and_select ( [...params])
BEGIN
 INSERT INTO mytable VALUES ([...]);
 SELECT * from mytable WHERE id=last_insert_id();
END
```

**Comment by sidorares** [comment]
Example using SP: https://github.com/mysqljs/mysql/blob/96fdd0566b654436624e2375c7b6604b1f50f825/test/integration/connection/test-procedure-with-single-select.js

**Comment by RickBollinger** [comment]
I am confused. You must have had the 'values of a row' to insert them. MySQL requires ALL columns to be set during INSERT that do not have default values. Where did these inserted values go? I don't think you need to query anything. I am missing something.

**Comment by bbito** [comment]
@RickBollinger the OP specifically mentioned

> also dates that are being generated automatically with "CURRENT_TIMESTAMP".

Those are generated in MySQL and this module can be running in a different time environment from the MySQL server and even if it isn't, it is likely that with fractional seconds turned on any `new Date()` generated in Node is not going to match what MySQL generates.
