### ISSUE TITLE
Buffer isn't unhexed when selecting

### ISSUE THREAD

**Issue by birjolaxew** [mysqljs/mysql#1722]
When inserting a Buffer, the Buffer gets turned into a hex string:

```javascript
let buffer = Buffer.from("hi there");
console.log("Saving buffer:",buffer,buffer.toString());
db.query(
    "INSERT INTO `test` (buffer) VALUES (?)",
    [buffer]);
```
| buffer BLOB              |
|---------------------|
| X'6869207468657265' |

When trying to retrieve it, the saved hex isn't unhexed

```javascript
db.query(
    "SELECT buffer FROM `test`",
    (err, results)=>{
        console.log("Got buffer:",results[0].buffer,results[0].buffer.toString());
    });
```

This results in the following being logged:

```
Saving buffer: <Buffer 68 69 20 74 68 65 72 65> hi there
Got buffer: <Buffer 58 27 36 38 36 39 32 30 37 34 36 38 36 35 37 32 36 35 27> X'6869207468657265'
```

**Comment by birjolaxew** [comment]
Just tried actually running my example, and it works :P Seems like I have an issue elsewhere in my code

**Comment by dougwilson** [comment]
It's no problem. If you do find something, feel free to re-open with additional information :)
