### ISSUE TITLE
Pool Cluster replication question

### ISSUE THREAD

**Issue by yeoksa** [mysqljs/mysql#1723]
Hello.I am finding the solution that supports mysql replication.But I will set Slave db read only.So, Update, Insert, Delete will processed by Master and only Select will processed by Slave.This module support this feature?

**Comment by dougwilson** [comment]
Yes, that is exactly what the pool cluster is for :) ! You want to define two pools: your master pool and slave pool. Then in your code, when you do a read, get the connection from the slaves, and when you write, get the connection from the master.

**Comment by yeoksa** [comment]
Is it possible select Master/Slave when every connection for query?

**Comment by dougwilson** [comment]
When you call `poolCluster.getConnection`, the first argument can be a string or regular expression. Examples are in the README: https://github.com/mysqljs/mysql#poolcluster

**Comment by yeoksa** [comment]
var master  = mysql.createPool({
  connectionLimit : 10,
  host            : 'master.db.com',
  user            : 'master',
  password        : 'mastersecret',
  database        : 'my_db'
});
var slave  = mysql.createPool({
  connectionLimit : 10,
  host            : 'slave.db.com',
  user            : 'slave',
  password        : 'slavesecret',
  database        : 'my_db'
});
master.query('INSERT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
slave.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
Like this code is possible?

**Comment by dougwilson** [comment]
Yea, that code would work just fine.

**Comment by yeoksa** [comment]
Thanks @dougwilson
