### ISSUE TITLE
Error when trying to pass JSON to stored procedure

### ISSUE THREAD

**Issue by sunojvijayan** [mysqljs/mysql#1724]
Hi I am trying to pass a JSON array to a stored procedure. I am getting this error

Error: UNKNOWN_CODE_PLEASE_REPORT: Invalid JSON text: \"Invalid value.\" at position 1 in value for column '.sales_details

I am using mySQL 7 so JSON is supported. Please help?

**Comment by sunojvijayan** [comment]
This is the JSON I am sending `[{"id":16,"branch_id":2,"name":"aaa","description":"","price":11,"discount":0,"qr_code":"123","quantity":10,"qty":1}]`

**Comment by dougwilson** [comment]
Hi @sunojvijayan that's strange, as I have been able to do this fine with the module, and you also shouldn't be getting UNKNOWN_CODE_PLEASE_REPORT for this unless you're using an old version. I can certainly take a look, can you provide all the following information?

1. The version of Node.js you are using.
2. The version of this module you are using.
3. The DDL of the table you are trying to operate on.
4. Code that uses this module performing the action you are getting that error from.
5. Instructions on how to set it all up and run your code.

Thanks!

**Comment by sunojvijayan** [comment]
1. node - v4.2.6
2. module - mysql@^2.13.0
3. [Dump20170513.sql.zip](https://github.com/mysqljs/mysql/files/998419/Dump20170513.sql.zip)
4. `var addSale = function (sale, user) {
    return new Promise(function (resolve, reject) {
        var total = 0;
        for (var i = 0; i < sale.length; i++) {
            total += (sale[i].price * sale[i].qty) - sale[i].discount;
        }
        logger.debug(new Date() + "Sales Total========" + total);
        logger.debug(new Date() + "Sale ========" + JSON.stringify(sale));
        /*var salesStr = '';
        for (var i = 0; i < sale.length; i++) {
            salesStr += '(5,' + sale[i].id + ',' + sale[i].qty + ')';
        }*/
        //logger.debug(new Date() + "Sales Details ========" + salesStr);
        var queryString = "SET @bill_id = 0;CALL dosale(?, ?, ?, ?, @status_msg); SELECT @bill_id as bill_id, @status_msg as status_msg;";
        //var queryString = "INSERT INTO sales(user_id, branch_id, date, total) VALUES (user_id,branch_id,NOW(),total);INSERT INTO sales_details(sales_id, product_id, quantity) VALUES ?;";
        var queryData = [user.id, user.branch_id, total, sale];
        mysql_db_helper.executePromiseQuery(queryString, queryData)
            .then(function (data) {
                //resolve(data);
                resolve({
                    status: 'S000',
                    code: 200,
                    text: data.payload[2][0].status_msg,
                    payload: [{
                        bill_id: data.payload[2][0].bill_id
                    }]
                });
            }).catch(function (data) {
                reject(data);
            });
    });
}`

A file is attached which has the db helper 
[mysql_helper.js.zip](https://github.com/mysqljs/mysql/files/998420/mysql_helper.js.zip)

**Comment by sunojvijayan** [comment]
Hi any help?

**Comment by dougwilson** [comment]
Hi @sunojvijayan sorry for not responding; I partially forgot and partially didn't have time to check it out. Can you provide instructions on how to set it all up and run your code? Perhaps someone else can lend a hand taking a look into this issue as well.

**Comment by dougwilson** [comment]
Hi @sunojvijayan just following up here since no one else has come by. Can you provide instructions on how to set it all up and run your code?

**Comment by kai-koch** [comment]
With the code you provide I assume, that the ```array sale```, you add as last element to the ```array queryData``` is not escaped as you expect it to be escaped. 
```sale``` is an array of objects and might not be flattened as your ```StoredProcedure dosale``` expects it to be.

You commented out ```saleStr```, maybe you meant to pass that into to the query data.

If that does not solve your problem, please provide additional information like the stored procedure itself.

**Comment by dougwilson** [comment]
Well, @kai-koch responded and no further responses from @sunojvijayan so I'm going to close this as stale.
