### ISSUE TITLE
express node js mysql connection issue

### ISSUE THREAD

**Issue by bswscube** [mysqljs/mysql#1727]
I am using AWS instances for node js.
I am using below code for connect with phpmyadmin.
```js
var connection = mysql.createConnection({
	host : 'ip', // AWS instance IP
	user : 'username',
	password : 'password',
	database : 'database_name' 
}); 
```
I am getting below error.
```
Error: connect ETIMEDOUT at Connection._handleConnectTimeout
```
Please help me out as soon as possible.

**Comment by dougwilson** [comment]
Hi @bswscube there isn't enough information provided here to assist with why you're getting a timeout connecting to your MySQL database from your web server. Have you tried to do a packet capture to see if there is a firewall blocking somewhere?

**Comment by sethkor** [comment]
Hi @bswcube,
If you are using RDS mysql you need to ensure the security group for your RDS instance allows incoming connections from your EC2 instance that is running your node.app.  

Give that a try.

Cheers
Seth

**Comment by dougwilson** [comment]
Closing since never heard back from OP.
