### ISSUE TITLE
Empty Array Issue

### ISSUE THREAD

**Issue by boxsnake** [mysqljs/mysql#1728]
In JS, array are recognized to be object (Array Object). For `?` pattern filling, with simple toString() method, empty array will be parsed into empty strings, so `connection.query('INSERT table SET ?', {t: []})` will look like `INSERT table SET t=`, which will cause a mysql error.

I think would it be better to use JSON.stringify to parse such arrays? Thank you.

**Comment by boxsnake** [comment]
Sorry, I saw you're using `SqlString` package. That's not the Array Object problem. It is only because it treats nested arrays as bulk insertions. However, I also hope you can have a json parsed formatting pattern. Thanks.

**Comment by dougwilson** [comment]
Hi @boxsnake yes, from the docs:

> Arrays are turned into list, e.g. ['a', 'b'] turns into 'a', 'b'

So an empty array would just end up as an empty array. If you have any ideas for an alternative implementation, do not hesitate to put together a pull request :) !
