### ISSUE TITLE
Attribute to get the error line number

### ISSUE THREAD

**Issue by cristianobarros** [mysqljs/mysql#1731]
Would it be possible to get the error line number, or the character position, when the query has some syntax error? 

In the example below it is expected to return line 2 and index 5, or just index 14, considering the line break.

> SELECT *
> FROM unknown_table

If this is not possible today, do you know if MySQL supports this kind of information?

The node-pg package supports this with the attribute position into the error object.

**Comment by dougwilson** [comment]
As far as I know, the MySQL server does not provide this kind of information.

**Comment by cristianobarros** [comment]
I did a search on the web, but could't find any way to accomplish this on MySQL server. You can close this issue if you want to. Thanks @dougwilson.

**Comment by cristianobarros** [comment]
I did a search on the web, but could't find any way to accomplish this on MySQL server, so I will close this issue. Thanks @dougwilson.
