### ISSUE TITLE
insert not performed well

### ISSUE THREAD

**Issue by sasu94** [mysqljs/mysql#1733]
Hi, this is my first experience with node js, and I need some help.
I've got a matrix of 2900 rows that i need to insert in my db but only 4 rows are added to the db

Here is where i call my sub:
![immagine](https://cloud.githubusercontent.com/assets/17903104/26154071/53fae7a6-3b0e-11e7-9da8-a28599fb4bea.png)

and this is the sub (the query is a bit long so i needed to cut it):

![immagine](https://cloud.githubusercontent.com/assets/17903104/26154118/868b747e-3b0e-11e7-98be-5723d1480a8d.png)

it's so important to me so thanks to everyone will help me

**Comment by dougwilson** [comment]
Hi @sasu94 that is really strange. Are you getting any error messages?

**Comment by sasu94** [comment]
no i don't get any error my only output is the log of inserted row (4 prints exactly as the rows in the db)

**Comment by sidorares** [comment]
@sasu94 what's rest of `insert into` query? ( just checking if you have `on duplicate ...` there and this is loop reference + async call problem like http://stackoverflow.com/a/26679537/705115)

**Comment by sasu94** [comment]
Sorry it's a bit long, i hope you can see it well. Matching with ? is correctly performed because the first rows are correct.


insert into Variation (`Subject`, `Chr`,`Start`,`End`,`Ref`,`Alt`,`Func.refgene`,`Gene.refgene`,`Gene.Detail.refgene`,`ExonicFunc.refgene`,`AAChange.refgene`,`1000G_ALL`,`1000G_AFR`,`1000G_AMR`,`1000G_EAS`,`1000G_EUR`,`1000G_SAS` ,`ExAC_Freq` ,`ExAC_AFR` ,`ExAC_AMR` ,`ExAC_EAS` ,`ExAC_FIN`,`ExAC_NFE` ,`ExAC_OTH` ,`ExAC_SAS` ,`ESP6500si_ALL` ,`ESP6500si_AA` ,`ESP6500si_EA` ,`CG46` ,`NCI60` ,`dbSNP`,`COSMIC_ID` ,`COSMIC_DIS` ,`ClinVar_SIG` ,`ClinVar_DIS` ,`ClinVar_STATUS` ,`ClinVar_ID` ,`ClinVar_DB` ,`ClinVar_DBID` ,`GWAS_DIS` ,`GWAS_OR` ,`GWAS_BETA` ,`GWAS_PUBMED` ,`GWAS_SNP` ,`GWAS_P` ,`SIFT_score` ,`SIFT_pred` ,`Polyphen2_HDIV_score` ,`Polyphen2_HDIV_pred` ,`Polyphen2_HVAR_score` ,`Polyphen2_HVAR_pred` ,`LRT_score` ,`LRT_pred` ,`MutationTaster_score` ,`MutationTaster_pred` ,`MutationAssessor_score` ,`MutationAssessor_pred` ,`FATHMM_score` ,`FATHMM_pred` ,`RadialSVM_score` ,`RadialSVM_pred` ,`LR_score` ,`LR_pred` ,`VEST3_score` ,`CADD_raw` ,`CADD_phred` ,`GERP++_RS` ,`phyloP46way_placental` ,`phyloP100way_vertebrate` ,`SiPhy_29way_logOdds` ,`Status` ,`Qual` ,`Depth` ,`Sample`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)

**Comment by sidorares** [comment]
as long as you don't see errors you should expect same number of records added as number of `db.newVariation` calls. I suggest you to add error handling to `.getConnection`  (though you'd see `can't call query function of undefined` or something similar in case of error)

**Comment by sasu94** [comment]
thanks a lot, it was a really stupid error, I forgot to release pool connection when done now it seems to work.
Thanks to all
