### ISSUE TITLE
Using mysql.createPool(): Getting "ER_CON_COUNT_ERROR: Too many connections"

### ISSUE THREAD

**Issue by roshanpaiva** [mysqljs/mysql#1734]
We used to use `mysql.createConnection()`, but recently switched to start using connection pools (`mysql.createPool()`). Once we did the switch we started getting the following errors when running a load test,
`ER_CON_COUNT_ERROR: Too many connections`.

Any idea why this could be happening? When we switched back to calling createConnection() we don't get the error. 

We had setup the pool with connectionLimit: 30. We called `pool.query()` instead of calling `pool.getConnection()` connection.query() and then `connection.release()` after each query. What we understood was that pool.query() does that for you, and calling getConnection explicitly was for transactions etc.

Everything else is the same.

**Comment by dougwilson** [comment]
Hi @roshanpaiva 'm not sure what the issue would be off-hand. Can y share something that reproduces the issue?

**Comment by pod4g** [comment]
@roshanpaiva Hi, I have just met this problem, My solution is reduce the `connectionLimit`
Try it

**Comment by adonike** [comment]
Same problem here with last version. When calling connection.release() the connection isn't released causing the pool to eventually run out of available connections. Also tried calling connection.destroy(), but the connection to the database persists in sleeping status, but it persists for the library model, so, the pool isn't able to retrieve any connection. The only way around so far is using pool.query() to run queries.

**Comment by dougwilson** [comment]
Until someone can share code to reproduce the issue, what are we supposed to do?

**Comment by roshanpaiva** [comment]
@dougwilson Sorry, i didn't close this out earlier. I was able to get over this by tweaking the following:
- Max connections on mysql
- connectionLimit on the pool. 
Basically, the gist was to ensure the sum of all the server nodes connectionLimit size < the db's max connections.

**Comment by dougwilson** [comment]
Glad to hear, @roshanpaiva ! That would make sense why I didn't hear back. Sorry to bother you :)

**Comment by deepakbasnal** [comment]
h
