### ISSUE TITLE
How to use transaction without throw?

### ISSUE THREAD

**Issue by fuadmuhtaz** [mysqljs/mysql#1735]
In the example, script use throw err when something not success. But its breaking my apps. Anyone have reference how to use transaction without throw.

Thanks

**Comment by anandp219** [comment]
Which example you are pointing to. Can you be more specific?

**Comment by fuadmuhtaz** [comment]
I use example from this repo documentation.
```js
connection.beginTransaction(function(err) {
  if (err) {
    throw err;
  }
  connection.query('INSERT INTO posts SET title=?', title, function(error, results, fields) {
    if (error) {
      return connection.rollback(function() {
        throw error;
      });
    }

    var log = 'Post ' + results.insertId + ' added';

    connection.query('INSERT INTO log SET data=?', log, function(error, results, fields) {
      if (error) {
        return connection.rollback(function() {
          throw error;
        });
      }
      connection.commit(function(err) {
        if (err) {
          return connection.rollback(function() {
            throw err;
          });
        }
        console.log('success!');
      });
    });
  });
});
```
I try to change the above code to promises and when error happen the transaction never rollback. But the problem has been resolved, inspired by this https://github.com/mysqljs/mysql/issues/1668#issuecomment-287519992

I'm never know when use two connection.query the query run separate. So i change the code to use connection.getConnection and everything ok. I think the documentation not mention it.

Thanks before

**Comment by dougwilson** [comment]
I'm not sure I understand the question / issue. If you don't want it to `throw`, then just change the code to do something different. Can you be more specific?

**Comment by fuadmuhtaz** [comment]
Sorry my bad, i dont know what happen with my code. Some weeks a go my code not work and now work without problem.

Lets say i have two tables:
- tbl_antrian_panggil
- tbl_history

| id_loket | id_user | nomor_antrian | waktu_mulai |
| -------- | -------- | ---------------- | -------------- |
| 1 | 1 | 1 | 2017-06-04 17:08:37 |

| id_loket | id_user | nomor_antrian | waktu_mulai | waktu_selesai |
| -------- | -------- | ---------------- | -------------- | --------------- |

I want to copy  tbl_antrian_panggil row to tbl_history with additional info and delete tbl_antrian_panggil row after the copy successfully. So i use this code

```javascript
var mysql = require('mysql');
var Q = require('q');

var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'antrian'
});

connection.beginTransaction(function() {
    Q.npost(connection, 'query', [
        'INSERT INTO tbl_history(id_loket, id_user, nomor_antrian, waktu_mulai, waktu_selesai) '+
        'SELECT id_loket, id_user, nomor_antrian, waktu_mulai, NOW() FROM tbl_antrian_panggil'
    ])
    .then(function() {
        return Q.npost(connection, 'query', ['DELETE FROM tbl_antrian_panggil LIMIT 1']);
    })
    .then(function() {
        return Q.npost(connection, 'commit');
    })
    .then(function() {
        console.log('success');
    })
    .catch(function(error) {
        console.log(error);
        connection.rollback();
    });
});
```

**Comment by dougwilson** [comment]
Gotcha. Yea, it looks like you're doing it using `Q`. If you were wondering what that would look like as callbacks:
```js
var async = require('async');
var mysql = require('mysql');

var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'antrian'
});

connection.beginTransaction((err) => {
  if (err) throw err;
  async.series([
    (next) => connection.query('INSERT INTO tbl_history(id_loket, id_user, nomor_antrian, waktu_mulai, waktu_selesai) SELECT id_loket, id_user, nomor_antrian, waktu_mulai, NOW() FROM tbl_antrian_panggil LIMIT 1', next),
    (next) => connection.query('DELETE FROM tbl_antrian_panggil LIMIT 1', next),
    (next) => connection.commit(next)
  ], (err) => {
    if (err) connection.rollback();
    else console.log('success');
  });
});
```
