### ISSUE TITLE
Query not replacing question mark at all after AJAX call - super weird

### ISSUE THREAD

**Issue by Cordello** [mysqljs/mysql#1736]
So I was trying to make a filter that would retrieve "events" from the database and render them without reloading the page. But this weird thing is happening where if I use the filter and then try to go to the specific page of one of those events, the sql query straight up doesn't parse. It doesn't replace the little question mark with my inserts. But if I don't use the filter route, it works just fine. Furthermore, on this same project there's a similar set up for "places", so if I use the filter and go to an individual place page it doesn't replace the question mark. Another level to the mystery is that if I do the place filter and then go to an event page, that query works just fine. But then if I go back to a place page any time after that, it doesn't work.

I've been using pooled connections because then I can do multiple sequences of queries in the callbacks, but honestly I don't fully understand what's going on under the hood, which might be getting me into trouble. The other possible culprit is that I used [the code snippet from the documentation](https://github.com/mysqljs/mysql#custom-format) in order to format my object as an insert. I have a feeling that's the problem, changing the query format stays latched on to the pool somehow, but maybe only on the code file it was executed from...? It doesn't make much sense to me, but that's all I can think of on my own that would illicit this kind of behavior.

Here's the code I'm using for the events. The places is almost identical.

    router.get('/filter', (req, res) => {
        pool.getConnection((err, con) => {
            con.config.queryFormat = queryconfig; // I took this straight from the node mysql docs, a function I stored on another file so I could insert objects into the 
            var query = 'SELECT DISTINCT events.eventID, events.name, (3959 * acos(cos(radians(:lat)) * cos(radians(lat)) * cos(radians(lon) - radians(:lon)) + sin(radians(:lat)) * sin(radians(lat)))) AS distance FROM events ';

        var inserts = {
            lat: req.query.lat, 
            lon: req.query.lon, 
            distance: req.query.distance,
            tags: [req.query.tags]
        };
        if(req.query.tags){
            query += 'JOIN events_tags ON events.eventID = events_tags.eventID JOIN tags ON events_tags.tagID = tags.tagID WHERE tags.name IN :tags HAVING distance < :distance';
        } else {
            query += 'HAVING distance < :distance';
            delete inserts.tags;
        }

        con.query(query, inserts, (err, result) => {
            res.send(result);
        });
        con.release(); // I tried moving this around because I don't really know where you're supposed to put it in relation to your query, but it didn't seem to matter
    });

    router.get('/:id', (req, res) => {
        pool.getConnection((err, con) => {
            console.log(req.params.id);

        var q = con.query('SELECT * FROM events WHERE eventID = ?', req.params.id, (err, result) => {
            console.log(q.sql); // THIS RIGHT HERE IS THE PROBLEM. If I've used the filter route at all before, this prints 'SELECT * FROM events WHERE eventID = ?' exactly, question mark and all. If I haven't used the filter route, it substitutes the id number in no problem.
            var event = result[0];
            con.query('SELECT name FROM tags JOIN events_tags ON tags.tagID = events_tags.tagID WHERE eventID = ?', event.eventID, (err, tags) => {
                event.tags = tags;
                res.render('events/show', {event: event});
            });
        });
        con.release();
    });

**Comment by Setitch** [comment]
Start from changeing 
```
    con.query(query, inserts, (err, result) => {
        res.send(result);
    });
    con.release(); // I tried moving this around because I don't really know where you're supposed to put it in relation to your query, but it didn't seem to matter
```

into 

```
    con.query(query, inserts, (err, result) => {
        if (err) {
            res.status(500).send(err);
            throw err;
        }
        res.send(result);
        con.release(); // release connection when you stop using it - not before sending query
    });
```

Do the same for the next query - when you release connection - you cannot use it in the code until you get new one. That means - your query to database is NEVER used - and you ALWAYS get error. As it releases connection before executing the query - therefore executes query on null or non working object.

**Comment by dougwilson** [comment]
Closing since there wasn't any follow up to the given answer.
