### ISSUE TITLE
Connection fails: Error: Handshake inactivity timeout in loopback

### ISSUE THREAD

**Issue by arvindkrbhatt** [mysqljs/mysql#1738]
Hi,
I have installed Node.js version 6.9.0 on my machine. I am trying to run sample for SQL database connectivity from examples. I am getting "Connection fails: Error: Handshake inactivity timeout" when i launch application. please help

regards
arvind

**Comment by dougwilson** [comment]
Hi @arvindkrbhatt the error means that it took longer than 10 seconds to establish a connection to your MySQL server. You may want to investigate packet captures to see what is making the connection establishment take so long, but you can always increase the timeout by changing the [`
acquireTimeout` pool option](https://github.com/mysqljs/mysql#pool-options).

**Comment by arvindkrbhatt** [comment]
where can i set this option in in sample at https://github.com/strongloop/loopback-example-database/tree/MySQL. i directly used this sample even getting same issue. I also tried to increase time out in sequence.js setting   this._timeout  = 100000; but no luck.

**Comment by bbito** [comment]
@arvindkrbhatt , As dougwilson pointed out, when the default timeout is exceeded it usually points to something else interfering with the connection such as a firewall or some configuration problem. However, if you want to extend the timeout for that Loopback demo you would add a configuration line after line 13:
https://github.com/strongloop/loopback-example-database/blob/mysql/server/datasources.json#L13
So it looks like:
```
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "accountDS": {
    "host": "demo.strongloop.com",
    "port": 3306,
    "database": "loopback-example-mysql",
    "username": "demo",
    "password": "L00pBack",
    "name": "accountDS",
    "connector": "mysql",
    "connectTimeout": 100000
  }
}
```
-Don't forget to add the comma at the end of line 13!

**Comment by arvindkrbhatt** [comment]
**@bbito** Unfortunately still i am getting same error. my colleagues also facing the same problem with sample. I'll be thankful to you if you could please suggest how can i debug it or any tool to debug. Setting up connectTimeout is also not working. I'll try to run this sample in my home network, just to verify if its related to firewall or something else.

**Comment by bbito** [comment]
@arvindkrbhatt As I wrote earlier, I have no trouble connecting to the Loopback Demo MySQL server using the supplied credentials via MySQL Workbench. I'd suggest trying that and if you do connect successfully, then I would suspect a problem with the Loopback Sample application. 

If you find that, the correct place to register an issue would be with the mysql branch of Loopback's loopback-example-database here:
https://github.com/strongloop/loopback-example-database/issues

**Comment by arvindkrbhatt** [comment]
Thanks. I'll log this issue to place you suggested.

**Comment by dhavalshah01** [comment]
I am facing the same issue. I am running node 4.6.1 version.

I tried connecting to local mysql server as well as the mysql server on the amazon aws. But i still face the same error. It does not look like its the code issue but has to do something with the firewall issue may be ? As i am able to connect to mysql from the workbench.

**Comment by mybluedog24** [comment]
I had the same issue and just fixed it. I use Amazon AWS RDS server and set the security group inbound for my IP only. And this morning somehow my IP address changed. So I just updated the IP on AWS and everything works. Hope this helps.

**Comment by luoshilu** [comment]
Try changing the address of your computer's DNS server and IP.
