### ISSUE TITLE
production deployment of loopback app

### ISSUE THREAD

**Issue by arvindkrbhatt** [mysqljs/mysql#1739]
Hi,
I am working on loopback application to create api. It'll be great help if you can suggest me the following.

1. How to build final executables, dlls for production deployment?
2. How to deploy on IIS or other server?

Regards
arvind

**Comment by dougwilson** [comment]
Hi @arvindkrbhatt did you mean to file this issue with the loopback project?

**Comment by arvindkrbhatt** [comment]
Not exactly but just checking what could be the best way for that. Any suggestions please.

**Comment by dougwilson** [comment]
Hi @arvindkrbhatt I'm not familiar with loopback, so have no idea what to suggest.

**Comment by bbito** [comment]
@arvindkrbhatt I thankfully haven't touched IIS in over 15 years, but I did find some reference to Loopback on IIS here: https://strongloop.com/strongblog/node-js-net-getting-started-part-two/
I expect you can get some help on the Loopback Google Group: https://groups.google.com/forum/#!topic/loopbackjs/1mHMJs8XLBU

**Comment by arvindkrbhatt** [comment]
Thanks a lot. It would help :)
