### ISSUE TITLE
EventEmitter memory leak warning for Pool

### ISSUE THREAD

**Issue by thexeos** [mysqljs/mysql#1742]
I get the following warnings when using a connection pool with connectionLimit larger than 10.

> (node) warning: possible EventEmitter memory leak detected. 11 acquire listeners added. Use emitter.setMaxListeners() to increase limit.
> (node) warning: possible EventEmitter memory leak detected. 11 connection listeners added. Use emitter.setMaxListeners() to increase limit.
> (node) warning: possible EventEmitter memory leak detected. 11 enqueue listeners added. Use emitter.setMaxListeners() to increase limit.
> (node) warning: possible EventEmitter memory leak detected. 11 release listeners added. Use emitter.setMaxListeners() to increase limit.

I suppose this is the reason why the current default is 10. Is there any way of suppressing this by calling `emitter.setMaxListeners(poolOptions.connectionLimit)`, where `emitter` is the EventEmitter object, when the pool is created?

**Comment by dougwilson** [comment]
Hi @thexeos the current limit is just arbitrary. Based on those messages, I think that those are coming from your code, since this library doesn't add any listeners on those events (they are just available for your code to hook into). Can you provide the code you are using that has the issue?

**Comment by thexeos** [comment]
Oops. Just realized I've listed the wrong event names. I was writing them out of my head. Checked the error log, here is what I got:

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connect listeners added. Use emitter.setMaxListeners() to increase limit
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 enqueue listeners added. Use emitter.setMaxListeners() to increase limit

I found the place where they are all added at once: [Connection.js#L114](https://github.com/mysqljs/mysql/blob/eeca1326c5f4d67725a486ddf1ef12c3f12d2187/lib/Connection.js#L114)

**Comment by dougwilson** [comment]
I would try adding  emitter.setMaxListeners there, but I don't know if that would fix it because you haven't provided a reproduction example. Can you provide code that reproduces the warnings, please?

I tried simply creating a pool of 100 connections and checked out all 100 at once and no warnings were printed.

**Comment by dougwilson** [comment]
Also what will help is if you enable traces on warnings in Node.js so we can see the exact file and line where the 11th listener was added.

**Comment by thexeos** [comment]
This is sidorares/mysql**2** and its Promise implementation sidorares/node-mysql2#577. Sorry for the confusion.

**Comment by dougwilson** [comment]
Oh, haha. It's no problem! It looks like the hint towards using tracing on the warnings here worked out anywhere over there :)

**Comment by andreyselin** [comment]
I got this when my colleague left `connection.on('error'...` inside pool query handler while moving to pooling connections
