### ISSUE TITLE
pool block the whole program

### ISSUE THREAD

**Issue by acekingke** [mysqljs/mysql#1743]
```js
const mysql = require('mysql');

var pool  = mysql.createPool({
  host: '127.0.0.1',
  user: 'root',
  password: '',
  database: 'test',
  charset: 'UTF8MB4_GENERAL_CI'
});

pool.getConnection(function(err, connection) {
  // Use the connection
  connection.query('show databases', function (error, results, fields) {
    // And done with the connection.
    connection.release();
  
    // Handle error after the release.
    if (error) throw error;
    console.log(results);
    // Don't use the connection here, it has been returned to the pool.
  });
});
```

**Comment by dougwilson** [comment]
Sorry, I don't understand the question / issue. Please elaborate.

**Comment by acekingke** [comment]
The file save as test.js, when I run as node test.js
the result is out to the console , I think it has finished ,but the program still run, util I press the CTLR and C button to stop it

**Comment by sidorares** [comment]
@acekingke node runs until there is as least one active handle (socket, timer, file etc)
In your case connection is still remain open in the pool ( by doing `connection.release();` you just "mark" it as available for other parts of you code for reuse ). If you actually done with db you can call `pool.end()` and it'll send quit command to all open connections. Once last network socket is closed node process will terminate

There is a module to tell you exactly what causing node process to run - https://github.com/mafintosh/why-is-node-running

**Comment by acekingke** [comment]
Thank you very much
