### ISSUE TITLE
connection.query callback doesn't work in lambda.

### ISSUE THREAD

**Issue by gyurobenjamin** [mysqljs/mysql#1744]
I will got a timeout with this. But if I do an insert, the data will be in the DB.

```js
exports.handler = function (event, context, callback) {
  return connection.query("SELECT 1", function (err, res) {
    return callback(err, {
      statusCode: 200,
      body: JSON.stringify(res)
    });
  });
};
```

**Comment by gyurobenjamin** [comment]
context.done and context.succeed is working, but my local proxy use the callback

**Comment by dougwilson** [comment]
I'm not sure I understand what the question / issue is. Can you elaborate?

**Comment by DanielOgorchock** [comment]
I'm having this problem as well. I have a test script that works completely fine on my pc, but in aws lambda, the mysql callbacks are never called. For example, when I attempt to to do a connection.connect(function(){}) , the code inside that callback never is run, even after a specified connectionTimeout value. Same thing with queries

**Comment by gyurobenjamin** [comment]
@DanielOgorchock You can use context.done() instead of callback.

**Comment by dougwilson** [comment]
Closing because no clarification / any response from the OP ever came.
