### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:3306 as AWS EC2 with nodes

### ISSUE THREAD

**Issue by XOneto9** [mysqljs/mysql#1745]
Hi.
I have Error and.. I look around all of web site. but all of solution didn't work.
My setting is below information.
1. AWS : EC2(linux), route53, load balancer
2. nodJs with express
3. express listen port : 80
4. mysql : port 3306 (also, in EC2 security group, I'm authorize RDS server using RDS endpoint).

in my case, a little odd..

because of connecting domain, I should use port 80 in my EC2. but problem is if I set the port 80, then the linux block.

so, I use 'sudo', and then it's work! 
but, the mysql to call the function give to me error like that Error: connect ECONNREFUSED 127.0.0.1:3306

if I change the express listen port to 3000 then mysql is good work!
but another way, If I set the port at express as 3000 and use keyword 'sudo', then It will be same error

So, I think problem is related to use keyword 'sudo'

do you know what happen???

I attach my source code... than you

```
const app = express();
const port = 3000;
app.use('/', express.static(__dirname + '/../public'));

app.post('/Master', (req, res) => {

    var name = req.body.name;
    var pwd = req.body.pwd;

    db.getMasterid(function(err, results){
        if(err) {
            res.send(500, "Server get  Error from Masterid");
            return;
        }
        
```
```
var pool = db.createPool({
    connectionLimit : 10,
    host            : process.env.MYSQL_HOST,
    user            : process.env.MYSQL_USER,
    password        : process.env.MYSQL_SECRET,
    database        : process.env.MYSQL_DB,
    port            : '3306',
    ssl             : "Amazon RDS",
})


exports.getMasterid = function(callback){
    var sql = 'select * from masterid';
    pool.getConnection((err, connection) => {
        if(err){
            console.log(err);
            callback(true);
            return;
        }
        connection.query(sql, (err, results, field) => {
            connection.release();
            if(err){
                console.log(err);
                callback(true);
                return;
            }
            callback(false, results);
        });
    });
};


```

Error Message

```
{ Error: connect ECONNREFUSED 127.0.0.1:3306
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
    --------------------
    at Protocol._enqueue (/home/ec2-user/mjlens/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Protocol.handshake (/home/ec2-user/mjlens/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/home/ec2-user/mjlens/node_modules/mysql/lib/Connection.js:130:18)
    at Pool.getConnection (/home/ec2-user/mjlens/node_modules/mysql/lib/Pool.js:48:16)
    at Object.exports.getMasterid (/home/ec2-user/mjlens/build/mysql_db/reservation_db.js:23:10)
    at /home/ec2-user/mjlens/build/main.js:111:30
    at Layer.handle [as handle_request] (/home/ec2-user/mjlens/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ec2-user/mjlens/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ec2-user/mjlens/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ec2-user/mjlens/node_modules/express/lib/router/layer.js:95:5)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 3306,
  fatal: true }
```

**Comment by sidorares** [comment]
hi @XOneto9 
you mentioned you are using RDS mysql but error is `ECONNREFUSED 127.0.0.1:3306`. Do you set `MYSQL_HOST` variable to RDS host?

**Comment by XOneto9** [comment]
@sidorares Hi, 
I'm setting MYSQ_HOST as RDS instance end point

**Comment by sidorares** [comment]
MYSQ_HOST or MYSQL_HOST ? try to log what's actually passed to `db.createPool`. If undefined it's trying to connect to localhost

**Comment by XOneto9** [comment]
@sidorares 
Sorry, My miss typo. MYSQL_HOST

how to check log on `db.createPool` ??

**Comment by sidorares** [comment]
```js
console.log({
    host            : process.env.MYSQL_HOST,
    user            : process.env.MYSQL_USER,
    password        : process.env.MYSQL_SECRET,
    database        : process.env.MYSQL_DB
 })
```

**Comment by XOneto9** [comment]
@sidorares Thank you!

**Comment by XOneto9** [comment]
@sidorares Yes,
your right....
I get a result...........all of....T^T OMG....

{ host: undefined,
  user: undefined,
  password: undefined,
  database: undefined }

**Comment by sidorares** [comment]
you probably set variables for current user. With sudo you het different set of env variables. Try to pass directly when you start it - `MYSQL_HOST=x.y.z node server.js` ( maybe `sudo su` before that)

**Comment by XOneto9** [comment]
@sidorares Thank you!!!
