### ISSUE TITLE
Amend docs. All "INSERT" examples are wrong now.

### ISSUE THREAD

**Issue by wzup** [mysqljs/mysql#1746]
The subject is [here](https://github.com/mysqljs/mysql#escaping-query-values), [here](https://github.com/mysqljs/mysql#getting-the-id-of-an-inserted-row), [here](https://github.com/mysqljs/mysql#transactions)

You do not have `fields` in a callback when you use `INSERT`! Instead your `fields` are in `results` exactly. And `fields` are `undefined`. Don't mislead users. Amend it.

```
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```

Your `results` looks like this:
```
{
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: "",
    protocol41: true,
    changedRows: 0
},
```

**Comment by dougwilson** [comment]
The docs are not wrong. Please read everything. The results argument of an insert is not the fields, that is the results. The fields is an array of fields, if available, otherwise undefined. The operation depends on your MySQL server version and exactly what your INSERT does.
