### ISSUE TITLE
ER_PARSE_ERROR for simple sql query

### ISSUE THREAD

**Issue by Zapeth** [mysqljs/mysql#1753]
This is the code piece in node.js for sending the query
```
conn.query(
   'USE information_schema;\nSELECT COUNT(*) FROM PROCESSLIST WHERE db=\'database_test12\' AND HOST LIKE \'localhost\'',
   function(err, rows, fields) {
      if (err) log.error(err.message);
      else log.info(rows);
});
```
which logs
> ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SELECT COUNT(*) FROM PROCESSLIST WHERE db=`database_test12` AND HOST LIKE 'local' at line 2

The same query works fine in Mysql Workbench and other queries in my javascript code work fine as well so I'm not quite sure what the problem could be (unless I'm missing something completely obvious?).

One thing to note that might or might not be related to this issue is that the err.message string doesn't list the entire sql query but cuts off at 'local', also not sure what the cause of this could be (I doubt its due to some fixed-size buffer?)

The MySQL version being used is v5.7.18, as for node.js it is v8.1.1.

**Comment by sidorares** [comment]
do you have [multiple statements](https://github.com/mysqljs/mysql#multiple-statement-queries) flag enabled @Zapeth ?

**Comment by Zapeth** [comment]
Whoops, seems like I overlooked that section when browsing through the readme.

After setting the flag that query works as well, thanks for the quick reply.
