### ISSUE TITLE
ER_PARSE_ERROR in sub request

### ISSUE THREAD

**Issue by YevhenStienin** [mysqljs/mysql#1766]
I'm trying to send simple request with sub request, and I'm getting ER_PARSE_ERROR. 
This is my request:
> "SELECT * FROM `companies` WHERE Name LIKE '%Пиво%' AND Rate >= 3 AND Id IN (SELECT `CompanyId` FROM `companydishtypes` WHERE DishTypeId IN (1, 2, 3)) ORDER BY `Rate` DESC, `Name` ASC LIMIT 5"`

I tried to escape the column name and table name using? and ??. But nothing helped. At what, if I copy this request from my code and try to execute it through WorkBench, then this query is executed without errors and I get the correct result. What can I do wrong?

I hope additional info will be able to help.
Connection:
```
 Name:  Local instance MySQL
 Host: localhost
 Port: 3306
 Server: MySQL Community Server (GPL)
 Version: 5.7.18-log
 Connector: C++ 1.1.4
 Login User: root
 Current User: root@localhost
 SSL: Disabled
```

Debug info from Node output console:
```
listening on 5001
Sat, 01 Jul 2017 11:08:49 GMT|POST|/api/companies/list|::1
<-- HandshakeInitializationPacket
HandshakeInitializationPacket {
  protocolVersion: 10,
  serverVersion: '5.7.18-log',
  threadId: 26,
  scrambleBuff1: <Buffer 1e 6a 57 58 4c 2e 13 2a>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63487,
  serverLanguage: 33,
  serverStatus: 2,
  serverCapabilities2: 33279,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 31 2a 64 2f 0f 70 49 03 7f 10 1b 16>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true }
--> ClientAuthenticationPacket
ClientAuthenticationPacket {
  clientFlags: 521167,
  maxPacketSize: 0,
  charsetNumber: 33,
  filler: undefined,
  user: 'root',
  scrambleBuff: <Buffer 9d 9c 20 42 22 96 49 8d 1b 8f c8 5a 31 6a b3 83 e7 e0 31 69>,
  database: 'food-delivery',
  protocol41: true }
<-- OkPacket
OkPacket {
  fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
--> ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: 'SELECT * FROM `companies` WHERE Name LIKE \'%Пиво%\' AND Rate >= 3 AND Id IN (SELECT `CompanyId` FROM `companydishtypes` WHERE DishTypeId IN (1, 2, 3)) ORDER BY `Rate` DESC, `Name` ASC LIMIT 5' }
<-- ErrorPacket
ErrorPacket {
  fieldCount: 255,
  errno: 1064,
  sqlStateMarker: '#',
  sqlState: '42000',
  message: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'`companydishtypes` WHERE DishTypeId IN (1, 2, 3)) ORDER BY `Rate` DESC, `Name` A\' at line 1' }
```

Environment info:

```
Node.JS: 6.11.0 LTS
MySQLjs module: 2.13.0
OS: Windows 10 Pro x64 1703 build 15063.447
```

**Comment by YevhenStienin** [comment]
I replaced the [mysqljs/mysql ](https://github.com/mysqljs/mysql) module with a [mysql2](https://github.com/sidorares/node-mysql2) module. But the result was the same. Most likely, I'm doing something wrong. But I need help.

**Comment by dougwilson** [comment]
That is weird indeed, and since the error is coming from your MySQL server, not this module, that would make sense why you still get the same error even when you trade it out. Nothing seems obviously wrong from what you provided, though, either :/ Perhaps I can poke at it if I can reproduce locally. Can you provide the DDL, and same data I need to load, and then a complete JavaScript file I can run to reproduce the issue?

**Comment by YevhenStienin** [comment]
@dougwilson 
The thing is, the project is big, and different modules respond to the generation and sending of the request. It will be problematic to single out this. The project is also written in typescript. Will it be enough if I send you the already translated js instead of the source code in ts? Or is it better if you have ts?
Thank you.

**Comment by dougwilson** [comment]
Hi @YevhenStienin I understand the project is probably big, and I was just asking if you can provide the DDL, and same data I need to load, and then a complete JavaScript file I can run to reproduce the issue. I don't see your entire project, just _something_ in which I can reproduce the issue. SO far nothing obvious from what you provided so far, and me copy-pasting your query in my own file, with DDL I made up didn't have the provided issue, and so right now you're the only person who has something to hook up a debugger to to figure out the issue.

Perhaps if you cannot provide anything, can you suggest the next step to take on this issue?

**Comment by YevhenStienin** [comment]
Hi, @dougwilson 
I created the [project](https://github.com/YevhenStienin/mysql-subquery-issue) with the minimum possible amount of code to reproduce this error. I hope that this will help to find a solution.

**Comment by dougwilson** [comment]
Thanks a lot, @YevhenStienin . I was able to track it down. Your issue is on this line: https://github.com/YevhenStienin/mysql-subquery-issue/blob/master/server/src/providers/sql.query.builder.ts#L50

The issue is that the character between `CompanyId` and `FROM` is not a space character (0x20 in hex), but is instead 0xc2 0xa0, which is a non-breaking space. This causes the parse error on the MySQL server. Just alter that file to fix the character to be an ASCII space instead of a non-breaking space and it works perfectly.

Here is the hex dump from that section of the file:
```
000006f0  28 53 45 4c 45 43 54 20  60 43 6f 6d 70 61 6e 79  |(SELECT `Company|
00000700  49 64 60 c2 a0 46 52 4f  4d 20 60 63 6f 6d 70 61  |Id`..FROM `compa|
00000710  6e 79 64 69 73 68 74 79  70 65 73 60 20 57 48 45  |nydishtypes` WHE|
```

**Comment by YevhenStienin** [comment]
Thanks a lot, @dougwilson 
You helped me very much. I do not even know how I managed put this character instead of a space. =)
