### ISSUE TITLE
SailsJs implementation of node mysql

### ISSUE THREAD

**Issue by himanshu-vr** [mysqljs/mysql#1767]
Hi,
This is not exactly an issue but I wanted to know is there any way to use this mysql package in sailsjs framework without using it's own sails-mysql adapter

**Comment by dougwilson** [comment]
I'm not familiar enough with SailsJs to know, but the README here shows how to use this module. If that is not enough, can you provide more information on what you mean, exactly?

**Comment by dougwilson** [comment]
I'm going to close since I never heard back.
