### ISSUE TITLE
LIKE escape string (percent sign and underscore) might not be escaped as expected

### ISSUE THREAD

**Issue by VdustR** [mysqljs/mysql#1768]
I've tried some SQL for percent sign escaping:

## Case 1:
```sql
SELECT '\%b' LIKE '%\%'
```

My string is:
```javascript
sql = 'SELECT \'\\%b\' LIKE \'%\\%\''
```

console.log the result, is 1:
```
{ results: [ RowDataPacket { '\'\%b\' LIKE \'%\%\'': 1 } ],
  fields: 
   [ FieldPacket {
       catalog: 'def',
       db: '',
       table: '',
       orgTable: '',
       name: '\'\\%b\' LIKE \'%\\%\'',
       orgName: '',
       charsetNr: 63,
       length: 1,
       type: 8,
       flags: 129,
       decimals: 0,
       default: undefined,
       zeroFill: false,
       protocol41: true } ] }
```

But in mysql cli, result is 0:
```
mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)
```

The result is also 0 in workbench:
![image](https://user-images.githubusercontent.com/29639463/27821896-680f36aa-60d6-11e7-9ffe-a7c7c8d4aac7.png)

## Case 2:
```sql
SELECT '%as' LIKE '%\%s'
```

My javascript string passed:
```javascript
sql = 'SELECT \'%as\' LIKE \'%\\%s\''
```

The result is 1:
```
{ results: [ RowDataPacket { '\'%as\' LIKE \'%\%s\'': 1 } ],
  fields: 
   [ FieldPacket {
       catalog: 'def',
       db: '',
       table: '',
       orgTable: '',
       name: '\'%as\' LIKE \'%\\%s\'',
       orgName: '',
       charsetNr: 63,
       length: 1,
       type: 8,
       flags: 129,
       decimals: 0,
       default: undefined,
       zeroFill: false,
       protocol41: true } ] }
```

The result is 0 in cli:
```
mysql> SELECT '%as' LIKE '%\%s';
+-------------------+
| '%as' LIKE '%\%s' |
+-------------------+
|                 0 |
+-------------------+
1 row in set (0.00 sec)
```

It's also 0 in workbench:
![image](https://user-images.githubusercontent.com/29639463/27822078-ff0f6070-60d6-11e7-9ee0-37d060fce638.png)

I got 1 in phpMyAdmin for these cases.
Thus, I have no idea why the results are different.

According to the [reference from MySQL website](https://dev.mysql.com/doc/refman/5.7/en/string-comparison-functions.html), I think they should be 0 in these cases.

Here is my environment:
OS: Ubuntu 17.04
node: 8.1.3
mysqljs: 2.13.0
sqlstring: 2.2.0
mysql: 5.7.18
php: 7.0.16
phpmyadmin: 4.7.0
workbench: 6.3.9

**Comment by dougwilson** [comment]
This module does not escape characters inside strings that have various meaning, only escapes characters that would cause the setting quotes themselves to end.

**Comment by dougwilson** [comment]
If you set debug: true in your connection option, you can examine the full SQL string being sent to the server and what the server is responding with. If the SQL string there is right and the server is sending back a packet with the 1 result, not sure what this module can do, because the server is what performs the queries and determines the results.

**Comment by VdustR** [comment]
I created a new project for the test cases and got right results '0'.

Then I enabled the debug mode and checked the logs.

Mysqljs sent the same SQL but receive different results.

I checked the options and found that charset are different.

Test in mysql cli:
```
mysql> SET collation_connection = utf8_unicode_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)

mysql> SET collation_connection = utf8_general_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)

mysql> SET collation_connection = utf8mb4_unicode_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)

mysql> SET collation_connection = utf8mb4_general_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                0 |
+------------------+
1 row in set (0.00 sec)

mysql> SET collation_connection = utf8mb4_unicode_520_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT '\%b' LIKE '%\%';
+------------------+
| '\%b' LIKE '%\%' |
+------------------+
|                1 |
+------------------+
1 row in set (0.00 sec)
```

It's not a mysqljs issue.

Thanks for your help!

**Comment by VdustR** [comment]
This issue has been reported to [MariaDB](https://jira.mariadb.org/browse/MDEV-13335).

There is also an [issue link](https://bugs.mysql.com/bug.php?id=74901) for MySQL.
