### ISSUE TITLE
Connection is not freed in error case?

### ISSUE THREAD

**Issue by chris-luo** [mysqljs/mysql#1772]
When there is an error in getting the connection, the connection is not freed. Connection is undefined so I cannot release it.
```js
   pool.getConnection((error, connection) => {
        if (!error) {
            console.log("no error");
            connection.release();
            console.log(pool._freeConnections.indexOf(connection)); //0
        }
        else {
            console.log(error);
            console.log(connection); //undefined
            console.log(pool._freeConnections.indexOf(connection)); //-1
        }
    });
```

**Comment by dougwilson** [comment]
In an error, no connection was created in order to give you. Are you seeing an extra connection somewhere?

**Comment by chris-luo** [comment]
No I am not, I made a new file to test this. But I got it, its what indexOf does. pool._freeConnections.indexOf(undefined) returns -1 which makes sense. That means that this way of checking if the connection is freed might be inconsistent because it will return -1 for connection undefined and connection in use.

**Comment by dougwilson** [comment]
Gotcha. So just change how you're doing the check, I suppose. Anything you think we need to change here or is the issue closed ? :)

**Comment by chris-luo** [comment]
Thanks
