### ISSUE TITLE
Question: MySQL Cluster (NDB) support

### ISSUE THREAD

**Issue by kaizen1** [mysqljs/mysql#1773]
Does this connector support MySQL Cluster (NDB)?
Thanks.

**Comment by sidorares** [comment]
as far as I know ndb talks same mysql binary protocol, but I have not tried using this library with ndb

Short answer is 'probably yes, but nobody reportet yet "I'm using this module with ndb and it works for me"'

**Comment by sidorares** [comment]
If you know quick way to start ndb via docker I can test it for you

**Comment by kaizen1** [comment]
Hi, thanks for the response. 
I think these are official docker images for testing NDB.
https://github.com/mysql/mysql-docker/tree/mysql-cluster

**Comment by sidorares** [comment]
@kaizen1 can confirm it works fine with mysql and mysql2

followed instructions from https://github.com/mysql/mysql-docker/tree/mysql-cluster and after

`docker run -it --net=cluster -v `pwd`:/node node /node/test.js` where test.js is

```js
const mysql = require("mysql");

const conn = mysql.createConnection({
  user: "root",
  password: "test",
  host: "192.168.0.10"
});

conn.query(`SHOW STATUS LIKE 'ndb_api%'`, console.log);
```

( let me know more reliable way to see it's actually working properly and not just talking to single mysqld node )

**Comment by sidorares** [comment]
> as far as I know ndb talks same mysql binary protocol, but I have not tried using this library with ndb

that's probably not exactly correct, ndb talks it's own protocol but clients connect to "normal" server

**Comment by kaizen1** [comment]
I'll update when we start the project and do real queries to the data nodes through mysqld.  I was just doing initial research. This is great at least it connects to mysqld. There is hope!
I'm surprised NDB isn't more popular. Rock solid, great write scalability and HA.
Cheers.
