### ISSUE TITLE
Update multiple rows and multiple columns

### ISSUE THREAD

**Issue by monis01** [mysqljs/mysql#1774]
Hi 
I am trying to update multiple rows with different values and I am not able to get the syntax but hints from these two :  
[1475](https://github.com/mysqljs/mysql/issues/1475) 
[1691](https://github.com/mysqljs/mysql/issues/1691)

However I came across this query to update multiple rows :
```sql
UPDATE drive
SET cost = CASE Id
    WHEN 1 THEN 1.60
    WHEN 3 THEN 3.60
    WHEN 10 THEN 10.60
END,
oil = CASE Id
    WHEN 1 THEN 126.3
    WHEN 3 THEN 326.3
    WHEN 10 THEN 1026.3
END,
  tyre = CASE Id
    WHEN 1 THEN 13.76
    WHEN 3 THEN 33.76
    WHEN 10 THEN 103.76
END
WHERE id IN (1,3,10)
```

but not able to convert according to **mysqljs** syntax, and my guess if I update cost then I have to :
```js
var sql  = 'UPDATE t_bt_drive SET cost = CASE id WHEN ?  THEN ? END WHERE Id IN (?)   ' ;
var result =  yield mysql.pool.queryP(sql,[1,2511.60,[1]]);
```
and I have to push values in array normally where I cannot distinguish the other values ? 
 e.g. `SET cost = CASE id WHEN ?  THEN ? ` I have to  [1,2511.60] OR
`SET cost = CASE id WHEN ?  THEN ? WHEN ?  THEN ? `(If i build query) then [3,35.65] etc.

I am little new to mysql but for this particular case what will be mysqljs syntax?

Thanks for your time.

**Comment by dougwilson** [comment]
There is no way to expand the `?` into a case statement currently in the expansion rules. If you think there should be, feel free to put together a proposal for how we would do that (either as a pull request or even just in writing if you're not sure how to start).
