### ISSUE TITLE
An error accurred when i use select * from table where, what should i do?

### ISSUE THREAD

**Issue by Sailor20** [mysqljs/mysql#1777]
An error accurred when i use select * from table where, what should i do? the code is:

const querySql = 'SELECT * FROM t_api_config WHERE ?';
const where = { type: 1, status: 1 };
mysql.queryAsync(querySql, where);

but i edit the where to {type: 1} or  {status: 1}, the error disappeared!

what should i do?

thanks for first!

**Comment by Sailor20** [comment]
sorry , the error info is :
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' `status` = 1' at line 1

**Comment by dougwilson** [comment]
This is because you cannot use the object expansion in a WHERE clause, as the object expansion generates a comma separated list for the SET clause.

**Comment by Sailor20** [comment]
thanks
