### ISSUE TITLE
RDS Cert for Indian Mumbai region 

### ISSUE THREAD

**Issue by madhuneal** [mysqljs/mysql#1780]
Missing RDS Certificate for Indian Mumbai region, Can you please Add missing Amazon RDS Certificates?

Many Thanks,
Madhu

**Comment by dougwilson** [comment]
Hi @madhuneal which certificates are those? Can you list their names / fingerprints or where to get them from?

**Comment by madhuneal** [comment]
Hi Doug, 

Thanks for writing; FYI below information will help you to add the the certs. 

"Amazon RDS creates an SSL certificate and installs the certificate on the DB instance when Amazon RDS provisions the instance. These certificates are signed by a certificate authority. The SSL certificate includes the DB instance endpoint as the Common Name (CN) for the SSL certificate to guard against spoofing attacks. The public key is stored at https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem ."

You can find Intermediate Certificates for a particular region, 
http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html#UsingWithRDS.SSL.IntermediateCertificates

As of now I need for Mumbai india Region.

Looking forward to hear from you.

Many Thanks,
Madhu

**Comment by dougwilson** [comment]
Ah, the ap-south-1 certificate. Yep, looks like we don't have that one in our list, so added! It'll be in the next release :)

**Comment by sidorares** [comment]
@dougwilson maybe some day we should extract this into "public-ssl-profiles" package under mysqljs org

**Comment by dougwilson** [comment]
@sidorares yea, that's a good idea :) I was just writing a script to automatically generate the file for RDS from the Amazon docs to keep it up-to-date easier. I'm thinking maybe the module should just be RDS and not just all profiles? After all this time that SSL profiles have been bundled here, the only set has been RDS, so it almost seems like there is no other provider that folks really care about to have bundled?

**Comment by dougwilson** [comment]
Or, I suppose only Amazon RDS is using it's own PKI instead of a public one that would always chain up to roots already trusted by Node.js core.

**Comment by sidorares** [comment]
would be good to bundle Azure as well, currently they offer to download certs and copy-paste config
https://docs.microsoft.com/en-us/azure/mysql/howto-connection-string

**Comment by sidorares** [comment]
actually it seems like in Azure you supposed to put your own cert on server https://docs.microsoft.com/en-us/azure/mysql/howto-configure-ssl

**Comment by dougwilson** [comment]
Yea, but the Azure certs all seem to root to Baltimore CyberTrust Root, which is a publically-trusted root. https://baltimore-cybertrust-root.chain-demos.digicert.com/ is setup to chain to that root as a test.
