### ISSUE TITLE
connection.destroy() is not a function?

### ISSUE THREAD

**Issue by PsyTae** [mysqljs/mysql#1782]
```
var mysql = require('mysql');

var connection = mysql.createPool(db_config);
```

ln 435:
`if(connection._freeConnections.length > connection.config.connectionLimit) connection.destroy();`

```
$ TypeError: connection.destroy is not a function
    at C:\nodeCode\Code\Code.js:435:89
    at C:\nodeCode\Code\node_modules\async\dist\async.js:421:16
    at processQueue (C:\nodeCode\Code\node_modules\async\dist\async.js:1565:20)
    at taskComplete (C:\nodeCode\Code\node_modules\async\dist\async.js:1588:9)
    at Query.<anonymous> (C:\nodeCode\Code\node_modules\async\dist\async.js:1612:17)
    at Query._callback (C:\nodeCode\Code\node_modules\async\dist\async.js:906:16)
    at Query.Sequence.end (C:\nodeCode\Code\node_modules\mysql\lib\protocol\sequences\Sequence.js:86:24)
    at Query._handleFinalResultPacket (C:\nodeCode\Code\node_modules\mysql\lib\protocol\sequences\Query.js:137:8)
    at Query.OkPacket (C:\nodeCode\Code\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
    at Protocol._parsePacket (C:\nodeCode\Code\node_modules\mysql\lib\protocol\Protocol.js:280:23)
```

**Comment by dougwilson** [comment]
Hi @PsyTae is it possible to provide the full code that causes this? Also may be useful to provide the version of Node.js and of this module you're using. `connection.destroy()` is used is almost every test we have without issue, so really not sure why you'd be getting that. A full reproduction case would help out unless you can submit a patch?

**Comment by dougwilson** [comment]
Oh, nevermind. As soon as I finished typing that, I see the issue. You have the following:
```js
var connection = mysql.createPool(db_config);
```

But just because you assigned that result to a variable doesn't make it a `connection` object; the `mysql.createPool` function returns a `pool` object, which has no `.destroy` method.

I hope that helps!

**Comment by PsyTae** [comment]
Then why does the documentation have 

> If you would like to close the connection and remove it from the pool, use connection.destroy() instead. The pool will create a new connection the next time one is needed.

**Comment by dougwilson** [comment]
Hi @PsyTae `connection.destory()` is perfectly fine, but your code above doesn't have a connection object assigned to the `connection` variable; instead you accidentally have a pool object assigned to a variable named `connection`. Just assigning a pool object to a different variable doesn't really make it not a pool object any longer :)

**Comment by PsyTae** [comment]
So connection.query("SQL STATEMENT", function(sqlError, sqlResult){});
will create a connection from the pool, execute the SQL STATEMENT, and release the connection.

Basically, I need a large pool (300) for the first 10 minutes the script is active and then start pruning back the needed connections to somewhere around 10.

This is what I am trying to do.
SetTimeout at 10 minutes to change connection.config.connectionLimit to 10, and Then on each connection.query() after that 10 minutes destroy the connection and shrink the pool till open connections are down to the new value.  I thought connection.destroy() would be able to start killing off the open connections in te pool.

**Comment by dougwilson** [comment]
Hi @PsyTae in your code above, your `connection` variable is not a reference to a connection, but instead a reference to a pool object, which is why you're getting that error. You can only call `.destroy()` on a connection object, not a pool object. If you want to "destroy" the pool object, there is the `.end()` method you can use.

**Comment by PsyTae** [comment]
so there is a big difference between
```
var pool= mysql.createPool(db_config);

pool.query("SQL STATEMENT", function(sqlError, sqlResult){});
```

and

```
var pool= mysql.createPool(db_config);

pool.getConnection(function(err, connection) {
    connection.query("SQL STATEMENT", function(sqlError, sqlResult){});
});
```

**Comment by dougwilson** [comment]
Yea, so the first one will just queue up a query against the pool. It will just take whatever first available connection and run the query on it.

The second does something similar, though you have to go through all the motions yourself: first ask for a connection and wait, then perform a query and wait, then return the connection back to the pool.

But in the second one, you have more control, and especially in relation to this question, you get an actual connection object you can choose to destroy.
