### ISSUE TITLE
why mysql.escape will parse  'hello' to '\'hello\''

### ISSUE THREAD

**Issue by aflext** [mysqljs/mysql#1786]
I will  escape the parameter at first then concat the sql statement when querying.
So when i concat query strings using `like`:
```
const name = mysql.escape(req.info.name)
const sqlString = `select...name like '%${name}%'`
```
 It will lead to `select ... where name like '%'hello'%'`
but what i want is `select ... where name like '%hello%'`

![image](https://user-images.githubusercontent.com/3211461/28709589-7d712b6c-73b3-11e7-9432-5487de9b383b.png)

**Comment by dougwilson** [comment]
Hi @aflext this is because the idea is that what you give to `.escape` is _exactly what you want to have in your column_. In order to construct a LIKE with wildcards around it, just concat the `%` prior to escaping:
```js
const sqlString = mysql.format('select...name like ?', [`%${req.info.name}%'])
```

**Comment by aflext** [comment]
@dougwilson In my scenario, i `mysql.escape`  the parameters at first and then pass the parameter module by module and concat the sql string at last,so i will concat the `%%` at the very last module but not at the first module.  And it will be not suitable to put the `%%` at the first module to filter the `req.info`

**Comment by dougwilson** [comment]
Hi @aflext all I had is the code you provided to go off of. You provided the following code:
```js
const name = mysql.escape(req.info.name)
const sqlString = `select...name like '%${name}%'`
```

and the solution is to do the following:
```js
const sqlString = mysql.format('select...name like ?', [`%${req.info.name}%`])
```

If this isn't your real code, if you can provide the full code for exactly what you're trying to do, perhaps I can provide a better solution?
