### ISSUE TITLE
SQL command works on sql shell but doesn't work from node

### ISSUE THREAD

**Issue by 3mmarg97** [mysqljs/mysql#1788]
Hello, I have the following code : 
```javascript
login: function (username, password, callback) { 
        db.query('SELECT id, password, expdate FROM users WHERE username=' +
            mysql.escape(username) + ';', function (err, rows) {
            var row = rows[0];
            if (err) console.error(err)
            if (!row)
                callback(ERR_USER_NOT_FOUND, null);
            else
            bcrypt.compare(password, row.password, function (err, result) {
                if (result){
                    var expdate = row.expdate;
                    var currDate = moment(new Date()).format('YYYY-MM-DD HH:mm:ss');
                    if (moment(currDate).isAfter(expdate) && row.id !== 1)
                        callback ('Please pay your monthly fee to be able to login', null);
                    else
                        callback(null, row)
                }
                else {
                    callback(ERR_WRONG_PASSWORD, null);
                }
            })
        });
    }
```

It is work great but after running server for 5 or 4 days it return 'rows' array as empty  and it is working again if i reset the server. Please help me !

**Comment by dougwilson** [comment]
Hi @3mmarg97 that's definitely weird. I don't see anything obvious from the code posted above that would explain the behavior you're experiencing. Can you provide the following information so we can take a look?

1. Version of this module you're using.
2. Version of Node.js you are using.
3. Complete code that reproduces the issue we can run. It doesn't need to be _your_ full code, just full code that we can run exactly as-is by copy-and-paste. If there are any other modules than this one in it, please let their versions as well.
4. The DDL to run to setup any necessary tables and any queries we need to populate data in them.
5. Complete instructions for how to setup the code, tables, and then how to run it to reproduce the issue.

Thanks!

**Comment by 3mmarg97** [comment]
Hello @dougwilson , sorry for the delay. create a new vps server and install the web application again. Then, I've checked the pm2 errors log every one hour. I have the same website on two server. The first server is active and there is too many users on the server and this server didn't had any error. The second server is for testing and I'm only watching the logs without using website and the error appeared after about 12 hours of creating the server and installing the website. This is the error : 

```sh
0|www      | No callback function was given.
0|www      | Error: Connection lost: The server closed the connection.
0|www      |     at Protocol.end (/home/ammar/node_modules/mysql/lib/protocol/Protocol.js:113:13)
0|www      |     at Socket.<anonymous> (/home/ammar/node_modules/mysql/lib/Connection.js:109:28)
0|www      |     at emitNone (events.js:91:20)
0|www      |     at Socket.emit (events.js:185:7)
0|www      |     at endReadableNT (_stream_readable.js:974:12)
0|www      |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
0|www      |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

And the error message of the code that I've put in the issue is "Cannot enqueue Query after fatal error."

Why the Mysql server disconnect ??

This is my connection code : 

```javascript
var mysql  = require('mysql');
var db     = mysql.createConnection(require('./config'));
db.connect();
```
And this is the 'config' file : 

```javascript
module.exports = {
    host    : 'localhost',
    user    : 'root',
    password: '*******',
    database: 'mytestingdb'
};
```

What is the reason of this problem ??

**Comment by dougwilson** [comment]
Your MySQL server will close inactive connections based on the `wait_timeout` setting on your server: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

Once the connection was closed, you cannot make queries on the connection because it's dead and the TCP socket is gone, which gives the `Cannot enqueue Query after fatal error.`

**Comment by 3mmarg97** [comment]
Thanks for response. How can I handle this ?

**Comment by dougwilson** [comment]
You can either use connection pooling instead of trying to hang onto a single connection or you need to build logic to create a new connection. Any network interrupt can cause it to close, for example.

**Comment by 3mmarg97** [comment]
Ok, thank you very much. After reading the readme file (disconnects section)  I handled the error using this way:
https://stackoverflow.com/questions/20210522/nodejs-mysql-error-connection-lost-the-server-closed-the-connection
