### ISSUE TITLE
Improve documentation for SQL string escaping

### ISSUE THREAD

**Issue by moberemk** [mysqljs/mysql#1790]
So the tl;dr of this is this: the documentation for the default handling of parameters is just not very useful as-is.

Some more detail on specific issues with the section of the README for "[Escaping Query Values](https://github.com/mysqljs/mysql#escaping-query-values)" below:

1. **There's a lack of concrete examples**, only terse explanations and one example of an `INSERT` query. That doesn't help me understand how to make use of the library quickly; when writing code, my mind is thinking in code; why not provide code examples to reference quickly instead of a list to read through, parse, and then extrapolate an answer from?
2. **The language is terse at best, going into a bare minimum of detail** about what values are converted to. What does "safely escaped" mean for instance? For nested arrays, how deep does that go? Object handling is similarly unclear, explaining that it turns into a `key='val'` pairs but without going into detail around, say, nested object handling. When should I use an array? When should I use an object? Does the behaviour maybe depend on the number of question marks in my query?
3. **I take issue with the phrase "If you paid attention" because it's condescending to the reader.** I don't understand that preface; you're giving the reader an example, not testing their understanding of what they just skimmed through.

Normally I'd just open a PR with suggested fixes, but honestly I have no idea how this feature is intended to work in edge cases or complex scenarios without actually sitting down and testing how it behaves. And before it's asked: I did look at the unit tests, but they test very specific (and small) parts of the system's behaviour; that doesn't tell me how to actually write a `SELECT`/`INSERT`/`UPDATE`/`DELETE`/etc. query in practice--that's what I believe this library desperately needs.

**Comment by dougwilson** [comment]
I agree that there is a lot to be desired. I don't remember when the docs came to be, but before I even really became involved. Any PRs (even multiple, over time) to help improve it is greatly appreciated!

**Comment by dougwilson** [comment]
Doing a `git blame` shows 2012 and earlier (https://github.com/mysqljs/mysql/commit/265174922bbdd37a53ebb0f69df96290d0662a37), wow! They could sure use someone to volunteer to give them some love :)

**Comment by dougwilson** [comment]
I created a new label "good first contribution" instead of that old "help wanted" label.

**Comment by moberemk** [comment]
Should doc updates go here or to the SqlString library? Or parallel PRs for
both?

**Comment by dougwilson** [comment]
Either is good. I just copied the docs into SqlString, so if you make a PR to just one, I can cherry pick the commit with auth info intact to the other. I try to keep the barrier low :) If you want to make parallel PRs, go for it! But if you just make them to one of them I'll land the changes on both for you automatically 👍

**Comment by dougwilson** [comment]
Closing as this is quite old now and hasn't seen any follow up from OP. The docs have changed a bit, at least.
