### ISSUE TITLE
question: mysql error for api, 500 error

### ISSUE THREAD

**Issue by webmobiles** [mysqljs/mysql#1792]
It's possible to get a 500 error status automatically from this lib when the sql run contains by example sintaxis errors?.

actually i get in response.body:

{
    "code": "ER_BAD_FIELD_ERROR",
    "errno": 1054,
    "sqlMessage": "Unknown column 'ddd' in 'field list'",
    "sqlState": "42S22",
    "index": 0,
    "sql": "select ddd, lastname,  email from customers  \n\t "
}

but the code is 200

must manually to send 500 status every time i run a sql command ? any idea that can help me? 
I see everything like must be prepared for api rest, but i get confused when every node library show differents way to produce error. If it had a normal way, then i could read errors from a 200 statuts...

**Comment by dougwilson** [comment]
Can you share the code you are using? The answer would depend on your web framework since this module has no relation to http.

**Comment by webmobiles** [comment]
it's a simple query:

**Comment by dougwilson** [comment]
I'm really not sure what you're asking. Perhaps make a pull request?

**Comment by michael-ts** [comment]
@dougwilson  How do you get "sql" and "sqlMessage" in @webmobiles bad query to be defined?  Whenever I have a syntax error in my code these are undefined, e.g.
```
try {
    var sqlGet='some query with a syntax error'; 
    db.query(sqlGet, callback);
} catch (e) {
    console.log("error code:",e.code);
    console.log("error sql:",e.sql);
    console.log("error sqlMessage:",e.sqlMessage);
}
```

yields this output:

```
error code: ER_PARSE_ERROR                                                                                                                                               │·································································
error sql: undefined                                                                                                                                                     │·································································
error sqlMessage: undefined
```

**Comment by dougwilson** [comment]
I don't know. I asked for tge code that was being used and never got a response.

**Comment by webmobiles** [comment]
sorry have no more the code, i tried the  project some days i was newbie with this library  and I dont remember well how i had that reply (200). I had problems with this library to use asyn await and manage errors, i work anymore with mysql at the moment, so i can't reproduce the output, but if this library is able to use with async await (no callback) maybe i try again.
But my question was wrong,  most of libraries give any type of error, or 200, 401,500 there is no standard, so the handling erros must be prepared for all type of situations. that is was learned, and working with graphl and no more apis,  the good reply for graphql is always 200, so, my ask for get 500 status erros is wrong.
