### ISSUE TITLE
Use in browser?

### ISSUE THREAD

**Issue by maximilianberndt** [mysqljs/mysql#1794]
Using node.js I've been using mysqljs in the terminal, however I would like to use it on my website.
I've tried using browserify, but it dosen't work an im getting this error:

`bundle.js:34764 Uncaught ReferenceError: require is not defined`

In [this](https://github.com/mysqljs/mysql/issues/1323) thread I read that I shouldn't use browserify.

Is there another way to use this library in browser?

**Comment by maximilianberndt** [comment]
Ok I've found a solution using php.

**Comment by dougwilson** [comment]
Hi @maximilianberndt this library implements the MySQL TCP format, and unfortunately web browser have no API to make raw binary TCP sockets to read/write to, so it's not possible to run in a web browser at this time. You'd have to run this on the server and implement an HTTP-based interface on top to talk between the web browser and this module.

**Comment by maximilianberndt** [comment]
Hey @dougwilson, thanks for clarifying!
