### ISSUE TITLE
TypeError: Cannot read property 'acquireTimeout' of undefined

### ISSUE THREAD

**Issue by ShunmugamAiyappan** [mysqljs/mysql#1798]
```
\node_modules\mysql\lib\PoolConfig.js:10
  this.acquireTimeout     = (options.acquireTimeout === undefined)
                                    ^

TypeError: Cannot read property 'acquireTimeout' of undefined
    at new PoolConfig (E:\Projects\FrontEnd\React-WorkSpace\incentivio-superadmin-portal\node_modules\mysql\lib\PoolConfig.js:10:37)
```
```js
module.exports = {
  host        : '<ipaddress>',
  port        : 3306,
  user        : 'user',
  password    : 'pass',
  database    : 'dbName',
  serverId    : 256,
  minInterval : 200,
  acquireTimeout: 300,
  connectionLimit: 100,
  connectTimeout: 2000,
  queueLimit: 0,
  debug: true,
  waitForConnection: true,
  dateStrings: true
};
```

**Comment by dougwilson** [comment]
Hi @ShunmugamAiyappan your exports there is fine, but the error is because at some point it's not getting passed to your `.createPool` call. Can you show the code around that?

**Comment by ShunmugamAiyappan** [comment]
var connectionPool = mysqlOffer.createPool(mysqlClientDB);

    connectionPool.getConnection(function(err, connection) {
      var tableName = dbsettings.clientTableName ? dbsettings.clientTableName : 'Client';
      var clientQuery = 'SELECT * FROM '+tableName;
      // Use the connection
      connection.query(clientQuery, function (error, results, fields) {
        // And done with the connection.
        if (results && results.length > 0){
           res.json(JSON.stringify(results));
          } else {
            res.json([]);
          }

        connection.release();
        // Handle error after the release.
        if (error) throw error;
          // Don't use the connection here, it has been returned to the pool.
      });
    });

**Comment by dougwilson** [comment]
Hi @ShunmugamAiyappan can you show the code where `mysqlClientDB` is getting set?

**Comment by ShunmugamAiyappan** [comment]
mysqldbSettings.js

module.exports = {
  host        : 'dbname',
  port        : 3306,
  user        : ' ',
  password    : '',
  database    : '',
  minInterval : 200,
};

import Mysqldb from './mysqldbsettings';
var mysqlClientDB = Object.assign({}, Mysqldb);

Now it works, But sometimes I am getting the error mentioned in the initial thread.  I couldn't debug that point.

**Comment by dougwilson** [comment]
Hi @ShunmugamAiyappan the error means that at some point, the argument you are providing to `.createPool` is `undefined`. If you can provide your full code and steps to reproduce, I can help you debug it.

**Comment by ShunmugamAiyappan** [comment]
Thanks @dougwilson. this one is Server.js  Node server file 


import path from 'path';
import { Server } from 'http';
import Express from 'express';
import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter as Router } from 'react-router-dom';
import Mysqldb from './mysqldbsettings';
import dbsettings from './dbsettings';

const app = new Express();
const server = new Server(app);

var clientdb  = require('mysql');


var mysql      = require('mysql');

var mysqlClientDB = Object.assign({}, Mysqldb);

var connectionPool = mysqlOffer.createPool(mysqlClientDB);


  app.get('/api/client/', (req, res) => {

    connectionPool.getConnection(function(err, connection) {
      var tableName = dbsettings.clientTableName ? dbsettings.clientTableName : 'Client';
      var clientQuery = 'SELECT * FROM '+tableName;
      connection.query(clientQuery, function (error, results, fields) {
        if (results && results.length > 0){
           res.json(JSON.stringify(results));
          } else {
            res.json([]);
          }

        connection.release();
        if (error) throw error;
      });
    });
  });
  
  
  mysqldbsettings.js
  
  module.exports = {
  host        : 'dbname',
  port        : 3306,
  user        : ' ',
  password    : '',
  database    : '',
  minInterval : 200,
};


Hope this helps you. Also, another situation is when I am using the same MySQL for different DB connection

**Comment by dougwilson** [comment]
Hi @ShunmugamAiyappan I'm trying to get your code running, but unable to. I keep getting the following error with various versions of Node.js:
```
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```


Can you provide instructions for how to get your code up and running?

**Comment by ShunmugamAiyappan** [comment]
oh okay. No worries I cannot share the complete file here . What I would do, modify the code and send that here, Anyways thanks @dougwilson.

**Comment by SammRojas** [comment]
hola buenos días, me esta sucediendo este mismo error, quisiera saber como se soluciona

**Comment by DonaldoJr1021** [comment]
Hola a todos, he solucionado el error de la siguiente forma.
Validando que sea una const y sin llaver la variable la cual se usara para pasar como parametro a .createPool()
es decir:
`
 const mysql = require('mysql') // Llamada del modulo de MySql
// llamada de la clase que contiene las credenciales de la conexión a la base de datos
const sqlconnection = require('./databasekeys);
/*ahora creamos la const que tendra la conexión a la base de datos y pasamos la const sqlconeccitoon *como parámetros al usar el método de sql -createPool()- puesto que sqlconnection es quien posee las *credenciales y automáticamente se el metodo identifica que parametros de conexión exiten dentro de *databasekeys.js  */
const dbconnection = mysql.createPool(sqlconnection)

// Luego realizas el proceso de conexión, en este caso sera basico
dbconnection.getConnection(connection =>{

    dbconnection.releaseConnection(connection);
    console.log('Db is Connected');
});


/* Archivo databasekeys.js */

module.export = {
 database {
  host = 'localhost', //o tu dirección IP 
  user = 'root', // o tu usuario
  password = 'tupassword',//tu contraseña
  database = 'prueba' //Aqui el nombre de la base de datos
 }
}

// En el index, solo debes requerir el archivo 
`
Se que puede haber distintas razones por las cuales se genere este inconveniente, en mi caso fue por colocar la const a la cual le asignaba los parámetros de conexión entre llaves

es decir: const {miconstante} = require('./databasekeys'); y miconstante al momento de pasarla como parametro no estaba siendo bien interpretada por el metodo createPool
