### ISSUE TITLE
query json escapment for select

### ISSUE THREAD

**Issue by clem91** [mysqljs/mysql#1799]
Hi,

I found one of the capabilities of this library really great! It's the "neat thing" with the json object and insert statement.

```js
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // INSERT INTO posts SET `id` = 1, `title` = 'Hello MySQL'
```
I tested this trick with select statement but unfortunately the separator is always a comma and it's only working with json with one parameter. 
I think it could be a great feature for this library to extend this trick to select and why not to other sql statements. With this kind of feature we can have a better generic query functions and a high level of abstraction. 

```js
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('SELECT *  FROM posts WHERE ?', post, function (error, results, fields) {
  if (error) throw error;
  // Neat!
});
console.log(query.sql); // SELECT *  FROM posts WHERE `id` = 1 and `title` = 'Hello MySQL'
```

**Comment by dougwilson** [comment]
Hi @clem91 I don't think it was implemented because there isn't a way to know the context of where the `?` is being used without fully parsing the SQL, witch is not trivial. If you know how to accomplish this, please feel free to submit a pull request!

**Comment by clem91** [comment]
From a quick overview I found the "guilty" function in dependency lib sqlstring : objectToValues(object, timeZone)
If I have time i'll try to make a PR enhancement to this function in order to analyse the sql statement and decide if coma or 'AND' is appropriate.

**Comment by dougwilson** [comment]
What about 'OR' as the joining as well?

**Comment by dougwilson** [comment]
There is also https://hiddentao.com/squel/ if you wanted a full-featured SQL builder library to build SQL to give to this driver if that's what you're looking for.

**Comment by clem91** [comment]
This lib for my part seems reallly gadget (squel) and not helping developers to have light and readable code.

I'm building an api and I'm making a lot of  queries that looks same with the same error management and stuff around it.

select [ string ] from [ string ] where { key = content (data reworked from client request)}

so I found in this trick the possibility to have an abstracted function for these kind of repetitives operations  where the changes are only in data entries provided.
That why I try to share this tought and have comments on it. Maybe  I saw an enhancement where it does'nt belong =)

**Comment by dougwilson** [comment]
Hi @clem91 sorry, I didn't really understand a lot of what you said there. I said you're welcome to make a pull request here to add it. I just followed up with something I've seen people using in case it fit your use-case, not trying to say not to make an enhancement (otherwise I'd never have said you should make a pull request...). Please clarify what you mean.
