### ISSUE TITLE
Problem With Connection To Mysql When I Open A Http Proxy 

### ISSUE THREAD

**Issue by qiangzi7723** [mysqljs/mysql#1807]
There is my code

```js
const pool = mysql.createPool(database);

const query = (sql, options, callback) => {
    pool.getConnection((err, conn) => {
        if (err) {
            callback(err, null, null);
        } else {
            conn.query(sql, options, (err, results, fields) => {
                callback(err, results, fields);
                conn.release();
            });
        }
    });
}

// for test
query('select * from singer where singer=1', [], (err, res) => {
    console.log(err,res);
})
```

If I open the vpn proxy such as shodowsocks and then the error callback

`Error: Connection lost: The server closed the connection.(…)`

If I close the vpn the mysql run normal without error.

Could anyone help me? 

I have no idea for this.

**Comment by dougwilson** [comment]
Hi @qiangzi7723 sorry we missed your question all that time ago. I'm not sure, nothing seems wrong with the code. Maybe can you help us replicate the issue?

**Comment by dougwilson** [comment]
I'm going to close this since I never heard back.
