### ISSUE TITLE
Possible to use parameter twice in statement for multipleStatements?

### ISSUE THREAD

**Issue by dskvr** [mysqljs/mysql#1814]
Consider the statement below

```
INSERT INTO `hello` (`foo`) VALUES ('bar') ON DUPLICATE KEY UPDATE foo = bar;
```

In the context of `multipleStatements`
```
  db.query("INSERT INTO `hello` (`foo`) VALUES ? ON DUPLICATE KEY UPDATE foo = ?", [ ["bar"], ["circle"]], function(err){
    console.log(err)
  });
// sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'?\' at line 1',
```
~Only solution I can find is~ Nevermind, doesn't work. 
```
[["bar","bar"], ["circle","circle"]]
```

Which would bring sadness to my otherwise logical code. _Is there another way?_

**Comment by dskvr** [comment]
Brain fart.

`INSERT IGNORE`

**Comment by michael-ts** [comment]
@dskvr  Is this supposed to work?  How did you get it to work? When I try to insert multiple records like you are doing, it only inserts the first record and ignores the rest...
