### ISSUE TITLE
Mysql query not returning not correct Column order

### ISSUE THREAD

**Issue by bala-drg** [mysqljs/mysql#1817]
Hi
i've written stored procedure which is returning result as below 

<img width="407" alt="screen shot 2017-09-07 at 8 01 32 pm" src="https://user-images.githubusercontent.com/13250640/30168776-0472d178-9408-11e7-96a1-a8cec6ecebf8.png">

but when i'm calling the same query in the application, i'm getting below result 
RowDataPacket {
      '2013': 2,
      '2014': 3,
      '2015': 4,
      'A':'Test,
      'B':'Test,
      'C':'Test'
}

I would like to expect the same column order which are A,B,C,2013,2014,2015... Please help

**Comment by dougwilson** [comment]
Hi @bala-drg unfortunately this is just how JavaScript works: it always orders keys that look like numbers before all other keys in an object. Here is an example:
```
$ node -pe 'o={};o["A"]="Test";o["B"]="Test";o["C"]="Test";o["2013"]=1;o["2014"]=2;o["2015"]=3;o'
{ '2013': 1, '2014': 2, '2015': 3, A: 'Test', B: 'Test', C: 'Test' }
```

You can see I added them in the order of your columns but internally Node.js will always iterate over the keys with the number-like keys first.

You can find more information about how object keys are ordered in JavaScript at http://2ality.com/2015/10/property-traversal-order-es6.html
