### ISSUE TITLE
changedRows is English language-specific

### ISSUE THREAD

**Issue by jniles** [mysqljs/mysql#1819]
The `changeRows` property is set [from a regex](https://github.com/mysqljs/mysql/blob/master/lib/protocol/packets/OkPacket.js#L25) that assumes an English language message response.  This functionality breaks in multi language environments.  For example, a French installation of MySQL will return `modifié`, which will be not be caught by the regex.

In my view, there are two solutions:
 1. Attempt to improve the regex to be multi-language.
 2. Document the language-specific nature of this property and suggest that non-English environments use `affectedRows` instead.

For further relevant information, see the discussion in https://github.com/mysqljs/mysql/issues/251 which pointed me to the `changedRows` property.

**Comment by dougwilson** [comment]
Ideally if it can be modified to support all languages that would be much better than a doc change. Docs can be easily overlooked and of course just working right is better anyway :)

**Comment by jniles** [comment]
That sounds like the best solution.  In light of https://github.com/mysqljs/mysql/issues/1819#issuecomment-329151763, would you like me to close https://github.com/mysqljs/mysql/pull/1820?

**Comment by dougwilson** [comment]
I can still merge the docs change, and keep this open for tracking getting it to actually work for all the languages.

**Comment by dougwilson** [comment]
Here is the translation strings from 5.7.17 for the message:
```
ER_UPDATE_INFO  
        cze "Nalezených řádků: %ld  Změněno: %ld  Varování: %ld"
        dan "Poster fundet: %ld  Ændret: %ld  Advarsler: %ld"
        nla "Passende rijen: %ld  Gewijzigd: %ld  Waarschuwingen: %ld"
        eng "Rows matched: %ld  Changed: %ld  Warnings: %ld"
        est "Sobinud kirjeid: %ld  Muudetud: %ld  Hoiatusi: %ld"
        fre "Enregistrements correspondants: %ld  Modifiés: %ld  Warnings: %ld"
        ger "Datensätze gefunden: %ld  Geändert: %ld  Warnungen: %ld"
        hun "Megegyezo sorok szama: %ld  Valtozott: %ld  Warnings: %ld"
        ita "Rows riconosciute: %ld  Cambiate: %ld  Warnings: %ld"
        jpn "該当した行: %ld  変更: %ld  警告: %ld"
        kor "일치하는 Rows : %ld개 변경됨: %ld개  경고: %ld개"
        por "Linhas que combinaram: %ld - Alteradas: %ld - Avisos: %ld"
        rum "Linii identificate (matched): %ld  Schimbate: %ld  Atentionari (warnings): %ld"
        rus "Совпало записей: %ld  Изменено: %ld  Предупреждений: %ld"
        serbian "Odgovarajućih slogova: %ld  Promenjeno: %ld  Upozorenja: %ld"
        spa "Líneas correspondientes: %ld  Cambiadas: %ld  Avisos: %ld"
        swe "Rader: %ld  Uppdaterade: %ld  Varningar: %ld"
        ukr "Записів відповідає: %ld  Змінено: %ld  Застережень: %ld"
```

**Comment by dougwilson** [comment]
It looks like it's the only message that would match the language-neutral pattern `/^[^:]+: ([0-9]+)[^:]+: ([0-9]+)[^:]+: ([0-9]+)/`

**Comment by dougwilson** [comment]
Ok, so looks like that regular expression seems to work fine. If you want to try it out before the next release, you can use the instructions at https://github.com/mysqljs/mysql#install to install the `master` branch to test.

**Comment by jniles** [comment]
Awesome!  I'll give it a whirl and comment back when we have some results.
