### ISSUE TITLE
Unable to start mysql service in ubuntu 16.04

### ISSUE THREAD

**Issue by R-yogesh** [mysqljs/mysql#1823]
getting error while starting mysql service

Job for mysql.service failed because the control process exited with error code. See "systemctl status mysql.service" and "journalctl -xe" for details.

and getting apparmor error

Sep 14 20:25:16 linux kernel: audit: type=1400 audit(1505400916.406:1956): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/proc/25909/status" pid=25909 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=108 ouid=108
Sep 14 20:25:16 linux kernel: audit: type=1400 audit(1505400916.406:1957): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/sys/devices/system/node/" pid=25909 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=108 ouid=0
Sep 14 20:25:16 linux kernel: audit: type=1400 audit(1505400916.406:1958): apparmor="DENIED" operation="open" profile="/usr/sbin/mysqld" name="/proc/25909/status" pid=25909 comm="mysqld" requested_mask="r" denied_mask="r" fsuid=108 ouid=108
Sep 14 20:25:17 linux systemd[1]: mysql.service: Main process exited, code=exited, status=1/FAILURE

please help us to solve this issue

**Comment by dougwilson** [comment]
Sorry, it seems you posted this in the wrong location. This is a mysql client library for Node.js.
