### ISSUE TITLE
How can I reproduce 'PROTOCOL_CONNECTION_LOST' error?

### ISSUE THREAD

**Issue by Randy808** [mysqljs/mysql#1824]
I, along with many others, have gotten this error while using a single connection using this module. After hours of searching through the web, I found a fix by error handling which for whatever reason is not working for me. Looking through the many issue requests, I can't seem to find a way to reproduce the error that would allow me to assess why the error handling fails. Instead, I see recommendations to use pooling. Pooling seems like a viable option, but solving this problem now will save me time down the line if for whatever reason it happens when pooling. I also don't want to restructure code using a whole bunch of getConnection callbacks at this time. Can anyone help me reproduce this error?

**Comment by dougwilson** [comment]
This error is raised when Node.js informs the module that the TCP connection closed, if that helps.

**Comment by ngerritsen** [comment]
I reproduced it locally by running mysql in a docker container, running the application and then killing the mysql container.

**Comment by o1lab** [comment]
I am using pooling and have started to see this problem today in my local setup - below is a reproducible scenario in my application

1. Start app
2. First query in app iterates over lot of rows (3000-4000 rows) in my case.
3. Subsequent queries result in PROTOCOL_CONNECTION_LOST. I have to restart mysql server after this step.

In step 2 - if there is NO iteration over result rows - problem is NOT seen.  
If step 2 is performed after few other queries to database - problem is NOT seen.


= = = = = =

About step2:
Query is made to INFORMATION_SCHEMA.columns and not to database for which pool was connected - (can this cause an issue?)
Time spent iterating over results is 2 milli seconds - not much as I initially thought.

= = = = = =

Strangely, below queries work fine even when PROTOCOL_CONNECTION_LOST is seen for select queries.

```
show tables
describe tableName
```
= = = = = =

```
pool.query(QUERY, params, function (err, results) {

  if (err) {
    console.log(err, results);
  } else {

    /**
     * iterates over 3k - 4k rows
     */
  }

})
```

**Comment by dougwilson** [comment]
Yep, that would do it, since killing the container would close the TCP connection. Not sure if there is anything additional wanted since there hasn't been anything more from @Randy808
