### ISSUE TITLE
about pool 

### ISSUE THREAD

**Issue by tcs2422bk** [mysqljs/mysql#1826]
there are most queued queries in pool not run yet , 
but mysql disconnected and breken before queued queries execute . 

Are there queued queries dismiss?
How could I restore there queued queries and execute they after mysql reconnect ?

Excuse me, my English is not good.

**Comment by victor0801x** [comment]
in my experience, you can't
you can store the data before query? but, i don't recommend
you should optimize your query command, or tune the database config to speed-up your db operators
ps. in my laptop (mariadb 10.1), default config can reach 5000~10000 opts/s per table

**Comment by sidorares** [comment]
> Are there queued queries dismiss?

yes, they all get callback called with error

> How could I restore there queued queries and execute they after mysql reconnect ?

you have to handle this [re trying] manually in your app logic

**Comment by tcs2422bk** [comment]
thank you. I try this right now .
