### ISSUE TITLE
Does not fill data from a complex query

### ISSUE THREAD

**Issue by AnimaDei326** [mysqljs/mysql#1832]
**The problem in /models/game.js  110 line**.

**Here is my question on stackoverflow:**

https://ru.stackoverflow.com/questions/722280/%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82-mysql-%D0%BD%D0%B5-%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D1%8F%D0%B5%D1%82-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%B8%D0%B7-%D1%81%D0%BB%D0%BE%D0%B6%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81%D0%B0

**My code is here:**
https://github.com/AnimaDei326/fss

**Comment by AnimaDei326** [comment]
Help me please...

**Comment by dougwilson** [comment]
Can you add `debug: true` to your connection config and run the code again? It should output the final query text that was sent to the server to STDOUT and we can compare how it's different from the expected query.

My first guess looking at your expected query and what is written seems to indicate the two `??.?? = ?` parts should actually be `??.?? = ??`.

**Comment by AnimaDei326** [comment]
you are a genius! genius, genius, genius! thank you very much!! ??. ?? = ??
![image](https://user-images.githubusercontent.com/29117053/30871186-eaa09c62-a320-11e7-9527-71af7a9d8c79.png)
