### ISSUE TITLE
Upsert query

### ISSUE THREAD

**Issue by sumveds** [mysqljs/mysql#1835]
I am new to mysql npm. Is there a way out to fire an upsert query? Something like below.
`INSERT INTO `{TABLE}` (`{COLUMN}`) VALUES (:value)
ON DUPLICATE KEY UPDATE `{COLUMN}` = :value_dup';`

**Comment by dougwilson** [comment]
Yea, should be. If you can put the exact query you would run on like the MySQL Workbench or similar, I can help you put it into this module.

**Comment by dougwilson** [comment]
Closing since I never heard back.
