### ISSUE TITLE
How to calculate "connectionLimit" for poolCluster?

### ISSUE THREAD

**Issue by glavince** [mysqljs/mysql#1836]
If I have 10 Node.js backend servers who connect to 5 Mysql servers using "poolCluster" and each MySql server has "max_connections" => 500.
What should be the correct value for "connectionLimit" ?

Should I count all MySql servers connections and divide with backend servers (5 x 500 / 10 = 250) ?  Or I should use other calculation?

**Comment by dougwilson** [comment]
So a pool cluster is just a collection of pool objects by names, with a method to select a pool to use. You would add up the connectionLimit of each pool added to the pool cluster to know what the max number of connections that cluster object can make to the db from that process.
