### ISSUE TITLE
Improper escaping of punctuation characters in password

### ISSUE THREAD

**Issue by ChrisHughes** [mysqljs/mysql#1842]
I noticed I was having connection issues recently on my previously working node.js app. Not sure if this is related directly to the mysql wrapper or an underlying npm library, however here goes:

The password I was using was auto-generated by a password manager, and contained some ASC-II punctuation characters. The password (as it is now changed) was h1gWs1]\'_nblx[aE(*;=md?>a

I could connect fine from the command line mysql client both locally on my Mac and on the Ubuntu 16.04 server. However when connecting via the mysql wrapper in nodejs (using bookshelf & knex), I receive a 

```
code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: 'Access denied for user \'user\'@\'blah\' (using password: YES)',
  sqlState: '28000',
  fatal: true }
```

After much troubleshooting trying to identify what the issue was, I ended up changing the password to one with just alphanumeric characters, and it worked.

I'm posting this here, rather than with knex etc as I've tested & demonstrated the password being passed unaltered down to this library, thus ruling out knex etc as contributing factors to the issue.

Hopefully this can help someone. This stack had lots of other tools, languages and utilities connecting to it just fine with that password, so it seems like this is a genuine bug.

**Comment by dougwilson** [comment]
Weird, there is no escaping this library does as part of the password at all. I'll get a MySQL server setup with a user with that password to see what is going on. Can you provide the following information?

1. Version of this module you are using.
2. Version of Node.js you are using.
3. The version of MySQL you are using.

Thank you! Also if you know what the issue is, pull requests are certainly welcome!

**Comment by ChrisHughes** [comment]
1. Recreated issue on both 2.14.1 and 2.15.0
2. Nodejs 8.3.0
3. Aurora MySQL 5.6.10a

**Comment by dougwilson** [comment]
Thanks! What is Aurora MySQL? Can you link me to the download site? If this is a different dialect lile MariaDB us, it's possible the auth works slightly different. We test against MySQL community edition and MariaDB right now though our CI and do one off tests against the Azure MySQL.

**Comment by ChrisHughes** [comment]
Amazon Aurora is a scalable drop-in replacement to MySQL https://aws.amazon.com/rds/aurora/details/

I've also just tested this on stock MySQL 5.6.27 and the issue persists.

**Comment by dougwilson** [comment]
Thanks! Yep, I was able to replicate with 5.6 MySQL community edition as well:
```
$ npm i mysql
+ mysql@2.15.0
added 11 packages in 1.725s

$ cat test.js
const mysql = require('mysql')

const connection = mysql.createConnection({
  user: 'test_user',
  password: "h1gWs1]'_nblx[aE(*;=md?>a"
})

connection.query('SELECT 1', (err, rows) => {
  if (err) throw err
  console.log(rows)
  connection.end()
})

$ docker run -d --name mysql-1842 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.6
Unable to find image 'mysql:5.6' locally
5.6: Pulling from library/mysql
85b1f47fba49: Pull complete 
27dc53f13a11: Pull complete 
095c8ae4182d: Pull complete 
0972f6b9a7de: Pull complete 
a11a67190c24: Pull complete 
908252bea0ce: Pull complete 
ffe3d1ca6af8: Pull complete 
e4a48a0019b4: Pull complete 
3b57faa79614: Pull complete 
55c3e5a390ed: Pull complete 
7a6f5c78394b: Pull complete 
Digest: sha256:2528302501835852673c6594a825c14894b16c41b46cdf036b81426700fdb469
Status: Downloaded newer image for mysql:5.6
20dd9e97d881a8559523476d790a0330a9221ce4801d651080d39a5e58c7dc24

$ docker exec mysql-1842 mysql -e 'select version()'
version()
5.6.37

$ docker exec mysql-1842 mysql -e 'grant all privileges on *.* to "test_user"@"localhost" identified by "h1gWs1]'"'"'_nblx[aE(*;=md?>a"'

$ docker exec mysql-1842 mysql -u test_user -p'h1gWs1]'"'"'_nblx[aE(*;=md?>a' -e 'select version()'
version()
5.6.37
Warning: Using a password on the command line interface can be insecure.

$ node test.js
/mysql-1842/test.js:9
  if (err) throw err
           ^

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'test_user'@'172.17.0.1' (using password: YES)
    at Handshake.Sequence._packetToError (/mysql-1842/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Handshake.ErrorPacket (/mysql-1842/node_modules/mysql/lib/protocol/sequences/Handshake.js:130:18)
    at Protocol._parsePacket (/mysql-1842/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/mysql-1842/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/mysql-1842/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/mysql-1842/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    --------------------
    at Protocol._enqueue (/mysql-1842/node_modules/mysql/lib/protocol/Protocol.js:145:48)
    at Protocol.handshake (/mysql-1842/node_modules/mysql/lib/protocol/Protocol.js:52:23)
    at Connection.connect (/mysql-1842/node_modules/mysql/lib/Connection.js:130:18)
    at Connection._implyConnect (/mysql-1842/node_modules/mysql/lib/Connection.js:461:10)
    at Connection.query (/mysql-1842/node_modules/mysql/lib/Connection.js:206:8)
    at Object.<anonymous> (/mysql-1842/test.js:8:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

**Comment by dougwilson** [comment]
So I'm trying to figure out what is wrong. The auth part of this module hasn't changed in many years, and looking at the protocol docs (http://web.archive.org/web/20160604101728/http://dev.mysql.com/doc/internals/en/secure-password-authentication.html#packet-Authentication::Native41) it seems like this module's doing the right thing:

> SHA1( password ) XOR SHA1( "20-bytes random data from server" <concat> SHA1( SHA1( password ) ) )

I wonder if there is something going on with encoding on any of those pieces. Do you know what the working ones are doing?

**Comment by ChrisHughes** [comment]
I'm unfamiliar with the internals of MySQL authentication, perhaps setting up a series of test cases and confirming the functionality of the various components in Auth.js might be a good starting point.

Particularly with type inference built into javascript when a string is broken down into respective bytes and one byte happens to be a number? 

``` nr = this.xor32(nr, this.add32(this.mul32(this.add32(this.and32(nr, [0, 63]), [0, add]), [0, c]), this.shl32(nr, 8))); ```

Where c is the current password byte being processed and c could be 'a' or c could be '3' and is then submitted to functions which operate on it with ^ or +. In these instances it would be easy for '3' to by interpreted as 3 rather than its ASC-II value 51.

Or with utf8 conversion creating some variances in the entered password from its byte represented value?

```  var stage1 = sha1((Buffer.from(password, 'utf8')).toString('binary')); ```

Not saying I've found the answer as I haven't tested this yet, but these are the two scenarios I can think of having looked over what's going on in there briefly.

**Comment by dougwilson** [comment]
Yea, I was just doing that and I think everything checks out. Here is the different stages for that password:
```
20 bytes from server: 0x703d7c796e3a745a483a28565c4b4041624d3b7e
password: 0x6831675773315d275f6e626c785b6145282a3b3d6d643f3e61 ("h1gWs1]'_nblx[aE(*;=md?>a")
sha1(password): 0x6a0b9be92e5bb4d34117abfb8bbf0ede6636165d
sha1(sha1(password)): 0xb3f769264b2a53597cad44ed134e01ef95352db5
20 bytes <concat> sha1(sha1(password)): 0x703d7c796e3a745a483a28565c4b4041624d3b7eb3f769264b2a53597cad44ed134e01ef95352db5
sha1(20 bytes <concat> sha1(sha1(password))): 0x1bbee829d46fad7e04cac9c3ef657871342f72a0
0x6a0b9be92e5bb4d34117abfb8bbf0ede6636165d xor 0x1bbee829d46fad7e04cac9c3ef657871342f72a0: 0x71b573c0fa3419ad45dd623864da76af521964fd
    0b0110101000001011100110111110100100101110010110111011010011010011010000010001011110101011111110111000101110111111000011101101111001100110001101100001011001011101
    0b0001101110111110111010000010100111010100011011111010110101111110000001001100101011001001110000111110111101100101011110000111000100110100001011110111001010100000
    0b0111000110110101011100111100000011111010001101000001100110101101010001011101110101100010001110000110010011011010011101101010111101010010000110010110010011111101
```

**Comment by dougwilson** [comment]
So

> var stage1 = sha1((Buffer.from(password, 'utf8')).toString('binary'));

gives the stage1 value as the hex form 0x6a0b9be92e5bb4d34117abfb8bbf0ede6636165d which certainly seems right, right? Is that the SHA1 you would expect for that password?

**Comment by dougwilson** [comment]
Another plan could be to figure out exactly which characters in the password are causing the issue, and then see which bits are 1 in those characters compared to the ones that work. You'd think if something was wrong with the routine it just won't work with any password, rather than only passwords with certain characters. Typical of Oracle (who remove the protocol docs from their site -- ugh) it's possible that the documentation itself may not actually 100% represent the algorithm in some way?

**Comment by dougwilson** [comment]
MySQL stores the `sha1(sha1(password))`, and selecting it shows that the mysql library does at least get that value correct:
```
$ docker exec mysql-1842 mysql -e 'select password from mysql.user where user = "test_user"'
password
*B3F769264B2A53597CAD44ED134E01EF95352DB5
```

**Comment by dougwilson** [comment]
Ok, sorry, I was on a goose chase for no reason... I didn't realize that I granted a user `test_user@localhost` by the user denied was `'test_user'@'172.17.0.1'`. Of course it was denied, because test_user was not allowed to connect from 172.17.0.1 in the setup I made. I re-did the setup and just allowed any host, instead of only allowing localhost. It works 100% fine with this module and the password you gave, as in I cannot reproduce the issue. Please take a careful look at my setup below and let me know exactly what is different between our setups so I can take another look:

```
$ npm i mysql
+ mysql@2.15.0
added 11 packages in 1.302s

$ node -v
v8.3.0

$ cat test.js
const mysql = require('mysql')

const connection = mysql.createConnection({
  user: 'test_user',
  password: "h1gWs1]'_nblx[aE(*;=md?>a"
})

connection.query('SELECT 1', (err, rows) => {
  if (err) throw err
  console.log(rows)
  connection.end()
})

$ docker run -d --name mysql-1842 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=test -p 3306:3306 mysql:5.6
20dd9e97d881a8559523476d790a0330a9221ce4801d651080d39a5e58c7dc24

$ docker exec mysql-1842 mysql -e 'select version()'
version()
5.6.37

$ docker exec mysql-1842 mysql -e 'grant all privileges on *.* to "test_user" identified by "h1gWs1]'"'"'_nblx[aE(*;=md?>a"'

$ docker exec mysql-1842 mysql -u test_user -p'h1gWs1]'"'"'_nblx[aE(*;=md?>a' -e 'select version()'
version()
5.6.37
Warning: Using a password on the command line interface can be insecure.

$ node test.js
[ RowDataPacket { '1': 1 } ]
```

**Comment by dougwilson** [comment]
I'm going to close this since I haven't heard back in 30 days.
