### ISSUE TITLE
Connect error - aws aurora reader endpoint

### ISSUE THREAD

**Issue by tonovation** [mysqljs/mysql#1847]
Help me.

node: 8.6.0
mysql: 2.15.0

mysql.createPool use
aws aurora Reader Endpoint connecting error.(Cluster Endpoint connecting success)
error: connect EAGAIN 172.x.x.x:3306 - Local (0.0.0.0:43777) 
mysql.createPoolCluster use
error: Pool does not exist.(Cluster Endpoint connecting success)

thank you.

**Comment by dougwilson** [comment]
Can you help us replicate the issue? There isn't enough information to figure out what is happening.

**Comment by tonovation** [comment]
1. test-cluster.cluster-test.ap-northeast-2.rds.amazonaws.com (master)
2. test-re1.test.ap-northeast-2.rds.amazonaws.com (replication)
3. test-cluster.cluster-ro-test.ap-northeast-2.rds.amazonaws.com (read endpoint, all replication connection url)

var connection = mysql.createConnection/createPool/createPoolCluster({
  host     : '1/2/3',
  user     : 'same',
  password : 'same',
  database : 'same'
})
1 - success
2/3 - fail

**Comment by tonovation** [comment]
Duplicate of #

**Comment by dougwilson** [comment]
Hi! Can you provide the steps to replicate? The value 1/2/3 isn't likely a valid hostname, whixh may be what the issue is.

**Comment by dougwilson** [comment]
Closing due to no response.
