### ISSUE TITLE
Geometry type is lost

### ISSUE THREAD

**Issue by kevinresol** [mysqljs/mysql#1852]
The [parser](https://github.com/mysqljs/mysql/blob/310c6a7d1b2e14b63b572dbfbfa10128f20c6d52/lib/protocol/Parser.js#L342-L389) should retain the geometry type. It would be nice to represent the geometry in some standard format, e.g.: GeoJSON

**Comment by sidorares** [comment]
there are built in functions to assist with this: https://dev.mysql.com/doc/refman/5.7/en/spatial-geojson-functions.html

I agree that it would be better to output geometry data as geojson but that's backwards incompatible change ( and also can be done on user side with `typeCast` function )

**Comment by kevinresol** [comment]
Would it be nice to add a new function? maybe named `geojson()`?

**Comment by dougwilson** [comment]
Just define a custom typecast to output in the format you need :+1:
