### ISSUE TITLE
dateString causing connection terminate

### ISSUE THREAD

**Issue by prashantbiradar92** [mysqljs/mysql#1853]
I wanted **date type** field should return as string and **timestamp or datetime** type as javascript object.

I configured like below
`mysql.createPool({
                           databaseString:['DATE']
                        });`

It is terminating application after some time.
Please help me,  Is this right way to achieve?

**Comment by dougwilson** [comment]
The tests for this in our test suite work fine, so not sure what is happening. Can you provide additional information, perhaps what error message you're getting, steps to reproduce, or something else?

**Comment by bbito** [comment]
@prashantbiradar92 Perhaps it is my lack of familiarity with pools, but I am not aware of `databaseString` options. I use the `dateStrings` option thusly: `dateStrings: ['DATE']`
See: https://github.com/mysqljs/mysql/blame/e16c52da980e46012a391232be884b797b8af070/Readme.md#L214-L216
Or find the `dateStrings` section in "Connection Options":  https://github.com/mysqljs/mysql#connection-options

**Comment by dougwilson** [comment]
I know about the option, but I don't understand what the issue you are having is.

**Comment by bbito** [comment]
@dougwilson - But don't the `createPool()` arguments expect normal connection options like `dateStrings` I can't find reference to `databaseString` in the docs...

**Comment by dougwilson** [comment]
There is no such thing as "databaseString" in this module.

**Comment by bbito** [comment]
> There is no such thing as "databaseString" in this module.
@prashantbiradar92 try: `mysql.createPool({ dateStrings:['DATE'] });`
Although I think you need the rest of your connection options in there as well, e.g.:
```
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret',
  database        : 'my_db'
  dateStrings     :['DATE']
});
```
from https://github.com/mysqljs/mysql#pooling-connections

**Comment by dougwilson** [comment]
Oh, I'm sorry, I didn't realize you weren't the OP :) So my reply doesn't make sense, sorry!

**Comment by bbito** [comment]
@dougwilson No problem! I was just trying to help out with this tiny corner of the module that I know something about :)

**Comment by prashantbiradar92** [comment]
@dougwilson @bbito 
 sorry! for my typo mistake  -  databaseString -> dateString
 Thanks for your support.
