### ISSUE TITLE
centos7.2 mysql 5.7 when I reboot Centos mysql can't start again

### ISSUE THREAD

**Issue by goonwzz** [mysqljs/mysql#1858]
Oct 30 16:05:49 izn2uz4ukl8094z mysql[2754]: Starting MySQL...The server quit without updating PID file (/data/mysql/izn2uz4ukl8094z.pid).[FAILED]
Oct 30 16:05:49 izn2uz4ukl8094z systemd[1]: mysql.service: control process exited, code=exited status=1
Oct 30 16:05:49 izn2uz4ukl8094z systemd[1]: Unit mysql.service entered failed state.
Oct 30 16:05:49 izn2uz4ukl8094z systemd[1]: mysql.service failed.

**Comment by dougwilson** [comment]
Hi @goonwzz I think you posted on the wrong place. This repository is a Node.js implementation of the MySQL protocol as a client driver.
