### ISSUE TITLE
how to do bulk insert for query with subquery

### ISSUE THREAD

**Issue by zebralight** [mysqljs/mysql#1859]
hello.  I have a question on how I can perform a bulk insert that doesn't have a single insert query written in the format in the official doc:

`insert into foo (a, b, c) values (d, e, f)`

but instead follows the following format

`insert into a (b, c) values (?, (select d from e where f = ? and g = ? and h = ?)', [i, j, k, l])`

cheers.

**Comment by kai-koch** [comment]
From your code snippet I would rewrite it as:
```SQL
INSERT INTO a
SELECT ? AS b, d AS c
  FROM e
  WHERE f = ? and g = ? and h = ?;
```
