### ISSUE TITLE
Connection pool connectivity errors crashing app

### ISSUE THREAD

**Issue by fit-aditya** [mysqljs/mysql#1860]
Hi,

I have a NodeJS ExpressJS Rest API in the cloud which is using MySQL as database and this library to connect to the database. I use connection pools like mentioned in the Readme. The pool object is created on app initialization and this object is passed to every route to create connections whenever a request comes. I am directly using the pool.query() method and not creating a connection, executing query and closing the connection as it already internally does that.

Now recently one of the cloud server MySQL instance was restarted for maintenance during which my NodeJS application crashed on getting an API request. Error was ECONNREFUSED.

How do I handle these errors? The major problem is the crashing of app with a fatal error which is not acceptable. The better way is to handle the error and API responds with a 500 error.

One way I think of is to not use the query method directly and create connection every time a database call is required. This is where I can also check for the ECONNREFUSED error as mentioned in the Readme. There is no problem as such with this method but I want to know if there are better ways/ best practices of doing this.

**Comment by dougwilson** [comment]
Hi @fit-aditya where is the error coming from that is crashing your app? Normally all errors are in the `err` argument you get to your `pool.query` callback. Are you throwing those at all? Perhaps can you share all the following and we can debug the issue? Version of this module, version of Node.js, complete code and complete instructions for how to replicate the issue.

**Comment by fit-aditya** [comment]
You are right. That did not crash the app. It's something else related to foreverJS. Thanks anyway.
