### ISSUE TITLE
Cannot Create Table 

### ISSUE THREAD

**Issue by jamalabo1** [mysqljs/mysql#1861]
## }); 

Error: 

{"code":"ER_PARSE_ERROR","errno":1064,"sqlMessage":"You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1","sqlState":"42000","index":0,"sql":"CREATE TABLE customers (name VARCHAR(255), address VARCHAR(255) "}

**Comment by dougwilson** [comment]
You have a zero width space character between the opening quote and the C.
