### ISSUE TITLE
Is it possible to set mysql @variables or use multiple statements?

### ISSUE THREAD

**Issue by Redsandro** [mysqljs/mysql#1863]
We use queries with mysql variables or options for reasons. Is it possible to re-use these queries, or can this module not handle multiple commands delimited by a `;` sign?

E.g. variables:

```
SELECT @ids := ids
FROM bar
WHERE baz = 198;

SELECT *
FROM foo
WHERE ids IN (@ids);
```

Or options:

```
SET foo=no;
SELECT bar;
SET foo=yes;
```

**Comment by dougwilson** [comment]
Hi @Redsandro in order to use multiple statements in a single query, you need to set `multipleStatements: true` in your connection / pool options (https://github.com/mysqljs/mysql#connection-options).

**Comment by Redsandro** [comment]
Ah, there's an option for that! Thank you @dougwilson. :+1:
