### ISSUE TITLE
Recieving ER_NO_DEFAULT_FOR_FIELD even though insertion still occurs

### ISSUE THREAD

**Issue by dkirshenbaum** [mysqljs/mysql#1865]
I have a query that goes as follows:
```js
					sql = "INSERT INTO groups SET ?";
					
					var inserts = {group_player_one_id: playerArray[0], group_player_two_id: playerArray[1], group_created_date: formatted};
					sql = mysql.format(sql, inserts);
					console.log(sql);
					con.query(sql, function(err, result){
						if (err) throw err;
						console.log(result);
					});
```

When I print the sql query it prints:
```sql
INSERT INTO groups SET `group_player_one_id` = 1, `group_player_two_id` = 4, `group_created_date` = '2017-11-08'
```

And the insertion into table groups still occurs yet i get the error
```
Error: ER_NO_DEFAULT_FOR_FIELD: Field 'group_player_two_id' doesn't have a default value
```

Any help would be appreciated on the subject.

**Comment by dougwilson** [comment]
Can you provide the DDL for the table?

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by akshaykumar12527** [comment]
I am getting the same error suddenly without changing MySQL version and driver version and it was working before without entering default values for the fields which have 'not allow null' in the definition.
