### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by michalhlavka** [mysqljs/mysql#1867]
Hello,

I am sending queries via mysqljs in anonymous function, which is called every time my app receive a socket. I was capturing heapdump every hour, so I have 5 dumps, because app leaks after 5 hours of running. 

I found out that garbage collector can not clean allocated string and arrays connected with mysqljs. 

https://www.dropbox.com/s/efjbp62h57y98wk/Screenshot%202017-11-11%2023.32.39.png?dl=0
https://www.dropbox.com/s/xgqgnsuedsh3n33/Screenshot%202017-11-11%2023.31.56.png?dl=0

I am calling for example DELETE query on the screenshots in callback of another query. 
Can you confirm that please? Or if is possible to tell me solution of this? 

Node version v8.9.0
Package version "github:mysqljs/mysql"

**Comment by dougwilson** [comment]
Hi @michalhlavka the screenshots I'm not sure I really understand. In order to even diagnose the memory leak myself, ideally I would need to be able to reproduce the issue. Can you share the following so we can take a look?

1. Version of this module
2. Complete source code that reproduces the memory leak
3. Instruction on how to setup and run the code to see the leak

Thanks!

**Comment by michalhlavka** [comment]
Hi @dougwilson, I understand you, perhaps I can not send you my application, there are too many valued logic. Version of the module is `2.15.0`. But in final it is very simple application. Imagine table with 7 float columns, which is filled about 50 rows per seconds.

**Comment by michalhlavka** [comment]
@dougwilson I will try postgres, but meanwhile I will prepare for you application with same logic, where will be memory leak.

**Comment by michalhlavka** [comment]
@dougwilson Ok after changing database to postgres, also removing mysqljs/mysql library, no memory leak appeared. You should consider to debug it. Its simple, call every second anonymous function which fill the table with 50 rows.

**Comment by dougwilson** [comment]
If you can ptovide the requested information I'll reopen the issue to check it out. If you would like me to try to poke at it in the dark, consider making a financial contribution to the project.
