### ISSUE TITLE
Docs reference deprecated crypto.createCredentials

### ISSUE THREAD

**Issue by sabinthomas** [mysqljs/mysql#1874]
Instructions on how to setup a mySQL SSL connection are unclear as the [docs](https://github.com/mysqljs/mysql#ssl-options) make reference to `crypto.createCredentials` in node.js. This has been deprecated in favor of [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options)

Reference:
- #1203 
- #1154

**Comment by dougwilson** [comment]
Cool, I'm updating the docs right now 👍 thanks for the report!

**Comment by sabinthomas** [comment]
Cool. I was going to push a pull request too.

**Comment by dougwilson** [comment]
Thanks @sabinthomas ! I'm confused about the `Reference:` section in your post above. Can you explain?

**Comment by sabinthomas** [comment]
Sure, I mentioned those issues in the Reference section only because they came up when I'd searched for issues with the terms `crypto.createCredentials` and looked to be relevant. I didn't want to create a new issue if one existed already, but it seems that those issues = #1203  and #1154 don't address the docs section specifically.

**Comment by dougwilson** [comment]
I'm not really sure how they are relevant here, because they were both not related to this module. Can you elaborate?

**Comment by sabinthomas** [comment]
On second thought, I agree with you that #1203 and #1154 are not relevant. We can ignore them. Let me know if you'd like me to edit my issue.
