### ISSUE TITLE
resign from getConnection request

### ISSUE THREAD

**Issue by manuxio** [mysqljs/mysql#1877]
Hello,
I believe there should be a way to cancel/drop a pool.getConnection() request.

There are cases where the requester loses interest in the connection (for example, in web, while waiting for the db, the client disconnects...) and this makes it hard if not almost impossible to release the connection when it is acquired in the future.

Say this happens:

t0: HTTP GET
t1: getConnection()
t2: remote client disconnects
t3: request ends, but cannot release() the connection
t4: the connection is returned from mysql 

In this case, no function will take care of releasing() the given connection. This will, in the next future of the app, cause a denial of service.

A way to handle this scenario is to change code:
t4: the connection is returned from mysql, check if it is still useful, if not, immediately release()

But I think a better way would be to:

var pendingRequest = pool.getConnection(cb);
[and later]
pendingRequest.resign()

If you agree to this, there should be some discussion if a resign should trigger cb() or not...

***************
Btw, I am 99% certain that there are a lot of express applications that suffer from such a possible DoS...
as soon as a Request is waiting for the next free dbConnection, if socket is closed, no one will release() the connection and the pool will become useless pretty soon.
Do you think I am wrong?

**Comment by dougwilson** [comment]
Discussions of security issues should not be done in a oublic forum.

**Comment by manuxio** [comment]
Where can this be done?

**Comment by dougwilson** [comment]
Apologies, a commit I made a month ago was never pushed. I just pushed it: https://github.com/mysqljs/mysql#security-issues It's just writing out the basic procedures for any GitHub repository to help clarify.
