### ISSUE TITLE
random ETIMEDOUT error

### ISSUE THREAD

**Issue by gabrythe23** [mysqljs/mysql#1878]
i randomly receive a timeout error with this function, works great if I call function for 100/200 times, but after seems crazy.

```
getEquipment: function (code) {
      var connection = mysql.createConnection(connectionSettings);
      var returned = String();
      var injcCode = connection.escape(code);
      var query = `SELECT model FROM equipment WHERE iataCode=${injcCode};`
      var queryInsert = `INSERT INTO equipment SET iataCode=${injcCode}`;

      connection.query(query, (err, rows)=>{
          if (err) throw err;
          if(rows[0]){
            connection.end()
            returned = rows[0].model;
          }else{
            connection.query(queryInsert,(err)=>{
              if(err)  throw err;
              connection.end()
            });
            returned = code;
          }
      });
      deasync.loopWhile((function () {
          return !returned;
      }));
      return returned;
  }
};
```

I've made a test with simple query in a for cycle. And I've seen that after 200 requests +/- I receive the error ETIMEDOUT.

BUT, only after 200 requests. so strange I don't know if is a library error or db error.

**Comment by kai-koch** [comment]
I guess you are using https://github.com/abbr/deasync.

This could be a side effect of implicit type casting an object via "!returned".
Try using a real Boolean Variable instead of returned.
