### ISSUE TITLE
How can i get the count(id) from RowDataPacket?

### ISSUE THREAD

**Issue by huaibaomengxiang** [mysqljs/mysql#1881]
The result is a RowDataPacket object when i run select count(id) from form;
i have a key that can not use-- count(id).

**Comment by dougwilson** [comment]
This module simply returns the exact same rows and column names the MySQL server is returning. By default MySQL will name columns that are function results the text of the function call. You cab rename the column in your query using the AS keyword like you would rename any column. The MySQL server would then return that as the xolumn name back to this driver.

**Comment by huaibaomengxiang** [comment]
Thanks
