### ISSUE TITLE
TypeScript definitions missing Connection.release() method

### ISSUE THREAD

**Issue by terbooter** [mysqljs/mysql#1882]
Docs says that
```
When you are done with a connection, just call connection.release() and the connection will return to the pool, ready to be used again by someone else.
```

But `interface Connection` in `index.d.ts` file miss this method signature

**Comment by dougwilson** [comment]
I'm not sure what an index.d.ts file is. I dont believe there is such a file in this repo, right? Maybe you can point me to the file you are referring to?

**Comment by terbooter** [comment]
@dougwilson, sorry, I mistakenly posted to this repo.
This issue for [`promise-mysql` module](https://github.com/lukeb-uk/node-promise-mysql/issues/73)
