### ISSUE TITLE
Passing extra variables to the connection.query function

### ISSUE THREAD

**Issue by astutesoftware** [mysqljs/mysql#1883]
I have a requirement where i want to pass a unique variable to the connection.query function and be able to retrieve it when it has made the recordset.

Use case.
1. I want to pass the unixtimestamp and get it back to compute execution time.

**Comment by sidorares** [comment]
@astutesoftware you can wrap it with another function and pass your variable to it

```js
const myQuery = (sql, cb) => {
  const start = +new Date();
  connection.query(sql, (err, rows, fields) => cb(err, rows, fields, new Date() - start))
}
```
