### ISSUE TITLE
Double conversion when selecting a timestamp record even if datetime is a UTC date.

### ISSUE THREAD

**Issue by ThomasPCG** [mysqljs/mysql#1886]
It seems like the library is treating all time selected from the database as the local timezone and converting it to UTC time even when the time is a UTC value. From the screenshot below, you can see that the SQL server is already at UTC timezone and when I select the record from MySQL workbench, it's showing the right UTC time. But when I did a console log of the selection in NodeJS, it shows the UTC time being automatically converted from local timezone (GMT+8) even when I didn't specify any special options for the SQL select statement. Any ideas why?

![screenshots](https://user-images.githubusercontent.com/25073827/33316604-78454d0e-d46f-11e7-885c-6500f8e5ac16.jpg)

**Comment by ThomasPCG** [comment]
Found out I need to set the timezone option to 'Z' when creating the connection to retrieve all dates as UTC object. My apologies.

**Comment by dougwilson** [comment]
It's no problem, no worries. If you think there is an action we can take, for example maybe make the README clearer regarding this, let us know, perhaps even make a PR :) !
