### ISSUE TITLE
Error: ER_ACCESS_DENIED_ERROR: Access denied for user

### ISSUE THREAD

**Issue by ali-bagheri** [mysqljs/mysql#1893]
Hi.
I get this error

message: 'Access denied for user \'sanjeshc_venus_user\'@\'localhost\' (using password: YES)' }

###	ERROR IN grant. Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'sanjeshc_venus_user'@'localhost' (using password: YES)

what solution?

**Comment by flyingrx** [comment]
I have the same problem.
my grants is right,but it doesn't make sense;

mysql> show grants  for 'QA'@'%';
+---------------------------------------------------------------------------------------------------+
| Grants for QA@%                                                                                   |
+---------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'QA'@'%' IDENTIFIED BY PASSWORD '*49DA781724763770869D8619EC543F0CD961518B' |
| GRANT ALL PRIVILEGES ON `miniProgram`.* TO 'QA'@'%'                                               |
+---------------------------------------------------------------------------------------------------+

my node version is 9,3,0 
mysql is 5.6.28
node-mysql version is 2.15.0

**Comment by dougwilson** [comment]
Hi @flyingrx can you paste the exact error you're getting?

**Comment by kai-koch** [comment]
After inserting the new User the privileges where flushed  or the server was restarted?

**Comment by dougwilson** [comment]
I'm going to close this due to no response.
