### ISSUE TITLE
Will the pool remove the connection with fatal-error and create again with new request ?

### ISSUE THREAD

**Issue by aflext** [mysqljs/mysql#1894]
My understanding:
I set the timeout as 40s so the pool will remove the connection when the server do not respond after 40s which will has an fatal error.

So, if the `connection count` of the `database` reach its `max limits` and there are also `continuous slow query` requests, the pool will try to remove the connection with fata-error and create new connection which is a `dead loop` because the timeout connection may not be release by the `mysql server`. You just remove the connection from the pool queue whitout caring the `really release` from the mysql server

Did i understand right?

`Question1`: If the connection limit is default which is 10, will the pool have more than 10 connections `at one moment` in any circumstance and why ?

`Question2`: Why do you make the timeout error as an fatal error ?  Dose the word fatal relate to nodejs core or something else ?

**Comment by dougwilson** [comment]
Hi! I'm reading through it and sorry if I misunderstand anything from your questions.

The connection pool will never have more connections than the limit, correct.

The fatal flag is a boolean that indicates if the error was fatal to the connection object. Once a fatal error occurs the connection is unusable. The reason a timeout is fatal is because the TCP connection will be terminated, making the connection object unusable.

**Comment by aflext** [comment]
@dougwilson Thanks for replying. If the connection count nearly hits the max count of a database server, i wonder what should i do to protect the database from refusing serving. 

Becasue if the DB server is using all the connections, when the request continues, the DB server will refuse serving and then the `mysql` library will remove `timeout` connection from the pool and will make space for new request and then the DB server can not release the conenction immiedately and then the DB server will always use all of its connections, at last ,all service related to the DB server will fail.

**Comment by dougwilson** [comment]
I'm really sorry I'm having trouble following what you're saying.

**Comment by aflext** [comment]
@dougwilson I mean, when the db server is using full connections and the new request of the db server got errors like `inactivity timeout`, will the pool continue trying to create new connections ?
