### ISSUE TITLE
message : javax.net.ssl.SSLException: Unsupported record version Unknown-0.0 ,code ":“ HANDSHAKE_SS

### ISSUE THREAD

**Issue by kaushalshriyan** [mysqljs/mysql#1897]
I am making use of https://www.npmjs.com/package/mysql in my setup using "Amazon RDS" profile for connecting to an Amazon RDS server from node.js code as per SSL options described in https://www.npmjs.com/package/mysql.  I am currently facing this issue {“message”:“javax.net.ssl.SSLException: Unsupported record version Unknown-0.0",“code”:“HANDSHAKE_SSL_ERROR”,“fatal”:true}  

Version details are as below :-

mysql version :- 2.15.0
nodeVersion :- 6.11.4
npmVersion :- 5.3.0

**Comment by dougwilson** [comment]
That is really strange, especially since you are getting a Java error. I just tried with Amazon RDS without issue. Is there any more information you can provide to help me replicate your issue?

**Comment by dougwilson** [comment]
Closing due to no response.
