### ISSUE TITLE
stored emojis come out with 2 backslashes 

### ISSUE THREAD

**Issue by dreamcatcha** [mysqljs/mysql#1901]
I'm not sure it's an issue, but I can't seem to find why it happens

I store a string with emojis like "\uD83D\uDCB9" in mysql but when I retrieve it
it comes like "\\uD83D\\uDCB9"

How to get it returned as it is in the database?

**Comment by sidorares** [comment]
standard advice is to use UTF8MB4_UNICODE_CI encoding

**Comment by dougwilson** [comment]
Both outputs look the same to me. For your description I've never seen that unless it's an artifact of how you're displaying them somewhere? Perhaps can you provide the following?

1. Version of Node.js
2. Version of this module
3. Complete code that does an INSERT with data and then a SELECT of that data that demonstrates that extra backslashes are being added.

That would help a lot to narrow down the issue. Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
