### ISSUE TITLE
Parameterized Query use list as value

### ISSUE THREAD

**Issue by bes1002t** [mysqljs/mysql#1903]
Hi,

I want to pass a list of values as parameter to my query. 

Code sample how it is:
`SELECT * FROM foo WHERE foo.name IN (mike, chris, harald);`

Code sample expected:
`SELECT * FROM foo WHERE foo.name IN ?;`

the content of the array is generated by user input so I want to use the questionmark to pass the array.
Passing the array itself does not work. Any suggestions how I could solve that?

**Comment by dougwilson** [comment]
For that format, just wrap the question mark in parentheses:

    SELECT * FROM foo WHERE foo.name IN (?);

**Comment by bes1002t** [comment]
ah nice that's it, thank you!
just have two pass the array directly instead of using .join(',').
