### ISSUE TITLE
why doesn't the pool have an option for limiting all the connections have been created?

### ISSUE THREAD

**Issue by aflext** [mysqljs/mysql#1905]
## scenario
- using 10 concurrent connection limit.
- all the queries are slow queries whch will lead an `inactivity timeout` fatal error.
- QPS is 100, eg the server query the db 100 timers per second.
- the request is lasting 1h.

## result
The db server has nearly 2000 connetion at one moment. If i keep testing longer, the DB server will using all of its available connection!

>So i wonder why doesn't the pool have an option for limiting all the connections have been created? How to protect the db server when in the worst situation like keep requsting the db with slow queries ?

##  probably code like below:

    const mysql = require(`mysql`);
    // cached pool
    const cachedPool = {};
    // timeout
    const defaultQueryTimeout = 40000;
    // config
    const connectionLimit = {
        'test.dbServer.com:8008': {
            limit: 250,
            current: 0
        }
    };

    const decreaseLimit = (limitKey, queryTimeout = 0) => {
        setTimeout(() => {
            const currentLimit = connectionLimit[limitKey];
            currentLimit.current = Math.max(
                (currentLimit.current || 0) - 1,
                0
            );
        }, queryTimeout);
    };
    const increaseLimit = (limitKey) => {
        const currentLimit = connectionLimit[limitKey];
        currentLimit.current = (currentLimit.current || 0) + 1;
    };

    // get a pool
    const getPool = (options) => {
        return new Promise((resolve, reject) => {
            if (cachedPool[options.host]) {
                resolve(cachedPool[options.host]);
                return 
            }
            const dbpoolOptions = Object.assign({
                    host: `test.dbServer.com`,
                    user: `xx`,
                    password: `xx`,
                    database: `xx`,
                    port: `8008`,
                    charset: `utf8`
                }, options ,{
                connectionLimit: 10
            });
            const pool = mysql.createPool(dbpoolOptions);
            const limitKey = `${dbpoolOptions.host}:${dbpoolOptions.port}`;
            // listen connection event
            pool.on(`connection`, () => {
                // increase counter
                increaseLimit(limitKey);
            });

            cachedPool[options.host] = pool;
            resolve(pool);
        });
    }

    // do q query like 'SELECT'
    const query = async (options) => {
        try {
            // get pool
            const pool = await getPool();
            const connectionConfig = pool.config.connectionConfig;
            const limitKey = `${connectionConfig.host}:${connectionConfig.port}`;
            const currentLimit = connectionLimit[limitKey];
            if (currentLimit.current > currentLimit.limit) {
                return Promise.reject(`Current pool[${limitKey}] has reached limit[${currentLimit.limit}]`);
            }

            return new Promise((resolve, reject) => {
                // get connection
                pool.getConnection((err, connection) => {
                    if (err) {
                        reject(err);
                        return;
                    }
                    connection.on(`end`, (err) => {
                        decreaseLimit(limitKey, defaultQueryTimeout);
                        reject(`db connection got end`);
                    });

                    connection.on(`error`, (err) => {
                        decreaseLimit(limitKey, defaultQueryTimeout);
                        reject(`db connection got error`);
                    });

                    // do query
                    connection.query(Object.assign({}, options, {
                        timeout: defaultQueryTimeout
                    }), (queryErr, results, fields) => {
                        if (queryErr) {
                            reject(queryErr);
                            return;
                        }
                        // resolce reslts
                        resolve(results);
                    });
                });
            });
        } catch (err) {
            return Promise.reject(err);
        }
    }
    module.exports = query;

**Comment by dougwilson** [comment]
Hi! It sounds like you are reporting a security issue. Please follow the procedure for reporting theses types of issues: https://github.com/mysqljs/mysql/blob/master/Readme.md#security-issues
