### ISSUE TITLE
 Error 1215: Cannot add foreign key constraint SQL Code:

### ISSUE THREAD

**Issue by Juninhohb** [mysqljs/mysql#1907]
I really don't know what im doing wrong can someone help me please >.<

When i forward engineer my EER i get this error.
My code is,

Executing SQL script in server
ERROR: Error 1215: Cannot add foreign key constraint
SQL Code:
        -- -----------------------------------------------------
        -- Table `mydb`.`Ticket`
        -- -----------------------------------------------------
        CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
          ` Filmnaam` VARCHAR(20) NOT NULL,
          ` Zaalnummer` INT NOT NULL,
          ` Zitplaats` INT NOT NULL,
          `Totaal ticketprijs` DOUBLE NOT NULL,
          ` Start film` DATETIME NOT NULL,
          ` Eind film` DATETIME NOT NULL,
          `Ticket id` INT NOT NULL,
          ` Buffetbon nr` INT NULL,
          PRIMARY KEY (`Ticket id`),
          INDEX `Verzinzelf1_idx` (` Filmnaam` ASC),
          INDEX `Verzinzelf3_idx` (` Zaalnummer` ASC, ` Zitplaats` ASC),
          INDEX `Verzinzelf2_idx` (` Start film` ASC, ` Eind film` ASC),
          INDEX `Verzinzelf4_idx` (` Buffetbon nr` ASC),
          UNIQUE INDEX ` Buffetbon nr_UNIQUE` (` Buffetbon nr` ASC),
          CONSTRAINT `Verzinzelf1`
            FOREIGN KEY (` Filmnaam`)
            REFERENCES `mydb`.`Film` (`Filmnaam`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT `Verzinzelf3`
            FOREIGN KEY (` Zaalnummer` , ` Zitplaats`)
            REFERENCES `mydb`.`Zitplek` (`Zaalnummer` , `Zitplaats`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT `Verzinzelf2`
            FOREIGN KEY (` Start film` , ` Eind film`)
            REFERENCES `mydb`.`Tijdperiode` (`Start film` , `Eind film`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
          CONSTRAINT `Verzinzelf4`
            FOREIGN KEY (` Buffetbon nr`)
            REFERENCES `mydb`.`Buffet bon` (`Buffetbon nr`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION)
        ENGINE = InnoDB

SQL script execution finished: statements: 9 succeeded, 1 failed

Fetching back view definitions in final form.
Nothing to fetch

**Comment by dougwilson** [comment]
Hi! I'm not sure if you are posting this in the right place. This is a Mysql driver for Node.js and issues for the driver. It sounds like this is a general MySQL question and unfortunately I don't know the answer to your question to help really quick :(

**Comment by Juninhohb** [comment]
Do you know where i can ask for help?

**Comment by dougwilson** [comment]
Not off hand
