### ISSUE TITLE
instanceof/constructor check fails if a class has different versions in node_modules

### ISSUE THREAD

**Issue by yinrong** [mysqljs/mysql#1909]
suppose my runtime directory structure is
```
my_pkg_1/
my_pkg_1/node_modules
my_pkg_1/node_modules/my_pkg_2@1.0.0
my_pkg_1/node_modules/my_pkg_3/
my_pkg_1/node_modules/my_pkg_3/node_modules/
my_pkg_1/node_modules/my_pkg_3/node_modules/my_pkg_2@1.1.0
```
a check like
```
my_instance.constuctor === MyType
```
or
```
my_instance instanceof MyType
```
may fail since MyType may point to eigher my_pkg_2@1.0.0 or my_pkg_2@1.1.0

I consider this may be a problem since I have experienced once during deploying process that it take __quite a long time__ to find out the bug.

**Comment by dougwilson** [comment]
Good find! What is the solution?

**Comment by yinrong** [comment]
sorry I should open this in nodejs

**Comment by yinrong** [comment]
I have to remove all duplicate packages every time during deploying process @dougwilson

**Comment by yinrong** [comment]
moved to https://github.com/nodejs/node/issues/17943
