### ISSUE TITLE
HAProxy with this connector

### ISSUE THREAD

**Issue by kaizen1** [mysqljs/mysql#1910]
I'm having some trouble configuring HAProxy on the node.js server + this mysql connector. I'm trying to load balance to a Galera Cluster. Below is the HAProxy config sitting on the node.js server. Would connector parameters be correct as follows: 
In app.js code:
Host: 'hostname-of-the-local-machine'
Port: '3307' 
localAddress: '127.0.0.1' [documentation calls this "source" IP but I'm not sure what source means in this context]

HAProxy configuration:
listen mysql
    bind 127.0.0.1:3307
    mode tcp
    option mysql-check user haproxy_check
    balance roundrobin
    server mysql-1 10.0.0.1:3306 check
    server mysql-2 10.0.0.2:3306 check

**Comment by dougwilson** [comment]
Hi @kaizen1 that looks correct. The `localAddress` is only for when you have multiple IP addresses on the same machine and multiple addresses can reach the same destination. You don't need to specify it, especially for localhost.

I hope that helps!
