### ISSUE TITLE
Advisory Lock returns `null`

### ISSUE THREAD

**Issue by scull7** [mysqljs/mysql#1912]
When attempting to obtain an advisory lock:
https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock

I'm receiving a `null` response instead of the `0` or `1` as specified by the MySQL documentation and as seen when I issue the query through the MySQL client.

<img width="585" alt="screenshot 2018-01-05 16 50 37" src="https://user-images.githubusercontent.com/234352/34634400-9989c3be-f238-11e7-9330-a6128f35a775.png">

```javascript
import test from 'ava'

import mysql from 'mysql1'

const pool = mysql.createPool({
  connectionLimit: 10,
  host: 'localhost',
  user: 'root',
  port: 3306,
  database: 'test',
  password: '',
})

const foo = () => new Promise((resolve) => {
  resolve(1)
})

const multiQuery = () => new Promise((resolve, reject) => {
  const sql = `
    SELECT GET_LOCK('test2', -1) AS test3;
  `
  pool.query(sql, (err, res) => (err == null ? resolve(res) : reject(err)))
})

test(async (t) => {
  const response = await multiQuery()
  console.log(response)
  t.is(await foo(), 1)
})
```

Response:
<img width="261" alt="screenshot 2018-01-05 16 52 52" src="https://user-images.githubusercontent.com/234352/34634462-219887f4-f239-11e7-8dce-b6d48cfc6c46.png">

Is this expected?

**Comment by dougwilson** [comment]
Are you sure you're using this module? This module has no promises and isn't even named "mysql1" like in your code.

**Comment by dougwilson** [comment]
I looked at the documentation link you provided and NULL is a valid value. Here is a quote from the docs thag explains what NULL means:

> Returns 1 if the lock was obtained successfully, 0 if the attempt timed out (for example, because another client has previously locked the name), or NULL if an error occurred (such as running out of memory or the thread was killed with mysqladmin kill).

**Comment by dougwilson** [comment]
So I tried to run the code you gave but cannot figure out how to get it to run with the `import` as it seems Node.js doesn't understand that syntax? I just ran the single query on the command line using Node.js v8.9.4 and v2.15.0 of this module and I got a `1` back:
```
$ node -e 'c=require("mysql").createConnection({});c.query("SELECT GET_LOCK('"'"'test2'"'"',-1) AS test3;",function(err,result){console.dir(result);c.end()})'
[ { test3: 1 } ]
```

Does running that command in bash result in a `1` for you? I would like to try running the code you provided if you can provide instructions for how to do that, and also what version of Node.js you are using and version of this module you're using. It's possible also the difference may be from the `Promise` wrapping, which I'm not really familiar with and not sure what would be happening there.

**Comment by scull7** [comment]
I'm using `babel-register` to translate the code before it's run.

**Comment by dougwilson** [comment]
Thanks for that information @scull7 ! I'm not really familiar with that, unfortunately. Did you run the snippet I provided? What was your result?

If you want me to run your code you provided, can you please provide what version of Node.js you are using and version of this module you're using? Also provide exactly how I'm supposed to run it, whatever the instructions are. Right now I just copy and pasted it into a file `test.js` and ran `node test.js`. Please expand on this so I can get your code up and running and debug through it 👍

**Comment by scull7** [comment]
Simplified version:
```javascript
const mysql = require('mysql')

const pool = mysql.createPool({
  connectionLimit: 10,
  host: '10.101.0.1',
  user: 'root',
  port: 20213,
  database: 'ip_financial',
  password: '',
})

const multiQuery = () => new Promise((resolve, reject) => {
  const sql = `
    SELECT GET_LOCK('test2', -1) AS test3;
  `
  pool.query(sql, (err, response, fields) =>
    (err == null ? resolve({ response, fields }) : reject(err)))
})

multiQuery()
  .then((response) => console.log(response))
  .then(() => process.exit())
```
Output:
<img width="371" alt="screenshot 2018-01-05 18 04 12" src="https://user-images.githubusercontent.com/234352/34635336-db192cca-f242-11e7-8744-8b23774ba930.png">

**Comment by dougwilson** [comment]
Thanks! I saved that as `t.js` and changed the credentials to my MySQL server. Here is the output:
```
/node t.js
{ response: [ RowDataPacket { test3: 1 } ],
  fields:
   [ FieldPacket {
       catalog: 'def',
       db: '',
       table: '',
       orgTable: '',
       name: 'test3',
       orgName: '',
       charsetNr: 63,
       length: 1,
       type: 8,
       flags: 128,
       decimals: 0,
       default: undefined,
       zeroFill: false,
       protocol41: true } ] }
```

I'm getting the `1` value, just like I was getting with the code I also provided earlier. So perhaps there is something different between our environments. Can you provide as much information as possible to get our environments set up the same? For example, think of if you had to reproduce this on a new machine with a new MySQL install. What are the parameters would need to setup in order to replicate your environment?

**Comment by sidorares** [comment]
@scull7 in your example server sends back `0131' bytes as only row which is "1" string. Type is LONGLONG so it's casted to `1` js number. Not sure why you expect null value

**Comment by scull7** [comment]
Thank you @dougwilson and @sidorares, I was expecting the `"1"` string and receiving the `null` value instead.  However, as described below the issue is an API difference between MariaDB and MySql.  I apologize for the confusion.

Also commenting here for reference:

It is an issue with MariaDB vs MySql.  MariaDB doesn't seem to support the negative timeout.  

From the [MySql Docs](https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_get-lock)
>A *negative* timeout value means infinite timeout. The lock is exclusive. While held by one session, other sessions cannot obtain a lock of the same name. 

The [MariaDB Docs](https://mariadb.com/kb/en/library/get_lock/) omit that line:
>Tries to obtain a lock with a name given by the string str, using a timeout of timeout seconds. Returns 1 if the lock was obtained successfully, 0 if the attempt timed out (for example, because another client 
has previously locked the name), or NULL if an error occurred (such as running out of memory or the thread was killed with mysqladmin kill).

I apologize, I did not notice the difference.
  
Results when using a positive integer for the timeout:
<img width="272" alt="screenshot 2018-01-05 18 35 42" src="https://user-images.githubusercontent.com/234352/34635640-580def14-f247-11e7-878f-6690abf05362.png">

**Comment by dougwilson** [comment]
While I've been trying to dig into this @scull7 I notice that the query you have in your screenshot is not the same as in your code. Since, as the documentation I pasted above, `NULL` is a valid return value for if there is an error and both parameters are different between the two statements, maybe there is a locking error occurring in your environment for the name you are passing in or something? I tried both locally and still got `1` for both, but just a though. Maybe show ** edit I stopped typing because @scull7 just responded **

**Comment by dougwilson** [comment]
Ah, that makes sense @scull7 . Since the documentation says `NULL` is a valid return value on an error, I suppose MariaDB is treating the negative timeout value as an error condition, so returning the signal for an error 👍 I'll close this issue at since it doesn't seem to be an issue with the module.

Let me know if there is anything else I need to take a look into 👍 I spent about an hour or so digging through this tonight, so probably won't have time to take a look into anything further until tomorrow or so.

**Comment by scull7** [comment]
@dougwilson Thank you for your help and all the time you spent looking into this.  Hopefully this will help someone else in the future.
