### ISSUE TITLE
timezone and dateStrings

### ISSUE THREAD

**Issue by diegofontana** [mysqljs/mysql#1914]
When using dateStrings=true, timestamp fields does not apply the specified timezone...

A) connection example: {... timezone: '-03:00', dateStrings: true ...}
query result: {... tra_dat: '2018-01-08 08:58:38' ...}

B) connection example: {... timezone: '-00:00', dateStrings: true ...}
query result: {... tra_dat: '2018-01-08 08:58:38' ...}

....
When using dateStrings=false, it works fine, but in my project i need to use dateStrings=true

**Comment by dougwilson** [comment]
Yes, this is because dateStrings means you get the exact string your MySQL server returned. To change the timezone in that value, you need to chabge that on your MySQL server.

I hope that helps!
