### ISSUE TITLE
Custom throw Error in pool query callback

### ISSUE THREAD

**Issue by DrobyshevAlex** [mysqljs/mysql#1915]
If i throw custom exception in query callback then server is crashed.

```
      this.query(sql, params, (err, rows) => {
        if (err) {
          this.app.log.error(err);
          throw new HandlerError({ common: 'Server error' });
        } else {
         ...
        throw new HandlerError({ password: 'Invalid email or password' });
      });
```
It's possible?

I found i can use conn.on('error',...) but i use PoolConnection and the code do not work for me.
I got server crash with **'throw err; // Rethrow non-MySQL errors'**

I wrote wrapper for callback

```
  query(sql, params, callback) {
    this.app.db.query(sql, params, (err, res) => {
      try {
        if (typeof(callback) == 'function') {
          callback(err, res);
        }
      } catch (e) {
        if (e instanceof HandlerError) {
          this.emit(e.event, e.getData())
        } else {
          this.app.log.error(e);
        }
      }
    });
  }
```

it's work fine, but maybe exists there's a simpler way?

**Comment by dougwilson** [comment]
In Node.js this happens anywhere you throw an error within a callback. You would need to either not throw your error or wrap the contents in a try block. This is unfortunately just how Node.js works :(

**Comment by DrobyshevAlex** [comment]
Maybe possible do like it:

```
db = mysql.createPool(...)
db.addErrorListener( (err) => {
  // 
})
db.query(sql, params, (err, res) => {
  ...
  throw new Error('custom error');
  ...
})
```

and in mysql lib wrap callback in try catch and if exists least one listener hook error and call listener, and if not exists listener then throw error.

Sorry for my bad english, i hope i clearly said want to

**Comment by dougwilson** [comment]
Yep, definitely understand your suggestion. But that will add complexity to the module and just cause more confusion in the end since that will make this module behave differently from all other Node.js module, and even Node.js core modules.
