### ISSUE TITLE
Support using single value for multiple placeholders

### ISSUE THREAD

**Issue by njbmartin** [mysqljs/mysql#1916]
As an example, I have a query that has multiple statements, which are essentially using the same value in the WHERE clause. I've simplified it here just to keep it simple:

```js
db.query(`SELECT *  FROM TABLE_A WHERE TABLE_A.id=?;
  SELECT * FROM TABLE_B WHERE ref_id=?;
  SELECT * FROM TABLE_C WHERE villa_id=?`, [id, id, id], (err, results) => {
      if (err) return reject(err);
      console.log(results);
});
```
To me it would makes sense that if I was to replace the array with a single value, then that value should be used for all placeholders.

```js
db.query(`SELECT *  FROM TABLE_A WHERE TABLE_A.id=?;
  SELECT * FROM TABLE_B WHERE ref_id=?;
  SELECT * FROM TABLE_C WHERE villa_id=?`, id, (err, results) => {
      if (err) return reject(err);
      console.log(results);
});
```

Happy to submit this as a PR, if you're happy with the proposal?

**Comment by dougwilson** [comment]
If I'm understanding your proposal correctly, it would break existing code (thus being a major version change), right? The second argument can already be a single value.

**Comment by njbmartin** [comment]
I've just re-read the docs and i missed the part about single values, but that still only supports a single placeholder. I haven't dived into the underlying code, but my assumption is that it iterates over the placeholders if there's more than one and and pull the value from an expected array of values.

Not sure if that would break existing code as it would compliment it with an additional way to use placeholders.

### Single placeholder
`db.query('SELECT *  FROM TABLE_A WHERE TABLE_A.id=?', id, () => {});`

`db.query('SELECT *  FROM TABLE_A WHERE TABLE_A.id=?', [id], () => {});`

_Both are currently supported_

### multiple placeholders using the same value

_Array is currently enforced_

`db.query('SELECT *  FROM TABLE_A WHERE TABLE_A.id=?; SELECT * FROM TABLE_B WHERE TABLE_B.ref_id=?', [id, id], () => {});`

_proposed addition_

`db.query('SELECT *  FROM TABLE_A WHERE TABLE_A.id=?; SELECT * FROM TABLE_B WHERE TABLE_B.ref_id=?', id, () => {});`

**Comment by dougwilson** [comment]
It would break the following:

    db.query('INSERT INTO TABLE1 (COL1, COL2) VALUES(?, "foo?")', id, () => {});

Since you are allowed to have more ? than replacement values and further ? are left as-is. I assume your proposal would cause the second ? to be the id value as well?

**Comment by njbmartin** [comment]
Would the second `?` be considered as a placeholder though? If so, it doesn't feel right...

Take this example:
`db.query('INSERT INTO TABLE1 (COL1, COL2) VALUES(?, "foo?"); INSERT INTO TABLE2 (COL1, COL2) VALUES(?, ?);', [id, id, token], () => {});`

"_foo_**?**" should not be considered for replacement as it's an intended string. So the intention would be to use regex to pull out actual placeholders following certain rules?

As I said, I've not dived into the code yet, so if the above example does in fact consider "foo**?**" to contain a placeholder and is used as such, it would indeed be a breaking change, but hopefully my proposal makes sense?

**Comment by dougwilson** [comment]
The current code does not parse SQL, so considers any literal `?` in the first argument to be a placeholder, regardless of placement.

**Comment by njbmartin** [comment]
Okay, took a dive into the code and found  `sqlstring` is a separate package, but currently has this regex:

`var placeholdersRegex = /\?\??/g;`

I think we've discovered an undesired side-effect of this regex, which will no doubt affect me shortly. As mentioned, if I was to do the last example I mentioned above, it's not how I'd expect it to treat "_foo_**?**" and would expect it to skip it.

Think we can kill two birds with one stone, however it does mean a breaking change if people are working around this. Would need to make the placeholder rules clear once a firmer regex is introduced.

**Comment by dougwilson** [comment]
Yea. The current behavior is intended right now, because otherwise you need to implement a full SQL parser / tokenizer to understand where the `?` is located. I'm not saying not to do this, but just what I remember why it wasn't done (this was before I was a part of the project). Not sure if there is a package you can leverage to parse SQL or you're planning to implement a parser for the full MySQL language set to do what you're looking for.

There are also server settings that change which characters are the quote characters and the escaping rules, so not sure if you can parse correctly without fetching settings from the MySQL server.

**Comment by dougwilson** [comment]
You can see it's intended based on the current documentation, apparently:

> Caution This also differs from prepared statements in that all ? are replaced, even those contained in comments and strings.

**Comment by njbmartin** [comment]
OK, thanks for bringing this to my attention. I realise that my queries would be using placeholders to insert the values (which could contain many question marks), and they would be unaffected by this.

**Comment by gitKearney** [comment]
I think a better option would be named parameters, like

```
SELECT * FROM users WHERE name = :name, and id = :id
{':name': 'bob', ':id': 12}

```

**Comment by dougwilson** [comment]
Yea, makes sense. You can use our named parameters module: https://github.com/mysqljs/named-placeholders
