### ISSUE TITLE
Can i launch hive sql requests using `mysql` package?

### ISSUE THREAD

**Issue by JoeyAspire** [mysqljs/mysql#1917]
Hi guys~ I need to connect to a hive server at port 10000, and send hive sql requests. Can this package help? If not , how can i get through this problem, thanks a lot!~

**Comment by dougwilson** [comment]
Hi @JoeyAspire I'm not familiar with what a hive server is, so not sure. This module implements the MySQL wire protocol, so should be able to connect to any server that speaks that protocol.
