### ISSUE TITLE
date empty string error

### ISSUE THREAD

**Issue by GoNode5** [mysqljs/mysql#1920]
When my front-end updates a date value (<input type=date>) where user uses x to delete date, the update post contains an '' as new value for date.

 UPDATE person SET    DOB = '' where id=470655
{ Error: ER_TRUNCATED_WRONG_VALUE: Incorrect date value: '' for column 'DOB' at row 1

I would expected an conversion to null?

**Comment by dougwilson** [comment]
Hi @GoNode5 you can see our type conversion rules here: https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-values

Because an empty string is a valid string value it cannot be converted to NULL otherwise no one could store an empty string.

I hope this helps!
