### ISSUE TITLE
Is it safe to keep mysqljs pool open until I need a connection?

### ISSUE THREAD

**Issue by vsdigitall** [mysqljs/mysql#1921]
I am developing an app where it is posible that mysql requests are not frequent. There could be a time of about 60 minutes between mysql calls.

However I would like to keep my pool opened because I may need to process thousands of requests at any moment.

Is it safe to have mysqljs pool just opened, or I have to ping mysql connection in order not to loose it?

```js
const mysql = require('mysql'),
      pool = mysql.createPool({
        multipleStatements : true,
        connectionLimit    : 5,
        connectTimeout     : 1000,
        acquireTimeout     : 1000,
        waitForConnections : true,
        queueLimit         : 0,
        host               : '192.168.247.128',
        port               : 3306,
        user               : 'root',
        password           : 'root',
        database           : 'db_name',
        supportBigNumbers  : true,
        bigNumberStrings   : true,
        timezone           : 'Z'
      });

server.on('request', function (rq) {
  ..
  pool.query("SELECT ...; UPDATE ...; ...", function (err,res) {});
  ..
});
```

Thansk for support!

**Comment by dougwilson** [comment]
Hi @vsdigitall yes, it is safe to keep the pool open in your app -- that is the purpose of a pool for databases, ultimately :) You don't need to ping the connections at all, as it's all managed under the covers to make sure when you need a connection later you will have one 👍
