### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by royigoldi** [mysqljs/mysql#1922]
Hi,

I want to ask, if i used connect to mySQL via the JDBC connection, table with 25 columns and 30000 rows,
is returing fast (1 seconds) but the toObjArray that parse the data into objects took 25 seconds.
I want to ask how this library execute the query and parse the data in one second!!!

(I need the JDBC for getting results also from Impala)

Thanks a lot,

**Comment by dougwilson** [comment]
I'm not really clear on what you're saying exactly, but the performance tries to be as fast as it can. If you have any contributions to improve performance, it would be much appreciated!

**Comment by royigoldi** [comment]
sorry I wasn't clear enough,

I need help if someone know how is the underline implementation for parsing the results less then second because is also use JDBC underline.. 
I doesn't find the "magic" in the sources...
I want to "copy" the fast parsing implementation when I work with the JDBC...

Thanks again

**Comment by dougwilson** [comment]
I'm still not sure what you mean. I know you keep referencing JDBC which I believe is something with Java. Are you sure you are looking at the right module? This is Node.js which is very different from Java.

**Comment by royigoldi** [comment]
yes I know it is node,  I also use the node jdbc driver from NPM:
https://www.npmjs.com/package/jdbc

this module also use it underline....

**Comment by dougwilson** [comment]
This module does not use jdbc in any way, not sure what you mean.
