### ISSUE TITLE
Can the same connection be used before answer is returned?

### ISSUE THREAD

**Issue by PRR24** [mysqljs/mysql#1924]
This is not a defect, but I could not find any clear info about safety requirements of reusing a connection. So my question is:
Can a connection be safely reused to execute multiple queries in sequence without making sure (on app level) that the prevous call has been finalized?

To explain what I mean let's look on a code (excluding err checks and connection relasing for code compression):
```
pool.getConnection(function(err, conn) {
    conn.query("INSERT INTO my_table (my_data) VALUES ('test'), function (error, results, fields) {
       console.log(results.affectedRows);
    });
   // Is the row below safe to execute?
    conn.query("INSERT INTO my_table (my_data) VALUES ('test'), function (error, results, fields) {
       console.log(results.affectedRows);
    });
});
```

**Comment by dougwilson** [comment]
Yep that is perfectly fine: https://github.com/mysqljs/mysql/blob/master/Readme.md#introduction
