### ISSUE TITLE
Query returns previus result after writerows binlog event

### ISSUE THREAD

**Issue by nzomedia** [mysqljs/mysql#1925]
Hi,
i'm currently using numtel-mysql, with MeteorJs. numtel-mysql uses mysql-live-select underneath in order to provide reactive select statements. And mysql-live-select uses a package called zongji to observe MySql binlog events and re-execute a given query when rows have changed.

In my application, when i do basic CRUD like adding a new item, most of the time the result set gets updated immediately on the client. I use a transaction to store the new item, and in my debugging console i can see that the transaction is opened, and commited right after the LMD query execution.
And after the commit, i can see that the "writerows" event is rised, the select statement i use to fetch data is re-executed but it returns the same previus rows. The new inserted item is not part of it.

If i do another LMD operation, the previus item i inserted before is then part of the new data returned by the select statement.
The problem doesn't happen everytime but is frequent enought to be problematic.
Can someone help me? i've seen an issue resembling the problem i'm having (Strange cache problem #849) but no solution was given, instead it was said to be a misuse of transactions.

**Comment by dougwilson** [comment]
Are you using this module at all here (you are referencing other module, but no reference of this module)? If so, I don't know off-hand. Can you try to provide all the following so we can dig into the issue?

1. Version of your MySQL server
2. Version of this module you are using 
3. Complete code we can run to reproduce the issue
4. Any necessary DDL to initialize an empty data ase with to get the code to run
5. Setup instructions
6. Steps to reproduce with the provided code and database

Thanks!

**Comment by nzomedia** [comment]
I'm sorry, in fact mysql-live-select package uses the npm mysql package in order to performe queries. here are more details:
MeteorJs 1.6 (the framework i'm using to develop my app)
numtel:mysql 1.0.6 (the package that provides reactive selects into Meteor)
    mysql-live-select 1.0.6 (whish executes queries using the mysql package)
    whish uses:
         "mysql": "^2.10.2", (the mysql driver)
         "zongji": "^0.4.2" (whish reads binlogs and rise events)

In the rest of my app i use mysql ^2.15.0
For instance, for doing manipulations (CRUD) i use an ORM package named node-orm2:
    "orm": "^3.2.4", (the ORM package)
    "orm-transaction": "0.0.2" (for creating transactions)

I'm not sure if i can provide a test case at the moment, but i'll try to.

**Comment by dougwilson** [comment]
Thanks! I'm not sure if there is anything I can really figure out without seeing the issue. You said 2.10.2 of this module which is a few versions ago a d 2 years old. You could always try something as simple as using the latest version of this module to see if the issue goes away.

**Comment by nzomedia** [comment]
Yes, i'll try to update the mysql driver version and see if that resolves the issue.  It's kind of hard to reproduce the issue since it doesn't happen often.. Thank you for your attention. i'll go back to you soon.

**Comment by nzomedia** [comment]
One last question, since my package uses binlogs  (with zongji) to know when the table content has changed,  do you think there can be some kind of race condition between the moment the new row is effectively written in the database and the moment the "writerows" event is fired.
Perhaps the "writerows" event is rised before the rows are effectively written to the database and therefore, the query i perform in the "writerows"-event-callback fires too soon. I think if that is the case, i could wait for some milliseconds before re-executing my select statement.

**Comment by dougwilson** [comment]
I'm unfortunately not familiar with binlogs or any of that to have an idea.

**Comment by nzomedia** [comment]
Ok, no problem, i'll try to update then. Again, thank you for taking your time to answer me.
