### ISSUE TITLE
 ER_PARSE_ERROR while retrieving data from database. mysql version: 5.7, node.js version: v8.9.4

### ISSUE THREAD

**Issue by mehtadhruv** [mysqljs/mysql#1928]
I am getting the following error when I tried to execute this statement in node.js
   **Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE map_media_user.media_id=trans_media.media_id andtrans_media.device_id=mst_' at line 1**

The same query gets executed in mysql.

connection.query("**select trans_media.device_id,media_name,loc_desc,"+
					"mst_sub_device.sub_device_id,mst_sub_device.group_label,"+
					"mst_sub_device.reading_threshold,avg_reading,trans_reading.created_on"+
					"from map_media_user,trans_media, mst_sub_device,trans_reading WHERE map_media_user.media_id=trans_media.media_id and"+ 
					"trans_media.device_id=mst_sub_device.device_id and mst_sub_device.sub_device_id=trans_reading.sub_device_id and user_id=?"+ 
					"order by reading_id desc limit 2** ",[req.headers['user_id']],function(err, result) {
			if(err){
				console.log("error "+err);
					}
			else{   //sommething
                                    }

**Comment by dougwilson** [comment]
Hi @mehtadhruv I'm not sure what is going on. I copy and pasted what you have there and (after creating some tables with the same column names) it executed without error, returning no rows (since I didn't populate any data).

If you copy and paste from this issue does it work? Is there any additional details you can provide at all? I used the same Node.js version and MySQL server version you have listed above. The error itself comes from the server and not this module, so not sure what it's choking on.

**Comment by mehtadhruv** [comment]
Hello @dougwilson , Thanks for quick reply.
**If you copy and paste from this issue does it work?** 
       No,I  am getting the same error.
But the same query gets executed in mysql .

What kind of additional information should I provide?

**Comment by dougwilson** [comment]
I'm not sure, because you already provided everything I normally ask for. Maybe which specific MySQL 5.7 you're using? I just pulled down the latest community edition for 5.7, but maybe there is some difference in the patches or you're using something other than the community edition?

**Comment by mehtadhruv** [comment]
@dougwilson I am using the mysql 5,7 community version.
When I run select version() command in mysql commandline, I get the version as 5.7.20-log

**Comment by dougwilson** [comment]
Thanks! I used 5.7.21 let me get some time to change my install to 5.7.20 and try again.

**Comment by mehtadhruv** [comment]
OK thanks

**Comment by mehtadhruv** [comment]
I am closing this issue since I got the cause for error. The error was that there was no space between last column name in select statement and from. Thanking @dougwilson for his time.
