### ISSUE TITLE
how to input limit value  mysql nodejs

### ISSUE THREAD

**Issue by jaman99** [mysqljs/mysql#1929]
```js
db.query('SELECT * FROM test Orders LIMIT = ?',[8],(err,result)=>{
     if(err) throw err;
      console.log(result);
  })
```

**Comment by ArtemBoltunov** [comment]
hi, @jaman99. There is a little  mistake in your code. You should remove "=" after Limit and start reading mysql docs.
ex: SELECT * FROM ratings ORDER BY category LIMIT 5

**Comment by jaman99** [comment]
var limitdata=5;

  db.query('SELECT * FROM test Orders LIMIT '+limitdata+'',(err,result)=>{
     if(err) throw err;
      console.log(result);
  })

**Comment by ArtemBoltunov** [comment]
var limitdata=5;

db.query('SELECT * FROM test Orders LIMIT ?', [5],(err,result)=>{
if(err) throw err;
console.log(result);
})

**Comment by dougwilson** [comment]
Thanks for helping @ArtemBoltunov , you rock! If I closed this in error, let me know and I can re-open ASAP :)
