### ISSUE TITLE
The minimum number of connections built in the mysql pool

### ISSUE THREAD

**Issue by qiapi** [mysqljs/mysql#1933]
Hi,I just learned the database for a few day and I have some question about the connection pool. I have learned that the connection pool has the minimum number connections and the maximum number connections. The minimum number connections is the number of the connections when the connection pool first build. But when I use npm mysql, I don't know whether the mysql can configure the minimum number of the connections?

**Comment by dougwilson** [comment]
The minimum is zero in our built in pool.
