### ISSUE TITLE
DB name escaped with env vars on Elastic Beanstalk

### ISSUE THREAD

**Issue by paulcanning** [mysqljs/mysql#1940]
I am using the following query:

```
connection.query(
    'CREATE TABLE IF NOT EXISTS ?.`foo` (`bar` LONGTEXT NOT NULL)',
    [process.env.RDS_DB_NAME],
    function (error, results, fields) {
      if (error) {
        console.error(error);
      }
    });
```

It throws an SQL syntax error:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'ebdb\'.`foo` (`bar` LONGTEXT NOT NULL)\' at line 1'

Why is the DB name being escaped like that?

**Comment by dougwilson** [comment]
This is because a table name is not a value but an identifier. Escaping identifiers: https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-identifiers

**Comment by dougwilson** [comment]
Yep. Sorry for brevity on a phone.

**Comment by paulcanning** [comment]
Cool, no worries, got it sorted now :)
