### ISSUE TITLE
Tables getting locked while using sequelize select query MYSQL.

### ISSUE THREAD

**Issue by JasimJamal** [mysqljs/mysql#1941]
## What are you doing?

```js
 var clientConfig = {

        getClientConfigId: function (req, callback) {
            models.clientConfig.findAll({
                raw: true,
                where: {
                    application: commonFunctions.getSourceApplication(req),
                    client: commonFunctions.getClient(req),
                    culture:commonFunctions.getCulture(req),
                    lineofbusiness: commonFunctions.getlineOfBusiness(req),
                    methodofpayment: commonFunctions.getMethodOfPayment(req)
                }, attributes:["clientconfigid"]

            }).then(
                clientConfig => {
                    callback(null, clientConfig);
                },
                err => {
                    callback(err, null);
            }); 
        }
    }
```

## What do you expect to happen?
Tables are getting locked. It is not happening on every hit. But sometimes when this query fires. We see that the tables get locked for hours and the application stuck. Is there some configuration that we are missing on. Help will be highly appreciated.

## What is actually happening?
We are getting some data from database using the above code. Once in a blue moon we see that the tables gets locked. If we use normal SQL query it does not happens. We had tested this ample of time. It is happening due to sequelize. May be some configuration that we are missing on.

**Comment by JasimJamal** [comment]
@dougwilson  can you please help.

**Comment by dougwilson** [comment]
Unless you set something up you're not showing, sequelize doesn't use this module.

**Comment by kai-koch** [comment]
Does another process Insert, Update or backup the database. (e.g.  a cronjob making a backup, imports new data or update the current data.)

If the tables are locked for hours, see what other queries are executed on the database-server when the error occurs. See the ```SHOW PROCESSLIST``` Alias https://dev.mysql.com/doc/refman/5.7/en/show-processlist.html
