### ISSUE TITLE
cant connect to google app engine with node mysql 

### ISSUE THREAD

**Issue by AyubaMakoa** [mysqljs/mysql#1942]
cant connect to google app engine with node mysql , when ever i try to connect, it throw back error {"error":{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":3306,"fatal":true}} i have followed all possible solutions, nothing seems to work

**Comment by dougwilson** [comment]
The error ECONNREFUSED is from Node.js and is an error opening the TCP connection. Can you give me access to take a look?

**Comment by dougwilson** [comment]
Closing because I never heard back.
