### ISSUE TITLE
Connection pool

### ISSUE THREAD

**Issue by nanom1t** [mysqljs/mysql#1943]
Hi,

I have a question about pooling connections to database. Let's imagine that I have 2 physical servers and 100 databases on each of them. My application frequently uses connections to each database on each server, so I want to use connection pools.
```
var mysql = require('mysql');
var pool  = mysql.createPool({
  host: 'example.org',
  user: 'bob',
  password: 'secret',
  database: 'my_db'
});
```
The problem is that I need to specify database in `mysql.createPool` method. So if I have 100 databases per server I need to create pool for each database on my server. For example:
```
var pool1 = mysql.createPool({host: 'server1', user: 'bob', password: '1', database: 'db1'});
var pool2 = mysql.createPool({host: 'server1', user: 'bob', password: '1', database: 'db3'});
var pool3 = mysql.createPool({host: 'server1', user: 'bob', password: '1', database: 'db3'});
....
```
But I want to save connections to server and create only connection pool to specific server (not for each db in my servers):
```
var server1Pool = mysql.createPool({host: 'server1', user: 'bob', password: '1'});
var server2Pool = mysql.createPool({host: 'server2', user: 'bob', password: '1'});
```
Then I want to do something like this:
```
server1Pool.query('SELECT * FROM db1.users', function(){});
server1Pool.query('SELECT * FROM db2.users', function(){});
server1Pool.query('SELECT * FROM db3.users', function(){});
....
server2Pool.query('SELECT * FROM db8.users', function(){});
```
Is it possible to do this and what is the best solution for this?

Thank you!

**Comment by dougwilson** [comment]
The database option is not required and yoi can already do what you're asking to do.
