### ISSUE TITLE
Does a insert query implicitly rollback the transaction on error?

### ISSUE THREAD

**Issue by bernardocs** [mysqljs/mysql#1944]
As the title suggests, I'm thinking if I may have to implement the same query with `beginTransaction`, `commit`, `rollback`, etc, if the `conn.query('insert ...')` fail and does not rollback the transaction.

I searched throught the docs and didn't find any entry about this. MySQL docs says that no transactions are rolled back right after the error occurs. Does this driver handle this? :thinking:

**Comment by dougwilson** [comment]
This driver simply sends the queries to your MySQL server. You will need to rollback the transaction yourself when you determine the error necessitates a transaction rollback.
