### ISSUE TITLE
IN operator only return the first value  

### ISSUE THREAD

**Issue by yepul2** [mysqljs/mysql#1946]
let ids = [1,2,3,4];
'SELECT * FROM user WHERE status = 1 AND id IN [ ids ]

will only return the user with id = 1.

**Comment by dougwilson** [comment]
That syntax does not look right in multiple ways. Can you show the full javascript?

**Comment by yepul2** [comment]
module.exports.GetProductVariant = (result ,callback) => {

    console.log("here " +result);
    let variants = [{
        variant_id : "",
        variant_name : "",
        variant_ext_cost : ""
    }];

    let fields = ['shipping_id', 'shipping_name', 'shipping_pi', 'estore_shipping', 'status', 1, 'shipping_id', result];
    let sql = "SELECT ??, ??, ?? FROM ?? WHERE ?? = ? AND ?? IN (?)";
    sql = mysql.format(sql, fields);

    db.query(sql, (error, result, fields)=>{
    // let ids = result;
    // console.log(ids);
    // // db.query('SELECT shipping_id, shipping_name, shipping_pi FROM estore_shipping WHERE status = 1 AND shipping_id IN (SELECT(UNNEST($1))',[result], (error, result)=>{//sql, (error, result, fields)=>{
    // db.query('SELECT shipping_id, shipping_name, shipping_pi FROM estore_shipping WHERE status = 1 AND shipping_id IN (SELECT(UNNEST($1))',[ids], function(error, result){//sql, (error, result, fields)=>{
        if(error){
            console.log(error /* + " " + sql */);
            return callback(error, null);
        }

        if(result){

            console.log("fdgfsdhdhdfhsfd "+ JSON.stringify(result));
            variants[0].variant_id = result[0].shipping_id;
            variants[0].variant_name = result[0].shipping_name;
            variants[0].variant_ext_cost = result[0].shipping_pi;
            console.log("dsgdgsdfgsfdgsd  "+ JSON.stringify(variants));

            return callback(null, variants);
        }
        
        
    });
}

**Comment by yepul2** [comment]
// function call
pichereStore.GetProductVariant(result[0].shipping_id, (error, resObj)=>{    
    resData.product.variants = resObj;
    return callback(null, resData); 
})

// result if I console.log(resData)
[{"variant_id": 1, "variant_name": "Option 1", "variant_ext_cost": 0 }]  //only the first value of from result(inside fields)

**Comment by dougwilson** [comment]
For us to format your IN currently, result needs to be an array of strings or numbers; an array of objects is not supported by our builder.

**Comment by yepul2** [comment]
Will it be supported in the future? Can I make a pull request for this issue?

**Comment by dougwilson** [comment]
Yea, we can try to support if possible. You're welcome to either (a) make a pull request with the chabge you want or (b) describe how you're thinking an array of objects should be formatted (i.e. what you expect the output of mysql.format('?', [[{foo:"bar"},{fizz:"buzz"}]]) to be so we can try as well :+1:

**Comment by yepul2** [comment]
I`m appreciate if you can do something like this:

[
            {
                "id": 1,
                "name": "Option 1"
            },
            {
                "id": 2,
                "name": "Option 2"
            },
            {
                "id": 3,
                "name": "Option 3"
            }
]

**Comment by dougwilson** [comment]
That doesn't look like SQL, is it?

**Comment by dougwilson** [comment]
Just can you show what the outout of the following should be, in SQL:

    mysql.format('?', [[{foo:"bar"},{fizz:"buzz"}]])

**Comment by Necromancerx** [comment]
```javascript
[
{
"id": 1,
"name": "Option 1"
},
{
"id": 2,
"name": "Option 2"
},
{
"id": 3,
"name": "Option 3"
}
]
```

If you mean this is the format of the _result_ variable. You can map it first as _id_, then add it to the parameter.


```javascript
result = result.map(x => x.id); // Resulting to [1,2,3]
```

Here is your final code.


```javascript
let fields = ['shipping_id', 'shipping_name', 'shipping_pi', 'estore_shipping', 'status', 1, 'shipping_id', result.map(x => x.id)];
let sql = "SELECT ??, ??, ?? FROM ?? WHERE ?? = ? AND ?? IN (?)";
```

**Comment by yepul2** [comment]
solved, my list of ids has been treated as string including commas ",". resolve by remove all commas and store in an array.
