### ISSUE TITLE
MySQL as Document Store issue

### ISSUE THREAD

**Issue by andreaslacza** [mysqljs/mysql#1947]
**Plattform Node.js and Express**

As of MySQL 5.7.8, MySQL supports a native JSON data type that enables efficient access to data in JSON (JavaScript Object Notation) documents.

When you have a simple key-value store table like this:
`Table: users`
`|id           | created      | jdoc   |     <- Column name`
`| int(11)   | DATETIME | JSON |     <- Column type`

you can save (in example: user data) as JSON in the jdoc Column:
`{`
`      "username": "github",`
`       "fullname": "thegithub",`
`       "urls": {`
`            "website1": "www.github.com",`
`            "website2": "www.github.io",`
       `}`
`}`

when you query (SELECT) a user or users you get the urls as an string:
`[ RowDataPacket {`
`       id: 1,`
`       date: 2018-02-23T21:57:37.000Z,`
`       fulname: 'thegithub'`
`       urls: '{"website1": "www.github.com", "website2": "www.github.io"}'`
` } ]`

and you can't render it in handlebars, mustache and co. is there a way to get nested values as JSON/Object or is this an issue?

**Comment by dougwilson** [comment]
There is not a default type cast for JSON fields yet, but you can add a custom typecast to parse the JSON in your project for the time being: https://github.com/mysqljs/mysql/issues/1267#issuecomment-230739821
