### ISSUE TITLE
when to call connection.release() in pool

### ISSUE THREAD

**Issue by phpmydev** [mysqljs/mysql#1948]
Hello - Doug? 
I have this:

    var mysql = require('mysql');
    var poolCluster	= null;

    exports.getStatus = function(octet,callback) {
	  var sys_conns = { 
	     INFO : {
		host: '192.168.3.'+octet, 
		user: 'user',       
		password: 'pass', 
		database:'INFO'
	      }
	  }
 	   poolCluster = mysql.createPoolCluster();
	   poolCluster.add('INFO', sys_conns.INFO);

	   getConn (octet,function(err, connection) {
		if(connection){
			callback(connection);
		} else {
			callback('no connection');
		}
	   });   
    }

    function getConn (octet,callback) {
	    poolCluster.getConnection(function (err, connection) {
		if(err) {console.log(err); callback(err);}       
		if(connection){
			connection.query("SELECT something as status FROM table;", function(err, rows) {
				callback(err,rows);
		        connection.release(); // either here	
                });
			connection.release(); // or here - neither work
		} else {
			callback('callback: '+err);      
		}
	    });
    }

the problem is the connection just sleeps after executing the query - it does not seem to get released and upon refresh, the connections build up until I restart the app.
any ideas?  Thanks!

**Comment by dougwilson** [comment]
Hi @phpmydev you're using a connection pool -- releasing a connection does not close it, but leaves it sleeping until you use it again. https://en.wikipedia.org/wiki/Connection_pool

**Comment by dougwilson** [comment]
I'm not sure what you mean. "ow to pass in the octet in the ip address" what does that mean, can you show an example?

**Comment by phpmydev** [comment]
I'm just getting the last octet from app.js which gets it from the index page javascript
all I really need iis a way to connect to the db at 192.168.3.12 let's say using the dynamic octet (12, 15,.etc)
I really appreciate your attention Doug!

**Comment by dougwilson** [comment]
You can specify the `host` when you create a new connection: https://github.com/mysqljs/mysql#establishing-connection

**Comment by phpmydev** [comment]
Great! Thank you, I sometimes wish I knew how to search better!

**Comment by dougwilson** [comment]
It's no problem at all :)
