### ISSUE TITLE
Add support for backticks

### ISSUE THREAD

**Issue by rotexhawk** [mysqljs/mysql#1950]
JS backticks makes queries like these easy to read but unfortunately it doesn't work with current implementation. I tried both escape and format. Any reason why it is not implemented?

```
const sql = `CREATE TABLE ? (
            id int(10) unsigned NOT NULL AUTO_INCREMENT,
            county varchar(255) DEFAULT NULL,
            race enum('B', 'I', 'W', 'A', 'T', 'O', 'U') NOT NULL,
            sex enum('M','F','U') NOT NULL,
            age int(11) DEFAULT NULL,
            city varchar(255) DEFAULT NULL,
            party enum('R','D','L','U') NOT NULL,
            precinct varchar(255) DEFAULT NULL,
            cong_dist int(11) DEFAULT NULL,
            house_dist int(11) DEFAULT NULL,
            sen_dist int(11) DEFAULT NULL,
            voting_method enum('C','M','G','S', 'V', 'B', 'T', 'E', 'L', 'O', 'P') NOT NULL,
            election_lbl date DEFAULT NULL,
            site_name varchar(255) DEFAULT NULL,
            PRIMARY KEY (id)
        )`;

        return this.dropTable().then(() => {
            return super.query(sql, [this.table]);
        });
```

**Comment by dougwilson** [comment]
Are you getting an error?

**Comment by dougwilson** [comment]
I was able to run your example with the backticks without issue. Maybe you can help me reproduce the issue, what do I need to change below to not work?
```
$ node -v
v6.13.0

$ cat foo.js
const mysql = require('mysql');

const sql = `CREATE TABLE ? (
    id int(10) unsigned NOT NULL AUTO_INCREMENT,
    county varchar(255) DEFAULT NULL,
    race enum('B', 'I', 'W', 'A', 'T', 'O', 'U') NOT NULL,
    sex enum('M','F','U') NOT NULL,
    age int(11) DEFAULT NULL,
    city varchar(255) DEFAULT NULL,
    party enum('R','D','L','U') NOT NULL,
    precinct varchar(255) DEFAULT NULL,
    cong_dist int(11) DEFAULT NULL,
    house_dist int(11) DEFAULT NULL,
    sen_dist int(11) DEFAULT NULL,
    voting_method enum('C','M','G','S', 'V', 'B', 'T', 'E', 'L', 'O', 'P') NOT NULL,
    election_lbl date DEFAULT NULL,
    site_name varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
)`;

console.log(mysql.format(sql, ['table_name']));

$ node foo.js 
CREATE TABLE 'table_name' (
    id int(10) unsigned NOT NULL AUTO_INCREMENT,
    county varchar(255) DEFAULT NULL,
    race enum('B', 'I', 'W', 'A', 'T', 'O', 'U') NOT NULL,
    sex enum('M','F','U') NOT NULL,
    age int(11) DEFAULT NULL,
    city varchar(255) DEFAULT NULL,
    party enum('R','D','L','U') NOT NULL,
    precinct varchar(255) DEFAULT NULL,
    cong_dist int(11) DEFAULT NULL,
    house_dist int(11) DEFAULT NULL,
    sen_dist int(11) DEFAULT NULL,
    voting_method enum('C','M','G','S', 'V', 'B', 'T', 'E', 'L', 'O', 'P') NOT NULL,
    election_lbl date DEFAULT NULL,
    site_name varchar(255) DEFAULT NULL,
    PRIMARY KEY (id)
)
```

**Comment by rotexhawk** [comment]
So if I print to console my output looks exactly as yours but when I do mysql.query(formatedQuery) I get this error. 

```
errno: 1064,
sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'\'prim1000\' (\n            id int(10) unsigned NOT NULL AUTO_INCREMENT,\n          \' at line 1',
sqlState: '42000',
index: 0,
sql: 'CREATE TABLE \'prim1000\' (\n            id int(10) unsigned NOT NULL AUTO_INCREMENT,\n            county varchar(255) DEFAULT NULL,\n            race enum(\'B\', \'I\', \'W\', \'A\', \'T\', \'O\', \'U\') NOT NULL,\n            sex enum(\'M\',\'F\',\'U\') NOT NULL,\n            age int(11) DEFAULT NULL,\n            city varchar(255) DEFAULT NULL,\n            party enum(\'R\',\'D\',\'L\',\'U\') NOT NULL,\n            precinct varchar(255) DEFAULT NULL,\n            cong_dist int(11) DEFAULT NULL,\n            house_dist int(11) DEFAULT NULL,\n            sen_dist int(11) DEFAULT NULL,\n            voting_method enum(\'C\',\'M\',\'G\',\'S\', \'V\', \'B\', \'T\', \'E\', \'L\', \'O\', \'P\') NOT NULL,\n            election_lbl date DEFAULT NULL,\n            site_name varchar(255) DEFAULT NULL,\n            PRIMARY KEY (id)\n        )' 
```

**Comment by dougwilson** [comment]
That's because a table name is not a value but an identifier, so you need to escape the string as an identifier. Try using `CREATE TABLE ??` as your first line in your sql string

**Comment by dougwilson** [comment]
Docs on escaping identifiers may help clarify as well: https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-identifiers

**Comment by rotexhawk** [comment]
Thank you. What's the difference between `?` and `??`.

**Comment by dougwilson** [comment]
Thr former escapes values and the latter identifiers.

**Comment by rotexhawk** [comment]
Adding this one line to the docs could save developers a lot of time unless it is a common knowledge and I am the only one who doesn't know about this. 

The other one is this, which gave some people in stackoverflow the impression that all queries are automatically escaped. Maybe we can make the word "Object" bold for emphasis?

> When you pass an Object to .escape() or .query(), .escapeId() is used to avoid SQL injection in object keys.

**Comment by dougwilson** [comment]
It seems to be common knowledge on how to write SQL in general knowing what a value is vs what an identifier is and where to use what. We have it right in our TOC next to each other so folks can pick exactly what they need. If there is misinformation on things like Stackoverflow and users are only getting info there vs reading the docs here I'm not sure I know how to solve that problem; any thoights I'd be interested to hear :+1:

> Maybe we can make the word "Object" bold for emphasis?

I'm not sure I understand what it would emphasize? Using .escape is for value and is what the single question mark is. Using escapeId is for identifiers is for and what the double question mark is. Both take Objects just fine.

**Comment by rotexhawk** [comment]
When you pass an Object to .escape(), .escapeId() is used to avoid SQL injection in object keys.
Technically this is an object `let a = new String('SELECT * from blah blah');` will it escape this. Because of the security implications it needs to be clear that it won't escape auto escape strings.

**Comment by dougwilson** [comment]
Report security issues as we ask in https://github.com/mysqljs/mysql/blob/master/Readme.md#security-issues so we have time to address instead of pubically disclosing them putting all module users at risk. I've locked the issue for now. Please continue the discussion in the proper security report.
