### ISSUE TITLE
Provide promises interface

### ISSUE THREAD

**Issue by shipagency** [mysqljs/mysql#1951]
Hi,

I've read #929  -- that discussion happened a while ago, and now two things have changed:

1) We have native promises in node
2) We have await/async -- a lot more people now _want_ to use promises

So... if anything, I think this would be a good time to release a native promise interface for this wonderful library!

Thanks for listening :D

**Comment by dougwilson** [comment]
Makes sense for sure! It's on my list, but if someone is willing to put together all the changes, I can take a look and even accept! I'm not trying to be mean by closing your issue, but we have #1687 as the Promises support tracking issue :)

**Comment by dougwilson** [comment]
In the interim you can use the wrapper https://www.npmjs.com/package/promise-mysql

**Comment by eslachance** [comment]
I think you probably mean https://github.com/sidorares/node-mysql2 - the promise-mysql wrapper forces bluebird and doesn't allow for native promises to be used ;)

**Comment by dougwilson** [comment]
Yea, there are a few to choose from. Whichever works best for you :)

**Comment by ritter** [comment]
@eslachance I hope you understand that bluebird out performs native promises, while also providing features not available yet in native promises. ;)

I'm glad to see this is being considered though, would really like to see promises directly from this module.
