### ISSUE TITLE
Try to connect to a sql server database

### ISSUE THREAD

**Issue by RogerKang** [mysqljs/mysql#1953]
There is an issue about mssql about try to connect a mysql database via mssql client:
https://github.com/tediousjs/node-mssql/issues/309
It will throw uncaughtException which crash the program.

And I try to connect to a sql server database via mysql database:
```
var mysql = require('mysql');
var options = { // it should be an valid sql server database
  host: '127.0.0.1',
  port: 1433,
  connectTimeout: 3000,
  database: 'test',
  user: 'sa',
  password: 'test'
};
var connection = mysql.createConnection(options);
console.time('test');
connection.connect(function(err){
  console.log(err);
  console.timeEnd('test');
});
```
the config about connectTimeout will not be effective, and it will get an error 'Error: read ECONNRESET' after a long wait (in my test, it cost about 90 seconds).

Not sure what is the relevance between mysql and sql server protocol, but both mysql and mssql client should handle this situation.

**Comment by dougwilson** [comment]
The connectTimeout is simply the timeout for establishing the TCP connection. I assume the TCP connection establishes instantly, of course. If you want a timeout on the .connect itself (which is the MySQL handshake sequence), you need to supply that:

```
connection.connect({ timeout: 3000 }, function(err){
  console.log(err);
  console.timeEnd('test');
});
```

You can read more about timeouts here: https://github.com/mysqljs/mysql/blob/master/Readme.md#timeouts

I hope this helps!
