### ISSUE TITLE
Stored procedure giving null row if no record found

### ISSUE THREAD

**Issue by sp-suresh** [mysqljs/mysql#1956]
I am calling a MySQL stored procedure using [MySQL][1] for NodeJS. However, when there is no matching record from the stored procedure the lib returns the object with `null` key values.

Below is the Stored Procedure

    CREATE DEFINER=`admin`@`%` PROCEDURE `ABC_AP_GET_LOGIN_DETAILS`(v_eml varchar(50))
    BEGIN
    	SELECT 
    		U.ABC_AP_USERS_ID uid
            ,U.FIRST_NAME fn
            ,U.LAST_NAME ln
            ,U.MOB_NUM mob
            ,U.PWD_HASH pwdhs
            ,D.ABC_AP_DEPARTMENTS_MASTER_ID did
            ,D.`NAME` dn
            ,GROUP_CONCAT(DISTINCT UR.ROLE_MASTER_ID ORDER BY UR.ABC_AP_USER_ROLES_ID ASC SEPARATOR ',') rids
    	FROM ABC_AP_USERS U
    	INNER JOIN ABC_AP_USER_ROLES UR ON UR.USER_ID = U.ABC_AP_USERS_ID
        INNER JOIN ABC_AP_DEPARTMENTS_MASTER D ON D.ABC_AP_DEPARTMENTS_MASTER_ID = U.DEPARTMENT_ID
    	WHERE U.EMAIL_ID = v_eml
        AND U.IS_ACTIVE = TRUE;
    END

When there is no USERS for specified `v_eml`. It returns the following:

    [ [ { uid: null,
          fn: null,
          ln: null,
          mn: null,
          pwdhs: null,
          did: null,
          dn: null,
          rids: null } ],
      { fieldCount: 0,
        affectedRows: 0,
        insertId: 0,
        serverStatus: 34,
        warningCount: 0,
        message: '',
        protocol41: true,
        changedRows: 0 } ]

How can I make the change to return empty array instead of `Object` with null values if no record matches?

  [1]: https://github.com/mysqljs/mysql

**Comment by dougwilson** [comment]
Hi @sp-suresh sorry no one has looked at this yet. I'd like to take a look in at it. Would it be possible to provide the DDL needed to setup the tables that I can run that sproc against and any data I would need in order to replicate the issue (though I assume zero rows in the tables would replicate it)?

Also the following to help me setup a similar environment:
1. Version of this module
2. Version of Node.js
3. Version of MySQL server

Thanks!

**Comment by sp-suresh** [comment]
This happens to be a default behavior of `GROUP_CONCAT` and to avoid this(null row) we have to add `GROUP BY` at the end of the query or Stored Procedure.

So, the updated Stored Procedure is as

    CREATE DEFINER=`admin`@`%` PROCEDURE `ABC_AP_GET_LOGIN_DETAILS`(v_eml varchar(50))
    BEGIN
      SELECT 
        U.ABC_AP_USERS_ID uid
            ,U.FIRST_NAME fn
            ,U.LAST_NAME ln
            ,U.MOB_NUM mob
            ,U.PWD_HASH pwdhs
            ,D.ABC_AP_DEPARTMENTS_MASTER_ID did
            ,D.`NAME` dn
            ,GROUP_CONCAT(DISTINCT UR.ROLE_MASTER_ID ORDER BY UR.ABC_AP_USER_ROLES_ID ASC SEPARATOR ',') rids
      FROM ABC_AP_USERS U
      INNER JOIN ABC_AP_USER_ROLES UR ON UR.USER_ID = U.ABC_AP_USERS_ID
        INNER JOIN ABC_AP_DEPARTMENTS_MASTER D ON D.ABC_AP_DEPARTMENTS_MASTER_ID = U.DEPARTMENT_ID
      WHERE U.EMAIL_ID = v_eml
        AND U.IS_ACTIVE = TRUE
        GROUP BY UR.USER_ID;
    END
