### ISSUE TITLE
`express-mysql-session` fails when using custom query format

### ISSUE THREAD

**Issue by rrsilaya** [mysqljs/mysql#1957]
`express-mysql-session` package fails when using custom query format. I suggest allowing the old query format with `?` and `??` together with the custom query format configured to work.

**Comment by dougwilson** [comment]
Nothing has really changed with anything you're describing that I'm aware of. Can you elaborate? Happy to make whatever changes, but I don't know what you're referring to, sorry. Perhaps what version of this module you're using and what version of this module used to work, and example of code using this module would help 👍

**Comment by rrsilaya** [comment]
I was able to resolve it by providing catch cases for queries with `?` and `??` as placeholders using this config:

```javascript
db.config.queryFormat = function(query, values) {
  if (!values) return query;

  if (Array.isArray(values)) {
    let offset = 0;

    return query.replace(
      /(\?{1,2})/g,
      function(text, match) {
        offset++;

        if (offset > values.length) return text;

        if (match.length === 2) return this.escapeId(values[offset - 1]);
        else return this.escape(values[offset]);
      }.bind(this),
    );
  } else {
    const escaped = query.replace(
      /\:(\w+)/g,
      function(text, key) {
        if (values.hasOwnProperty(key)) {
          return this.escape(values[key]);
        }

        return text;
      }.bind(this),
    );

    return escaped.replace(/\[(\w+)\]/g, function(text, key) {
      if (values.hasOwnProperty(key)) {
        return this.escapeId(values[key]);
      }

      return text;
    });
  }
};
```
