### ISSUE TITLE
TypeError: http.IncomingMessage.prototype is not an object or null

### ISSUE THREAD

**Issue by El-Mahbub** [mysqljs/mysql#1966]
I want to displaying response from database with mysql but showing an error : TypeError: http.IncomingMessage.prototype is not an object or null.

![er](https://user-images.githubusercontent.com/20553210/37506175-37021646-291b-11e8-9728-312680f8fc7c.png)

How i can fix this ? (I am using mysql on xampp and phpmyadmin for managing my database)

Here is my codes : 

Connection.js : 

```js
var express = require('express');
var app = express();

var mysql = require('mysql');
var con = mysql.createConnection({
  host: "localhost",
  user: "root",
  password: "",
  database: "forum_ilmu_islam"
});
const Connection = ()=>{
	con.connect(function(err){
	  if(err){
	    console.log('Error connecting to Db');
	    return;
	  }
	  con.query("SELECT * FROM admin", function (err, result, fields) {
	    if (err) throw err;
	    console.log(JSON.parse(JSON.stringify(result[0])));
	  });
	});
}
export default Connection;
```

Index.js

```js
var app = express();
app.get('/',function(req,res) {
	$.getJSON(Connection, function(data) {
		console.log(data);
	});
});
`

Thank :-)

**Comment by sidorares** [comment]
this error is not related to driver at all

Something else is altering loaded `http` module. Can you isolate your bug to self contained example one can clone and run with no extra setup?

**Comment by El-Mahbub** [comment]
Thank for your reply/comment sir.

I found that error in express js : 

`var accepts = require('accepts');
var deprecate = require('depd')('express');
var isIP = require('net').isIP;
var typeis = require('type-is');
var http = require('http');
var fresh = require('fresh');
var parseRange = require('range-parser');
var parse = require('parseurl');
var proxyaddr = require('proxy-addr');

/**
 * Request prototype.
 * @public
 */

var req = Object.create(http.IncomingMessage.prototype) <-- This is an error`

I am using reactjs then i just importing express and mysql module but that error is showing without codes specially. So what is example are you need ?
I want to use express and mysql sir. My mysql version is : mysql@2.15.0 and my express version : express@4.16.2.
How i can fix this sir ?

**Comment by sidorares** [comment]
mysql driver never accesses `http` module, so this must be some other code ( other dependencies or your code). Try to dissect this by disabling various bits of functionality. Do you still see problem if you comment out all database logic?

**Comment by El-Mahbub** [comment]
No thank sir, i will try your suggest.
