### ISSUE TITLE
How to reconnect if AWS RDS recovery happens

### ISSUE THREAD

**Issue by lajpatshah** [mysqljs/mysql#1967]
Hi

How have I written the code
1) createPool is used at the start of the app
2) then for every request I am using getConnection

I am using AWS RDS & it went into sudden recovery mode, due to which my db url was unchanged but instance IP must have changed as it was created in another AZ

So for such a scenario I am supposed to reinitialize my db connection so that new instance DNS is updated.

The issue is in such a scenario I did not received any timeout error or connection error. So how do I capture this type of error?

Kindly guide if possible.

Thanks

**Comment by dougwilson** [comment]
Hi @lajpatshah I've never used AWS RDS and not familiar with what would be happening. If you can provide a pull request with the changes necessary to support your case, that would be awesome 👍

**Comment by Necromancerx** [comment]
Duplicate of https://github.com/mysqljs/mysql/issues/821

**Comment by dougwilson** [comment]
Thanks for linking as a duplicate. Closing this one out, then.
