### ISSUE TITLE
How to set the idle connect and release it by automatically

### ISSUE THREAD

**Issue by Sailor20** [mysqljs/mysql#1968]
One trouble is pressing on me, It's the connect pool always full after some time, Because some connect was not released, Is there any way to automatically release these free connect?

**Comment by dougwilson** [comment]
Hi @Sailor20 I'm sorry, your question is not clear to me.

**Comment by Sailor20** [comment]
For example, i get a connection by pool.getConnection, sometimes when the connect.release() was not executed, the connection will never be released!  the more times this happens, the more times it will happen.After a period of time， when the pool is full, the server is not avaliable

if automatically release these connect, this will not be happended

**Comment by dougwilson** [comment]
Ah, gotcha. Yes, you have to release the connection when you're done with it. If you have an idea to make it automatic, please describe in detail so we can implement (or even feel free to submit a PR).

**Comment by KudosAbhay** [comment]
I'm having the same issue as well. I want to close those idle connections when they are not in use.

**Comment by dougwilson** [comment]
If you have an idea to make it automatic, please describe in detail so we can implement (or even feel free to submit a PR).
