### ISSUE TITLE
do we have to  stringify a JSON object before saving?

### ISSUE THREAD

**Issue by angelochen960** [mysqljs/mysql#1969]
HI,

I got this table in mysql 5.7.19"

```
CREATE TABLE `animals` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `name` char(30) NOT NULL,
  `info` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1 |
```
with following code to store a json object, I got an error:Error: ER_INVALID_JSON_TEXT: Invalid JSON text: "Invalid value." 
```
var post = { name : 'pug', info : {age : 1, gender : 'M'} };
var query = connection.query('INSERT INTO animals SET ?', post, function (error, results, fields) {
    if (error) throw error;
    // Neat!
});
```

this works:
```
var post = { name : 'pug', info : JSON.stringify({age : 1, gender : 'M'}) };
var query = connection.query('INSERT INTO animals SET ?', post, function (error, results, fields) {
    if (error) throw error;
    // Neat!
});
```
is the JSON.stringify needed?

**Comment by dougwilson** [comment]
You can read how the `?` works for different value types here: https://github.com/mysqljs/mysql#escaping-query-values

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.

If you're passing in an object that need a different behavior, then yes, you need to pass in an altered type. In your case, you just want the `?` to correspond to a single string that is the JSON to store it. `JSON.stringify` is the way to do that 👍
