### ISSUE TITLE
Building a SELECT statement from Object

### ISSUE THREAD

**Issue by codeoverdoze** [mysqljs/mysql#1970]
Hello,
I'd be glad to get help with the following.
Say i have an object.
```js
let params = {
    name: "Michael",
    age: 16,
    gender: "Male"
}
```
And i want to use this in my SQL statement.
Eg.
```js
db.query("SELECT * FROM tbl WHERE ?", params, (err, results, fields) => {
     if(err){
        console.log(err);
     }
});
```
I will get an error in my SQL syntax because the SQL query produced will be
```sql
SELECT * FROM tbl WHERE name = 'Michael' , age = 16, gender = 'Male';
```
But i want to get a way to do (AND/OR instead of comma-separated).

Any help will be appreciated. 
I could loop through the object to create a query string but i'm assuming there will be a more elegant 
solution.

Thanks

**Comment by dougwilson** [comment]
You can read how the `?` works for different value types here: https://github.com/mysqljs/mysql#escaping-query-values

> Objects are turned into key = 'val' pairs for each enumerable property on the object. If the property's value is a function, it is skipped; if the property's value is an object, toString() is called on it and the returned value is used.

If you're passing in an object that need a different behavior, then yes, you need to pass in an altered type 👍
