### ISSUE TITLE
Handshake inactivity timeout - PROTOCOL_SEQUENCE_TIMEOUT

### ISSUE THREAD

**Issue by jatinseth2007** [mysqljs/mysql#1971]
Getting this error while trying to save data into mysql in night job where we fire job to update 100 users parallely . My node version is `v9.8.0`. My mysql version is `mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper` and mysql module version is `2.15.0`. My pool options are given below:

```js
var mysql = require('mysql');
var config = require('../../config');
var tracer = require('../../api/helpers/tracer');

// Connect to database
var pool = mysql.createPool({
    canRetry: true,
    database: config.mysql.database,
    host: config.mysql.host,
    user: config.mysql.user,
    password: config.mysql.password,
    connectionLimit: 100,
    connectTimeout: 60 * 60 * 1000,
    aquireTimeout: 60 * 60 * 1000,
    timeout: 60 * 60 * 1000,
    supportBigNumbers: true,
    bigNumberStrings: true,
    charset: 'utf8mb4_unicode_ci',
    multipleStatements: true
});

// Attempt to catch disconnects 
pool.on('connection', (connection) => {

    // Below never get called
    connection.on('error', (err) => {
        // And done with the connection.
        connection.release();

        //show error
        tracer.error(new Date(), 'MySQL error', err);
    });
    connection.on('close', (err) => {
        tracer.error(new Date(), 'MySQL close', err);
    });
});
```

**Comment by dougwilson** [comment]
Very strange. The error should only be occurring if the handshake to your MySQL server is timing out. I'm not sure if you can help me replicate this on my end, can you? How long does the handshake take when that error occurs, do you know?

The `acquireTimeout` option will change this timeout for you, which defaults to 10 seconds. I see your connection object above, and there is a lot of weirdness in there. For example, what does `canRetry: true` do? We don't have any `canRetry` option in this module. Also you have a `aquireTimeout` but that has "acquire" misspelled, so it doesn't change the `acquireTimeout` option.

**Comment by jatinseth2007** [comment]
Sorry for these silly mistakes, I have updated this file as give below and will update you with new output soon.

```
// Connect to database
var pool = mysql.createPool({
    database: config.mysql.database,
    host: config.mysql.host,
    user: config.mysql.user,
    password: config.mysql.password,
    connectionLimit: 100,
    connectTimeout: 60 * 60 * 1000,
    acquireTimeout: 60 * 60 * 1000,
    supportBigNumbers: true,
    bigNumberStrings: true,
    charset: 'utf8mb4_unicode_ci',
    multipleStatements: true,
    //debug: true,
    // debug: (process.env.NODE_ENV === 'dev') ? ['ComQueryPacket'] : false,
    //debug: ['RowDataPacket'],
    //waitForConnections: true,
    //queueLimit: 0
});
```

**Comment by dougwilson** [comment]
Closing due to no replication steps materializing

**Comment by jatinseth2007** [comment]
Sorry I forgot to reply on this one, I found the problem and it was something else. I was running 3 different apps on same db which was creating the problem. So, I was giving 100 connections each app but in my mysql only 152 connections were allowed, so , it was creating the problem.

**Comment by CedYF** [comment]
> Sorry I forgot to reply on this one, I found the problem and it was something else. I was running 3 different apps on same db which was creating the problem. So, I was giving 100 connections each app but in my mysql only 152 connections were allowed, so , it was creating the problem.

So what was the solution @jatinseth2007
