### ISSUE TITLE
Object doesn't support property or method 'createConnection'

### ISSUE THREAD

**Issue by ricardolx** [mysqljs/mysql#1972]
I'm trying to connect to a database on another PC on the local network via the IP address. Both are windows machines. My code is the following:
```js
var mysql = require('mysql');
let connection = mysql.createConnection({
    host: '192.30.200.10',
    user: 'DBUser',
    password: 'password',
  });

connection.connect();
```
Whether using connection.connect(); or implicitly with a query, I get an error stating: TypeError: Object doesn't support property or method 'createConnection' pointing to line 89 on the Connection.js file
```js
this._socket = (this.config.socketPath)
```
I'm having trouble finding any sort of documentation on this method. Is there something wrong with my createConnection?

**Comment by dougwilson** [comment]
The Net.createConnection is part of Node.js. the docs for that is here: https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_net_createconnection

**Comment by kai-koch** [comment]
You define ```connection``` with ```let``` as a local variable.
The error indicates, you are trying to access the local ```connection.connect();``` in another scope (global or another block scope).

Please provide a complete code example.

**Comment by dougwilson** [comment]
Closing due to no response.
