### ISSUE TITLE
'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\'testusername\'\' at line 1' }

### ISSUE THREAD

**Issue by matak33** [mysqljs/mysql#1973]
Hi everyone, so I try to save on a sql database some data (user data) and I have this error. I try to put some quotes etc. 
But when I try I get this error can you help me please ? 
Thanks 
the error : 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\'testusername\'\' at line 1' }

The log : 

testusername
testname
testname1
testpassword
test@gmail.com
1f134419-14c5-439e-95a5-a46d675085bd

Connected!
--> ComQueryPacket
ComQueryPacket {
  command: 3,
  sql: 'INSERT INTO utilisateurs  (nomutilisateur, Nomfamille, prenomutilisateur, mdp, email, setup, token) VALUES \'testusername\'' }

<-- ErrorPacket
ErrorPacket {
  fieldCount: 255,
  errno: 1064,
  sqlStateMarker: '#',
  sqlState: '42000',
  message: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \'\'testusername\'\' at line 1' }

/home/gaspard/Bureau/Gaspard/inscription/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: this._callback.apply is not a function

and The source code (I can't show all the code because is confidential)

        var pseudo = req.body.pseudo
           
console.log(pseudo);
    var data2 =  req.body.nomfamille
    
 console.log(data2);
 
    var data3 =  req.body.prenom
    
    console.log(data3);
    var data5 = req.body.mdp
    
    console.log(data5);
    
    var data6 = req.body.email
    
    console.log(data6);
    var token = uuid.v4();
    
       var setup = setup
       
       console.log(token);
       
      con.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
  var sql = 'INSERT INTO utilisateurs  (nomutilisateur, Nomfamille, prenomutilisateur, mdp, email, setup, token) VALUES ?';
  con.query(sql,[pseudo],[data2],[data3],[data5],[setup],[token], function (err, result) {
 console.log(err);
 

I try this code : 

 con.query('INSERT INTO utilisateurs  (nomutilisateur, Nomfamille, prenomutilisateur, mdp, email, setup, token) VALUES ?', pseudo,data2,data3,data5,data6,token,setup, function(err, result) {

and : 

 con.query('INSERT INTO utilisateurs  (nomutilisateur, Nomfamille, prenomutilisateur, mdp, email, setup, token) VALUES ?', '"+pseudo"','"+data2"','"+data3"','"+data5"','"+data6"','"+token"','"+setup"', function(err, result) {
I use the latest version of node sql , node js and npm.

**Comment by dougwilson** [comment]
Hi @matak33 your query should be the following 👍 
```js
con.query('INSERT INTO utilisateurs (nomutilisateur, Nomfamille, prenomutilisateur, mdp, email, setup, token) VALUES (?)', [[pseudo,data2,data3,data5,data6,token,setup]], function(err, result) {
```
