### ISSUE TITLE
Search multiple data in one query. 

### ISSUE THREAD

**Issue by matak33** [mysqljs/mysql#1975]
Hi everyone, yesterday I post a issue about write multiple data in a var on a sql database. So is working perfectely thanks to @dougwilson.

I have a new problem when I try to search user data for example username is working well when I search only username code : 

   
    var mdp = req.body.mdp
    var email = req.body.email
con.query('SELECT * FROM `utilisateurs` WHERE email = ?', [email], function (error, results, fields) {
	 console.log(results);
	 	 console.log(fields);

if (results.length < 0) {
	if (results)
	
	
	res.redirect('/home');
	
	}

}); 

So when I try to use this code (for multiple search data : the password and the email)

con.query('SELECT * FROM `utilisateurs` WHERE email AND mdp = ?', [email],[mdp], function (error, results, fields) {

This code is working but it can't found a existing value in database. I try this code : 

con.query('SELECT * FROM `utilisateurs` WHERE email AND mdp = ?', [[email,mdp]], function (error, results, fields) {

Same problem. But I have a sql syntax error :  
error : 
message: 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \' \'aqwzsx123!\'\' at line 1' }

undefined
undefined

 Can you help me. I think is a syntax error problem. 

Thanks you.

**Comment by kai-koch** [comment]
hi!
You got a typo in your query:
... 'SELECT * FROM utilisateurs WHERE email AND mdp = ?', ...
Try this:
... 'SELECT * FROM utilisateurs WHERE email = ? AND mdp = ?', [email,mdp] ...

See https://github.com/mysqljs/mysql#escaping-query-values

Re-open this issue with more details, if this does not solve your problem, please.

**Comment by matak33** [comment]
Thanks for your answer. I have a another question if I try to get some data stored on sql database (for example token) 

Is the good code : 

var token = (results.token);  

So I try this code and I can't get my data. 
Thanks 


The entire code if you want : 

   
    var mdp = req.body.mdp
    var email = req.body.email
con.query( 'SELECT * FROM utilisateurs WHERE email = ? AND mdp = ?', [email,mdp], function (error, results, fields) {
	 console.log(results);
	 	 console.log(fields);
if (results.length > 0) {
	if (results)
	       var token = results.token;
	       console.log(token);



and the log : 
undefined  (for the token var)

**Comment by sidorares** [comment]
@matak33 results is array. Try this

```js
if (results.length > 0) {
  console.log(results[0].token);
}
```

( results array never sparse so no need for extra `if(results[0])` test )

**Comment by matak33** [comment]
@sidorares Thanks is working perfectely ! Thanks
