### ISSUE TITLE
Mysql replication failure during the delete operation

### ISSUE THREAD

**Issue by nalexs** [mysqljs/mysql#1980]
Mysql Master and 2 full Slave:
When delete some entity on Master associated by foreign key with many tables, on Slave all records for all this tables delete, but on the master not delete.  Errors  on master there are no. 
The next update or delete this entity on master slave broken, because on slave have already been deleted.

Mysql Distrib 5.7.21
...
gtid-mode               = on
binlog_format           = row
enforce-gtid-consistency= true
slave_compressed_protocol       = 1
slave_preserve_commit_order     = 1
slave-parallel-type             = LOGICAL_CLOCK
...

Why this can happen?

**Comment by dougwilson** [comment]
This is an issue tracker for a Node.js MySQL driver.
