### ISSUE TITLE
Mysql looses connection and stop trying to reconnect after X tries (server unreachable)

### ISSUE THREAD

**Issue by NoxWorld258** [mysqljs/mysql#1985]
Hello,

So i have a proxy running with MySQL, the proxy checks that the user have access to the destination through mysqljs.

I had a few problems with connection lost, and i used a popular modification of the .connect() function (See my code below).

So the driver lost connections to my database for some reason (it appears i have a "Host unreachable" error at some point ; The exact error was " _connect EHOSTUNREACH_ " ). And my code is supposed to try to reconnect to the database every 3s. And it did, for some time. I seems that after a few tries (i'd say 20, but i'm not sure), it stopped to try reconnecting.

My questions : Is this something intended or related to the mysql driver ? 
Or is it me and my code ? (Maybe i should include more error code to reconnect in specific cases ?)

```
function handleDisconnect()
{
  dbh = mysql.createConnection(db_config); 		// Recreate the connection, since
                                                // the old one cannot be reused.

  dbh.connect(function(err) {
    if(err) {
      proxy_logger.error('error when connecting to db:', err);
      setTimeout(handleDisconnect, 5000); // We introduce a delay before attempting to reconnect,
    }
	else{proxy_logger.info("Connected to database.");}	// to avoid a hot loop, and to allow our node script to
  });                                     // process asynchronous requests in the meantime.
                                          // If you're also serving http, display a 503 error.
  dbh.on('error', function(err) {
    proxy_logger.log('Database error : ', err);
    if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
      handleDisconnect();                         // lost due to either server restart, or a
    } else {                                      // connnection idle timeout (the wait_timeout
      console.error(err);                                  // server variable configures this)
    }
  });
}

handleDisconnect();
```

**Comment by dougwilson** [comment]
> Is this something intended or related to the mysql driver ?

Not that I'm aware of.

> Or is it me and my code ? (Maybe i should include more error code to reconnect in specific cases ?)


That's what it looks like -- you only ever retry on `err.code === 'PROTOCOL_CONNECTION_LOST'` but any other error you don't try to reconnect. Are you sure that the error doesn't change from host unreachable to something else after some period of time? If they were to happen, your code looks like it would definitely stop attempting to reconnect.

If you can provide instructions on how to setup an environment and reproduce your issue, I can help debug through it to see what is happening.

**Comment by NoxWorld258** [comment]
Thanks for you answer Dougwilson.

Providing more information about the environment will be tricky as the environment is a cloud and i don't know the whole network map. I think the error comes from my code, but i don't know how to fix it, explaination follows.

I have a server in a network, let's say 192.168.1.10 , with a MySQL database.
Then the server that runs the nodeJS script, let's say in 192.168.1.20
I assume at some point, the network or the MySQL server failed and the connection was lost.

So in this case, i also assume that if you have an open connection, there is a ' PROTOCOL_CONNECTION_LOST' error,  but then when the script tries to reconnect, the error seems to change to 'EHOST_UNREACH', which i guess means 'host unreachable'.

So if i'm right, it's due to my code and totally legit that it doesn't try to reconnect as the error code changed to something i don't support.
My question is therefore, how should i handle connections errors to "revive" (or create a new) connexion ? 
And is there a list of the error code somewhere (related to connexion) , so i could handle them properly ?

**Comment by killboard** [comment]
Hi, The section `https://github.com/mysqljs/mysql#error-handling` talks about Error handling in connection. Follow my form to handle connection error:

```
const connectMysqlDatabase = (app, datasource, done) => {
  const mysqlDbOptions = app.config.mysqlDB
      , mysqlDbConnection = mysql.createConnection(mysqlDbOptions);

  let secondsToTryAgain = 0;

  mysqlDbConnection.on('error', (err) => {
    console.error('Mysql! Fatal error!', err.code,'trying again in', secondsToTryAgain);
    mysqlDbConnection.connect(handleConnection);
  });

  function handleConnection(err) {
    if (err) {
      if(secondsToTryAgain <= 30000)
        secondsToTryAgain += 5000;

      console.error('Mysql! Fatal error to connect!', err.code)
      console.log('trying again in', secondsToTryAgain / 1000, 'seconds...');

      return setTimeout(() => {
        mysqlDbConnection.connect(handleConnection);
      }, secondsToTryAgain);
    }

    datasource.mysqlDbConnection = mysqlDbConnection;
    console.log('Mysql! Connected in', mysqlDbOptions.host,  mysqlDbOptions.database);
    done(null, app, datasource);
  };

  mysqlDbConnection.connect(handleConnection);
};

```
