### ISSUE TITLE
"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","fatal":true},"

### ISSUE THREAD

**Issue by Tobzzy** [mysqljs/mysql#1993]
Mysql refuse to connect API i try PSQL too same thing this is the error im getting 
`{"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"10.179.105.32","port":3306,"fatal":true},"response":null}`

<h3>here is my code</h3>
<p>this in my app.js</p>

```js
app.use(function(req, res, next){
	global.connection = mysql.createConnection({
	  	host     : '****',
	  	user     : '****',
		password : '****',
  		database : '****'
	});
	connection.connect();
	next();
});
app.use('/', index);
app.use('/api/v1/users', users);
```
<br>
<p> and this in my user.js</p>
<br>

```js
var express = require('express');
var router = express.Router();


router.get('/', function(req, res, next) {
	connection.query('SELECT * from dbtable', function (error, results, fields) {
	  	if(error){
	  		res.send(JSON.stringify({"status": 500, "error": error, "response": null})); 
	  	
	  	} else {
  			res.send(JSON.stringify(results));
  			
	  	}
  	});
});


module.exports = router;
 ```

**Comment by dougwilson** [comment]
Hi @Tobzzy , both of those errors are Node.js errors. You can read more about them at https://nodejs.org/dist/latest-v10.x/docs/api/errors.html#errors_common_system_errors and what they mean.
