### ISSUE TITLE
connection.end() callback issue

### ISSUE THREAD

**Issue by narayanmp** [mysqljs/mysql#1994]
Hi,

I have a Node JS program where one js file takes care of creating a connection, querying and closing the connection by calling connection.end(). The functionality is exposed with a function named query().

This function is being called repeatedly from another file in a loop. The problem I have is, it reaches max connection. Ideally I am expecting the connection to be closed after each query. The code seems correct. I noticed that the connection.end() is called on time but the callback which is passed into the end() function is called almost at the end. Can I get some help on why it is delaying ending connection?

**Comment by dougwilson** [comment]
All of Node.js networking operations are async. Node.js doesn't provide an async network interface, so you have to wait for the callbacks to complete.
