### ISSUE TITLE
which version Introduced the System Variables "max_statement_time" ?

### ISSUE THREAD

**Issue by bosiam** [mysqljs/mysql#1999]
from refman 5.7,we can saw the max_statement_time Introduced in verison 5.7.4

![image](https://user-images.githubusercontent.com/2595133/38796034-c1e5659a-418c-11e8-9e89-1b045485b12d.png)

but i saw the max_statement_time in version 5.6.32

![image](https://user-images.githubusercontent.com/2595133/38796131-0eff57fa-418d-11e8-91b9-4665c3f82287.png)

**Comment by dougwilson** [comment]
This repo is for a Node.js driver, not the server software.
