### ISSUE TITLE
Whenever '%' is present in LIKE clause criteria, It replacing every space of a with '20%'

### ISSUE THREAD

**Issue by badcoder28** [mysqljs/mysql#2004]
This must be a bug.

Whenever i try to search a record with **key**: `SODIUM CHLORIDE .65%` in my query:

 ```
// I omitted some code for simplicity sake.
const query = connection.query(`SELECT id, name FROM generic WHERE name LIKE ?;`, `%${key}%`);

console.log(query.sql);
```

The output betray the actual query with this new key criteria.
```
SELECT id, name FROM generic WHERE name LIKE '%SODIUM%20CHLORIDE%20.65%%';
```
Is there any proper way to handle this, i think i missed something here.

Im using **v2.15.0**.

> **UPDATE**

I suspect **queryFormat** might be the cause?

Here is how i set a custom queryFormat

```
connection.config.queryFormat = (query, values) => {
    if (!values) return query;
    return query.replace(/\:(\w+)/g, function (txt, key) {
        if (values.hasOwnProperty(key)) {
            return connection.escape(values[key]);
        }
        return txt;
    }.bind(this));
};
```
This is my query line exactly looks like:

```
// I simply provide this to be the criteria since it came from the request.query
// of expressjs.
const query = { key: 'SODIUM CHLORIDE .65%' };
query.key = `%${query.key}%`;  

const sql = connection
            .format(`SELECT id, name FROM generic WHERE name LIKE :key LIMIT 30`, query);

// Logging the query.key;
console.log(query.key);

// I logged this before connection.query() function.
// The output is the same from the issue above
console.log(sql);
```

**OUTPUT:**

```
%SODIUM%20CHLORIDE%20.65%%
SELECT id, name FROM generic WHERE name LIKE '%SODIUM%20CHLORIDE%20.65%%';
```

**Comment by dougwilson** [comment]
Weird, I just tried it and I got 
```
SELECT id, name FROM generic WHERE name LIKE '%SODIUM CHLORIDE .65%%';
```
when
```
var key = 'SODIUM CHLORIDE .65%'
```

Can you show the output of `console.log(key)` in your code above to see what it is? Just put it right in the same place as the `console.log(query.sql)`. For example:
```
// I omitted some code for simplicity sake.
const query = connection.query(`SELECT id, name FROM generic WHERE name LIKE ?;`, `%${key}%`);

console.log(key);
console.log(query.sql);
```

**Comment by badcoder28** [comment]
Im using a custom queryFormat which I copy from the docs. I suspect this may be the cause. Sorry, please let me edit my issue to be more precise in my current situation.

**Comment by dougwilson** [comment]
Ok. When you edit it doesn't notify me, so make sure you leave a new comment after you make the changes so I know to come back and look 👍

**Comment by badcoder28** [comment]
@dougwilson i updated my issue, can you look after it? A lot of thanks

**Comment by dougwilson** [comment]
If `console.log(query.key);` is `%SODIUM%20CHLORIDE%20.65%%` then of course you'll still have those `%20` in the string for MySQL. I'm not sure I understand what the bug is here.

When I run
```
const query = { key: 'SODIUM CHLORIDE .65%' };  

const sql = connection
            .format(`SELECT id, name FROM generic WHERE name LIKE :key LIMIT 30`, query);
```

With the custom formatter setup, `console.log(sql)` outputs `SELECT id, name FROM generic WHERE name LIKE 'SODIUM CHLORIDE .65%' LIMIT 30` isn't that what you get?

**Comment by badcoder28** [comment]
You are exactly right. **NOT A BUG**. I think i figure out what really causing this one, Sorry for the bother but your process expose my mistake though, so hats off and really lot of thanks man.
