### ISSUE TITLE
Question: connection.end() in node module? Does it disconnect for everyone at same time?

### ISSUE THREAD

**Issue by peppies** [mysqljs/mysql#2008]
Greetings,

I have a small Node.js chat server and have a few modules, each of which connects to MySQL and runs a single query.

When I use connection.end() in the modules, does this kill the connection being used in all of the other modules? What happens if 1000 people are logging in at once, lets say the module runs MySQL for the first user and then it calls disconnect.end(), does it prematurely disconnect all the other users connecting to the module?

Node.js is a bit new to me, I'm used to PHP and MySQL in which it can handle a ton of users at once, each page load has it's own separate MySQL. I'm not sure if Node.js is using MySQL in such a way that connections called by users can interfere with each other?

**Comment by dougwilson** [comment]
It all depends on how you wrote the code. When you call createConnection that will return you one connection. If you call .end on that object it will end that connection.

**Comment by dougwilson** [comment]
You've accidentally declared the variable outside the function. Just move your declaration inside your function to make sure the connection variable doesn't change during the query:
```js
var mysql = require('mysql'),
  db_config = {
    host: '****',
    user: '***',
    password: '***',
    database: '***'
  };

// var connection; <-- this is incorrect, needs to be in function

module.exports = function testMysql(socket, userid) {
  var connection; // <-- new placement
  connection = mysql.createConnection(db_config);

  connection.connect(function(err) {
    if(err) {
      connection.end();
    }
    else {
      console.log('MYSQL QUERY BEGIN');
      connection.query('SELECT COUNT(*) FROM items WHERE quantity = "1" AND live = "1"', function(error, results, fields) { // takes 30 seconds
         connection.query('INSERT INTO testmysql (completed) VALUES ("1")', function(error, results, fields) { // after 30 seconds do insert query to confirm connection still exists.
            console.log('MYSQL CONNECTION END');
            connection.end();
        });
      });
    }
  });
}
```

**Comment by peppies** [comment]
Awesome, thanks a lot! Things almost got really scary there for a sec.
