### ISSUE TITLE
Basic connection causes error

### ISSUE THREAD

**Issue by ivan770** [mysqljs/mysql#2012]
This code was obtained from [https://www.w3schools.com/nodejs/nodejs_mysql.asp](url), basic mysql module tutorial. Tried using 3 different servers, every time I receive this error: 
![default](https://user-images.githubusercontent.com/14003886/39934732-6c34376c-554f-11e8-91f4-216876571b87.png)
```
var mysql = require('mysql');

var con = mysql.createConnection({
  host: "localhost",
  user: "yourusername",
  password: "yourpassword"
});

con.connect(function(err) {
  if (err) throw err;
  console.log("Connected!");
});
```

**Comment by ivan770** [comment]
@dougwilson Wow, idk what was that but... It worked without any code changes...
Anyway, thanks for assistance!

**Comment by dougwilson** [comment]
No problem. Very strange. If there is some weird issue let us know. You mentioned electron so not sure as I have never used it so maybe there could be something going on there that we could improve.
