### ISSUE TITLE
json insert

### ISSUE THREAD

**Issue by borodadada** [mysqljs/mysql#2015]
hello i use mysql 8 server
in mysql doc write example - INSERT INTO t1 VALUES('{"key1": "value1", "key2": "value2"}');
i try
```
                let a = {"key1": "value1", "key2": "value2"}
                pool.query( 'INSERT INTO news VALUES(?)' , [a], function (error, results, fields) {
                    if (error) throw error;
                        console.log(error)
                });
```
dont work, how i can send data in json format?

**Comment by dougwilson** [comment]
You can find the rules for how we stringify values at https://github.com/mysqljs/mysql/blob/master/Readme.md#escaping-query-values

> Objects are turned into key = 'val' pairs for each enumerable property on the object. 

Which is not what you want. You need to JSON.stringify the value before passing to this lib.
