### ISSUE TITLE
batch update does not work

### ISSUE THREAD

**Issue by kunlan** [mysqljs/mysql#2018]
```js
function updateSilverTicket(ids, cb) {
    let sql = 'update t_mission_benefit_card set money=0 where id in (?)';
    let args = [ids];
    console.log('args:'+args);
    pomelo.app.get('dbclient').update(sql, ids, function (err, res) {
        console.log('resresres:'+ JSON.stringify(res));
        if (!err) cb(null, true);
    });
}
```
when ids is [35,36],  changedRows: 1

**Comment by dougwilson** [comment]
Very strange. I would love to take a look. Can you help us replace your issue?

1. Version of Node.jz
2. Version of this module
3. DDL to create required table(s)
4. SQL to populate the data to test update
5. Full code that I can copy and paste and run without modification. 

Thanks!

**Comment by kunlan** [comment]
😂 i careless, the second parameter should be args
`update(sql, ids, function (err, res)`
