### ISSUE TITLE
Looking for Interfaces for TypeScript

### ISSUE THREAD

**Issue by Blair2004** [mysqljs/mysql#2032]
Hi, 
thank you for your work so far. I'm using this project with Angular 6, and currently it's a bit difficult to remember all the member of the class MySQL. does anyone has yet interfaces for all members ?

Sorry if that thread makes me look like a lazy developper 😆

**Comment by dougwilson** [comment]
Yes, there are type definitions available through the DefinatelTyped project https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mysql
