### ISSUE TITLE
mysql a strange problem; table not found; and table exists;

### ISSUE THREAD

**Issue by MisterChangRay** [mysqljs/mysql#2033]
today, i delete the 'file' table , but i no backup;

I see my friend import all database sql; 
i say: i just delete  one table, so he stop and rollback; 
ok;

now  file table not access;
we want delete this table but tips: table not found;
we want create this table but tips: table exists;
I'm confused.

**Comment by dougwilson** [comment]
Hi! I believe you may have opened this issue on the wrong issue tracker. This is a Node.js mysql driver. It sounds like you're asking questions about the server itself.
