### ISSUE TITLE
How to create table with FK?

### ISSUE THREAD

**Issue by eserdinyo** [mysqljs/mysql#2036]
I want to create a table that has a Foreign Key.
I wrote this syntax but there is an error.
`"CREATE TABLE customers (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), address VARCHAR(255), FOREIGN KEY (name) REFERENCES accounts (id)";`

**Comment by dougwilson** [comment]
I would ask generic SQL questions on Stackoverflow or similar. This tracker is for issues related to the module itself :+1:

**Comment by dougwilson** [comment]
P.S. I don't happen to know the answer off hand to provide one.
