### ISSUE TITLE
Conditionals for relational database is not working or lacking documentation

### ISSUE THREAD

**Issue by joaop-oliveira** [mysqljs/mysql#2037]
cannot get the result query when writing a where statement 

```javascript
const Player = async () => {
  const session = await mysqlx.getSession(options);
  const schema = session.getSchema('math-battle');
  const player = schema.getTable('players');
  return player;
};
```

```javascript
playerRouter.get('/show/:id', async (req, res) => {
  const player = await Player();
  const { id } = req.params;
  const users = [];
  player
    .select(['full_name', 'user_name', 'email'])
    .where('id = :id')
    .bind('id', id)
    .execute((row) => {
      console.log(row);
      users.push({
        id: row[0],
        full_name: row[1].trim(),
        user_name: row[3].trim(),
        email: row[4].trim(),
      });
    })
    .catch((error) => {
      console.log(error);
    });
  res.status(202).json(users);
});
```

it doesn't show any errors or anything but it doesn't return the results to

**Comment by dougwilson** [comment]
Hi! Sorry you're having trouble. I don't even see anywhere you're using this module in your code above. Perhaps you opened in wrong repo or you pasted the wrong code?

**Comment by ruiquelhas** [comment]
Looks like you are using the [xdevapi](https://github.com/mysql/mysql-connector-nodejs) connector and not this module.

On a first look, seems like the issue might be related to the fact that you are sending back a response before the operation finishes. `execute()` is returning a `Promise` so you should wrap that code inside a `then()` or just use `await` as well.

```js
playerRouter.get('/show/:id', async (req, res) => {
  try {
    await player
      .select(['full_name', 'user_name', 'email'])
      .where('id = :id')
      .bind('id', id)
      .execute((row) => {
        // ...
      });
    res.status(202).json(users);
  } catch(error) {
    console.log(error);
    // res.status(500);
  }
});
```

If you're still having issues, feel free to submit a bug report in the MySQL [tracker](https://bugs.mysql.com/) using the `Connector for Node.js` category.

@dougwilson sorry for spamming (I guess you can close this).

**Comment by joaop-oliveira** [comment]
OMG so sorry man wrong repo....
