### ISSUE TITLE
handshake inactivity timeout - How to catch this error?

### ISSUE THREAD

**Issue by ianbale** [mysqljs/mysql#2038]
I've seen a lot of issues reported here by people receiving this error. Whilst the responses suggest ways in which it may be caused and how to avoid it, none mention how to recover from it...?

There is no getting away from the fact that DBs can go down and when they do this error is going to occur. Right now it takes my app down with an unhandled exception error.

I've tried adding try/catch around every piece of my DB code, but to no avail, the exception remains uncaught.  

Can you explain how we can trap this error and deal with it gracefully please?

**Comment by dougwilson** [comment]
The error should be coming though a callback or event. Without providing your full code base it's hard for me to say where you are missing the capture point. Can you provide access to the code so we can take a look? There could also be a bug in the lib.

Can you provide one of the following? (1) full code we can copy and paste and run without modification and instruction on how to see the issue occur with the code or (2) a pull request with a fix. If there is a third method in which we can proceed, please suggest :+1:

**Comment by Liaozzzzzz** [comment]
@dougwilson I got the same questions when getConnection after createPool, my conifg : node- v8.11.2 ; mysql: 2.15.0 ; I have tried different version for my node.js and mysql ,but it seems not work!

**Comment by dougwilson** [comment]
Can you provide one of the following? (1) full code we can copy and paste and run without modification and instruction on how to see the issue occur with the code or (2) a pull request with a fix. If there is a third method in which we can proceed, please suggest 👍

**Comment by dougwilson** [comment]
Oh, haha, that can do it. If the port has something listening on it so it was able to actually setup the TCP connection, then this module would write the handshake packet. If whatever is on that port then never writes any data back (even non mysql data) then handshake inactivity timeout can happen since the module is waiting for a response to the handshake packet it sent :+1:
