### ISSUE TITLE
Pooled connections run into error

### ISSUE THREAD

**Issue by yashgt** [mysqljs/mysql#2039]
We create connections using a pool. If the connection obtained from the pool is in error, how do we fix that connection? In the below code, the connect function takes a command callback which expects a good connection to be passed to it. This connection comes from a pool. **How should I structure my code to handle the error.** The documentation at [](https://github.com/mysqljs/mysql#error-handling) shows only how to log the error and not how to recover. I do not want to report an error. My application should remain always-running and hence should recreate connections that fail.

```
exports.createPool = function createPool(dbConfig)
{
        logger.debug('Creating pool');
        pool = mysql.createPool(dbConfig);
};

exports.connect = function connect(command)
{
        pool.getConnection(     function(err, conn){
                if(!err)
                {
                        conn.on('error', function(err) {
                                logger.error(err); // 'ER_BAD_DB_ERROR'
                        });
                        command(conn);
                }
        });
};
```

I get logs saying:
```
[Sat Jun 02 2018 02:59:52 GMT+0550] [ERROR] app.js - {
        "fatal": true,
        "code": "PROTOCOL_CONNECTION_LOST"
}
```

**Comment by dougwilson** [comment]
If you have a pool connection and you get any error with fatal = true like in your example, the only thing you can do is call .release() on that connection and get a new one using .getConnection

**Comment by yashgt** [comment]
Yes. But I come to know of the fatal only in the 'error' event. Even if I release the connection, how do I give a new connection to the calling program?

**Comment by dougwilson** [comment]
You should also see the error in the callback to anything you do on the connection like .query()

**Comment by dougwilson** [comment]
Right, once there is a fatal error, the connection is useless (your particular error is that the TCP connection is closed). You jave to call .getConnection() to get a new, good connection and then call the .query() on that new connection.

The tickCallback is something from Node.js core. I don't know the details on it, but you could always also on their issue tracker to understand it better.
