### ISSUE TITLE
Misleading information on README.md

### ISSUE THREAD

**Issue by srcspider** [mysqljs/mysql#2040]
In https://github.com/mysqljs/mysql#introduction the example uses connection.end which is deprecated. 

In https://github.com/mysqljs/mysql#establishing-connections the connection is established from a pool but not released. This is very dangerous. Many libraries dealing with database will do not require this explicit release of connections but this library does. In addition if the pool has 100 connections then it won't be immediately obvious why it's failed and there won't even be any timeout warning or anything, requests will just timeout from async workloads with not particular error thrown out from anywhere since the system would just wait for the never-to-be-released connections.

In https://github.com/mysqljs/mysql#terminating-connections there is the suggestion for the end method again; it also suggests using a callback. The end method, besides being deprecated, from looking at the code doesn't even have a callback.

**Comment by dougwilson** [comment]
None of what you said is accurate. Connection (when it is a non pooled connection) has a .end with a callback that is not deprectaed. Only connection.end on a pooled connection is deprecated. Also the section doesn't create a pool, it created a non pooled connection so there is no where to release.
