### ISSUE TITLE
Why do you return this result?

### ISSUE THREAD

**Issue by xuya227939** [mysqljs/mysql#2041]
```
var mysql = require('mysql')
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'dbuser',
  password : 's3kreee7',
  database : 'my_db'
});

connection.connect()

connection.query('SELECT likes as likes FROM user WHERE userName = "Thomas"', function (err, rows, fields) {
  if (err) throw err

  console.log('The solution is: ', rows[0].solution)
})

connection.end()
```

I copied from the official website example and found that the output is [ RowDataPacket { likes: '1' } ],why not is rows[0].likes ???

local mysql  5.7.22
npm mysql 2.15.0

**Comment by dougwilson** [comment]
I seem to be getting something different running the code you provided:
```
The solution is: undefined
```

Can you double-check that that is the exact code you're running and provide the DDL and data to load to be sure I'm running exactly the same thing and seeing the same thing to look into what is going on? Thanks!

**Comment by xuya227939** [comment]
I just give an example, my actual code is written like this  

```
const mysql = require('mysql');
mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: 'xuya227939',
  port: 3306,
  database: 'sight',
  multipleStatements: true
});
mysql.connect();
mysql.query('SELECT likes as likes FROM user WHERE userName = "Thomas" ', function(err, row, fields) {
  console.log(row);
});
mysql.end();
```
The result I expect to get is  row[0].likes  but returned to me [ RowDataPacket { likes: '1' } ]

**Comment by dougwilson** [comment]
Ah, gotcha. Yes, that's is just now Node.js's `console.log` output is. `[` for opening array, `RowDataPacket` is the name of the object class, `{` is new object`, `likes` is key in the object`, `'1'` is a string the value of one.

**Comment by xuya227939** [comment]
ok, It's my problem
