### ISSUE TITLE
Bulk inserts not functioning correctly?

### ISSUE THREAD

**Issue by Renari** [mysqljs/mysql#2042]
```js
const mysql = require('mysql');

const insertValues = [
  [
    'value 1.1',
    'value 2.1',
    'value 3.1',
  ],
  [
    'value 1.2',
    'value 2.2',
    'value 3.2',
  ]
];

let connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'root',
  password : '',
  database : 'test'
});

connection.connect();

connection.query('INSERT INTO `table` (`Column 1`, `Column 2`, `Column 3`) VALUES ?',
  insertValues,
  function (error, results, fields) {
  if (error) throw error;
});

connection.end();
```

The above test case throws an exception saying `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''value 1.1', 'value 2.1', 'value 3.1'' at line 1`.

I have also tried using `VALUES (?,?,?)` which results in a different error of `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?)' at line 1`.

mysql version: 2.15.0

**Comment by dougwilson** [comment]
The second argument to `connection.query` is an array of values, where each element matches a `?` mark. You want `insertValues` to be the replacement for the first question mark, so you need it to be the first element of that array, but you're instead passing `insertValues` as the array itself, making the first element of _that_ the `?` value. See https://github.com/mysqljs/mysql#escaping-query-values . Here is the corrected line:
```js
connection.query('INSERT INTO `table` (`Column 1`, `Column 2`, `Column 3`) VALUES ?',
  [insertValues],
  function (error, results, fields) {
  if (error) throw error;
});
```

**Comment by Renari** [comment]
I was able to get around this by constructing my query like so:
```sql
INSERT INTO `table` (`Column 1`, `Column 2`, `Column 3`) VALUES (?), (?)
```
Although I'm fairly sure inserting arrays like above worked previously.

**Comment by dnutels** [comment]
@dougwilson Unfortunately your suggestion doesn't work. @Renari was enclosing the second parameter in an array from the start.

Basically, for the following query:  `INSERT INTO `table` (`Column 1`, `Column 2`, `Column 3`) VALUES (?)`, none of the following work:

`connection.query(insertStatementAbove, [['a', 'b', 'c'], ['a', 'b', 'c']]...`
`connection.query(insertStatementAbove, [[['a', 'b', 'c'], ['a', 'b', 'c']]]...`

or any amount of nesting (starting from 0, which doesn't work for obvious reasons).
