### ISSUE TITLE
What does the return serverStatus mean when I delete it in bulk? Where was it defined?

### ISSUE THREAD

**Issue by KeepFing** [mysqljs/mysql#2043]
![2w g7tn s klo l8v5tws](https://user-images.githubusercontent.com/28626688/41136402-b1030dae-6b08-11e8-9c91-e0fc0b1f71ac.png)

**Comment by dougwilson** [comment]
It comes from your MySQL server and this module simply presents it to you as-is. Consult the documentation for your specific MySQL server. If you are using the MySQL community edition this is the docs: https://dev.mysql.com/doc/internals/en/status-flags.html
