### ISSUE TITLE
promise resolves with result.insertId = 0

### ISSUE THREAD

**Issue by Sosomqk** [mysqljs/mysql#2045]
I call an insert query and expect an integer > 0.
Instead I get insertId = 0. After querying the db manually, the id is correct?

What possible ways are there to debug this?

I have console logged the returnted result,
checked the db schema and logs, but everything is as expected..

**Comment by MiroslavIsikiyski** [comment]
.

**Comment by dougwilson** [comment]
Not sure. There are no promises in this module.

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by chrise86** [comment]
@Sosomqk did you ever resolve your issue? Facing the same now.

**Comment by Isikiyski** [comment]
@chrise86 I do not. Can't quite remember how and if I fixed it, but try to dump the whole results object and check the id. Also make sure you are always awaiting the returned promise wherever you call the function
