### ISSUE TITLE
Deprecated packages in MySQL

### ISSUE THREAD

**Issue by OmerFlame** [mysqljs/mysql#2050]
Hello community, I am in a major need for help.

I tried to make a Angular 6 project and connect it to a MySQL database. MySQL installed beautifully, but trying to connect to a database gave me an error, about unresolved imports: "crypto", "fs", "tls", "timers", "net" and "stream". Crypto is DEPRECATED for so long! Same with "fs", "timers", "net" and "stream"! So I attempted to install said packages, and they installed successfully. Then I ran into another issue: "fs" and "crypto" didn't have any index.js files, since they were deprecated! They only contained a poor little "package.json" file! So I tried to export the "package.json" file as the package, with "module.exports". I tried, and it somehow didn't show any problems, but then I bumped into ANOTHER PROBLEM, which is what I'm stuck with now: The whole website's components de-rendered. There is nothing on the webpage, and I took a second look the app.component.html file to see if it was empty, and it's NOT!

If you know how to fix the problem, I BEG YOU TO HELP ME! I'm stuck with this issue for a whole month and still no working fix found for the issue.

Thank you for your time,
         Omer Shamai.

**Comment by dougwilson** [comment]
This package is a Node.js module and only works in Node.js not Angular. If you would like to see Angular support, someone will need to add it, as otherwise it will never work. You're welcome to make a pull request to add Angular  6 support!
