### ISSUE TITLE
npm install mysql is giving error

### ISSUE THREAD

**Issue by vivekmodi23** [mysqljs/mysql#2051]
i am trying to run 
`npm install mysql `
command but its giving me

npm ERR! Unexpected end of JSON input while parsing near '....tgz"},"engines":{"no'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-06-15T19_06_00_720Z-debug.log
this error

**Comment by dougwilson** [comment]
Hi @vivekmodi23 this is typically an npm issue on your machine. You can email npm support to get help with how to debug and correct the issue. I tried on my machine and there doesn't seem to be a general issue:
```
$ date
Thu Jun 21 19:41:57 EDT 2018

$ npm install mysql
/tmp/test
└─┬ mysql@2.15.0 
  ├── bignumber.js@4.0.4 
  ├─┬ readable-stream@2.3.3 
  │ ├── core-util-is@1.0.2 
  │ ├── inherits@2.0.3 
  │ ├── isarray@1.0.0 
  │ ├── process-nextick-args@1.0.7 
  │ ├── string_decoder@1.0.3 
  │ └── util-deprecate@1.0.2 
  ├── safe-buffer@5.1.1 
  └── sqlstring@2.3.0 

```
