### ISSUE TITLE
MaxListenersExceededWarning:

### ISSUE THREAD

**Issue by luo200619** [mysqljs/mysql#2052]
(node:5328) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 enqueue listeners added. Use emitter.setMaxListeners() to increase limit

Excuse me, in the process of using mysql, there is a warning that the event exceeds the limit. How can I solve this problem?

**Comment by dougwilson** [comment]
Hi @luo200619 this error is coming from Node.js and it's meaning is that somewhere in your code, you're adding a `'enqueue'` listener over and over again to the same object. The warning gets emitted the 11th time your code adds a listener with the same name to the same object.

The Node.js documentation has some more information about this error as well as tips for how to debug your code to determine where this is happening here: https://nodejs.org/dist/latest-v10.x/docs/api/events.html#events_eventemitter_defaultmaxlisteners

**Comment by luo200619** [comment]
@dougwilson  Thank you for your help. I will modify my code. Thank you again.
