### ISSUE TITLE
BIGINT numbers < Number.MAX_SAFE_INTEGER

### ISSUE THREAD

**Issue by k1ker** [mysqljs/mysql#2054]
I was using bigInt in my tables for dates in numbers (like Date.now()), and mySQL works with it without any problem. Then, I started work with tables, that includes bigger bigInt numbers, like "510150259679379456", so I changed **mysql** settings to: `supportBigNumbers: true,  bigNumberStrings: true`

But now, I getting many errors in my code, like: NaN. 
Is there a way, make all bigInt numbers (strings), wich lower than 16 chars, to integer?

**Comment by dougwilson** [comment]
Don't set bigNumberStrings to true if you want that behavior:

> Enabling supportBigNumbers but leaving bigNumberStrings disabled will return big numbers as String objects only when they cannot be accurately represented with [JavaScript Number objects] (http://ecma262-5.com/ELS5_HTML.htm#Section_8.5) (which happens when they exceed the [-2^53, +2^53] range), otherwise they will be returned as Number objects.
