### ISSUE TITLE
rowdatapacket response is not uniform 

### ISSUE THREAD

**Issue by krishna-kanth** [mysqljs/mysql#2060]
when I changed the select query from 

1. "Select *  from .."  to 
2. "select col_1,col_2 from .." 

format the the "RowDataPacket " object is getting populated with multiple properties with objects.
Also the count on "affectedRows" is 0

Case1: 
results
```
Array(2) [Array(2), OkPacket]
length:2
__proto__:Array(0) [, …]
0:Array(2) [RowDataPacket, RowDataPacket]
   length:2
   __proto__:Array(0) [, …]
   0:RowDataPacket {user_login: Object}
   1:RowDataPacket {user_login: Object}
1:OkPacket {fieldCount: 0, affectedRows: 0, insertId: 0, …}
```
Case 2 :
results
```
Array(2) [Array(2), OkPacket]
length:2
__proto__:Array(0) [, …]
0:Array(2) [RowDataPacket, RowDataPacket]
   length:2
   __proto__:Array(0) [, …]
   0:RowDataPacket {user_login: Object, "": Object}
   1:RowDataPacket {user_login: Object, "": Object}
1:OkPacket {fieldCount: 0, affectedRows: 0, insertId: 0, …}
```

**Comment by dougwilson** [comment]
Hi @krishna-kanth typically the results are exactly what your MySQL server returns. I won't be able to answer why the MySQL server returns different results based on that off-hand (you'd need to ask the MySQL server folks), but I can validate that there isn't an issue with the library. If you can provide all the following, I can take a look:

1. Verison of Node.js
2. Version of this module
3. DDL to create the necessary tables
4. SQL to insert data into the tables to select
5. Complete .js file that will produce the output you have above using the table and data provided

Thanks!

**Comment by dougwilson** [comment]
Closing due to no response.
