### ISSUE TITLE
Is it possible to have a synchronous query and to evaluate the result? thanks

### ISSUE THREAD

**Issue by mzambo** [mysqljs/mysql#2063]

**Comment by dougwilson** [comment]
Node.js need to provide a synchronous network API.

**Comment by dougwilson** [comment]
You'll want to ask on stackoverflow.com :+1: a lot of great amazing people there will work with you to help you out faster than I can.

**Comment by mzambo** [comment]
Yes Doug I did it ,  and I found it  sync-mysql. ...

**Comment by SirPhemmiey** [comment]
@mzambo is that really a permanent solution? Won't it affect the performance of your app?
