### ISSUE TITLE
DeprecationWarning: timers.unenroll()

### ISSUE THREAD

**Issue by isaacdew** [mysqljs/mysql#2068]
When using this package a deprecation warning is issued. The warning says to use clearTimeout instead of timers.unenroll().

**Comment by dougwilson** [comment]
Hi! I noticed this recently too. I just recently got a fix on master hopefully. Can you test it real quick to verify before I release? Just follow the instructions at the bottom of https://github.com/mysqljs/mysql/blob/master/Readme.md#install

**Comment by AssetKid** [comment]
Hello @dougwilson 

It seems the fix is working.

![capture](https://user-images.githubusercontent.com/40426812/42724770-e4df986a-8780-11e8-9cf1-5181caf54d7e.PNG)

The latest GitHub version is not throwing the errors (DEP0095 & DEP0096)

**Comment by isaacdew** [comment]
@dougwilson No longer throwing an error on my end! Thanks!
