### ISSUE TITLE
Cant get to work with react dom replacement

### ISSUE THREAD

**Issue by jonathn6** [mysqljs/mysql#2071]
I have a very basic react application where I do a simple dom element replacement.  I ran npm install mysql.  I have this code in my index.js file:

import React from 'react';
import ReactDOM from 'react-dom';
 
let appTitle_literal = "Title Not Found";
let appDescription_literal = "Description Not Found";

//
// const mysql = require('mysql');
//
//
//   const con = mysql.createConnection({
//    host: 'rds-mysql-wmcw.cgz0te1dlkah.us-east-1.rds.amazonaws.com',
//     user: 'masterUsername',
//     password: 'masterPassword',
//     database : 'db_wmcw'
//   });
const appTitle_element = React.createElement('div', null, appTitle_literal);
const appDescription_element = React.createElement('div', null, appDescription_literal);

ReactDOM.render(appTitle_element, document.getElementById('appTitle'));
ReactDOM.render(appDescription_element, document.getElementById('appDescription'));

When I execute npm start from the command prompt, a browser page opens, and the text of <div id='appTitle'> and <div id='appDescription'> are populated by the ReactDOM.render statments as shown above.

As soon as I activate the code line const mysql = require('mysql');, I get the following errors when rebuilding the bundle.js:
ERROR in ./~/mysql/lib/Connection.js
Module not found: Error: Can't resolve 'net' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib'
 @ ./~/mysql/lib/Connection.js 3:23-37
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./~/mysql/lib/Connection.js
Module not found: Error: Can't resolve 'tls' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib'
 @ ./~/mysql/lib/Connection.js 4:23-37
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./~/mysql/lib/protocol/sequences/Query.js
Module not found: Error: Can't resolve 'fs' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib\protocol\sequences'
 @ ./~/mysql/lib/protocol/sequences/Query.js 6:19-32
 @ ./~/mysql/lib/Connection.js
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

The page in the browser still shows the correct text even after refreshing the page.

Then, when I activate the code which actually creates the connection to the database, I get the same set of errors:

ERROR in ./~/mysql/lib/Connection.js
Module not found: Error: Can't resolve 'net' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib'
 @ ./~/mysql/lib/Connection.js 3:23-37
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./~/mysql/lib/Connection.js
Module not found: Error: Can't resolve 'tls' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib'
 @ ./~/mysql/lib/Connection.js 4:23-37
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

ERROR in ./~/mysql/lib/protocol/sequences/Query.js
Module not found: Error: Can't resolve 'fs' in 'c:\jrs\final_project\forth_attempt\React\node_modules\mysql\lib\protocol\sequences'
 @ ./~/mysql/lib/protocol/sequences/Query.js 6:19-32
 @ ./~/mysql/lib/Connection.js
 @ ./~/mysql/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js
webpack: Failed to compile.

But this time, when I refresh the browser page, the text replacements disappear.

What, in my mind should be a simple process of connecting to a mySql database and replacing the data in the DOM has turned into a 2 day search and destroy missing.

I have attached complete versions of my index.js, index.html, and webpack.config.js files.
[react_app.zip](https://github.com/mysqljs/mysql/files/2216446/react_app.zip)

**Comment by dougwilson** [comment]
This is a Node.js module; it does not work in the web browser (or anything that is not Node.js). If you would like to see support for other environments, you're welcome to make a pull request to add such support!
