### ISSUE TITLE
How to recieve binlog ?

### ISSUE THREAD

**Issue by RifeWang** [mysqljs/mysql#2075]
May I recieve real-time binlog from mysql through this lib and how to do that ?

**Comment by dougwilson** [comment]
This module just implements the mysql text protocol. Myswl does not provide a way to do that over the text protocol.

**Comment by dougwilson** [comment]
This module just implements the mysql text protocol. Myswl does not provide a way to do that over the text protocol.

**Comment by sidorares** [comment]
@RifeWang https://github.com/nevill/zongji extends this driver to add binlog parsing
Also there is binlog support in https://github.com/sidorares/node-mysql2
