### ISSUE TITLE
AWS Lambda "Error: Quit inactivity timeout" fix

### ISSUE THREAD

**Issue by i6mi6** [mysqljs/mysql#2082]
I am here to provide a solution I found while encountering this problem. I am using AWS Lambda connecting to the database and the code used to look like this:

```javascript

const query = (query, values) => new Promise((res, rej) => {
  const connection = mysql.createConnection({
    host: DB_HOST,
    port: DB_PORT,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_DATABASE,
  });
  connection.query(query, values, (error, results, fields) => {
    connection.end()
    if (error) {
      console.log(error);
      rej(error)
    } else {
      res(results, fields)
    }
  });
})
```

When a query is executed `connection.end()` is called in the code above which does not destroy the connection immediately but instead waits (for some reason even if no other connections are established) until it eventually times out (in my case it would timeout every 30-60 seconds). This resulted in the error. The fix is calling `connection.destroy()` instead of `connection.end()`.

Note: Deliberately not using pool because sudden spike in users spin up many lambdas causing pesistent pooling connections to flood the database.

**Comment by dougwilson** [comment]
If you use .destroy your db may lock your account for too many errors. Just place your code in a callback to the .end method as noted in the docs. The .end is not immediate because mysql does a handshake to end the connection gracefully
