### ISSUE TITLE
How to execute a list of SQL commands sequentially?

### ISSUE THREAD

**Issue by Slyke** [mysqljs/mysql#2083]
I'm trying to do something like this:

```
        dbQueries = ['multiple', 'sql', 'statements', 'that', 'need', 'to', 'be', 'executed', 'in', 'order'];
        executedQueries = 0;
        dbConn = mysql.connect();
        maxQueries = dbQueries.length;
        dbQueries.forEach(async (dbQuery)  => {
          console.log("Start");
          return dbConn.query(dbQuery, function(err, results, fields) {
            console.log("Finish");
            if (err) {
              errorList.push({ err, results, fields, dbQuery });
            }
            executedQueries++;

            if (executedQueries >= maxQueries) {
              if (errorList.length > 0) {
                console.log("Error: ", databaseTable.name, "  Errors reported: ", errorList);
              }
              if (typeof(callbackFunc) === 'function') { callbackFunc(errorList, executedQueries); }
            }
          });
        });
```

But what ends up happening is that sometimes queries finish out of order. I know this because I setup the columns, then modify the table by adding in primary keys etc, and it sometimes errors with `Table 'blah.blah' doesn't exist`. The errors change each time. I could see this due to there being multiple `Start`s before seeing multiple `Finish`es. Not sure if I am using async correctly or not.

I do not want to turn on `multipleStatements` if possible.

**Comment by dougwilson** [comment]
The issue is that you need to wait for the callback to run before executing your next query. This is a standard Node.js flow control question unrelated to this module. Asking on Stackoverflow will get you an answer much quicker than here :+1:
