### ISSUE TITLE
Modules not installed on Elastic Beanstalk

### ISSUE THREAD

**Issue by conorot** [mysqljs/mysql#2086]
I'm running a simple project very easily on my localhost. However as soon as I deploy to AWS Elastic Beanstalk, certain files from the mysql package are not installed. Specifically the server throws this error:

`(node:3118) UnhandledPromiseRejectionWarning: Error: Cannot find module './AuthSwitchRequestPacket'`

When I SSH in to the server and look for that file in .\node_modules\mysql\lib\protocol\packets\AuthSwitchRequestPacket.js it does not exist - its almost as if certain files are been ignored when Elastic Beanstalk runs `npm install` as part of the deploy procedure.

I'm using the latest version of the mysql package: 2.16.0 and my package.json looks like this:

```{
  "name": "myApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "body-parser": "^1.18.3",
    "config": "1.26.2",
    "cookie-parser": "~1.4.3",
    "cron": "^1.2.1",
    "debug": "~2.6.3",
    "dotenv": "^4.0.0",
    "ejs": "~2.5.6",
    "express": "^4.16.3",
    "express-myconnection": "^1.0.4",
    "fast-csv": "^2.4.0",
    "format-currency": "^1.0.0",
    "handlebars": "^4.0.11",
    "moment": "^2.19.3",
    "morgan": "^1.9.0",
    "mysql": "^2.16.0",
    "mysql-ssh": "^1.0.6",
    "node-datetime": "~2.0.3",
    "nodemailer": "^4.1.0",
    "nodemailer-smtp-transport": "^2.7.4",
    "pm2": "^3.0.3",
    "promise": "^8.0.1",
    "serve-favicon": "~2.4.2",
    "stylus": "0.54.5"
  }
}
```

When I `ls` the `.\node_modules\mysql\lib\protocol\packets\` directory, only these files have been installed:
```ClientAuthenticationPacket.js  ComStatisticsPacket.js  FieldPacket.js                    OldPasswordPacket.js      UseOldPasswordPacket.js
ComChangeUserPacket.js         EmptyPacket.js          HandshakeInitializationPacket.js  ResultSetHeaderPacket.js
ComPingPacket.js               EofPacket.js            index.js                          RowDataPacket.js
ComQueryPacket.js              ErrorPacket.js          LocalDataFilePacket.js            SSLRequestPacket.js
ComQuitPacket.js               Field.js                OkPacket.js                       StatisticsPacket.js
```

Has anyone come across this before?

**Comment by dougwilson** [comment]
Weird. I also never heard of Elastic Beanstalk until now. I assume that it installs Node.js modules the same way as your own workstation would? Do you know if there is something we need to change or if there is a way we can debug the issue to figure it out?

**Comment by conorot** [comment]
Hey @dougwilson - So Elastic Beanstalk takes the package.json and runs `npm install` when its spinning up the server/s so it should be identical to running it on any apache/ nginx/ local server.

I'm a bit stumped on this still to be honest and was hoping someone else had experienced the issue too. What seems strange to me is that when I view the files in my IDE, the problematic files are greyed out - in the same way that I would expect gitignored files to be greyed out. I don't have these files singled out in any way in a .gitignore file though and I'm wondering if there's anything in the repo itself that could be ignoring files?

I'll do some more digging and I'm sorry for being vague on this - was hoping this might be something someone has dealt with before.

**Comment by dougwilson** [comment]
Sorry it doesn't looks like anyone else has commented, so maybe you are the only one or the audience here doesn't intersect with beanstalk users, not sure.

As for hour IDE, without knowing the exact conditions in which files are shown greyed out, it would just be speculation. This project does have a gitignore, which you can see here: https://github.com/mysqljs/mysql/blob/master/.gitignore

**Comment by conorot** [comment]
Its possible its an incompatibility with EB itself or with Amazon's base AMI. I'm going to close this off for the moment until I find a solution or another user reports the same.

Thanks!

**Comment by sidewapboss** [comment]
I am having similar issue with Nodejs, it keeps telling me it can't find module dotenv even though I installed it as devDependency
