### ISSUE TITLE
charset=utf8mb4 don't work

### ISSUE THREAD

**Issue by czd890** [mysqljs/mysql#2089]
mysql nodejs version:2.16.0

var connection = mysql.createConnection("****?charset=utf8mb4");

connection.query("show variables like '%char%';", (err, result, fields) => {
        for (let index = 0; index < result.length; index++) {
            const element = result[index];
            console.log(`${element.Variable_name}=${element.Value}`)

        }
    })

output :

character_set_client=utf8
character_set_connection=utf8
character_set_database=utf8mb4
character_set_filesystem=binary
character_set_results=utf8
character_set_server=utf8
character_set_system=utf8
character_sets_dir=/usr/share/mysql/charsets/

connection.query("set names utf8mb4")
//output 

character_set_client=utf8mb4
character_set_connection=utf8mb4
character_set_database=utf8mb4
character_set_filesystem=binary
character_set_results=utf8mb4
character_set_server=utf8
character_set_system=utf8
character_sets_dir=/usr/share/mysql/charsets/

**Comment by ruiquelhas** [comment]
Are you sure the connection string is correctly formatted (no duplicate query string fragments, etc.)? Any specific MySQL version you are using (maybe 8.0, since `character_set_server=utf8`)? Are you sure you are not overriding the server charset configuration? I'm not able to reproduce with the latest 5.7 or 8.0 versions (using the default configuration).

```js
var mysql = require('mysql');
var connection = mysql.createConnection('mysql://<user>:<password>@<host>/?charset=utf8mb4');

connection.query("show variables like '%char%';", (err, result, fields) => {
  for (let index = 0; index < result.length; index++) {
    var element = result[index];
    console.log(`${element.Variable_name}=${element.Value}`);
  }
});
```

**MySQL 5.7**
```
character_set_client=utf8mb4
character_set_connection=utf8mb4
character_set_database=latin1
character_set_filesystem=binary
character_set_results=utf8mb4
character_set_server=latin1
character_set_system=utf8
```

**MySQL 8.0**
```
character_set_client=utf8mb4
character_set_connection=utf8mb4
character_set_database=utf8mb4
character_set_filesystem=binary
character_set_results=utf8mb4
character_set_server=utf8mb4
character_set_system=utf8
```

**Comment by czd890** [comment]
mysql version : 5.7.19;

my.cnf 
[mysqld]
......
pid-file=/var/run/mysqld/mysqld.pid
character_set_server=utf8
init_connect='set names utf8'

**Comment by czd890** [comment]
hi，@ruiquelhas
confirm that the connection string is ok
mysql default config  installed，Is it because "init_connect='set names utf8'"?
my mysql server info：
mysql version : 5.7.19;

my.cnf
[mysqld]
......
pid-file=/var/run/mysqld/mysqld.pid
character_set_server=utf8
init_connect='set names utf8'

**Comment by ruiquelhas** [comment]
Right. With that configuration, seems like you are getting the expected values for the [charset-related](https://dev.mysql.com/doc/refman/5.7/en/charset-connection.html) session system variables. So, it does not look like an issue to me.

> SET NAMES indicates what character set the client will use to send SQL statements to the server. Thus, SET NAMES 'cp1251' tells the server, “future incoming messages from this client are in character set cp1251.

`init_connect='set names utf8'` seems to override the client choice, so you will probably have to either remove that and leave the job for the client or maybe update it to `init_connect='set names utf8mb4'`.

**Comment by czd890** [comment]
@ruiquelhas thx!

after the test server deletes "init_connect='set names utf8'"
//output
character_set_client=utf8mb4
character_set_connection=utf8mb4
character_set_database=utf8mb4
character_set_filesystem=binary
character_set_results=utf8mb4
character_set_server=utf8
character_set_system=utf8
character_sets_dir=/usr/share/mysql/charsets/

prod server cannot be restarted，so，execute "query('set names utf8mb4')" once after "getconnection"
