### ISSUE TITLE
Unhandled 'error' event with connections

### ISSUE THREAD

**Issue by Steague** [mysqljs/mysql#2096]
Probably related to #2049 

Error:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (/Users/steagu/src/parc-aprmds-warm-storage-api/node_modules/mysql/lib/protocol/Protocol.js:113:13)
    at Socket.<anonymous> (/Users/steagu/src/parc-aprmds-warm-storage-api/node_modules/mysql/lib/Connection.js:109:28)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

Versions:
```
$ npm -v connect-mysql
6.1.0
$ node -v
v8.11.2
$ npm -v mysql
6.1.0
```

The error occurs after leaving the app running for many hours and then attempting a new query. The code below is what I am using:

Code:
```
import dotenv from 'dotenv';
import mysql from 'mysql';

dotenv.config();

let _instance = null;

export default class Mysql {
    constructor() {
        if (!_instance) {
            _instance = this;
        }

        this._type = 'DB';
        this._conn = mysql.createConnection({
            host     : process.env.MYSQL_HOST,
            user     : process.env.MYSQL_USER,
            password : process.env.MYSQL_PASSWORD,
            database : process.env.MYSQL_DATABASE
        });

        return _instance;
    }

    get type() {
        return this._type;
    }

    set type(value) {
        this._type = value;
    }

    async query(sql, arr = []) {
        return await new Promise((resolve, reject) => {
            this._conn.config.queryFormat = (query, values) => {
                if (!values) return query;
                return query.replace(/:(\w+)/g, (txt, key) => {
                    if (values.hasOwnProperty(key)) {
                        return mysql.escape(values[key]);
                    }
                    return txt;
                });
            };

            this._conn.query(sql, arr, (err, results, fields) => {
                if (err) {
                    reject(err);
                    return;
                }

                resolve({
                    results,
                    fields
                });
            });
        });
    }
}

```

**Comment by Steague** [comment]
I have added your suggested code. I will need to wait some hours to see if the error is caught. Thank you in advance!

**Comment by dougwilson** [comment]
No problem! Let me know. I'll keep this open to hear back.

**Comment by Steague** [comment]
So the error as reported is gone. but now a different functionality is happening.

1. After a long period of inactivity. (As well as running the node server off my local laptop which I close and then reopen in the morning)
2. I attempt an action that triggers a query that, after 30 seconds, results in an `Error: read ETIMEDOUT`
3. I attempt the same action and get a different error: `Error: Cannot enqueue Query after fatal error.`

At this point I have to restart my node service to be able to establish a new connection to mysql.

How can I get the app back into a safe state?

**Comment by dougwilson** [comment]
So when you close your laptop the tcp connection is severed which is why that happens. You have to create a new connection when that happens.

**Comment by Steague** [comment]
@dougwilson good to know. Are there any hooks to determine the state of the tcp connection within the mysql package ( did look at the documentation but am not seeing anything sticking out to me)?

**Comment by dougwilson** [comment]
So Node.js doesn't really provide any hooks for us to expose. That's why you noticed that it sat there until a timeout just to know the connection is bad. If you know of a way to check this in Node.js sockets, I'd love to add it!

**Comment by Steague** [comment]
In that case, I will just catch the error message directly and attempt to reopen/connect -> retry the query. Thank you for your help. This issue can be closed.

**Comment by neoadventist** [comment]
@Steague did that work? I have the same error and am interested in a good solution.
