### ISSUE TITLE
Stop Node MySql From Converting JSON Formatted String Into Query Format

### ISSUE THREAD

**Issue by koder217** [mysqljs/mysql#2097]
I am trying to update a JSON stringified string in my table. Schema is as follows:

```
user_id : VARCHAR(50)
name : VARCHAR(50)
preferences: MEDIUMTEXT
```
Desired record:

```
user_id | name | preferences
------------------------------
44566 | Bob | {"color": "red", "band": "Red hot chilli peppers"} 
```
From my express app, I run the following query:

```
mysql.query("UPDATE users_prefs SET preferences = ?, name = ? 
WHERE user_id = ?",[JSON.stringify({color:'red', band:'Red hot chilli peppers'}), 
"Bob", "44566"]);
```
When I run the above statement, The following query is run instead:

`UPDATE users_prefs SET preferences = `color`='red', `band`='Red hot chilli peppers', name = 'Bob' WHERE user_id = '44566'`
Resulting in error.

Note that I am passing JSON.stringified string to node-mysql query function. I am NOT passing an object. Yet, node-mysql is converting a JSON formatted string to a JSON object and into it's own query format.

if i use

`mysql.escape(JSON.stringify({color:'red')...`
Query is generated as expected and desired output is achieved. But I don't understand why I need to escape a string like this ?

The changes I need to make are extensive in my project if I have to do .escape() everywhere since this same code worked in earlier versions of node-mysql.

How do I make sure my JSON.stringified strings are not mutated in node-mysql ?

**Comment by koder217** [comment]
There was a problem in my own code. node-mysql is fine. closing this issue.

**Comment by agarwalkartik** [comment]
> There was a problem in my own code. node-mysql is fine. closing this issue.

I am facing a similiar issue, can you tell me how did you solved this?
