### ISSUE TITLE
Transactions can cause hanging

### ISSUE THREAD

**Issue by jensengar** [mysqljs/mysql#2098]
Most of my application is not using transactions. I recently added one because I need the `for update` functionality in mysql. I have noticed that sometimes the database will hang when doing reads afterwards. This seems to only happen *sometimes*. However, I was able to find something related. If I create a transaction, do some stuff, then commit the transaction (no errors), then later try and drop the table it just hangs until the connection is actually closed. This seems to be repeatable every time. If I remove the transaction and just do my queries independently I don't have any issues. Any advice is welcome.

Using Innodb, mysql 5.7.22, mysqljs 2.13.0

**Comment by dougwilson** [comment]
Definitely sounds like an issue somewhere. Would it be possible to provide some runnable code that reproduces the issue? I'm not even sure where to start.

**Comment by jensengar** [comment]
I'll try and or something together this morning.

On Sep 13, 2018 7:01 AM, "Douglas Wilson" <notifications@github.com> wrote:

Definitely sounds like an issue somewhere. Would it be possible to provide
some runnable code that reproduces the issue? I'm not even sure where to
start.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mysqljs/mysql/issues/2098#issuecomment-420998012>, or mute
the thread

**Comment by jensengar** [comment]
Turns out it was an issue in my own code. I was returning on an edge case without committing the transaction. Sorry for the false alarm.
