### ISSUE TITLE
Prettier for formatting

### ISSUE THREAD

**Issue by kibertoad** [mysqljs/mysql#2100]
Are there any objections to introducing prettier for automatic resolution of all formatting-related inconsistencies?

**Comment by dougwilson** [comment]
As long as it will pretty into the currently defined format and not change to some new format.

**Comment by kibertoad** [comment]
Thanks! I'll give it a shot and try to figure out ruleset that would be consistent with what is currently used.

**Comment by dougwilson** [comment]
I'm going to close this, as I believe I was able to answer your question, though the issue doesn't seem to have gotten anyone else to perform the task. You're welcome to ask more questions / make a pull request still.
