### ISSUE TITLE
Getting ER_ACCESS_DENIED_ERROR in Node but can connect successfully using command line mysql

### ISSUE THREAD

**Issue by Tmp2k** [mysqljs/mysql#2101]
The error I'm getting is:    Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

I get this error using Scotbox VM (https://box.scotch.io/) same error in ScotchBox v3 and v3.5. 

I'm actually using execsql, but this is just a wrapper for mysql. It's being called from a gulp script. This gulp script is fairly complex. Previously everything worked fine on Scotchbox v3, which was running Node v5. Since I've updated to Scotchbox v3.5, this comes with node v8.9, I've also updated all my npm packages and dependencies as they were well out of date. I've since tried the gulp script on scotchbox v3 after manually updating to Node 8.12, but I get the same result.

So I've concluded the issue is not with the VM, it's something to do with the version of node and/or package dependencies. 

Here's what packages I'm using...
```
    "execsql": "0.0.3",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^3.1.0",
    "gulp-bump": "^2.6.1",
    "gulp-clean-css": "^3.9.4",
    "gulp-concat": "^2.6.0",
    "gulp-insert": "^0.5.0",
    "gulp-jshint": "^2.0.0",
    "gulp-livereload": "^3.8.1",
    "gulp-minify-css": "^1.2.1",
    "gulp-notify": "^2.2.0",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^4.0.1",
    "gulp-strip-comments": "^2.4.3",
    "gulp-uglify": "^1.5.1",
    "mysql": "^2.16.0",
    "request": "^2.69.0",
    "run-sequence": "^1.2.2",
    "yargs": "^3.32.0"
```

And here's the relevant bit of my gulpfile...

```js
    var connsettings = {
        host: 'localhost',
        user: 'root',
        password: 'root'
    };

    execsql.config(connsettings)
        .exec(sql,function(err){
            if(err) {
                console.log(err);
                execsql.end();
            } else {
                execsql.execFile(__dirname + '/db/structure.sql', function (err) {
                    if(err) console.log(err);
                    execsql.end();
                });
            }
        });

    });
```
If I enter "mysql -u root -p" into the command line I can connect just fine.  

If I go back to an old version of this file, running on the same VM, but with Node v5 it works fine.

**Comment by TmpR** [comment]
So here's a simpler example...

This works:

``

**Comment by TmpR** [comment]
Here's a simpler example.

So this works...

```
var mysql      = require('mysql');                               
var connection = mysql.createConnection({                        
  host     : 'localhost',                                        
  user     : 'root',                                             
  password : 'root'                                              
});                                                              
                                                                 
connection.connect(function(err) {                               
  if (err) {                                                     
    console.error('error connecting: ' + err.stack);             
    return;                                                      
  }                                                              
                                                                 
  console.log('connected as id ' + connection.threadId);         
});                                                              
```

But this doesnt....

```
    var execsql = require('execsql');

    var connsettings = {
        host: 'localhost',
        user: 'root',
        password: 'root'
    };

    execsql.config(connsettings)
        .exec('select NOW()',function(err){
            if(err) {
                console.log(err);
                execsql.end();
            } else {

            }
        });
```

So it looks like an issue with the execsql wrapper, but I can't see where becasue the code in execsql is the same as the mysql example above that works.

https://github.com/node-fun/execsql/blob/master/index.js

What am I missing here?

**Comment by dougwilson** [comment]
So I see you said that `mysql -u root -p` does work. By default that is likely using a UNIX socket to connect and not TCP. The user you are connecting to is likely setup to only allow UNIX socket connections and not TCP connections. Can you try the following command?
```
mysql -u root -h localhost -p
```

**Comment by dougwilson** [comment]
Closing due to no response.
