### ISSUE TITLE
pool acquireTimeout - doesn't error when waiting 

### ISSUE THREAD

**Issue by thirteen-eleven** [mysqljs/mysql#2105]
Perhaps, I don't understand the intent of acquireTimeout - or it has a bug.  

I can set my pool to a small number (e.g. 2), and invoke (bad) code that does not properly release a connection.  Once, I exhaust the connectionLimit, connections start queuing - but will wait indefinitely regardless of how low I specify the acquireTimeout (e.g. 1000ms).

I can force an error with lowering the queueLimit, or by setting waitForConnections: false, but what I really wanted was to only generate an error when it takes a long time to get a connection from the pool.  

(I did see a[ feature request referring to a maxWait or queueWaitTimeout](https://github.com/mysqljs/mysql/pull/1591) - but a comment said it was the same as acquireTimeout.)

Thanks for any assistance.

**Comment by dougwilson** [comment]
Ah, yea, I think the docs can be improved there -- the acquireTimeout option does not have anything to do with waiting for a checked out connection to be released back to the pool -- there is no timeout option around that case currently.

The acquireTimeout comes with the "acquire" routine internally which basically is the process or either (a) opening a new connection to the server or (b) validating a free connection is still alive.

It sounds like two things from your report:
(a) improve docs around acquireTimeout to better describe what exactly the timeout is around (what I said is just an incomplete summary -- someone needs to validate that is accurate to land in docs)
(b) add a timeout option around requests that are in the queue to wait for a connection to be returned to the pool.

**Comment by thirteen-eleven** [comment]
Thanks for the quick reply, @dougwilson .  

Just confirmed your (a) above in Pool.js lines 42-48:
```
   if (this.config.connectionLimit === 0 || this._allConnections.length < this.config.connectionLimit) {
    connection = new PoolConnection(this, { config: this.config.newConnectionConfig() });

    this._acquiringConnections.push(connection);
    this._allConnections.push(connection);

    connection.connect({timeout: this.config.acquireTimeout}, function onConnect(err) {
```
... as the acquireTimeout only applies when the pool has at least one free connection.


(b) would be nice . 👍

**Comment by devMYC** [comment]
> (b) add a timeout option around requests that are in the queue to wait for a connection to be returned to the pool.

+1 for this
