### ISSUE TITLE
How can I do a while loop and update 400 rows

### ISSUE THREAD

**Issue by mrrovot** [mysqljs/mysql#2109]
HI, 

I have an array and need to update 400 rows each with data[index] from the array, the problem is that when I execute a while loop I get `Error: ER_USER_LIMIT_REACHED`because it seems each call is a new pool connection, is there a way to 400 updates in one pool connection?

my current code is like this:

```
var position = 0;
results.forEach(function(nimi) {
 position++;
 db.query('UPDATE nimipets SET nim_position = ? WHERE ID = ?', [position, nimi.ID], function(error, results, fields) {
    if (error) console.log(error);

        })
   });
```

thanks

**Comment by dougwilson** [comment]
Hard to understand what is causing the issue when no code is posted.

As for the generic answer is just (1) create a connection (mysql.createConnection) and (2) make 400 update queries on that (connection.query) connection.

**Comment by mrrovot** [comment]
@dougwilson updated with code, thanks

**Comment by dougwilson** [comment]
What does db var refer to?

**Comment by mrrovot** [comment]
to this on db.js:
```

var connection = mysql.createPool({
  connectionLimit: 10,
  // waitForConnections: true,
  host     : process.env.DB_HOST,
  user     : process.env.DB_USERNAME,
  password : process.env.DB_PASSWORD,
  database : process.env.DB_NAME,
  port : process.env.DB_PORT,
  timezone: 'utc' ,

});

module.exports = connection;
```

and then

`const db = require('../db.js');
`

**Comment by dougwilson** [comment]
https://stackoverflow.com/questions/39150633/has-exceeded-the-max-user-connections-resource
