### ISSUE TITLE
mysql-node is escaping double quote unnecessarily

### ISSUE THREAD

**Issue by Nixtis** [mysqljs/mysql#2111]
Hello,

When I'm trying to insert a line in a column with a string value that contents double quotes, I have backslashes in it, having this code :

```javascript
const connection = mysql.createConnection(...)
const values = [
  'article',
  'title',
  'content',
  'My title',
  'This is the content of my article and I "love it"',
]

connection.query('INSERT INTO ?? (??) VALUES (?)', values)
```

The query given by `mysql-node` look like this:
`INSERT INTO article (title, content) VALUES ('My title', 'This is the content of my article and I \"love it\"'`
As you see the values are wrapped by a single quote so it doesn't need to backslash the double quotes

And when I fetch I get :

- title: My title
- content: This is the content of my article and I \\"love it\\"

I've a MySQL 5.7.23 server on a AWS RDS

Thank you

**Comment by dougwilson** [comment]
Can you show the code you are using to fetch? I just tried that query as you wrote and looking in the database directly there are no backslashes. Do you see the backslahes in the database column using other tools?

**Comment by Nixtis** [comment]
Hello !

Yes I see Backslashes in the data base using Workbench. There is a weird thing, in my local Database (same version) there is no backslashes =/ Do you think that there is a configuration problem ?

**Comment by dougwilson** [comment]
It's possible. What is your sql mode set to in the one that has backslashes?

**Comment by Nixtis** [comment]
the actual sql_mode value is : NO_ENGINE_SUBSTITUTION

**Comment by dougwilson** [comment]
Strange, I'm not sure. What else is different? Is the one that works the mysql community edition and the one that doesn't work the aws rds one?

**Comment by dougwilson** [comment]
I'm not sure the issue, and have nothing to debug locally. I'm going to close this as stale since there isn't a way I can move it forward. If you have any ideas of what is causing the issue, let me know here and I can always reopen.
