### ISSUE TITLE
Can't decrypt password

### ISSUE THREAD

**Issue by FrAgOrDiE02** [mysqljs/mysql#2117]
Hi everyone, I made this code but it doesn't work:

var mysql = require('mysql');
var con = mysql.createConnection({
    host: "localhost",
    user: "csitabot",
    password: "password",
    database: "csitabot"
});

var sql = "select aes_decrypt(password, 'mypass') as password FROM utenti WHERE id = 7;";
con.query(sql, function (err, malcry){

console.log(malcry[0].password);

});

I receive this as output: 

<Buffer 63 69 61 6f>

And I need the decrypted password, how can I do?

**Comment by FrAgOrDiE02** [comment]
The same code works in the mysql command line!

**Comment by dougwilson** [comment]
So it looks like the protocol is returning the type of that column as a binary value. Binary values are represented in Node.js as Buffer objects which output like you saw in the console.log function. You can see it's value as a string by using .toString()

console.log(malcry[0].password.toString());

If you cast it as a string in your SQL as well so Mysql protocol doesn't pass it as binary then you won't have to toString in Node.js.

I hope that helps.
