### ISSUE TITLE
Can't retrieve from OkPacket the insertId that is Varchar Type

### ISSUE THREAD

**Issue by celtaheaven** [mysqljs/mysql#2119]
Basically, im using this query: 

`this._connection.query('INSERT INTO Aluno SET ? ON DUPLICATE KEY UPDATE ?', args, callback)`

which works, either for insert case and update, but, i can't ever retrieve the insertID that is an VARCHAR, it always comes like this:

> OkPacket {
> fieldCount: 0,
> affectedRows: 1,
> insertId: 0,
> serverStatus: 34,
> warningCount: 0,
> message: '',
> protocol41: true,
> changedRows: 0 }

There is any kind of support to solve this problem? Thank you a lot.
PS.: `supportBigNumbers` and `bigNumberStrings` are already on.

**Comment by dougwilson** [comment]
The mysql protocol does not support that. If you know otherwise, please open a pull request or provide a pcap of your traffic where is is coming back and point out where that data is located and we can reopen.
