### ISSUE TITLE
MySQL Version:AsText() is deprecated as of MySQL 5.7.6 and will be removed in a future MySQL release.

### ISSUE THREAD

**Issue by pujianjun** [mysqljs/mysql#2127]
I use mysql server version 8.0.12 ,  typeorm/mysql and mysqljs v2.16.0，my nodejs application throws an exception  that ER_SP_DOES_NOT_EXIST: FUNCTION AsText does not exist. If I insist on using  8.0.12, how to use ST_AsText() instead of AsText() ? thx.

**Comment by dougwilson** [comment]
Closing due to no response.

**Comment by kaznovac** [comment]
@pujianjun i used "legacySpatialSupport": false and it worked in typeorm
