### ISSUE TITLE
how can i connect with mariadb? is it supported?

### ISSUE THREAD

**Issue by Cariaga** [mysqljs/mysql#2135]
`const pool = mysql.createPool({
  host:process.env.MARIADB_SERVICE_HOST|| 'localhost',
  user: 'user',
  password: 'user',
  database: 'sampledb',
  waitForConnections: true,
  port: process.env.MARIADB_SERVICE_PORT||3306,
  connectionLimit: 160,
  //queueLimit: 0,
});
`

**Comment by dougwilson** [comment]
Yep, MariaDB is supported. We even test against it in CI https://github.com/mysqljs/mysql/blob/master/.travis.yml#L30-L39
