### ISSUE TITLE
fs dependency was not found

### ISSUE THREAD

**Issue by patrioticcow** [mysqljs/mysql#2141]
Hello,

I am using 

    "fs": "0.0.1-security",
    "mysql": "^2.16.0",

and I get

    This dependency was not found:
    * fs in ./node_modules/mysql/lib/protocol/sequences/Query.js 
    To install it, you can run: npm install --save fs 

MySql connects just fine. I get `Connected!` from the code below. 
Any ideas?

Here's my NuxtJs plugin

```
import Vue from 'vue'
import mysql from 'mysql'

const con = mysql.createConnection({
  host: '...',
  user: '...',
  password: '...',
  database: '...'
})

con.connect(function (err) {
  if (err) throw err
  console.log('Connected!')
})

Vue.prototype.$mysql = () => con
```

**Comment by dougwilson** [comment]
This module uses the `fs` that is part of Node.js core: https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_file_system so there is no dependency to install; it's just there in Node.js.
