### ISSUE TITLE
ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by henaege** [mysqljs/mysql#2142]
Hello,

I have a node app that uses a mysql database (Server version: 5.7.24-0ubuntu0.16.04.1 (Ubuntu)). It used to work fine but just recently I get the ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO) error when running the app. I see afew other similar issues reported but they don't seem to be the same.

Here is my javascript:
```javascript
function handleDisconnect() {
    var connection = mysql.createConnection({
        host: 'localhost',
        user: 'x',
        password: 'password',
        database: 'database_name'
}) 

connection.connect(function(err) {              
    if(err) {                                     
      console.log('error when connecting to db:', err);
      setTimeout(handleDisconnect, 2000);
    }                                     
  });                                     
                                         
  connection.on('error', function(err) {
    console.log('db error', err);
    if(err.code === 'PROTOCOL_CONNECTION_LOST') { 
      handleDisconnect();                         
    } else {                                      
      throw err;                                  
    }
  });
}
```

I can log in to the mysql server just fine on CLI. The issue appears to be that for whatever reason the user name and password aren't being used by mysql (Access denied for user ''@'localhost' (using password: NO)) even though they are specified above. I don't have an anonymous ('') user listed, which I think would cause the ''@'localhost' if that were the case?
```
mysql> select user, host from mysql.user;
+------------------+-----------+
| user             | host      |
+------------------+-----------+
| debian-sys-maint | localhost |
| mysql.session    | localhost |
| mysql.sys        | localhost |
| root             | localhost |
| x                | localhost |
+------------------+-----------+
5 rows in set (0.00 sec)
```
So why is mysql apparently looking for an anonymous user and not recognizing the password parameter? Please let me know what additional information you may need. Thanks!

**Comment by dougwilson** [comment]
Hi @henaege that is very strange. I just did a quick test with the same MySQL server and didn't have the issue. It's possible there are more variables between our cases, though. Can you provide the following to start?

1. Version of this module you're using
2. Version of Node.js running on
3. If you can add `debug: true` to your connection options and paste the output of the failed login here

See https://github.com/mysqljs/mysql#debugging-and-reporting-problems for more help on what we need to help you 👍

**Comment by dougwilson** [comment]
Hi @henaege thanks for this information. That is indeed the correct output. I only see successful authentications in that output, no ` ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)` errors. Can you include the output for when you're getting that error?

As for your error `TypeError: Cannot read property 'host' of undefined`, that occurs when your code is calling `.createConnection(options)` where `options === undefined`.

Is is possible to share your full code on here so I can better assist? I'm not sure what is going on more than that without seeing the code and actually being able to reproduce the issue and look at it through a debugger.

**Comment by henaege** [comment]
Hi @dougwilson,

The output that includes the error message is in the [pm2](http://pm2.keymetrics.io/) logs, which I have attached the log file here. [app-out-0.log](https://github.com/mysqljs/mysql/files/2638070/app-out-0.log)

The repository for the project can be found [here](https://github.com/henaege/game-on-project).

The entry point for the app is /app.js. The database connection is created in /routes/index.js. Sorry the code is a mess right now, I've been working on it trying to get it running. I think those are the main 2 things you'll need to access to run the app and troubleshoot but if you have questions about where anything else is please let me know.

Thanks!

**Comment by dougwilson** [comment]
Thank you @henaege . Is it possible you can please update that repo to be the exact same code that produced that log file? Or if you can re-produce that log file with the repo that is up there? The line numbers in there don't match up with the repo you provided and it's difficult to understand what is going on exactly in your code that is causing the issue, and I don't have confidence the repo is actually the same code when the line numbers do not line up.

**Comment by henaege** [comment]
Hi @dougwilson,

I started the app using the same version of the code that is in the repo to generate new log files. I previously had to trim the log file because it was too large to upload; that's probably why the lines don't match. I also added the app error file; that is where I'm seeing ```TypeError: Cannot read property 'host' of undefined```. Ideally that does what you need: 

[app-error-0.log](https://github.com/mysqljs/mysql/files/2642393/app-error-0.log)
[app-out-0.log](https://github.com/mysqljs/mysql/files/2642395/app-out-0.log)

If not, would you be able to show me exactly what you're looking at/for so I can get the data you need?

I also created [a new branch](https://github.com/henaege/game-on-project/tree/original) that contains the original code that used to work but now does not. It's how the code was before I started changing things (specifically /routes/index.js).  I think you would need the config file before you'd be able to use it; what would be the best way to send that directly to you if you need it?

Thanks

**Comment by Ruudii8** [comment]
Hi,
I'm facing the same problem. Code is copied from your readme, I just changed the username, database name and query.

Version of mysql - module: 2.16.0

**Comment by kai-koch** [comment]
´´´var serverInfo = require('../config/config')´´´

The required file is not include in the repo. (Of course it is not! And for a good reason! ;-))

Please, double check, if it contains the right credentials and if they are exports as your app expects them to be exported. (Did you change the case of the variable names at one point?) Maybe include a config.sample with dumy values for inspecting the structure of the exports.

Although the line-numbers do not match in the error-log, the logs show "no user" and "no password" (possibly "no host" too, but that might default to 'localhost', when undefined).

My money is on the above require().

**Comment by Roncarlos** [comment]
I have the same problem when I don't use a password. 
When I add a password, it recognizes my user (But of course it won't connect since my db account don't have password).

Im using:
- Nodejs 12.16.1 (LTS)
- Mysql module 12.16.1
- I'm using MariaDB 10.4.12 (It previously worked with 10.3 mariadb)

* Without password
```js
Error: ER_DBACCESS_DENIED_ERROR: Access denied for user ''@'localhost' to database 'discord_bot_rpg'
    at Handshake.Sequence._packetToError (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    --------------------
    at Protocol._enqueue (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:116:18)
    at Connection._implyConnect (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:454:10)
    at Connection.query (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:196:8)
    at internal/util.js:286:30
    at new Promise (<anonymous>)
    at Connection.query (internal/util.js:285:12)
    at Object.query (D:\discordbotrpg-discord\conf\mysql.js:13:34)
    at ModuleHandler.loadPrefixes (D:\discordbotrpg-discord\src\Modules\ModuleHandler.js:270:14) {
  code: 'ER_DBACCESS_DENIED_ERROR',
  errno: 1044,
  sqlMessage: "Access denied for user ''@'localhost' to database 'discord_bot_rpg'",
  sqlState: '42000',
  fatal: true
}

<-- HandshakeInitializationPacket {
  protocolVersion: 10,
  serverVersion: '5.5.5-10.4.12-MariaDB',
  threadId: 59,
  scrambleBuff1: <Buffer 43 40 55 69 34 65 22 73>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63486,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 33279,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 07 00 00 00>,
  scrambleBuff2: <Buffer 40 27 3f 46 26 26 2e 54 3d 72 49 53>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true
}

--> (59) ClientAuthenticationPacket {
  clientFlags: 521167,
  maxPacketSize: 0,
  charsetNumber: 224,
  filler: undefined,
  user: 'discord_bot_rpg',
  scrambleBuff: <Buffer >,
  database: 'discord_bot_rpg',
  protocol41: true
}

<-- (59) ErrorPacket {
  fieldCount: 255,
  errno: 1044,
  sqlStateMarker: '#',
  sqlState: '42000',
  message: "Access denied for user ''@'localhost' to database 'discord_bot_rpg'"
}

Connection {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  config: ConnectionConfig {
    host: 'localhost',
    port: 3306,
    localAddress: undefined,
    socketPath: undefined,
    user: 'discord_bot_rpg',
    password: undefined,
    database: 'discord_bot_rpg',
    connectTimeout: 10000,
    insecureAuth: false,
    supportBigNumbers: false,
    bigNumberStrings: false,
    dateStrings: false,
    debug: undefined,
    trace: true,
    stringifyObjects: false,
    timezone: 'local',
    flags: '',
    queryFormat: undefined,
    pool: undefined,
    ssl: false,
    localInfile: true,
    multipleStatements: true,
    typeCast: true,
    maxPacketSize: 0,
    charsetNumber: 224,
    clientFlags: 521167
  },
  _socket: undefined,
  _protocol: Protocol {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    readable: true,
    writable: true,
    _config: ConnectionConfig {
      host: 'localhost',
      port: 3306,
      localAddress: undefined,
      socketPath: undefined,
      user: 'discord_bot_rpg',
      password: undefined,
      database: 'discord_bot_rpg',
      connectTimeout: 10000,
      insecureAuth: false,
      supportBigNumbers: false,
      bigNumberStrings: false,
      dateStrings: false,
      debug: undefined,
      trace: true,
      stringifyObjects: false,
      timezone: 'local',
      flags: '',
      queryFormat: undefined,
      pool: undefined,
      ssl: false,
      localInfile: true,
      multipleStatements: true,
      typeCast: true,
      maxPacketSize: 0,
      charsetNumber: 224,
      clientFlags: 521167
    },
    _connection: [Circular],
    _callback: null,
    _fatalError: null,
    _quitSequence: null,
    _handshake: false,
    _handshaked: false,
    _ended: false,
    _destroyed: false,
    _queue: [],
    _handshakeInitializationPacket: null,
    _parser: Parser {
      _supportBigNumbers: false,
      _buffer: <Buffer >,
      _nextBuffers: [BufferList],
      _longPacketBuffers: [BufferList],
      _offset: 0,
      _packetEnd: null,
      _packetHeader: null,
      _packetOffset: null,
      _onError: [Function: bound handleParserError],
      _onPacket: [Function: bound ],
      _nextPacketNumber: 0,
      _encoding: 'utf-8',
      _paused: false
    },
    [Symbol(kCapture)]: false
  },
  _connectCalled: false,
  state: 'disconnected',
  threadId: null,
  [Symbol(kCapture)]: false
}
```

* With password everything is fine user is detected
```js
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'discord_bot_rpg'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    --------------------
    at Protocol._enqueue (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (D:\discordbotrpg-discord\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:116:18)
    at Connection._implyConnect (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:454:10)
    at Connection.query (D:\discordbotrpg-discord\node_modules\mysql\lib\Connection.js:196:8)
    at internal/util.js:286:30
    at new Promise (<anonymous>)
    at Connection.query (internal/util.js:285:12)
    at Object.query (D:\discordbotrpg-discord\conf\mysql.js:14:34)
    at ModuleHandler.loadPrefixes (D:\discordbotrpg-discord\src\Modules\ModuleHandler.js:270:14) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'discord_bot_rpg'@'localhost' (using password: YES)",
  sqlState: '28000',
  fatal: true
}

<-- HandshakeInitializationPacket {
  protocolVersion: 10,
  serverVersion: '5.5.5-10.4.12-MariaDB',
  threadId: 60,
  scrambleBuff1: <Buffer 5d 67 6c 6b 52 3c 70 43>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63486,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 33279,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 07 00 00 00>,
  scrambleBuff2: <Buffer 3c 44 22 76 53 79 2c 68 4a 77 3d 64>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true
}

--> (60) ClientAuthenticationPacket {
  clientFlags: 521167,
  maxPacketSize: 0,
  charsetNumber: 224,
  filler: undefined,
  user: 'discord_bot_rpg',
  scrambleBuff: <Buffer 7d 0d ed 2e fb db 05 7b d3 3b 11 66 e8 26 c6 85 8f 44 41 e0>,
  database: 'discord_bot_rpg',
  protocol41: true
}

<-- (60) ErrorPacket {
  fieldCount: 255,
  errno: 1045,
  sqlStateMarker: '#',
  sqlState: '28000',
  message: "Access denied for user 'discord_bot_rpg'@'localhost' (using password: YES)"
}
```

**Comment by deepikasingh3715** [comment]
> Hello,
> 
> I have a node app that uses a mysql database (Server version: 5.7.24-0ubuntu0.16.04.1 (Ubuntu)). It used to work fine but just recently I get the ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO) error when running the app. I see afew other similar issues reported but they don't seem to be the same.
> 
> Here is my javascript:
> 
> ```js
> function handleDisconnect() {
>     var connection = mysql.createConnection({
>         host: 'localhost',
>         user: 'x',
>         password: 'password',
>         database: 'database_name'
> }) 
> 
> connection.connect(function(err) {              
>     if(err) {                                     
>       console.log('error when connecting to db:', err);
>       setTimeout(handleDisconnect, 2000);
>     }                                     
>   });                                     
>                                          
>   connection.on('error', function(err) {
>     console.log('db error', err);
>     if(err.code === 'PROTOCOL_CONNECTION_LOST') { 
>       handleDisconnect();                         
>     } else {                                      
>       throw err;                                  
>     }
>   });
> }
> ```
> 
> I can log in to the mysql server just fine on CLI. The issue appears to be that for whatever reason the user name and password aren't being used by mysql (Access denied for user ''@'localhost' (using password: NO)) even though they are specified above. I don't have an anonymous ('') user listed, which I think would cause the ''@'localhost' if that were the case?
> 
> ```
> mysql> select user, host from mysql.user;
> +------------------+-----------+
> | user             | host      |
> +------------------+-----------+
> | debian-sys-maint | localhost |
> | mysql.session    | localhost |
> | mysql.sys        | localhost |
> | root             | localhost |
> | x                | localhost |
> +------------------+-----------+
> 5 rows in set (0.00 sec)
> ```
> 
> So why is mysql apparently looking for an anonymous user and not recognizing the password parameter? Please let me know what additional information you may need. Thanks!


hi @henaege ,

I also faced the same issue.

In my case, it worked when I used " connection.config "  rather than only using  " connection " because  mysql.createConnection()  returns an object containing one of the key named - config, responsible for holding connection string.

**Comment by VijaykumarBhavanur** [comment]
@deepikasingh3715  Even I'm facing same issue could you please suggest where to add connection.config? or it will be helpful if you attach code snippet.

**Comment by deepikasingh3715** [comment]
> @deepikasingh3715 Even I'm facing same issue could you please suggest where to add connection.config? or it will be helpful if you attach code snippet.

hi @VijaykumarBhavanur 

Let's say for the given code :

var mysqlConnection = mysql.createConnection({
    host: "localhost",
    user:"user",
    password:"password",
    database:"database",
    multipleStatements : true,
    dialect: "mysql",
    pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
});

here mysqlConnection is an object having these properties -

Connection {_events: Object, _eventsCount: 0, _maxListeners: undefined, config: ConnectionConfig, _socket: undefined, …}

So you can retrieve properties of connection string by using : connection.config.password,
 or whatever properties you want to use while configuring it with your choice of ORM. 

For example, if I use sequelize , it should be :

const sequelize = new Sequelize(mysqlConnection.config.database, connection.mysqlConnection.user,connection.config.password, {
  host: mysqlConnection.config.host,
  dialect: mysqlConnection.config.dialect,
  dialect:'mysql',
  pool: {
    max: mysqlConnection.config.pool.max,
    min: mysqlConnection.config.pool.min,
    acquire: mysqlConnection.config.pool.acquire,
    idle: mysqlConnection.config.pool.idle
  }
});


Thanks

**Comment by VijaykumarBhavanur** [comment]
@deepikasingh3715  Thank you for detailed solution.

**Comment by TayyabNaveed** [comment]
> > Hello,
> > I have a node app that uses a mysql database (Server version: 5.7.24-0ubuntu0.16.04.1 (Ubuntu)). It used to work fine but just recently I get the ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO) error when running the app. I see afew other similar issues reported but they don't seem to be the same.
> > Here is my javascript:
> > ```js
> > function handleDisconnect() {
> >     var connection = mysql.createConnection({
> >         host: 'localhost',
> >         user: 'x',
> >         password: 'password',
> >         database: 'database_name'
> > }) 
> > 
> > connection.connect(function(err) {              
> >     if(err) {                                     
> >       console.log('error when connecting to db:', err);
> >       setTimeout(handleDisconnect, 2000);
> >     }                                     
> >   });                                     
> >                                          
> >   connection.on('error', function(err) {
> >     console.log('db error', err);
> >     if(err.code === 'PROTOCOL_CONNECTION_LOST') { 
> >       handleDisconnect();                         
> >     } else {                                      
> >       throw err;                                  
> >     }
> >   });
> > }
> > ```
> > 
> > 
> > I can log in to the mysql server just fine on CLI. The issue appears to be that for whatever reason the user name and password aren't being used by mysql (Access denied for user ''@'localhost' (using password: NO)) even though they are specified above. I don't have an anonymous ('') user listed, which I think would cause the ''@'localhost' if that were the case?
> > ```
> > mysql> select user, host from mysql.user;
> > +------------------+-----------+
> > | user             | host      |
> > +------------------+-----------+
> > | debian-sys-maint | localhost |
> > | mysql.session    | localhost |
> > | mysql.sys        | localhost |
> > | root             | localhost |
> > | x                | localhost |
> > +------------------+-----------+
> > 5 rows in set (0.00 sec)
> > ```
> > 
> > 
> > So why is mysql apparently looking for an anonymous user and not recognizing the password parameter? Please let me know what additional information you may need. Thanks!
> 
> hi @henaege ,
> 
> I also faced the same issue.
> 
> In my case, it worked when I used " connection.config " rather than only using " connection " because mysql.createConnection() returns an object containing one of the key named - config, responsible for holding connection string.

Can you please Provide the code.

**Comment by TayyabNaveed** [comment]
> > @deepikasingh3715 Even I'm facing same issue could you please suggest where to add connection.config? or it will be helpful if you attach code snippet.
> 
> hi @VijaykumarBhavanur
> 
> Let's say for the given code :
> 
> var mysqlConnection = mysql.createConnection({
> host: "localhost",
> user:"user",
> password:"password",
> database:"database",
> multipleStatements : true,
> dialect: "mysql",
> pool: {
> max: 5,
> min: 0,
> acquire: 30000,
> idle: 10000
> }
> });
> 
> here mysqlConnection is an object having these properties -
> 
> Connection {_events: Object, _eventsCount: 0, _maxListeners: undefined, config: ConnectionConfig, _socket: undefined, …}
> 
> So you can retrieve properties of connection string by using : connection.config.password,
> or whatever properties you want to use while configuring it with your choice of ORM.
> 
> For example, if I use sequelize , it should be :
> 
> const sequelize = new Sequelize(mysqlConnection.config.database, connection.mysqlConnection.user,connection.config.password, {
> host: mysqlConnection.config.host,
> dialect: mysqlConnection.config.dialect,
> dialect:'mysql',
> pool: {
> max: mysqlConnection.config.pool.max,
> min: mysqlConnection.config.pool.min,
> acquire: mysqlConnection.config.pool.acquire,
> idle: mysqlConnection.config.pool.idle
> }
> });
> 
> Thanks

@deepikasingh3715  I am having the same problem but how to use connection.config without sequelize and with just mysql driver?

**Comment by BenRacicot** [comment]
Hi, has anyone found any direct causes for this? I'm on Google Cloud SQL instance and am getting this error consistently.

App server error
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'recruiter'@'69.9.50.185' (using password: YES)

MySQL Workbench Error
Failed to Connect to MySQL at 30.231.190.19:3306 with user ben
Access denied for user 'ben'@'69.9.50.185' (using password: YES)

Terminal
https://cloud.google.com/sql/docs/mysql/connect-admin-ip
mysql --host=30.231.190.19 --user=ben --password
ERROR 1045 (28000): Access denied for user 'recruiter'@'69.9.50.185' (using password: YES)

May specific example may be a GCP issue however the MySQL error matches directly and WAS working then stopped abruptly without any intervention.

**Comment by dougwilson** [comment]
Hello everyone, I understand this thread is long, but this issue is not resolvable or has been shown to be caused my this module specifically. The error mesaage you are seeing is being generated by the MySQL server itself as part of authentication and not by this module. If you are having trouble connecting from this client or another, please work though the excellent troubleshooting steps the MySQL server documentation has: https://dev.mysql.com/doc/refman/5.7/en/problems-connecting.html
