### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by QinZonger** [mysqljs/mysql#2143]
When I input  'mysql -u root -p' .
I was prompted to enter the password, but the password I was sure was correct, and it still made this mistake.

**Comment by QinZonger** [comment]
The problem has been solved.
This method is ：https://stackoverflow.com/questions/18339513/access-denied-for-user-root-mysql-on-mac-os

**Comment by dougwilson** [comment]
Hi @QinZonger it seems you may have posted to the wrong place. This is a Node.js driver for MySQL, not the `mysql` command line program. Sorry for the confusion.
