### ISSUE TITLE
How to use typeCast when using a connection string?

### ISSUE THREAD

**Issue by maximedupre** [mysqljs/mysql#2147]
Is it even possible?

For example

    var connection = mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');

How do I add the typeCast param? With a connection option, I would do like that:

	 mysql.createConnection({
		host: '127.0.0.1',
		user: 'root',
		password: 'sdf23rf-g',
		database: 'test',
		typeCast: (field, next) => {
	            if (field.type === 'DATE') {
		        return field.string();
	            }
 
	            return next();
            }
	})

**Comment by dougwilson** [comment]
What value are you trying to set it to? You can set it to true or false in the string by adding it as a query parameter like you have debug in your example.

**Comment by maximedupre** [comment]
@dougwilson Thanks for the quick reply. I edited my question, I would like to use a function instead.

**Comment by dougwilson** [comment]
Gotcha. There really is no good way to represent code in a connection string, especially with security concerns. Code as a value in the string is not supported.

**Comment by maximedupre** [comment]
Oh ok, I thought maybe there was a way to pass a connection string and an option object, e.g.

    var connString = 'mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700'
    var connection = mysql.createConnection(connString, {typeCast: () => {...}});

I guess I will just extract values from my connection string and build a connection object then. Thanks :)

**Comment by dougwilson** [comment]
No problem. Also for your example (assuming that us what you want), you can use the dateStrings option instead of typeCast to get the same result. That can be in the connection string. Example:

   mysql://user:pass@host/db?debug=true&dateStrings=["DATE"]

**Comment by maximedupre** [comment]
Oh! Perfect. That is what I want. Cheers!
