### ISSUE TITLE
Pool connection end?

### ISSUE THREAD

**Issue by AmitMY** [mysqljs/mysql#2151]
I am using mysqljs with a distributed platform (cloud functions), and it seems like if I run many functions in parallel, that I run out of connections. This can only happen if a single function hogs the connection and doesn't close it.

I thought of doing the following after the function finishes:
```js
this.db.getConnection((err, connection) => {
      if (!err) { // If is connected
        connection.end();
      }
    });
```

But this results in the following error:
> Calling conn.end() to release a pooled connection is deprecated. In next version calling conn.end() will be restored to default conn.end() behavior. Use conn.release() instead. 

From my understanding, `conn.release` just returns the connector to the pool, and does not actually close it.
Is there a way to forcefully close the connection?

**Comment by dougwilson** [comment]
Well, that is not an error, just a printed warning.

> From my understanding, conn.release just returns the connector to the pool, and does not actually close it.

That's correct.

> Is there a way to forcefully close the connection?

`conn.destroy()`

**Comment by AmitMY** [comment]
Now instead of that warning, I get many:
> Handshake inactivity timeout at

**Comment by dougwilson** [comment]
So that error is during the connection phase. By default there is an inactivity timeout of 10 seconds for the mysql handshake to complete. This is set via the `connectTimeout` option. Do you know if your mysql server just needs a longer timeout? Otherwise not sure what is causing that without debugging.

**Comment by AmitMY** [comment]
Hmmm, I don't think the server needs more time. It is a GCP cloud SQL, which seem to be working fine with upward of 200 connections

![image](https://user-images.githubusercontent.com/5757359/49942456-fff8cd80-feed-11e8-8ac6-4a51c70ff6ab.png)

**Comment by dougwilson** [comment]
Hm, then I have no idea. You're always welcome to make a pull request with a fix that worked for you of course. I'm not sure where to go from here without attaching a debugger and trying to step though the code to see what is happening and/or to use a packet capture like Wireshark to understand what is happening at the network level between Node.js and the mysql server.

If you're able to do that stuff, that would be awesome if you can and can gather what is happening for us. Alternatively if you can walk us through creating a replication of your issue perhaps we can debug it :+1:

**Comment by AmitMY** [comment]
I limited the cloud function to 50 maximum simultaneous runs, 
I now get (for 2000 function runs) - only 3 times:
> Error: Connection lost: The server closed the connection.

To close this, just one more question - do you think it is feasible to catch this error, and retry after 5 seconds? and if it fails 5 times then really throw it? or would that just add load to the system?

**Comment by dougwilson** [comment]
That sounds like something you can do. If it will add load to the system, I really cannot say. It would depend on what exactly is happening on the server during that timeout -- for example if it just does nothing and doesn't send a response or it's using 100% CPU. I would suggest testing it out and watching your server metrics to determine what load it would induce on your server system.

**Comment by Zikoel** [comment]
> Well, that is not an error, just a printed warning.
> 
> > From my understanding, conn.release just returns the connector to the pool, and does not actually close it.
> 
> That's correct.
> 
> > Is there a way to forcefully close the connection?
> 
> `conn.destroy()`

Sorry if I reply to this closed issue but destroy function's behavior is strange for me! Every time I destroy a connection from a pool my db log that
```
Aborted connection 114 to db: 'TEST_DB' user: 'root' host: '127.0.0.1' (Got an error reading communication packets)
```
I don't know if it is a problem but my log is completely flooded by this message! I believe the the destroy close hardly the connection node side not respecting the correct way to close the connection by the protocol, is that possible? Is that a bug or I miss something?
