### ISSUE TITLE
Error: Packets out of order. Got: 80 Expected: 0

### ISSUE THREAD

**Issue by jnyheim** [mysqljs/mysql#2152]
I'm posting this aventho there's previous issues regarding this. I could not find a solution to this, so i hope by posting this that I'd get some help figuring out how to fix this problem. I have posted a question about this on StackOverflow in the hopes of getting an solution to this error, that question can be found [Here](https://stackoverflow.com/questions/53762064/im-getting-a-error-using-node-package-mysql-v2-16-0-while-connecting-to-databas). I'm looking forward to be reading from anyone.
Thanks in advance.
Jonas N

**Comment by dougwilson** [comment]
Hi @jnyheim based on the stack trace from the issue, this error happens on the handshake. The hex char 80 is the latin capital P (`P`). The packet number the 4th byte of the stream, and so likely the server is sending back `HTTP/1.1 ...` i.e. a HTTP response. Try accessing the destination host / port in a web browser. If this is a HTTP server, that is the issue: this needs to connect to a MySQL server.

I hope this helps.
