### ISSUE TITLE
why the idle connection of pool was not release

### ISSUE THREAD

**Issue by yqsailor** [mysqljs/mysql#2153]
I set the connectionLimit is 10, When the number of connections increases to 10 and then falls down，but the number of database connections is always 10, what should i do?

thanks for first

**Comment by marcus-hiles** [comment]
@yqsailor don't quiet get your question...

but when number of allowed connections are reached in mysql, mysql server hungs or fails to respond. So its best you close connections everytime single time you open them, or if you need a lot of connections at a time, you could just increase it in mysql configurations.

**Comment by dougwilson** [comment]
This is how a connection pool works. From https://en.wikipedia.org/wiki/Connection_pool

> In connection pooling, after a connection is created, it is placed in the pool and it is used again so that a new connection does not have to be established.
