### ISSUE TITLE
Include "finished" event in docs

### ISSUE THREAD

**Issue by kyleVsteger** [mysqljs/mysql#2154]
`con.query(getHoles)
    .stream({ highWaterMark: 5 })
    .pipe(...)
    .on('finish', () => console.log('finished'))`
The docs should include the `on('finish', () => {})` event

**Comment by dougwilson** [comment]
Hi @kyleVsteger Node.js streams have many move events and will depend on the version of Node.js you're using. For this reason our documentation for streaming https://github.com/mysqljs/mysql#piping-results-with-streams already explains you get back a Readable Stream object with a link to the Node.js documentation: https://nodejs.org/api/stream.html#stream_class_stream_readable

It documents the `finish` event there, among many other events: https://nodejs.org/api/stream.html#stream_events_finish_and_end
