### ISSUE TITLE
 SET_FOREIGN_KEY = 0 or 1 not WorK

### ISSUE THREAD

**Issue by umberto12345** [mysqljs/mysql#2157]
when I have a table without an external key, just one drop table for delete table but if have constraint and use  `SET foreign_key_checks = 0;`  after of the query not work... error is 

> Cannot delete or update a parent row: a foreign key constraint fails

please help me 
I do not want to change package I'm fine with this

**Comment by MatthewJohnSymons** [comment]
Are you trying to disable foreign key checks so that it allows you to delete data? If so, I believe the command is:

`SET foreign_key_checks = 0;`

When you want to enable it again, it is simply:

`SET foreign_key_checks = 1;`

Hope this helps.

**Comment by umberto12345** [comment]
I had written badly sorry but just with what you say does not work

**Comment by marcus-hiles** [comment]
@umberto12345 Kindly correct grammar in your question above, I can't understand a thing, in your question.

**Comment by kai-koch** [comment]
Do you use the ```SET foreign_key_checks = 0;``` on the same connection or you using Pool connections?
If you are using the first connection in a pool with  ```SET ...``` and then getting the second connection from the pool, the second connection has still  ```foreign_key_checks = 1``` set.

**Comment by dougwilson** [comment]
I'm going to close this since it's been lingering waiting for OP.
