### ISSUE TITLE
Unknown column 'NaN' in 'where clause

### ISSUE THREAD

**Issue by AKSKMY** [mysqljs/mysql#2158]
### Hi, New to this SQL Database and Javascript stuff, but can't figure out what is the problem. Seems to do with the WHERE idComments, but i'm sure how to solve it. Help would be appreciated

**Below is the output from POSTMAN**
`"code":` "ER_BAD_FIELD_ERROR",
`"errno":` 1054,
`"sqlMessage":` "Unknown column 'NaN' in 'where clause'",
`"sqlState":` "42S22",
`"index":` 0,
`"sql":` "UPDATE comments SET Description = 'NICE!', Date = '2019-02-19', Time = '20:10:00', Title = 'Review describes accurately the game itself' WHERE idComments = NaN"

**This is the js file code from the database models folder**
```js
"use strict";

var db = require('../db-connection');
class AkskmyNetworkCommentsDB
{
    getAllComments(callback){
        var sql = "SELECT * from akskmynetwork.comments";
        db.query(sql, callback);
    }
    addComment(comments, callback)
    {
        var sql = "INSERT INTO comments (Description, Date, Time, Title, Personal_Review_idReview, User_Profile_idUSER) VALUES (?, ?, ?, ?, ?, ?)";

        db.query(sql, [comments.getDescription(), comments.getDate(), comments.getTime(), comments.getTitle(), comments.getPersonal_Review_idReview(), comments.getUser_Profile_idUSER()], callback);
    }
updateComment(comments, callback)
    {
        var sql = "UPDATE comments SET Description = ?, Date = ?, Time = ?, Title = ? WHERE idComments = ?";

        return db.query(sql, [comments.getDescription(), comments.getDate(), comments.getTime(), comments.getTitle(), comments.getidComments()], callback);      
    }
}
module.exports = AkskmyNetworkCommentsDB;
```
### Do Let Me Know if you need the other files in solving this problem thank you in advance!

**Comment by dougwilson** [comment]
So based on the code and the error message, it is saying that `comments.getidComments()` is returning `NaN`.
