### ISSUE TITLE
Node program stuck without error, probably problem with mysql client?

### ISSUE THREAD

**Issue by zq1995012** [mysqljs/mysql#2159]
I have a Node.js program that running with high concurrency to communicate with the database. Since the actions of the program have a sequential dependency, I forced the communication like this:
`con.query(sql,function(err,result){
       if(err) return;
       doSomething();}
   function doSomething(){
        return;}`
My program has deeper nested callbacks than this.
The program always stuck at some point without any errors. I have checked several documents online but none related to this. I guess the problem is caused by the mysql client but not sure the exact causes. Please help me if you have any thoughts!

**Comment by dougwilson** [comment]
Very strange. The client shouldn't be getting stuck like you're describing. We may have missed some strange edge case, though.

Is it possible you can provide all the information necessary such that we can reproduce the same error? Someone who is able to reproduce the issue can then attach a debugger and start examining what is happening when this condition occurs and see why it's not being handled.

1. Version of Node.js
2. Version of this module you're using
3. Full source code that can run without modification that will reproduce this condition
4. All relevant steps to get the code running and trigger the condition 

Thanks!

**Comment by zq1995012** [comment]
@dougwilson Thanks for replying. The source code has some concerns about confidentiality. I tried to rewrite some part and tested on my local machine, but everything worked fine. So I think the problem may be caused by the cloud server. Anyway, thank you for paying attention to my question.
