### ISSUE TITLE
How to get queued connection timeStamp

### ISSUE THREAD

**Issue by DivyaR194** [mysqljs/mysql#2160]
I want to track the time taken by the pool to allocate a released connection to the connection which was in queue (waiting time). Is there any way to find this time difference between when the connection was requested and when the connection was actually assigned with a released connection?

**Comment by dougwilson** [comment]
Hi @DivyaR194 there are various events the pool gives off during the lifecycle. The documentation section is here: https://github.com/mysqljs/mysql#pool-events

If I'm understanding you correctly, you want to calculate queued waiting time for connections. Here is one possible implementation for such instrumentation:
```js
// given a `pool` object:

const waits = []
pool.on('enqueue', () => waits.push(Date.now())
pool.on('acquire', () => {
  const wait = waits.length
    ? (Date.now() - waits.shift()) : 0
  console.log('Request in queue for %d ms', wait)
})
```
