### ISSUE TITLE
Cannot use For loop to update data

### ISSUE THREAD

**Issue by Isebella** [mysqljs/mysql#2168]
I've tried to use a for loop in an sql update and it only updates one of the proper ids that I enter into the for loop. Any ideas for a fix?

**Comment by izio38** [comment]
Hi Isebella,

Could you elaborate a bit more?
Otherwise you could provide a repro case.

Izio.

**Comment by Isebella** [comment]
@izio38 Hey, I don't exactly have a repository seeing as the code is private but I can try my best to provide context. I basically make a for loop then call the query and select the data from the users (in the for loop) then try to update it and it only runs it under user (users in the for loop)

**Comment by marcus-hiles** [comment]
@Isebella can you provide more background info? 
Which programming language are you using, are you looping through the programming language code or through sql queries alone, or is it stored procedures?

Please also paste the lines of codes that does the looping with the queries here so we help you debug? The issue might be with the code or logic, thanks

**Comment by Isebella** [comment]
@marcus-hiles I use javascript, I can't exactly send much but I can try to make sense of it. I'm trying to update users coins value in the database by first running a for loop about the data of the users in the array that were in the "game". Then I am trying to get the coins from the users in the db and update the users simultaneously in the for loop.

**Comment by kai-koch** [comment]
Without any provided source code, my first guess would be, the way you loop thru the data is not asyncronous or you do loop with somekind of closure and get the reference to the items, you want to update wrong.
So that instead of looping over every item, only the first or the last item is updated, because the reference in the closure is to the same item over and over again.

**Comment by Isebella** [comment]
This works with forEach, sorry for the concern. Thanks for your time and thoughts though!
