### ISSUE TITLE
ETIMEDOUT when connecting from local server

### ISSUE THREAD

**Issue by Sikro** [mysqljs/mysql#2169]
Good afternoon,

I've read (all?) topics regarding the known ETIMEDOUT error message. However, I am yet to find a solution to my problem. 
When I connect to my external DB using a clean connection script I get connected (using CMD> node file.js):

```
var conn = mysql.createConnection({
            host: 'EXT_IP',
            user: 'EXT_USR',
            password: 'EXT_PW',
            database: 'EXT_DB',
            port: '3306'
        });
conn.connect(function (err) { console.log('Got connected');});
```

However. When I run the above script using my own server (from 127.0.0.1:22005) I get the error as shown below. The DB is an external host and they're not cooperating to help me find the problem. So I need to know; is this solved from within the server-side or database-side? Is there anything I can do to help them find the solution?

```
{ Error: connect ETIMEDOUT
    at Connection._handleConnectTimeout (node_modules\mysql\lib\Connection.js:419:13)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:449:8)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    --------------------
    at Protocol._enqueue (node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Protocol.handshake (node_modules\mysql\lib\protocol\Protocol.js:52:23)
    at Connection.connect (node_modules\mysql\lib\Connection.js:130:18)
    at Object.connect (packages\mysql\mysql.js:18:21)
    at Object.<anonymous> (packages\admin\index.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true }
```

**Comment by Sikro** [comment]
It's just this unfortunately. I've thoroughly tested three situations: 1 with external DB as parameters in the createConnection, 1 with localhost parameters and 1 situation where I run the file directly using terminal and run node <filename>. The last two situations all seem to work. For what it's worth I've checked the privilege of the user I'm trying to connect with in information_schema. The user exists of 'USRNAME'@'%' for DB 'def' type 'USAGE' isgrantable 'NO'. That seems to me the only difference between localhost (own machine) and external DB (somewhere else). 

The service that is trying to connect from my own machine is using 127.0.0.1:22005 as IP address/port. Not sure if that's valuable information.

**Comment by Isebella** [comment]
Why aren't you using the default MySQL port by the way?

**Comment by Isebella** [comment]
What version is the server running of MySQL?

**Comment by Isebella** [comment]
Do you have the sleep timer and other things like that at the default rate @Sikro?

**Comment by Sikro** [comment]
If that's something I can configure without modifying the server then I guess I can give that a try. I just can't edit server variables etc.

**Comment by dougwilson** [comment]
The error `connect ETIMEDOUT` means that Node.js was unable to open a TCP connection to the host and port you provided. This could be a routing issue or firewall issue.

**Comment by ramandeepKaur2222** [comment]
the thing is i have directadmin cpanel, as there atrical saiyd go to databases and under bottom add a remote host, i haven't found any remote host option but there was a option to add host, so i added my own host, with localhost, and i try to connect with node connection.js , it said ETIMEOUT..... so lovely, isn't it, 
so now i installed a xampp php mysql, and i successfully connected to it using node, but how i have to manually transfer my databases to cpanel :) 

var mysql      = require('mysql');
var connection = mysql.createConnection({
    connectionLimit: 10,
    acquireTimeout: 30000,
    host                   : 'here is put my own created hostname,i tried ip address of my domain too',
    user                   : 'username',
    password           : 'pass',
    database           : 'dbname',
    multipleStatements : true
});
connection.connect(function(err) {
    if (!err) {
        console.log("mysql connected")
    } else {
        console.log("mysql connection lost");
    }
});


answer: mysql connection lost
