### ISSUE TITLE
protocol/packets/Field.js typeToString(t) uses O(n) lookup

### ISSUE THREAD

**Issue by mbecker16** [mysqljs/mysql#2170]
I was doing some performance profiling with sequelize and found that a lot of time was being spent in the typeToString(t) function in protocol/packets/Field.js
It's doing a linear lookup in the protocol/contants/types.js file. I switched this to a create a lookup table when the module is loaded and noticed a considerable speed up.

I'm happy to make the code change to this file but wanted to know if there anyone has a preferred approached.

Do you prefer to have lookup table (map) created in the protocol/packets/Field.js file when the module is loaded?
or
Have the lookup by gex put in the protocol/constants/types.js file as it is in the protocol/constants/errors.js file?

**Comment by sidorares** [comment]
Yes, I think doing similar to errors.js  ( thought shorter array with just lookup by code and no holes might be much faster)

**Comment by mbecker16** [comment]
Would it be reasonable to put them in seperate file named TypesLookup.js and use that file in Field.js?

**Comment by dougwilson** [comment]
Just dynamically create lookup table from Types export inside Field.js and save in variable.

**Comment by mbecker16** [comment]
Ok, thanks.
