### ISSUE TITLE
inserting multiple rows - one error leads to no insert at all

### ISSUE THREAD

**Issue by oliverdolgener** [mysqljs/mysql#2174]
I'm using nested arrays to insert multiple rows at once. I really like this option. It makes things so much easier for my use case. There is one thing though that keeps me thinking: when inserting multiple rows and there is an error with one value (like a duplicate entry or so) then all of the rows are getting rejected. Is it possible to only reject the ones with the errors?

```
const locations = req.body.locations.map(x => [req.params.id, x.latitude, x.longitude, x.timestamp]);
connection.query(
    'INSERT INTO location (user_id, latitude, longitude, timestamp) VALUES ?',
    [locations],
    (err, data) => {
      if (err) {
        console.log(err);
      }

      res.status(201).json(req.body.locations);
    }
);
```

Thanks in advance!

**Comment by dougwilson** [comment]
This is just how MySql itself works, there is nothing we can change in the driver, unfortunately. 

You can send one INSERT per row instead if you want them to succeed / fails on a row by row basis instead of as a batch.
