### ISSUE TITLE
ECONNRESET while querying remote MySQL db if the query has EXACTLY 253 characters

### ISSUE THREAD

**Issue by i-m-sac** [mysqljs/mysql#2176]
The ECONNRESET has been a nightmare with unknown causes until I finally dug up into the node_modules to find no matter what the query is if the query is 253 characters long then ECONNRESET error is thrown.
Just a sample query that makes the issue easy to repro- 
```sql
INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')
```
Doesn't matter whether you have the table or coloumns as long as the db is not local, so don't bother creating them - just run this query after connecting to a remote db. Also make sure that the length is **253**, i.e there are no unwanted white spaces or new lines.
The query is generated by Loopback.
Faced the same issue with a select query and the only solution was to add an order by Id at the end of the query so that the query isn't 253 characters anymore.

**Comment by dougwilson** [comment]
Hi @i-m-sac were you able to try the above code?

**Comment by i-m-sac** [comment]
Hi @dougwilson ,
Apologies for the delay
Tried the above code and still the error persists.


`Running query:
INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b
',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')

Length: 253

{ Error: read ECONNRESET
    at TCP.onread (net.js:656:25)
    --------------------
    at Protocol._enqueue (D:\CodeBase\Cymorg\GamingModule\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Connection.query (D:\CodeBase\Cymorg\GamingModule\node_modules\mysql\lib\Connection.js:200:25)
    at Object.<anonymous> (D:\CodeBase\Cymorg\GamingModule\corporates\localhost\test\dbTest.js:19:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true }
`

**Comment by dougwilson** [comment]
Have you tried another computer at all? It does not error on any machine I have tried so far. Maybe it depends on some factors like node.js version and mysql server version, if you can provide those?

**Comment by dougwilson** [comment]
If you're curious, this is what I get when running the script I provided, which is the expected error output:
```
$ node test.js 
Running query:
INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')

Length: 253

{ Error: ER_NO_SUCH_TABLE: Table 'test.SeriesRules' doesn't exist
    at Query.Sequence._packetToError (node_modues/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (node_modues/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket node_modues/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (node_modues/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (node_modues/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (node_modues/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (node_modues/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (node_modues/mysql/lib/Connection.js:201:25)
    at Object.<anonymous> (node_modues/mysql/bar.js:8:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlMessage: 'Table \'test.SeriesRules\' doesn\'t exist',
  sqlState: '42S02',
  index: 0,
  sql: 'INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES(\'deadd530-2a08-11e9-abce-a15029b6d551\',\'7b1836b5-0661-4560-9d35-181b0d4b455b\',12,true,false,\'2019-02-06 12:15:19.555\',\'2019-02-06 12:15:19.555\')' }
```

**Comment by i-m-sac** [comment]
> If you're curious, this is what I get when running the script I provided, which is the expected error output:
> 
> ```
> $ node test.js 
> Running query:
> INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')
> 
> Length: 253
> 
> { Error: ER_NO_SUCH_TABLE: Table 'test.SeriesRules' doesn't exist
>     at Query.Sequence._packetToError (node_modues/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (node_modues/mysql/lib/protocol/sequences/Query.js:79:18)
>     at Protocol._parsePacket node_modues/mysql/lib/protocol/Protocol.js:291:23)
>     at Parser._parsePacket (node_modues/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (node_modues/mysql/lib/protocol/Parser.js:43:10)
>     at Protocol.write (node_modues/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:91:28)
>     at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:525:10)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     --------------------
>     at Protocol._enqueue (node_modues/mysql/lib/protocol/Protocol.js:144:48)
>     at Connection.query (node_modues/mysql/lib/Connection.js:201:25)
>     at Object.<anonymous> (node_modues/mysql/bar.js:8:6)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>   code: 'ER_NO_SUCH_TABLE',
>   errno: 1146,
>   sqlMessage: 'Table \'test.SeriesRules\' doesn\'t exist',
>   sqlState: '42S02',
>   index: 0,
>   sql: 'INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES(\'deadd530-2a08-11e9-abce-a15029b6d551\',\'7b1836b5-0661-4560-9d35-181b0d4b455b\',12,true,false,\'2019-02-06 12:15:19.555\',\'2019-02-06 12:15:19.555\')' }
> ```

@dougwilson then I might be wrong about not needing the table. Could you please create the table with the necessary columns and try? And also please make sure the db isn't in your machine but hosted on a server

**Comment by i-m-sac** [comment]
> If you're curious, this is what I get when running the script I provided, which is the expected error output:
> 
> ```
> $ node test.js 
> Running query:
> INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')
> 
> Length: 253
> 
> { Error: ER_NO_SUCH_TABLE: Table 'test.SeriesRules' doesn't exist
>     at Query.Sequence._packetToError (node_modues/mysql/lib/protocol/sequences/Sequence.js:47:14)
>     at Query.ErrorPacket (node_modues/mysql/lib/protocol/sequences/Query.js:79:18)
>     at Protocol._parsePacket node_modues/mysql/lib/protocol/Protocol.js:291:23)
>     at Parser._parsePacket (node_modues/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (node_modues/mysql/lib/protocol/Parser.js:43:10)
>     at Protocol.write (node_modues/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:91:28)
>     at Socket.<anonymous> (node_modues/mysql/lib/Connection.js:525:10)
>     at emitOne (events.js:116:13)
>     at Socket.emit (events.js:211:7)
>     --------------------
>     at Protocol._enqueue (node_modues/mysql/lib/protocol/Protocol.js:144:48)
>     at Connection.query (node_modues/mysql/lib/Connection.js:201:25)
>     at Object.<anonymous> (node_modues/mysql/bar.js:8:6)
>     at Module._compile (module.js:653:30)
>     at Object.Module._extensions..js (module.js:664:10)
>     at Module.load (module.js:566:32)
>     at tryModuleLoad (module.js:506:12)
>     at Function.Module._load (module.js:498:3)
>     at Function.Module.runMain (module.js:694:10)
>     at startup (bootstrap_node.js:204:16)
>   code: 'ER_NO_SUCH_TABLE',
>   errno: 1146,
>   sqlMessage: 'Table \'test.SeriesRules\' doesn\'t exist',
>   sqlState: '42S02',
>   index: 0,
>   sql: 'INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES(\'deadd530-2a08-11e9-abce-a15029b6d551\',\'7b1836b5-0661-4560-9d35-181b0d4b455b\',12,true,false,\'2019-02-06 12:15:19.555\',\'2019-02-06 12:15:19.555\')' }
> ```
@dougwilson then I might be wrong about not needing the table. Could you please try again with the table? And also please make sure that the db isn't in your local machine but hosted remotely.

**Comment by i-m-sac** [comment]
> It does not error on any machine I have tried so far. Maybe

as a matter of fact, I tried a lot of machines and different versions of the package and still encountered this issue. @dougwilson pls note this error doesn't occur if the db is in the same machine. The db and the node instance must be situated in different machines

**Comment by dougwilson** [comment]
I have only tried with a mysql server instance on a separate machine so far, as I assumed it was network related. I never tried with the server on the same machine.

I can try with the tabe. Can you provide the create table statement to run?

**Comment by i-m-sac** [comment]
> I have only tried with a mysql server instance on a separate machine so far, as I assumed it was network related. I never tried with the server on the same machine.
> 
> I can try with the tabe. Can you provide the create table statement to run?

This should do it 
`Create table SeiresRules1(Id varchar(40), CreatedOn datetime, SeriesId varchar(40),
Name varchar(40), Description varchar(40), Version int, IsActive tinyint, IsFrozen tinyint, 
ModifiedDate datetime);`

**Comment by dougwilson** [comment]
Hi @i-m-sac thanks for that. I was confused why I was still getting a non-existing table error after running that and noticed that you had a typo -- `SeiresRules` instead of `SeriesRules`. Once I changed that, I ran the same script above, and still, no issue. Here is the output I get now that the table exists. I ran this against a MySQL server across the Internet, so there is plenty of network between my machine and the MySQL server if that helps:
```
$ node foo.js 
Running query:
INSERT INTO `SeriesRules`(`Id`,`SeriesId`,`Version`,`IsActive`,`isFrozen`,`ModifiedDate`,`CreatedOn`) VALUES('deadd530-2a08-11e9-abce-a15029b6d551','7b1836b5-0661-4560-9d35-181b0d4b455b',12,true,false,'2019-02-06 12:15:19.555','2019-02-06 12:15:19.555')

Length: 253

null
```

**Comment by i-m-sac** [comment]
Hi, @dougwilson so do you think is causing the issue? Earlier I encountered the same error that was for a select statement of the same length, I had to resolve that issue by adding an order by at the end of the query so that the length changes

**Comment by dougwilson** [comment]
Hm, there are many variables at play here. If it were me, I would try the following:

1. Does a different mysql server version fix the issue?
2. Does the mysql server being on a different server work?
3. What if the mysql server is accessed across the Internet?
4. Are there any firewalls between the client server, and can a test avoid them to see if they are causing it?
5. Are there any wafs on the network and are they causing it?
6. Packet capture at simultaneously on server and client during one of these. Does what they see match up or is there a discrepancy?

**Comment by dougwilson** [comment]
Hi @i-m-sac I'm going to close this for now since there doesn't seem to be any further information I can act on. Were you able to look into any of the above things I listed above?
