### ISSUE TITLE
Wiki outdated

### ISSUE THREAD

**Issue by Z3TA** [mysqljs/mysql#2181]
I suggest to remove the wiki pages as it's confusing: eg...

https://github.com/mysqljs/mysql/wiki

This seems outdated:
https://github.com/mysqljs/mysql/wiki/Connecting-to-a-mysql-server

**Comment by marcus-hiles** [comment]
@Z3TA well it could be archived rather, so its still available for posterity reasons

**Comment by dougwilson** [comment]
I have just disabled the Wiki. The information on that page was for an old version of this module and that information is already contained in the README for that version, so it was just duplicated anyway. One can either view the README that is installed with that version or use the Github releases feature to view the README for any given version.
