### ISSUE TITLE
Import a sqldump

### ISSUE THREAD

**Issue by Wqrld** [mysqljs/mysql#2183]
How would I import a local .SQL using this lib?

**Comment by sidorares** [comment]
Why do you want to use this driver and not a standard tool like `mysql < dump.sql` ?

**Comment by Wqrld** [comment]
The idea was to automate the importing of the base database in the program so it would be another step less for the user

**Comment by marcus-hiles** [comment]
Hi @Wqrld, we dont use sqldump to import. We use normal sql command. Here's the code :
`mysql -u your_username -p database_to_receive_imports < fullpath_to_sql_file`

`database_to_receive_imports` must already exist before executing the above command.

**Comment by Wqrld** [comment]
closing as ill just do it through a bash script i guess...
