### ISSUE TITLE
How to properly validate that an error is an insert error and not a DB connection error

### ISSUE THREAD

**Issue by gangelovq6inc** [mysqljs/mysql#2184]
The problem I am trying to solve is that I want to check that if my query returns an error, that that error is NOT a database connection error. My goal is to identify that if an error occurs, to identify if it's data related or connection related.

I've read the docs, and specifically https://github.com/mysqljs/mysql#error-handling but the examples just show some of the connection related errors and not all.
Is there a way to know if a query failed due to data error and not a connection error ?

**Comment by dougwilson** [comment]
That is what the fatal flag signals.

**Comment by dougwilson** [comment]
If you're looking for a specific error, you'll need to know which errors you want to check for from the MySQL Server documentation (example https://dev.mysql.com/doc/refman/5.5/en/server-error-reference.html) and then the errors this module provides populates several properties with information about the error your code can check for the condition it wants to handle.

**Comment by gangelovq6inc** [comment]
@dougwilson, so the fatal flag indicates that the error is DB related ( connection issues ) and not data related ?

**Comment by marcus-hiles** [comment]
@gangelovq6inc Looking at the server error page sent by @dougwilson, I guess u can use error number specified for each error to determine whether its database connection or data error?

**Comment by dougwilson** [comment]
Fatal indicates only if the error is fatal to the connection, regardless of the error source. But you can still have non-fatal-non-data errors. For example transaction deadlock or query terminated on the server. These errors are not related to the data, but are not fatal to the connection, as you can continue to use the connection.
