### ISSUE TITLE
LOCAL_FILES not working 

### ISSUE THREAD

**Issue by ddddyyy** [mysqljs/mysql#2185]
```js
var connection = mysql.createConnection("mysql://localhost/test?flags=-LOCAL_FILES");
```

it does not work. 
I want to know how to disable the function of local_file.

**Comment by marcus-hiles** [comment]
Hi @ddddyyy, can you please provide more background info here ... what programming language, mysql version and what error you get?

**Comment by dougwilson** [comment]
Hi @ddddyyy yes, I do see the issue. I worked on getting this fixed. Can you take a look at the branch https://github.com/mysqljs/mysql/tree/feature/infile-switch and see if that fixes the issue for you before I add it to a release? You can install it with `npm install mysqljs/mysql#feature/infile-switch` .

Just trying to turn off the flag as in your original code above should work with that branch.

**Comment by marcus-hiles** [comment]
nice @dougwilson

**Comment by RamprasadAkella** [comment]
@dougwilson Can you please let us know when this fix will be released ?

**Comment by RamprasadAkella** [comment]
Any update on this ? @dougwilson

**Comment by dougwilson** [comment]
Can someone confirm if it fixed the reported issue?

**Comment by RamprasadAkella** [comment]
Yes, I can confirm the fix is working. @dougwilson

**Comment by dougwilson** [comment]
Thank you for confirming. And it is not working for you on the current version without that change? I have not had any issue with setting the flag to disable it on master, so looking for (ideally OP) something who also does not work on master so I can get a test added that replicates the underlying issue.

What MySQL server version are you running where master is not working?

**Comment by dougwilson** [comment]
I will still release when I get back to my home county next week, but if you can provide that in the meantime I can make sure it gets added to our test matrix.

**Comment by dougwilson** [comment]
And to clarify: I'm not waiting for your response to make a release with this. I forgot about this issue after I asked for someone to test it and then no one ever did, haha. I do not have a solid Internet connection where I am so ideally I can just get it included when I get back home next week. I was working on merging some PRs for a release before I left (which is the pending changes you can see in master) so I will make sure this gets included.

The branch I have there is two changes: adds a top-level option for this flag (but you can still use the flag like in previous versions) to make setting it easier and changes around the way the packets are parsed.
