### ISSUE TITLE
affectedRows on insert.. on duplicate key query

### ISSUE THREAD

**Issue by justvinz** [mysqljs/mysql#2194]
Hi, 

I'm executing a query:

```js
const mysql = require('mysql');
const connection = mysql.createConnection(config);

connection.connect();

connection.query(`INSERT INTO my_table (topic_id, id, text)
VALUES ('abc', 'def', 'test')
ON DUPLICATE KEY UPDATE text = 'foo';`, function (error, results, fields) {
  if (error) throw error;
  console.log(results);
});

connection.end();
```

As stated in [MySql documentation](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html):
> With ON DUPLICATE KEY UPDATE, the affected-rows value per row is 1 if the row is inserted as a new row, 2 if an existing row is updated, and 0 if an existing row is set to its current values.

**1. First execution**

```js
{
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

✔️ affectedRows: 1 (insert)

**2. Second execution:**

```js
{
    fieldCount: 0,
    affectedRows: 2,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

✔️ affectedRows: 2 (existing row updated)

**3. Third (and following) execution:**

```js
{
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 }
```

❗️ affectedRows: **1** => **I was expecting 0 instead**: existing row is set to its current values

--

If I execute the same query directly on mysql, it works as expected.

Any suggestion?

version: 2.16.0
Database: MySql 5.7.25

Thanks

**Comment by dougwilson** [comment]
This module enables FOUND_ROWS by default. You're describing the behavior when that is disabled. You can disable that if you like: https://github.com/mysqljs/mysql#example The MySQL docs you linked to does explain what the FOUND_ROWS behavior is; the value is just returned by the server to this module.

> If you specify the CLIENT_FOUND_ROWS flag to the mysql_real_connect() C API function when connecting to mysqld, the affected-rows value is 1 (not 0) if an existing row is set to its current values.
