### ISSUE TITLE
Insert problem with pool.query

### ISSUE THREAD

**Issue by hvbnet** [mysqljs/mysql#2196]
Insert into table does not work and not return callback when use pool connection, but work fine when using pool.getConnection 
```
pool.query('INSERT INTO TableA SET ?', {id: 1, post: "name"}, function (error, results, fields) {
   if (error) throw error;
   callback(null, false);
});
```

**Comment by dougwilson** [comment]
I ran your code both with a tableA missing (to get an error) and with it there for success. Both call the callback. Can you add the following information?

Version of node.js
Version of this module
A complete file i can run to reproduce without any modification.

**Comment by marcus-hiles** [comment]
yeah @hvbnet, more info here will do

**Comment by dougwilson** [comment]
Closing due to lack of response.
