### ISSUE TITLE
escape comma 

### ISSUE THREAD

**Issue by charmjeh** [mysqljs/mysql#2201]
```js
    var sqlQuery = 'SELECT ?? FROM ?? INNER JOIN ?? ON ?? WHERE ??';
    var inserts = [
    "a.thumbnail thumbnail ",
    "a.title title ",
    "a.content content ",
    "a.year year ",
    "b.innerTitle innerTitle ",
    "b.innerBody innerBody ",
    ];
    connection.query(sqlQuery, [inserts, 'article as a', 'article_list as b', 'a.id = b.article_id', 'a.id = '+id],

```
i wanted to join statement with two table 
but i cannot use this query.
The result of the query is shown below.

how can i fix it?

 ```
sql:
   'SELECT `a`.`thumbnail thumbnail `, `a`.`title title ....
```

**original mysql statement(This works fine) : 
```sql
SELECT 
    a.thumbnail thumbnail,
    a.title title,
    a.content content,
    a.year year,
    b.innerTitle innerTitle, 
    b.innerBody innerBody
FROM article as a
inner join article_list as b
on a.id=b.article_id
where a.id= 1;

```

**Comment by marcus-hiles** [comment]
Hmmm, interesting @charmjeh which programming language are you using and its version, which mysql connector and version, and which specific errors does this display please?

**Comment by dougwilson** [comment]
This is because `??` does not support the syntax you're trying to use (https://github.com/mysqljs/mysql#escaping-query-identifiers). It expects the string to be the actual column name to use, i.e. by passing in the string `'a.thumbnail thumbnail '` to `??`, it will produce the result you see.

**Comment by charmjeh** [comment]
> This is because `??` does not support the syntax you're trying to use (https://github.com/mysqljs/mysql#escaping-query-identifiers). It expects the string to be the actual column name to use, i.e. by passing in the string `'a.thumbnail thumbnail '` to `??`, it will produce the result you see.

I solved the problem with mysql.escapeId in the link you gave me.
i appreciate it +1
