### ISSUE TITLE
Hello, what's the difference between mysql and mysql2? Are they all on the NPM website?

### ISSUE THREAD

**Issue by AmandaYi** [mysqljs/mysql#2202]
Hello, what's the difference between MySQL and mysql2? Are they all on the NPM website?

**Comment by dougwilson** [comment]
https://github.com/sidorares/node-mysql2/blob/master/README.md#history-and-why-mysql2

**Comment by dougwilson** [comment]
Both are on npm, yes.

**Comment by melroy89** [comment]
This package didn't receive any update for 6 years, I'm pretty sure you want to use `mysql2` now.
