### ISSUE TITLE
Callback called before row inserted with pool

### ISSUE THREAD

**Issue by ddykhoff** [mysqljs/mysql#2205]
I have a query (`CREATE_FEEDBACK_ENTRIES`) I am executing with a pool:

    INSERT INTO eventshub.tbl_feedback (notification_id, user_id)
      SELECT
        @notificationId AS notification_id,
        s.subscriber_user_id AS user_id
      FROM eventshub.tbl_subscriber s
      WHERE s.subscription_id = @subscriptionId
      AND FIND_IN_SET(s.subscriber_user_id, @filteredSubscribers)

And the table DDL:

    CREATE TABLE `tbl_feedback` (
      `feedback_id` bigint(20) NOT NULL AUTO_INCREMENT,
      `notification_id` bigint(20) NOT NULL,
      `user_id` varchar(8) NOT NULL,
      `isread` char(1) DEFAULT 'N',
      `read_dt` timestamp NULL DEFAULT NULL,
      `liked` char(1) DEFAULT NULL,
      `liked_dt` timestamp NULL DEFAULT NULL,
      `viewed_dt` timestamp NULL DEFAULT NULL,
      PRIMARY KEY (`feedback_id`),
      KEY `user_id` (`user_id`),
      KEY `tbl_feedback_ibfk_1_idx` (`notification_id`),
      KEY `notification_id_idx` (`notification_id`),
      CONSTRAINT `tbl_feedback_ibfk_1` FOREIGN KEY (`notification_id`) REFERENCES `tbl_notification` (`notification_id`)
    ) ENGINE=InnoDB AUTO_INCREMENT=281437 DEFAULT CHARSET=utf8

Node.js version: 10.0.0
lib version: 2.16.0

    let pool: Pool
    
    class Executor {
      public static update = (sql: string, parameters?: { [key: string]: string|number }): Promise<InsertResult> => {
        return new Promise((resolve, reject) => {
          Executor.getPool().query(sql, parameters, (error, results, fields) => {
            if (error) {
              reject(error);
              return;
            }
            resolve({
              insertId: results.insertId,
              affectedRows: results.affectedRows
            });
          });
        });
      }
    
      /**
       * Create or return a configured MySQL connection pool
       */
      public static getPool = (): Pool => {
        if (pool) {
          return pool
        }
        pool = mysql.createPool(config)
        return pool
      }
    }
    
    Executor.update(CREATE_FEEDBACK_ENTRIES, {
      notificationId: apiResponseInfo.notification_id,
      subscriptionId: request.subscriptionId,
      filteredSubscribers: filteredSubscribers
    })
      .then((result: InsertResult) => {   
	    // perform action dependent on row being present
        triggerPushMessage(...)
      })
      .catch((err) => log.error(err));

The problem I am experiencing is that the query is executed and the callback is fired, however when I query the table for a short time after this, the rows are not returned. I have verified this from workbench as well as the application from another endpoint which relies on the data being present in a timely manner. If I wait a few minutes, then the row appears and the issues resolve themselves. 

This is a Cloud SQL instance running on GCP, MySQL version 5.7

**Comment by dougwilson** [comment]
When this issue happens, are you getting a `results.insertId` from the callback response, and is that the row ID that ends up eventually appearing?

**Comment by ddykhoff** [comment]
I recently added that log point to the my application, and the issue is very intermittent right now, so I should know next time it happens in my deployment environment. I haven't been able to reproduce the behavior on my local environment.

**Comment by dougwilson** [comment]
Sweet,  thanks! If there is an insertId being returned in this case, that would mean that the Mysql server actually did send a response back, so as far as this module would know the INSERT is "done".

**Comment by ddykhoff** [comment]
I was never able to get this to reproduce so I can't directly answer your question about the `insertId`, however I do believe I resolved my issue by changing the transaction isolation level to `READ COMMITTED` for each connection in the connection pool upon the connection creation.

    pool.on('connection', (connection) => {
      connection.query('SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED', (err) => {
        if (err) log.error(`Failed to set transaction isolation level: ${err}`)
      })
    });
