### ISSUE TITLE
Deprecated bignumber dependency

### ISSUE THREAD

**Issue by frbuceta** [mysqljs/mysql#2206]
Console Output
`npm WARN deprecated bignumber.js@6.0.0: Custom ALPHABET bug fixed in v7.0.2`

**Comment by dougwilson** [comment]
Thanks for the report @frbuceta 👍. I just looked through the change log between 6 and 7 and it looks like we can upgrade safely. I'll get a patch release of this module ready for release in a few hours.

**Comment by frbuceta** [comment]
Perfect ;) thanks

**Comment by dougwilson** [comment]
Published as 2.17.1
