### ISSUE TITLE
PROTOCOL_SEQUENCE_TIMEOUT when connecting to MySQL

### ISSUE THREAD

**Issue by trickoooo** [mysqljs/mysql#2216]
I got a `PROTOCOL_SEQUENCE_TIMEOUT` when my nodejs API is trying to connect to MySQL RDS instance in AWS. The stack shows `Error: Handshake inactivity timeout.`

Basically my NodeJS API runs a stored procedure in MySQL when an endpoint is called. My API is deployed in AWS Lambda.

It's a bit weird since this is happening intermittently, however it causes my API errors on my logs.
Is this has something to do on how I establish connection to mySQL. Code below:

```
const databaseconfig = config.databaseconnection;
databaseconfig.host = databaseconfig.host[0];
const pool = mysql.createPool(databaseconfig);

databaseconfig.host = databaseconfig.host[1];


const dataconnection = {};

const ropool = mysql.createPool(databaseconfig);
dataconnection.runquery = function (query, values, next, mode) {
    let startTime = Date.now();

    let connectionpool = pool;

    if (Array.isArray(databaseconfig.host)) {
        if (mode === "read" && databaseconfig.host.length > 1) {
            connectionpool = ropool;
        }
    }

    return connectionpool.getConnection(function (err, connection) {
        if (err) {
            console.log("Error Getting Connection!");
            console.log(JSON.stringify(err));
            return next.apply(this, arguments);
        }
        else {
            let sql = connection.format(query, values);
            return connection.query(sql, function (error, results, fields) {
                connection.release();
                return next.apply(this, arguments);
            });
        }
    });
}
```
Lambda Runtime: `NodeJS 8.10`
MySQL Server: `AWS Aurora 5.7.12`

**Comment by dougwilson** [comment]
By default, this module sets a 10 second timeout to opening a new connection (https://github.com/mysqljs/mysql#connection-options). If your server and network needs more than 10 seconds to establish the connection, you can adjust that with the `connectTimeout` option.
