### ISSUE TITLE
Localhost connection pool not release 

### ISSUE THREAD

**Issue by EroTiXx** [mysqljs/mysql#2219]
Hello everyone !

I'm having a little problem with the pool release
[https://github.com/mysqljs/mysql#pooling-connections](https://github.com/mysqljs/mysql#pooling-connections)
```javascript
var mysql = require('mysql');
var pool  = mysql.createPool({
  connectionLimit : 10,
  host            : 'example.org',
  user            : 'bob',
  password        : 'secret',
  database        : 'my_db'
});

pool.query('SELECT 1 + 1 AS solution', function (error, results, fields) {
  if (error) throw error;
  console.log('The solution is: ', results[0].solution);
});
```

All my requests are of the same kind and the connections are not released in Localhost ! 
**BUT, in production mode, everything is working...**

On MySql Workbench, I can see that with each request the number of threads increases.

Configuration : 
- AWS RDS MySql Database 
- Node express API with AWS Lambda (I use Serverless Framwork)

Do you have an idea where the problem may be because I do not understand why :(

Thank you

**Comment by dougwilson** [comment]
I don't really understand the description of the problem. What is the problem, exactly? And then what is different between production mode and not?

**Comment by EroTiXx** [comment]
I solved all my problems just with this package and with almost no modifications.

[https://github.com/jeremydaly/serverless-mysql](https://github.com/jeremydaly/serverless-mysql)

So for those using AWS lambda this will be greatly helpful
