### ISSUE TITLE
affectedRows and changedRows are undefined in SELECT query result

### ISSUE THREAD

**Issue by hieuhlc** [mysqljs/mysql#2220]
I'm using mysql v2.17.1 to access MySQL v5 DB. Here are the screenshots from my project:
![code](https://user-images.githubusercontent.com/4828178/57764680-1d94c200-772e-11e9-9299-f60a9d7d4e94.png)
In my code I log the results from a simple SELECT query: `select * from users;` but both `affectedRows` and `changedRows` are undefined

<img width="502" alt="Screen Shot 2019-05-15 at 16 24 33" src="https://user-images.githubusercontent.com/4828178/57764691-24233980-772e-11e9-8736-6c1f7eb0bf2b.png">

Please help. Thank you in advance.

**Comment by dougwilson** [comment]
The mysql protocol does not return those values for SELECT statements.
