### ISSUE TITLE
ER_PARSE_ERROR but the sql works ok with phpmyadmin

### ISSUE THREAD

**Issue by nieben** [mysqljs/mysql#2222]

**Comment by nieben** [comment]
Hello, i am tring to create a trigger, and i got the error response blow:

{ Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER $$ CREATE TRIGGER `t_afterinsert_http_201808` AFTER INSERT ON `17ce_ch' at line 1
    at Query.Sequence._packetToError (C:\wamp64\www\kafka-node\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (C:\wamp64\www\kafka-node\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (C:\wamp64\www\kafka-node\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (C:\wamp64\www\kafka-node\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (C:\wamp64\www\kafka-node\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\wamp64\www\kafka-node\node_modules\mysql\lib\Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    --------------------
    at Pool.query (C:\wamp64\www\kafka-node\node_modules\mysql\lib\Pool.js:199:23)
    at Promise (C:\wamp64\www\kafka-node\test.js:20:14)
    at new Promise (<anonymous>)
    at query (C:\wamp64\www\kafka-node\test.js:19:12)
    at createTrigger (C:\wamp64\www\kafka-node\test.js:124:20)
    at Object.<anonymous> (C:\wamp64\www\kafka-node\test.js:119:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'DELIMITER $$ CREATE TRIGGER `t_afterinsert_http_201808` AFTER INSERT ON `17ce_ch\' at line 1',
  sqlState: '42000',
  index: 0,
  sql: 'DELIMITER $$ CREATE TRIGGER `t_afterinsert_http_201808` AFTER INSERT ON `17ce_check_log`.`check_log_http_201808`  FOR EACH ROW BEGIN  set @uid = (SELECT api_uid FROM 17ce.user_api_data WHERE taskid = NEW.taskid);  set @nid = (SELECT sid from 17ce.node_info where status=4 and ip = NEW.nodeip limit
 1);  IF @uid != "" and @nid != "" THEN  SELECT count(id) into @user FROM 17ce.user_api_point where user_id = @uid and nodeid = @nid;  if @user <=0 then  insert INTO 17ce.user_api_point ( user_id, nodeid, tasks) values (@uid, @nid, 1);  elseif @user >=1 then   update 17ce.user_api_point SET tasks=tasks+1
 where user_id = @uid and nodeid = @nid;  END IF;  END IF;  END $$  DELIMITER;' }

but when i exec the sql output above with phpmyadmin, it works fine. I have tried with the sql for a while and didnot find out where the problem is. the code is like blow:

function query(sql) {
    return new Promise(( resolve, reject ) => {
        pool.query(sql, function (error, results, fields) {
            if (error) {
                reject(error);
            } else {
                resolve(results, fields);
            }
        });
    })
}

function getTrigger(triggierName, dbName, tableName) {
    return "DELIMITER $$" +
        " CREATE TRIGGER `"+triggierName+"` AFTER INSERT ON `" + dbName + "`.`" + tableName + "` " +
        " FOR EACH ROW BEGIN " +
        " set @uid = (SELECT api_uid FROM 17ce.user_api_data WHERE taskid = NEW.taskid); " +
        " set @nid = (SELECT sid from 17ce.node_info where status=4 and ip = NEW.nodeip limit 1); " +
        " IF @uid != \"\" and @nid != \"\" THEN " +
        " SELECT count(id) into @user FROM 17ce.user_api_point where user_id = @uid and nodeid = @nid; " +
        " if @user <=0 then " +
        " insert INTO 17ce.user_api_point ( user_id, nodeid, tasks) values (@uid, @nid, 1); " +
        " elseif @user >=1 then  " +
        " update 17ce.user_api_point SET tasks=tasks+1 where user_id = @uid and nodeid = @nid; " +
        " END IF; " +
        " END IF; " +
        " END" +
        " $$ " +
        " DELIMITER;";
}

async function createTrigger() {
    let sql = getTrigger('t_afterinsert_http_201808', '17ce_check_log', 'check_log_http_201808');
    let rt = await query(sql);
    console.log(rt);
}

createTrigger();

And there is no params with this sql.

**Comment by dougwilson** [comment]
This is because `DELIMITER` is not SQL, and so your MySQL server does not understand it. Just remove those parts and it will work OK:
```js
function getTrigger(triggierName, dbName, tableName) {
    return "CREATE TRIGGER `"+triggierName+"` AFTER INSERT ON `" + dbName + "`.`" + tableName + "` " +
        " FOR EACH ROW BEGIN " +
        " set @uid = (SELECT api_uid FROM 17ce.user_api_data WHERE taskid = NEW.taskid); " +
        " set @nid = (SELECT sid from 17ce.node_info where status=4 and ip = NEW.nodeip limit 1); " +
        " IF @uid != \"\" and @nid != \"\" THEN " +
        " SELECT count(id) into @user FROM 17ce.user_api_point where user_id = @uid and nodeid = @nid; " +
        " if @user <=0 then " +
        " insert INTO 17ce.user_api_point ( user_id, nodeid, tasks) values (@uid, @nid, 1); " +
        " elseif @user >=1 then  " +
        " update 17ce.user_api_point SET tasks=tasks+1 where user_id = @uid and nodeid = @nid; " +
        " END IF; " +
        " END IF; " +
        " END";
}
```
