### ISSUE TITLE
Can not start Mysql service

### ISSUE THREAD

**Issue by devit-chea** [mysqljs/mysql#2223]
3:53:58 PM  [mysql] 	Attempting to start MySQL service...
4:02:10 PM  [mysql] 	Attempting to start MySQL service...
4:03:15 PM  [mysql] 	Attempting to start MySQL service...
It defended by **Verified Publisher: Microsoft Windows**

**Comment by devit-chea** [comment]
phpMyadmin Access denied.

**Comment by dougwilson** [comment]
Hi @devit-chea this repository is a Node.js driver for MySQL access, not for the MySQL server software or phpMyAdmin.
