### ISSUE TITLE
Can not set user variable without enabling `multipleStatements`

### ISSUE THREAD

**Issue by avin3sh** [mysqljs/mysql#2227]
We are using version `2.17.1` in our production. However I noticed that I am unable to set variable unless I enable `multipleStatements` - which has nothing to do with user defined variables. It is necessary to mention that we are using `createPool` method.

The following code does not work,

```
const query1 = `SET @var1 = 123`;
const query2 = `SELECT @var1`;

db.query(query1, (err1, result1) => {
  db.query(query2, (err2, result2) => {
    console.log(result2); //@var1 is NULLL
  });
});
```

However after enabling `multipleStatements` in `createPool` configuration, and rewriting the query as following gives the desired result,

```
const query = `SET @var1 = 123; SELECT @var1';

db.query(query, (err, result) => {
  console.log(result[1]); //@var1 is 123 in this case
});
```

I am not sure if this is a bug or expected behavior.

Perhaps in the first case I am using two different pool instances thus the variable is session specific only to the first query and not the second, as mention in the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/user-variables.html) ?

**Comment by dougwilson** [comment]
Is your `db` variable a pool object? If so, then db.query

> This is a shortcut for the pool.getConnection() -> connection.query() -> connection.release() code flow. Using pool.getConnection() is useful to share connection state for subsequent queries. This is because two calls to pool.query() may use two different connections and run in parallel.
