### ISSUE TITLE
"RangeError: out of range index" in HandshakeInitializationPacket.parse

### ISSUE THREAD

**Issue by aniltallam** [mysqljs/mysql#2230]
Opened this issue because #2228 was closed without actually verifying if the issue is resolved or not.

Actual Issue:  Following line in our code
```
mysql.createPool(connConfigs).getConnection(function (err, connection) {
...})
```
is sometimes causing following uncaught errors (noticed in production server logs) which we couldn't handle by simple try catch blocks
> RangeError: out of range index, at RangeError (native),
>     at Parser.parseBuffer (/srv/www/integrator/node_modules/mysql/lib/protocol/Parser.js:319:16),
>     at Parser.parseFiller (/srv/www/integrator/node_modules/mysql/lib/protocol/Parser.js:276:15),
>     at HandshakeInitializationPacket.parse (/srv/www/integrator/node_modules/mysql/lib/protocol/packets/HandshakeInitializationPacket.js:50:39),
>     at Protocol._parsePacket (/srv/www/integrator/node_modules/mysql/lib/protocol/Protocol.js:262:12),
>     at Parser.write (/srv/www/integrator/node_modules/mysql/lib/protocol/Parser.js:76:12),
>     at Protocol.write (/srv/www/integrator/node_modules/mysql/lib/protocol/Protocol.js:39:16),
>     at Socket. (/srv/www/integrator/node_modules/mysql/lib/Connection.js:103:28),
>     at emitOne (events.js:96:13), at Socket.emit (events.js:188:7),
>     at readableAddChunk (_stream_readable.js:176:18),
>     at Socket.Readable.push (_stream_readable.js:134:10),
>     at TCP.onread (net.js:547:20)

Looks like proper error handling is missing when a handshake packet from server has incorrect data.

Since we couldn't reproduce the issue locally, I tried placing `throw new Error('Hello 123')` at line no. 50 in HandshakeInitializationPacket.js but still, I am getting following uncaught error instead of getting the error in the callback of mysql.createPool(connConfigs).getConnection
> Uncaught Error: Hello 123
>     at HandshakeInitializationPacket.parse (node_modules/mysql/lib/protocol/packets/HandshakeInitializationPacket.js:50:11)
>     at Protocol._parsePacket (node_modules/mysql/lib/protocol/Protocol.js:272:12)
>     at Parser._parsePacket (node_modules/mysql/lib/protocol/Parser.js:433:10)
>     at Parser.write (node_modules/mysql/lib/protocol/Parser.js:43:10)
>     at Protocol.write (node_modules/mysql/lib/protocol/Protocol.js:38:16)
>     at Socket. (node_modules/mysql/lib/Connection.js:91:28)
>     at Socket. (node_modules/mysql/lib/Connection.js:525:10)
>     at Socket.EventEmitter.emit (domain.js:441:20)
>     at addChunk (_stream_readable.js:284:12)
>     at readableAddChunk (_stream_readable.js:265:11)
>     at Socket.Readable.push (_stream_readable.js:220:10)
>     at TCP.onStreamRead (internal/stream_base_commons.js:94:17)
>     at TCP.onread (node_modules/async-listener/glue.js:188:31)

We are using 2.14.0 version on production server, but issue is occuring on latest (2.17.1) also.

**Comment by dougwilson** [comment]
https://github.com/mysqljs/mysql/issues/2228#issuecomment-499920053
