### ISSUE TITLE
Can't authenticate. Doesn't recognize user

### ISSUE THREAD

**Issue by christian-hess-94** [mysqljs/mysql#2232]
I have the folling connection info but I recieve an error message when trying to connect. the mysql server is running and all info are correctly spelled:
```js
var con_details = mysql.createConnection({
    host: '172.25.19.52',
    port: 3306,
    user: 'root',
    password: 'some_password',
    database: 'my_schema'
});

let connection = mysql.createConnection(con_details)

connection.connect((err: any) => {
        if (err) {
            Log.i('DATABASE', `  ${err.code} - Error while connecting:  ${err.name} - ${err.message} `)
            return;
        }
        res.send("It worked!")
    })
```
This returns:
[DATABASE] (01/05/2019, 15:04:31:423)   ER_ACCESS_DENIED_ERROR - Error while connecting:  Error - ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)

It's like the module doesn't recognize the user being passed (root)

**Comment by dougwilson** [comment]
Hi! Sorry you are having trouble. This is because you are creating a new connection and then creating a second connection with the first connection as the option argument. You just need to make a connection one time:
```js
var con_details = {
    host: '172.25.19.52',
    port: 3306,
    user: 'root',
    password: 'some_password',
    database: 'my_schema'
};

let connection = mysql.createConnection(con_details)

connection.connect((err: any) => {
        if (err) {
            Log.i('DATABASE', `  ${err.code} - Error while connecting:  ${err.name} - ${err.message} `)
            return;
        }
        res.send("It worked!")
    })
```

**Comment by christian-hess-94** [comment]
I feel so dumb now. Thank you
