### ISSUE TITLE
JSON_EXTRACT of a float value gets returned as string

### ISSUE THREAD

**Issue by 5an1ty** [mysqljs/mysql#2234]
In example below:

```
select JSON_UNQUOTE(JSON_EXTRACT(JSON_SET("{}", '$.a', 0.123), '$.a')) test; 
```

The returned value is a string while I would expect it to be a number.

**Comment by 5an1ty** [comment]
Currently solved it with the ability of passing your own custom typeCast function:

```
      typeCast: function (field, next) {
        if (field.type === 'LONG_BLOB') {
          try {
            return parseFloat(field.string());
          } catch(_) {
            return next();
          }
        } else {
          return next();
        }
      }
```

Seems a bit weird that the default behaviour is wrong however.

**Comment by dougwilson** [comment]
Hi! Sorry if that is unexpected,  but that is how the MySQL server is returning the value, as a string. The MySQL documentation on JSON_UNQUOTE seems to state this as well:

https://dev.mysql.com/doc/refman/5.7/en/json-modification-functions.html

> JSON_UNQUOTE(json_val)
> 
> Unquotes JSON value and returns the result as a utf8mb4 string. Returns NULL if the argument is NULL.
