### ISSUE TITLE
AWS Aurora Serverless Data API

### ISSUE THREAD

**Issue by Can-Sahin** [mysqljs/mysql#2242]
AWS Aurora Serverless have now a **DATA API** that you can execute sql statements over **HTTPS**

[Blog](https://aws.amazon.com/blogs/aws/new-data-api-for-amazon-aurora-serverless/)

[Usage](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)

[Javascript SDK Documentation](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/RDSDataService.html)

It's an EXTREMELY useful feature that many `serverless` developers were waiting for literally years. It's solves the problem of connections pools and counts and now `serverless` trend can fully embrace `mysql`. 

How is this gonna happen? Any plan to support? Can users configure by themselves it without any update(i am stranger to insights of the`mysql` package)

**Comment by dougwilson** [comment]
This package implements the MySQL protocol, which is defined by Oracle. What you've linked to looks like a different HTTP-based protocol, which is outside the scope of this module. I hope that answers your question :)

**Comment by Can-Sahin** [comment]
Yes actually you are right. This is a client for mysql protocol in a way. Thanks.
