### ISSUE TITLE
Cannot find module 'bignumber.js'

### ISSUE THREAD

**Issue by egalarza007** [mysqljs/mysql#2244]
The Parser in lib is throwing missing module warnings 

Stack
```
Error: Cannot find module 'bignumber.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/node_modules/mysql/lib/protocol/Parser.js:4:36)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```
It looks like in the most recent change logs you have updated the version
```
## v2.17.1 (2019-04-18)

* Update `bignumber.js` to 7.2.1 #2206
  - Fix npm deprecation warning

## v2.17.0 (2019-04-17)

...
* Update `bignumber.js` to 6.0.0
```

**Comment by dougwilson** [comment]
That error usually is because there was an issue during your npm install. Can you run npm install again and paste the output here?

**Comment by egalarza007** [comment]
I am building in a cloud environment and the application is serverless. 
I piped the content of a local install into file located below. 
[log.txt](https://github.com/mysqljs/mysql/files/3377699/log.txt)

**Comment by dougwilson** [comment]
Thanks for the log. It shows that `bignumber.js@7.2.1` is being installed successfully somewhere.

Can you run `npm ls bignumber.js` to see where it installed to?

**Comment by egalarza007** [comment]
Thank you Mr Wilson for rapid response. It looks like it is being installed in the correct location but when deployed to Lambda I still get that same Error: Cannot find module 'bignumber.js'
npm ls bignumber.js output

└─┬ serverless-mysql@1.4.0
  └─┬ mysql@2.17.1
    └── bignumber.js@7.2.1

**Comment by dougwilson** [comment]
Hm. How does the deployment process work?

**Comment by egalarza007** [comment]
It's the same process as run locally sir. 
I have a build spec that runs the package.json script for build like 

`npm run build`

The only difference is ` --only=production` to reduce the size of the zip sir
This is the content of scripts in package.json
```
  "scripts": {
    "test": "jest --coverage",
    "test:update": "jest --verbose --coverage --updateSnapshot",
    "test:watch": "jest --verbose --watch",
    "coverage": "jest --verbose --coverage && open ./coverage/lcov-report/index.html",
    **"build": "npm install --only=production",**
    "eslint": "./node_modules/.bin/eslint --ignore-path .gitignore ."
  },
```

**Comment by dougwilson** [comment]
So are you able to replicate the error locally? Can you help me repliacate locally? I could then have something in hand to try and debug how to fix.

**Comment by egalarza007** [comment]
Mr Wilson-
I just created a unit test and it looks like this issue does not appear locally. 
I updated my deployment script to also output the location of bignumber.js after build and it also looks correct sir. 
Output below
```
added 14 packages in 1.608s 
post-slack-event@1.0.0 /codebuild/output/src082596253/src/PostSlackEvent 
`-- serverless-mysql@1.4.0 
  `-- mysql@2.17.1 
    `-- bignumber.js@7.2.1  
```

I also see the package in node_module

![Screen Shot 2019-07-10 at 9 33 34 AM](https://user-images.githubusercontent.com/7209462/60987224-06b9b880-a2f6-11e9-902b-1552e66a2254.png)

This issue must be isolated to Lambda runtime for Node. 
Thank you for all your help sir. 
You may close this issue and I will continue troubleshooting in Lambda.

**Comment by egalarza007** [comment]
Mr. Wilson-
I have resolved the issue and it was related to the Lambda deployment. After installing and building the project I would remove certain files to reduce size of zip for deployment. Removal of the .json config files also removed the package.json for the node_modules which prevented Lambda from finding these modules. 
Thank you for all your help sir.

**Comment by dougwilson** [comment]
Hi @egalarza007 sorry for the late response; I'm glad you were able to get it working :) !
