### ISSUE TITLE
remove schema definitions

### ISSUE THREAD

**Issue by HosseinAlipour** [mysqljs/mysql#2245]
Is there a way to remove Schema Definitions from results? 
I tried to set NO_SCHEMA flag without luck...
```js
db = mysql.createPool({
   ...
  multipleStatements: true,
  flags: '+NO_SCHEMA'
});
```

**Comment by dougwilson** [comment]
That flag is listed as not implemented: https://github.com/mysqljs/mysql/blob/master/Readme.md#other-available-flags
