### ISSUE TITLE
Why does MySQL return OkPacket object with results when a SQL query string ends in a comment?

### ISSUE THREAD

**Issue by ericatallah** [mysqljs/mysql#2249]
I get back the OkPacket object at the end of the array of results (causing actual results data to get nested two arrays deep).  I'm using an instance of mysql.createPool() which I have promisify the pool.query method to use async/await syntax on.

Something like:

`const sql = 'SELECT table1.id, table1.foo, table1.bar FROM table1 WHERE table1.id = 1; -- mysql comment!';`

`const result = await pool.query(sql);  // below is result`

`[
  [
    {
    "id": 1,
    "foo": "Some string1",
    "bar": "Some string2"
    }
  ],
  {
    "fieldCount": 0,
    "affectedRows": 0,
    "insertId": 0,
    "warningCount": 0,
    "message": "",
    "changedRows": 0,
    ...etc
  }
]`

However, if the comment is omitted, the results are as expected:

`const sql = 'SELECT table1.id, table1.foo, table1.bar FROM table1 WHERE table1.id = 1;';`

`const result = await pool.query(sql);  // below is result`

`[
  {
    "id": 1,
    "foo": "Some string1",
    "bar": "Some string2"
  }
]`

This obviously isn't a huge deal, but it would be cool to know what's going on here.  Thanks!

**Comment by sidorares** [comment]
this is how driver returns multiple statements results. In your example second statement is comment, result for it is OK packet.

You can also get multiple results even using single statement, for example call to stared procedure can yield multiple resultsets

**Comment by ericatallah** [comment]
I see, thanks for the reply.
