### ISSUE TITLE
How can I wait for results?

### ISSUE THREAD

**Issue by CheyenneForbes** [mysqljs/mysql#2250]
After reading some issues I realized this library doesn't support promises nor async/wait.

How can I "block" to wait on the results without adding another library? Its being used a library that  needs a value or promise to be returned from the handler function.

**Comment by dougwilson** [comment]
You will want to construct a promise and then inside the callback of the query call the given resolve function:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

This is what other libraries are doing and hide from you, so if you don't want to use another library you just have to copy what they are doing directly into your code.
