### ISSUE TITLE
Multi statement bulk insert

### ISSUE THREAD

**Issue by redixhumayun** [mysqljs/mysql#2251]
I've been wondering what the best way to achieve a bulk insert as part of a multi statement transaction is. 

I have 3 tables that I need to update all at once, and here is the SQL query I use for that. 

```BEGIN;
INSERT INTO `FAB_BCGH` (`OCNO`, `CUSTNAME`, `STYLENO`, `STYLDESC`) VALUES(1, 'FATFACE', 'w2526', '12t1g13g')
on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, '2i2ht12t', 'white', 1000)
on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;
INSERT INTO FAB_BCGR (`BCGUNIQ`, `BCGLINE`, `ROLLNO`, `RLENGTH`, `RWIDTH`, `PONO`) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, '123456', 100, 50, '21t8h12h'), (@last_inserted_id_var_1, @last_inserted_id_var_2, '12367', 100, 50, '21t8h12h')
on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
COMMIT;
```

As you can see, I update the third table with two sets of values. However, the insertion of those values depends on the @last_inserted_id_var_1 and @last_inserted_id_var_2 variables. 

I tried to do the same with this library in the following format.

(Here nestedData is of the following format):

```
[ [ 79, 56, 1, 15, 'NJPO1603761' ],
  [ 79, 56, 2, 15, 'NJPO1603761' ],
  [ 79, 56, 3, 15, 'NJPO1603761' ],
  [ 79, 56, 4, 15, 'NJPO1603761' ] ]
```

```
connection.query(`
 BEGIN;
 INSERT INTO FAB_BCGH (OCNO, CUSTNAME, STYLENO, STYLDESC) VALUES(${mysql.escape(OC)}, ${mysql.escape(CustName)}, ${mysql.escape(StyleNo)}, ${mysql.escape(StyleDesc)})
      on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
      SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
      INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, ${mysql.escape(ItemNo)}, ${mysql.escape(ItemDesc)}, ${mysql.escape(tableData.length)})
      on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
      SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;
      INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, RWIDTH, PONO) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, (?), (?), (?))
      on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
      COMMIT;`, [nestedData], function(err, results, fields) {
      console.log(results)
      connection.release()
      if (err) {
        throw err
      }
    })
```

However, this doesn't work. I get the following error when I run the above transaction. 

```You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '?), (?)) on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);```

Now, presumably, the library doesn't allow partially parameterized queries like the above for bulk inserts? I'm not sure. 

I had to hack my way around it by doing the following

 ```
 connection.query(`
      BEGIN;
      INSERT INTO FAB_BCGH (OCNO, CUSTNAME, STYLENO, STYLDESC) VALUES (${mysql.escape(OC)}, ${mysql.escape(CustName)}, ${mysql.escape(StyleNo)}, ${mysql.escape(StyleDesc)})
      on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
      SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
      INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, ${mysql.escape(ItemNo)}, ${mysql.escape(ItemDesc)}, ${mysql.escape(tableData.length)})
      on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
      SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;
      SELECT @last_inserted_id_var_1 as index1, @last_inserted_id_var_2 as index2;
      COMMIT;
    `, function(err, results, fields) {
      if (err) throw err
      const { index1, index2 } = results.map(r => {
        if (Array.isArray(r)) {
          return r
        }
      }).filter(r => r)
        .flat()[0]
      const nestedData = tableData.map(rollObj => {
        return [index1, index2, rollObj.roll, rollObj.length, PONumber]
      })
      connection.query(`
        INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, PONO) VALUES ?
        on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
      `, [nestedData], function(err, results, field) {
        if (err) throw err
      })
      connection.release()
    })
```

Now, I don't believe that this is the best way to achieve the results I want. Is there a better way to do what I want?

**Comment by dougwilson** [comment]
Hi, and sorry you're having trouble. Have you enabled multi statement support on your connection? https://github.com/mysqljs/mysql/blob/master/Readme.md#multiple-statement-queries

**Comment by redixhumayun** [comment]
@dougwilson - Hi, no need to apologise. I love the work you're doing with this lib and how active you are with it! Thank you for that!

Yes, I have the multi statement support enabled. Multiple statements work fine. I'm just having trouble with partially parameterizing a query. Is that even possible?

**Comment by dougwilson** [comment]
I apologize again, haha. I try to triage issues in the morning before work and I overlooked your specific syntax error. The syntax error is because there are three placeholders in your query (the ?) but in the values array you only passed in one value (that array of arrays) so the other two ? had no values to be expanded.

I'm not sure I understand what you're trying to do by reading this issue so far. Maybe would it be possible to show the exact SQL you were expecting that code (the first block) to send to the server, given the javadcript and variable?

**Comment by redixhumayun** [comment]
No need to apologise. 

Let me start off by explaining exactly what I'm trying to do. There might be an easier way to do what I'm attempting. I have a scenario where I have three tables (I'll call them FAB_BCGH, FAB_BCGD and FAB_BCGR. I'm picking these names because these are the names I've assigned in my query, so it'll be easier to follow along). 

The relationship between FAB_BCGH and FAB_BCGD is 1 -> many. The relationship between FAB_BCGD and FAB_BCGR is 1 -> many. Now, when I send data to the server, I want to insert a record into FAB_BCGH, insert 1+ records into FAB_BCGD, and insert 1+ records into FAB_BCGR. 

The other thing I want to take care of is if a duplicate record exists in either FAB_BCGH or FAB_BCGD, I don't want to insert a new record. Instead, I want to find the pk of the previously inserted record in the table with the duplicate key. 

Here is the SQL query I am running in my editor which gives me the results I want. 

```
BEGIN;
INSERT INTO `FAB_BCGH` (`OCNO`, `CUSTNAME`, `STYLENO`, `STYLDESC`) VALUES(1, 'FATFACE', 'w2526', '12t1g13g')
on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, '2i2ht12t', 'white', 1000)
on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;
INSERT INTO FAB_BCGR (`BCGUNIQ`, `BCGLINE`, `ROLLNO`, `RLENGTH`, `RWIDTH`, `PONO`) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, '123456', 100, 50, '21t8h12h'), (@last_inserted_id_var_1, @last_inserted_id_var_2, '12367', 100, 50, '21t8h12h')
on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
COMMIT;
```

The reason I have three placeholders is because the nested array I'm creating is of the following format:

```
[ [ a, b, c, d ],
  [ e, f, g, h ],
  [ i, j, k l ],
  [ m, n, o, p] ]
```

So, I would need three placeholders then right?

**Comment by dougwilson** [comment]
So you should only need a single placeholder, right? At least, I'm not following where the number of placeholders being three would come from given that example.Like which expansion rule are you trying to trigger with that value?

**Comment by redixhumayun** [comment]
Sorry, the nested array above should have only three columns. 

I have 3 placeholders because I have three columns I need to bulk insert values for in FAB_BCGR. The first two columns are populated by `@last_insert_id_var_1` and `@last_insert_id_var_2`.

All the examples I see for bulk insert, insert the entire row through the array. I, unfortunately, don't have that option. 

I was also going off [this issue](https://github.com/mysqljs/mysql/issues/887) where you suggested using multiple placeholders for different values.

**Comment by dougwilson** [comment]
Thanks, but I guess I would like to help come up with a solution, but I'm still not clear on what you're expecting the final SQL to look like in order to understand. I'm not sure I understand what you're trying to do by reading this issue so far. Maybe would it be possible to show the exact SQL you were expecting that code to send to the server, given the javadcript and variable?

**Comment by redixhumayun** [comment]
It sounds like I may be missing something but I thought I posted the exact SQL i was after 2 comments up?

Here is the nestedData variable

```
[[123456, 100, 50, '21t8h12h'],
  [123678, 100, 50, '21t8h12h']]
```

Now, when I run the following SQL query using mysql

```
connection.beginTransaction(function (err) {
      if (err) throw err
      connection.query(`
        INSERT INTO FAB_BCGH (OCNO, CUSTNAME, STYLENO, STYLDESC) VALUES (${mysql.escape(OC)}, ${mysql.escape(CustName)}, ${mysql.escape(StyleNo)}, ${mysql.escape(StyleDesc)})
        on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
        SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
        INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, ${mysql.escape(ItemNo)}, ${mysql.escape(ItemDesc)}, ${mysql.escape(tableData.length)})
        on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
        SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;
        INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, PONO) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, ?)
        on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
      `, nestedData, function(err, results, fields) {
        if (err) {
          return connection.rollback(() => {
            throw err
          })
        }
        connection.commit(err => {
          if (err) {
            return connection.rollback(() => {
              throw err
            })
          }
          console.log('Committed')
        })
        console.log(results)
      })
    })
```

I want the following SQL result:
```
BEGIN;
INSERT INTO `FAB_BCGH` (`OCNO`, `CUSTNAME`, `STYLENO`, `STYLDESC`) VALUES(1, 'FATFACE', 'w2526', '12t1g13g')
on duplicate key update BCGUNIQ = LAST_INSERT_ID(BCGUNIQ);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_1;
INSERT INTO FAB_BCGD(BCGUNIQ, ITEMCODE, ITEMDESC, TTLROLLGEN) VALUES (@last_inserted_id_var_1, '2i2ht12t', 'white', 1000)
on duplicate key update BCGLINE = LAST_INSERT_ID(BCGLINE), TTLROLLGEN = TTLROLLGEN + VALUES(TTLROLLGEN);
SELECT LAST_INSERT_ID() INTO @last_inserted_id_var_2;

INSERT INTO FAB_BCGR (`BCGUNIQ`, `BCGLINE`, `ROLLNO`, `RLENGTH`, `PONO`) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, '123456', 100, 50, '21t8h12h'), (@last_inserted_id_var_1, @last_inserted_id_var_2, '12367', 100, 50, '21t8h12h')
on duplicate key update BCGREVL = LAST_INSERT_ID(BCGREVL);
COMMIT;
```

If you look at the last INSERT statement, which is right after the line break, you'll notice there are two sets of VALUES being provided. I want to be able to provide an N set of values.

However, when I insert those N sets of values, I need the two variables:
`@last_inserted_id_var_1` and `@last_inserted_id_var_2`. Unfortunately, I can't seem to do something like the following

```
INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, PONO) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, ?), nestedData, function(err, results, fields) {}
```

This only inserts the first row from my nested array. I'm not sure why, though. 

If I try to change it to 

```
INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, PONO) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, ?, ?, ?), nestedData, function(err, results, fields) {}
```

I get the following error:

`Column count doesn't match value count at row 1`

Hopefully, this explains more clearly what I was trying to accomplish?

**Comment by kai-koch** [comment]
A nesteddata array does not work for your usecase.
If you have an nested array like:
```JavaScript
nesteData = [[123456, 100, 50, '21t8h12h'], [123678, 100, 50, '21t8h12h']];
```
This is transformed with the values escaped into:

```(123456, 100, 50, '21t8h12h'), (123678, 100, 50, '21t8h12h')```

Which is convenient when you got a simple Bulk-Insert like:
```mysql
INSERT INTO myTable (A,B,C,D) VALUES ?
```
and have the end result of:
```mysql
INSERT INTO myTable (A,B,C,D)
 VALUES (123456, 100, 50, '21t8h12h'), (123678, 100, 50, '21t8h12h')
```

Your example SQL-String would have the result:
```mysql
INSERT INTO FAB_BCGR (BCGUNIQ, BCGLINE, ROLLNO, RLENGTH, PONO)
VALUES (
    @last_inserted_id_var_1,
    @last_inserted_id_var_2,
    (123456, 100, 50, '21t8h12h'),
    (123678, 100, 50, '21t8h12h')
)
```

What you try to do is:
Mixing serverside mysql variables ```@last_inserted_id_var_1, @last_inserted_id_var_2``` with clientside data provided by JavaScript.

So building the Query with ```mysql.escape()``` is the way to go for your usecase, even if it looks a bit ugly.

The 'nestedData' functionality is convenient for simple Bulk-Statements. Under the Hood it use ```mysql.escape()``` just the same as you have in one of your examples.

**Comment by redixhumayun** [comment]
@kai-koch So when you say

> So building the Query with mysql.escape() is the way to go for your usecase, even if it looks a bit ugly.

can you give me an example of what that would look like for my use case? Is it the same as what I've already done using two separate transactions?

**Comment by kai-koch** [comment]
@redixhumayun 

```JavaScript
var myData = [[1, "a", 3], [4, "b", 6], [7, "c", 9]],
    i = 0, iLen = myData.length, sql = '';

for (i; i < iLen; i += 1) {
    sql = 'INSERT INTO myTable (ID1, ID2, A, B, C)'
        + ' VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, '
        + [
            con.escape(myData[i][0]), con.escape(myData[i][1]), con.escape(myData[i][2])
        ].join(', ') // [1,2,3].join(', ') = '1, 'a', 3'
        + ');';
    // INSERT INTO myTable (ID1, ID2, A, B, C) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, 1, 'a', 3);
    // INSERT INTO myTable (ID1, ID2, A, B, C) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, 4, 'b', 6);
    // INSERT INTO myTable (ID1, ID2, A, B, C) VALUES (@last_inserted_id_var_1, @last_inserted_id_var_2, 7, 'c', 9);
    con.query(sql, function (err, results, fields) {
        // this is the anonymous call back for one insert only
        // each query is enqued to be exacuted somewhen after the this tick
        if (err) { throw err; }
        console.log(results];
        console.log(fields);
    });
}
// => next tick the callback start coming in
```
In this code the whole myData array will be processed at once and each row creates an own query and callback. so if you have many data-rows enable multiple line statements or do only chunks of the data array , and wait for the callbacks to come back and then enqueue more rows only. 

How many rows at once depends on your server setup, but it is certainly not a good idea to queue up 10000 Rows in one event loop tick. (Overhead in Node.JS and DOS-ing your DB-Server.)

**Comment by kai-koch** [comment]
Or the short answer would have been:
"yes the way you already did it." ;-)

**Comment by redixhumayun** [comment]
@kai-koch I just realised I never thanked you for your answer! So, thank you!
