### ISSUE TITLE
UTC dates and dateStrings option default

### ISSUE THREAD

**Issue by adadgio** [mysqljs/mysql#2252]
Why would dateStrings be false by default ? In my opinion It is *not* the job of the library to change a mysql DATETIME string.

**Comment by dougwilson** [comment]
Mainly because type casting in on by default. Without type casting everything would be a string over the mysql protocol (dates, times, numbers, etc.). Over the years users wanted to interact with native types of Javascript.

The module provides the ability to configure it how you like, though.
