### ISSUE TITLE
Get a possible security issue.

### ISSUE THREAD

**Issue by ZeddYu** [mysqljs/mysql#2258]
Sorry for ignoring the security rules. And I may find a possible security issue. Who should I report?

**Comment by dougwilson** [comment]
You can report it to me, though I already have the report you filed, so you would only need to email me if you want to have a further conversation or updates.

Here is my email from the package data:

https://github.com/mysqljs/mysql/blob/99d6f78ba00f926de162dbef42865029b6e8ec39/package.json#L10
