### ISSUE TITLE
nestTables with generated columns, blank key

### ISSUE THREAD

**Issue by sh0ber** [mysqljs/mysql#2260]
When using nestTables, generated columns based on a MySQL function are placed under an empty string key instead of the appropriate table key.  Is there a fix/workaround for this?

EXAMPLE:
Query:
"SELECT orders.id, date_format(orders.date, '%m/%d/%Y') AS orderdate FROM orders";

Expected:
[{
  "orders":{
    "id":10,
    "orderdate":"04/09/2018"
  }
}]

Returns:
[{
  "orders":{
    "id":10
  },
  "":{
    "orderdate":"04/09/2018"
  }
}]

**Comment by dougwilson** [comment]
They are just placed under the name of the column and table that the MySQL server is sending back to this module.

With nest tables it prefixes all column names with the given name of the table. The MySQL server always returns an empty table name for a calculated column, without any additional information to know what table the column belongs to, unfortunately.
