### ISSUE TITLE
Received invalid filler

### ISSUE THREAD

**Issue by xuhp** [mysqljs/mysql#2262]
Sometimes I can connect properly， but sometimes I have the following problems。What can cause the following problems？

![image](https://user-images.githubusercontent.com/4987802/64017183-95f78580-cb5b-11e9-8b1e-6769b7ee4621.png)

**Comment by dougwilson** [comment]
Can you use a product like Wireshark to capture the packets that are exchanged between the client and server when that happens?

**Comment by dougwilson** [comment]
Closing due to no response.
