### ISSUE TITLE
BETWEEN does not work

### ISSUE THREAD

**Issue by etisdew** [mysqljs/mysql#2265]
I cannot affect the schema as this is a read only database. We have unix timestamps that I'd like to perform a where between query on. I get valid results from mysql itself but through this I get absolutely nothing not even an error.

Would any be willing to attempt a select {something} from {somewhere} where timestamp between {some lower value} and {some upper limit}; ? I believe it is failing in this package. Stamps are INT.

ie

`SELECT * FROM actions WHERE stamp BETWEEN '1000000000' AND '1567630955' ORDER BY stamp DESC LIMIT 100;`

Thank you for your attention.

version 5.7 server with package 2.17.1

**Comment by dougwilson** [comment]
Hi @etisdew sorry you're having trouble. The MySQL `BETWEEN` can have various results depending on the types of both the arguments you have provided it (strings in your example) and the type of the columns. Without the DDL of your table, I cannot say what the expected out come is for your case when providing stings to `BETWEEN`.

How `BETWEEN` works is documented in the MySQL manual here: https://dev.mysql.com/doc/refman/8.0/en/comparison-operators.html#operator_between as well as you can find the rules for how it works with mis-matched types here: https://dev.mysql.com/doc/refman/8.0/en/type-conversion.html

You say they are INTs, so if you are providing strings, typically the MySQL server returns no results in that situation. Have you tried using plain numbers in your `BETWEEN`? For example:

```sql
SELECT * FROM actions WHERE stamp BETWEEN 1000000000 AND 1567630955 ORDER BY stamp DESC LIMIT 100;
```

**Comment by etisdew** [comment]
Yes I have, I have also read the documentation. I can also run the command outside in the cli, aswell as all other querys I'v needed.

**Comment by dougwilson** [comment]
That is very strange indeed. Sorry you're having trouble. Would you be able to add `debug: true` to your code (see https://github.com/mysqljs/mysql#debugging-and-reporting-problems) and then run that query and paste all the output it produces here? Hopefully that should be enough to see what is going on.

**Comment by etisdew** [comment]
Unfortunately I could only take my work home in spirit tonight. I take it you have no issue with a between on unix timestamp?

**Comment by dougwilson** [comment]
There is no such column type as a UNIX timestamp in MySQL that I am aware of. What is the exact type of the MySQL column you are trying to use `BETWEEN` on?

**Comment by etisdew** [comment]
they are usually stored as ints

**Comment by dougwilson** [comment]
So if it is an `INT`, no, I have never had an issue using this module to do `BETWEEN` on INT columns.

**Comment by etisdew** [comment]
and have you tested 2.17.1?

**Comment by dougwilson** [comment]
Yes, I use this module in several of my own product apps, always the latest version.

**Comment by etisdew** [comment]
I'll need to see if there is any debug output for more information. Have you found any common incompatabilitys with node and datatypes for instance? Traps to step into? I'm most perplexed I get no feedback what might be happening, no errors, everything perfect around the specific query, query working outside the application. Going mad, thank you.

**Comment by dougwilson** [comment]
I just tried right now with 2.17.1 of this module in MySQL server 5.7.27 the following, with no issue:
```js
var conn = mysql.createConnection({ /* my details */);
conn.query('CREATE TEMPORARY TABLE `issue_2265` (id INT PRIMARY KEY)');
conn.query('INSERT INTO issue_2265 (id) VALUES (1),(2),(3),(4),(5),(6),(7),(8),(9)');
conn.query('SELECT * FROM issue_2265 WHERE id BETWEEN 4 AND 8', function (err, rows) {
  if (err) throw err;
  console.dir(rows);
});
```
and the output is:
```
[
RowDataPacket { id: 4 },
RowDataPacket { id: 5 },
RowDataPacket { id: 6 },
RowDataPacket { id: 7' },
RowDataPacket { id: 8 }
]
```

I'm not aware of any incompatibilities with data types. This module just implements the MySQL protocol. Under the hood, that protocol simply sends your query as a text string to the MySQL server and the server is what parses and runs the query. Then it sends back the row results the same as it would for any query, no matter what the `WHERE` looked like.

**Comment by etisdew** [comment]
Thats the expectation and what I love about this module. I really appriciate you taking a moment to look at this with me this late. I'm up against a milestone and would really hate life replacing. :( Tomorrows gunna be a long day.

**Comment by dougwilson** [comment]
It's no problem. I wish I knew what was wrong to just have solution for you :(

**Comment by dougwilson** [comment]
But yea, just thinking of things I would check if I were in your shoes, when you are back in the grind:

If you add `debug: true` to your connection, you can watch the output. Check that (a) you see the query you expect to see with the BETWEEN and then see what the results back are for it

Then, based on what that displayed, I could see three different paths:

(a) You saw no BETWEEN or the wrong query -- then run though the logic that should be sending / constructing said query, as there may be an issue there

(b) You saw the query and there were results shown -- then run though the logic that shuttles the results from this module to where you're expecting to see them, as there may be an issue there

(c) You saw the query but it displayed there were no results -- validate that it is going against the expected database / user / server.

That may not be the only things, but hopefully that list will help out when you get back to it. There is certainly a possibility there is a bug in this module too -- I'm definately not going to rule it out, as you never really know.

**Comment by etisdew** [comment]
Expecting 7 entrys from query, confirmed working when sent as plain query to cli. Unable to potentially leak sensitive information. Strong suspicion that the large ints were creating this issue. Confirmed that is not the issue. Query confirmed as composed correctly with three other partys. Server confirmed as correct. Is it possible its being flagged as a compound statement with an AND?

[sendlog.txt](https://github.com/mysqljs/mysql/files/3581374/sendlog.txt)

**Comment by dougwilson** [comment]
Hi @etisdew thanks for that log. I assume that last query with the `BETWEEN` is the one in question? I'm not sure what was in the `...` spot that was cut out, but I guess just 7 more `FieldPacket`s, right? If so, the server itself is saying there are no results, so if that query sent is the correct query, then there is nothing this module can do in this case to correct the issue, as it is not sending back any results.

This is because in the response sequence, you get the `ResultSetHeaderPacket`, which signals how many fields are in the results (8), then that many `FieldPacket`s next, then the `EofPacket` to signal the end of fields, then the number of `RawDataPackets` for each of the result rows, then then `EofPacket` to signal the end of results. Zero result rows would be inticated by the server with the double EofPackets at the end, as you are seeing.

You can find this flow diagramed out in the MySQL server protocol documentation from Oracle here: https://dev.mysql.com/doc/internals/en/com-query-response.html#packet-COM_QUERY_Response

I'm not sure there is anything further I can say here besides the logs are showing that at the protocol level your MySQL server is returning zero result rows. Probably the only way to really more forward here is perhaps you can provide all relevant instructions such that I can get a replication of this set up on my end to just trial and error to determine what is happening. It could even be some kind of arcane bug in the MySQL server itself, I'm not sure.

How the other clients with the exact same query are getting results are beyond me. Perhaps a network-level packet capture of the transaction between one of those other clients and the MySQL server would provide some answers.

**Comment by etisdew** [comment]
I goofed and failed to sanitize two words of the log, but on deeper inspection of the logs I see no hints toward an issue. Appears as a valid query without any results. But because I don't see any way to even ask for help at this point Im going to unclutter your issue board with this item.

**Comment by etisdew** [comment]
Going to request a migrational field with proper date format and see if I can work with that. The size of the query without a range is simply too large to handle sort and filter client side.

**Comment by zhuangrb** [comment]
i sorry to make issue here, but question is really hard to me. question is:  **mysql explode string into one column**

**Comment by kai-koch** [comment]
@zhuangrb try concat() . Look under String- functions in the MySQL
documentation.
