### ISSUE TITLE
Question: How to get total results in a paginated query?

### ISSUE THREAD

**Issue by bonbonio** [mysqljs/mysql#2272]
I am doing a select query with a limit and offset, but I'd still like to know the total rows possible to return (For a x-total-count header), is there a way to do this within a single query, perhaps using SQL_CALC_FOUND_ROWS?

Many Thanks - if its documented then I apologise, but I did look!

**Comment by dougwilson** [comment]
Hi @bonbonio this would be done the same way with any MySQL client software, as it is specific to your MySQL server and not related to which client software you are using. MySQL does not provide a way to do this with a single query -- you must perform two separate queries. You can find the MySQL documentation on SQL_CALC_FOUND_ROWS here: https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_found-rows
