### ISSUE TITLE
when $ is at the last character of the text, escape removes it

### ISSUE THREAD

**Issue by shamseertk** [mysqljs/mysql#2273]
let's say if name =' test $' ,   If I use params={ '@name': `${mysql.escape(name)}`}  or params={ '@name': mysql.escape(name)} ,  the insert query I get looks like: VALUES( 'test , 'TEST,TEST',...) 

the issue happens only when $ is at the last character of the text, escape removes it

Is there any workaround?

**Comment by dougwilson** [comment]
Hi @shamseertk thanks for the report! Unfortunately I cannot reproduce the issue. Perhaps can you provide the information recommended for opening issue at https://github.com/mysqljs/mysql#debugging-and-reporting-problems ?

Here is the code example that I tried on version 2.17.1 of this module, Node.js 12.10.0:
```
$ node -pe 'require("mysql").escape("test $")'
'test $'
```

You can see the returned value does have the `$` character at the end, as expected.The code you provided above doesn't seem to be valid JavaScript code, so I'm unsure how to run it, exactly.

**Comment by dougwilson** [comment]
Closing due to no response.
