### ISSUE TITLE
How to return the result of sql execution to the outer function? In the callback function

### ISSUE THREAD

**Issue by liukai90** [mysqljs/mysql#2278]
When I execute sql, I need to return the query result to the upper layer call, and how to return the result in the callback function.
```js
var mysql = require('mysql');
var pool = mysql.createPool({
    connectionLimit : 10,
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: 'root',
    database: 'chat'
});
function getUserByAccount(account) {
    let result = null;
        pool.query('select * from user where account = ?',account).on('result', (res) => {
            result = res;
        });
    return result;
    
}

```

**Comment by dougwilson** [comment]
Hi @liukai90 and welcome to Node.js. You cannot do what you are trying to do. Node.js has an introduction to using callbacks here: https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/

The gist is that you need to have your `getUserByAccount` function take a callback itself and then call that callback with the result from within the MySQL callback. Example:
```js
var mysql = require('mysql');
var pool = mysql.createPool({
    connectionLimit : 10,
    host: 'localhost',
    port: 3306,
    user: 'root',
    password: 'root',
    database: 'chat'
});
function getUserByAccount(account, callback) {
        pool.query('select * from user where account = ?',account).on('result', (res) => {
            callback(res);
        });
    
}
```

**Comment by liukai90** [comment]
> 大家好@ liukai90，欢迎来到Node.js。您无法做您想做的事。Node.js在这里介绍了使用回调的方法：[https](https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/)：[//nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/](https://nodejs.org/en/knowledge/getting-started/control-flow/what-are-callbacks/)
> 
> 要点是，您需要让`getUserByAccount`函数本身执行一个回调，然后使用MySQL回调中的结果调用该回调。例：
> 
> ```js
> var mysql =  require（' mysql '）;
> var pool =  mysql。createPool（{
>     connectionLimit ： 10，
>     主机： ' localhost '，
>     端口： 3306，
>     用户： “ root ”，
>     密码： ' root '，
>     数据库： “聊天”
> }）;
> 函数 getUserByAccount（帐户，回调）{
>          池。查询（“从用户帐户中选择*，其中account =？”，帐户）。on（' result '，（res）=> {
>              回调（res）;
>         }）;
>     
> }
> ```
I want to return the result value to the upper layer, just like promise and async awit。

**Comment by dougwilson** [comment]
If you want to use it in a promise form, it would be done just like anything else from Node.js like fs.readFile: use https://nodejs.org/dist/latest-v12.x/docs/api/util.html#util_util_promisify_original
