### ISSUE TITLE
Amazon certs expiring in March 2020

### ISSUE THREAD

**Issue by winzig** [mysqljs/mysql#2281]
Received some warnings from Amazon about their RDS certs expiring in March 2020. They want people to switch over to using the new certs by the end of this month. The certs can be found on this page: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html

**Comment by dougwilson** [comment]
Thanks for the note. @codebykenny made PR #2280 with the new root cert I'm landing here in the next release this week.

**Comment by tobias7an** [comment]
As the deadline for this update requirement is approaching, would a timely release with PR #2280  resolving this issue be something users could still expect, or should all impacted users pursue other solutions?

**Comment by dougwilson** [comment]
The API of this module allows you to pass in any CA certs you want and an upgrade to this module in no way prevents you from using the updated certificates. If you think that the PR is required before you can use updated certificates, please let me know how we can clarify the README in how you can provide any certificates that you want.

**Comment by winzig** [comment]
I didn't realize this was possible, so it seems fine. However, if the plan is not to continue to support RDS out of the box, shouldn't it be removed completely from the options so as to avoid confusion?

**Comment by dougwilson** [comment]
Closing this to track landing in #2280
