### ISSUE TITLE
mysql.format() parameter count issue

### ISSUE THREAD

**Issue by jabarihunt** [mysqljs/mysql#2289]
Suppose you have the following...

```javascript
let query = 'INSERT INTO contacts (name, email, timestamp) VALUES (?, ?, UNIX_TIMESTAMP())';
let values = ['John', 'john@doe.com'];

let formattedQuery = mysql.format(query, values);

```
The following error will be thrown:
>ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count

I'm not sure why this is.  Maybe it's using something like `params.split(',')` rather than counting the number of question marks?!?!?  This can get _REALLY_ confusing for certain queries.  Take for example...

```javascript
let query = 'INSERT INTO contacts (name, email, timestamp) VALUES (?, ?, UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE timestamp = ?';
let values = ['John', 'john@doe.com', '1234567'];
```

The number of question marks match the number of values, so someone may spend quite a bit of time trying to figure out why they are getting an error related to a mismatch count!  I believe it should count values based on the number question marks (or double question marks in the case of column names).

**Comment by dougwilson** [comment]
Hi @jabarihunt sorry for the trouble. This module just counts the question marks, like you are expecting. I'm not sure what you're asking for, I'm sorry.

In your example,
```js
let query = 'INSERT INTO contacts (name, email, timestamp) VALUES (?, ?, UNIX_TIMESTAMP())';
let values = ['John', 'john@doe.com'];

let formattedQuery = mysql.format(query, values);
```

The output of `formattedQuery` is the following:
```
INSERT INTO contacts (name, email, timestamp) VALUES ('John', 'john@doe.com', UNIX_TIMESTAMP())
```

What about that is unexpected?

Your second example,
```js
let query = 'INSERT INTO contacts (name, email, timestamp) VALUES (?, ?, UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE timestamp = ?';
let values = ['John', 'john@doe.com', '1234567'];
let formattedQuery = mysql.format(query, values);
```


The output of `formattedQuery` is the following:
```
INSERT INTO contacts (name, email, timestamp) VALUES ('John', 'john@doe.com', UNIX_TIMESTAMP()) ON DUPLICATE KEY UPDATE timestamp = '1234567'
```


So if that is not what you're expecting, can you help us understand what you're expecting the output to be?

**Comment by jabarihunt** [comment]
@dougwilson Very weird...I'm getting the error I mentioned in my post.  I'm running this on a GCP function and consistently get that error.

**Comment by dougwilson** [comment]
Right, I'm not doubting you're getting that error, but based on what was posted I guess I have no idea why that would be. Is there any more information you can provide to help? Otherwise I'm not sure what we can do to fix it, unfortunately.

**Comment by jabarihunt** [comment]
I ran it in a different environment and it's working fine.  It must be something related to this GCP instance.  I'm closing the issue, thank you!
