### ISSUE TITLE
Error: (Node 9304) 

### ISSUE THREAD

**Issue by Spenoabdiel** [mysqljs/mysql#2290]
It says, “Error: (Node: 9304) UnhandledPromiseRejectionWarinng: AssertionError [ERR_ASSERTION]: unexpected PromiseRejectEvent
![A26A904D-DB33-4F51-90A2-219B20041360](https://user-images.githubusercontent.com/60018997/72689546-70eeb980-3ae0-11ea-9900-d2012dc6233b.jpeg)
![6F2DC029-0353-4DED-8A0D-F1920634CD7B](https://user-images.githubusercontent.com/60018997/72689547-70eeb980-3ae0-11ea-8bc7-bacd61df0683.jpeg)
![1196B2E6-031F-4075-B1AD-5EED99344EA8](https://user-images.githubusercontent.com/60018997/72689548-70eeb980-3ae0-11ea-8a22-4439bcc05393.jpeg)
![2E192ED2-B0FA-45F9-9669-92671EFB0629](https://user-images.githubusercontent.com/60018997/72689549-70eeb980-3ae0-11ea-9c2c-c861e5b583d4.jpeg)
![898D8E5E-00F6-488C-AC83-6C1989C7247F](https://user-images.githubusercontent.com/60018997/72689550-70eeb980-3ae0-11ea-985b-6ac6ad200f75.jpeg)
![BAD62763-33A4-4ACA-B02A-0C8FF1CA2731](https://user-images.githubusercontent.com/60018997/72689551-71875000-3ae0-11ea-89a4-7025280efd6d.jpeg)

**Comment by dougwilson** [comment]
I don't think that is an issue in this module as (1) this module does not use promises and (2) none of the stack traces are from this module.

**Comment by Spenoabdiel** [comment]
And then where can I get help? I dont know how to fix it.

**Comment by dougwilson** [comment]
What are you using? There is not enough information provided to understand the issue.

**Comment by Spenoabdiel** [comment]
Im using HeidiSQL, Xampp.. Im trying to setup my FXServer_ESX, everything loads good, until those error that I posted, Im not sure on what promises is, I’ve been looking videos to fix it but they are old.

**Comment by dougwilson** [comment]
I haven't heard of any of those things you listed...

**Comment by Spenoabdiel** [comment]
Oh ok, and then what kind of SQL you recommend me? The ESX is a script for a roleplay server, im getting frustrated men

**Comment by dougwilson** [comment]
I'm still not familiar with what you are asking. "What kind of SQL"? "The ESX"? What role play server? Is that something you're building?
