### ISSUE TITLE
how to properly parse response return after running store procedure.

### ISSUE THREAD

**Issue by kashifaliquazi** [mysqljs/mysql#2294]
clientConnection.query('set '@insertedId =0 ; call testSp(); select '@insertedId;',function(err,res){
    console.log(err);
    if(err!=null)
    reject(err)
    resolve(res);
  });

This call return response [ OkPacket {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 10,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 },
  [ RowDataPacket {
      eventId: '5e300aee762f4394f5f92d6b',
      messageFrom: 'ccb41bc2-1934-427c-980c-6dafa5fd9708',
      MessageTo: '0f3c5b55-b4e6-4185-b4d2-32c7ab1bd7d4',
      textMessage: '12345678' } ],
  [ RowDataPacket { chat_details_id: 21 } ],
  [ RowDataPacket { 'Message Sent': 'Message Sent' } ],
  OkPacket {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 42,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0 },
  [ RowDataPacket { '@insertedId': 45 } ] ]

I am not able to extract '@insertedId from response.

Please help!

**Comment by dougwilson** [comment]
`res[2].['@insertedId']`
