### ISSUE TITLE
Strange `nestTable` behavior

### ISSUE THREAD

**Issue by atlascoder** [mysqljs/mysql#2295]
I have the following tables (pseudo):

TableA:
```
+-----------+-------------+------+-----+---------+----------------+
| Field     | Type        | Null | Key | Default | Extra          |
+-----------+-------------+------+-----+---------+----------------+
| TableA_id | int(11)     | NO   | PRI | NULL    | auto_increment |
| text      | varchar(45) | YES  |     | NULL    |                |
+-----------+-------------+------+-----+---------+----------------+
```

TableB:
```
+-----------+-------------+------+-----+---------+----------------+
| Field     | Type        | Null | Key | Default | Extra          |
+-----------+-------------+------+-----+---------+----------------+
| TableB_id | int(11)     | NO   | PRI | NULL    | auto_increment |
| TableA_id | int(11)     | NO   |     | NULL    |                |
| TableC_id | int(11)     | NO   |     | NULL    |                |
| text      | varchar(45) | YES  |     | NULL    |                |
+-----------+-------------+------+-----+---------+----------------+
```

TableC:
```
+-----------+-------------+------+-----+---------+----------------+
| Field     | Type        | Null | Key | Default | Extra          |
+-----------+-------------+------+-----+---------+----------------+
| TableC_id | int(11)     | NO   | PRI | NULL    | auto_increment |
| text      | varchar(45) | YES  |     | NULL    |                |
+-----------+-------------+------+-----+---------+----------------+
```

TableD:
```
+-----------+-------------+------+-----+---------+----------------+
| Field     | Type        | Null | Key | Default | Extra          |
+-----------+-------------+------+-----+---------+----------------+
| TableD_id | int(11)     | NO   | PRI | NULL    | auto_increment |
| TableB_id | int(11)     | NO   |     | NULL    |                |
| text      | varchar(45) | YES  |     | NULL    |                |
+-----------+-------------+------+-----+---------+----------------+
```
Tables with data: [test_tables.txt](https://github.com/mysqljs/mysql/files/4127986/test_tables.txt)

And I use the following code to select required data:
```
    const sql = 
        `SELECT * FROM TableA a \
         INNER JOIN TableB b USING(TableA_id) \
         INNER JOIN TableC c USING(TableC_id) \
         INNER JOIN TableD d USING(TableB_id) \
         WHERE a.TableA_id = ?`;
         
    connection.query(
        {sql: sql, nestTables: true},
        [1],
        (e,r) =>{
            if (e) {
                callback(e);
            }
            else {
                console.log(JSON.stringify(r));
                callback(null, r);
            }
        }
    );

```

Data are being fetched, but the structure looks strange: `TableB.TableA_id`, `TableC.TableC_id` and `TableD.TableB_id` - are absent:
```
[
    {
        "b":{
            "TableB_id":1,
            "TableC_id":1,
            "text":"B1"
        },
        "a":{
            "TableA_id":1,
            "text":"A1"
        },
        "c":{
            "text":"C1"
        },
        "d":{
            "TableD_id":1,
            "text":"D1"
        }
    },
    {
        "b":{
            "TableB_id":2,
            "TableC_id":2,
            "text":"B2"
        },
        "a":{
            "TableA_id":1,
            "text":"A1"
        },
        "c":{
            "text":"C2"
        },
        "d":{
            "TableD_id":2,
            "text":"D2"
        }
    },
    {
        "b":{
            "TableB_id":3,
            "TableC_id":3,
            "text":"B3"
        },
        "a":{
            "TableA_id":1,
            "text":"A1"
        },
        "c":{
            "text":"C3"
        },
        "d":{
            "TableD_id":3,
            "text":"D3"
        }
    }
]
```

When I use `nestTable: '_'` I also don't these keys: `c_TableC_id` is absent.

Using the both options for `nestTable` I get values for the expected keys, but they appear in referenced tables, e.g., actual value of `TableC_id` appears in the `b` object or like `b_TableC_id`.

I understand that this must be not a bug, but rather a design feature. But I think this is not the best solution, because, in the result we expect to see full data from appropriate tables, even if these data are duplicated.

Though the current solution makes more compact results - is it possible to make an option for full data response?

**UPDATE**

It works as expected when using Joins with `ON` instead of `USING` even if field names are the same - the following SQL returns full response:
```
    const sql = 
        `SELECT * FROM TableA a \
         INNER JOIN TableB b ON b.TableA_id = a.TableA.id \
         INNER JOIN TableC c ON c.TableC_id = b.TableC_id) \
         INNER JOIN TableD d ON d.TableB_id = b.TableB_id) \
         WHERE a.TableA_id = ?`;
```

And now it looks more like inconsistent behavior, because, if I am not mistaking, `USING` is an equivalent to `ON` if tables are linked by fields having the same names, and switching between `USING` and `ON` should not change query results.

**Comment by dougwilson** [comment]
Hi @atlascoder it is likely that the MySQL server is what is not sending the duplicated columns. If you're interested in the internal workings: MySQL server protocol sends data in columns, with each column having a name and a schema (table name). The nested table feature of this module just combines what comes from MySQL server with the character you provide. Missing data typically indicates that MySQL server is just not sending what you're expecting it to send -- and this module doesn't know the structures of your tables and data beyond what the MySQL server sends back.

Can you add `debug: true` to your `createConnection` or `createPool` config and then paste the debug information that prints when making the query above?

**Comment by dougwilson** [comment]
> And now it looks more like inconsistent behavior, because, if I am not mistaking, USING is an equivalent to ON if tables are linked by fields having the same names, and switching between USING and ON should not change query results.

Sorry, I didn't see your update when I wrote the above response. If what you're saying it true, the bug would be in your MySQL server, and not in this module. If you perform the `debug: true` test in my previous comment on both queries, and you see different column sets, then indeed the issue is in the way in which the MySQL server is sending the data back to the client (this module).

**Comment by atlascoder** [comment]
Hi, @dougwilson!

I attached the logs for several options.

But I understand your point: the issue is not in the module - it is in the mysql client or server. Below are outputs from mysql client (mysql  Ver 14.14 Distrib 5.7.29, for Linux (x86_64) using  EditLine wrapper), and they show that outputs for `ON` and `USING` joins are different:

```
mysql> SELECT * FROM TableA a INNER JOIN TableB b USING(TableA_id) INNER JOIN TableC c USING(TableC_id) INNER JOIN TableD d USING(TableB_id) WHERE a.TableA_id = 1;
+-----------+-----------+-----------+------+------+------+-----------+------+
| TableB_id | TableC_id | TableA_id | text | text | text | TableD_id | text |
+-----------+-----------+-----------+------+------+------+-----------+------+
|         1 |         1 |         1 | A1   | B1   | C1   |         1 | D1   |
|         2 |         2 |         1 | A1   | B2   | C2   |         2 | D2   |
|         3 |         3 |         1 | A1   | B3   | C3   |         3 | D3   |
+-----------+-----------+-----------+------+------+------+-----------+------+
```

```
mysql> SELECT * FROM TableA a INNER JOIN TableB b ON b.TableA_id = a.TableA_id INNER JOIN TableC c ON c.TableC_id = b.TableC_id INNER JOIN TableD d ON d.TableB_id = b.TableB_id WHERE a.TableA_id = 1;
+-----------+------+-----------+-----------+-----------+------+-----------+------+-----------+-----------+------+
| TableA_id | text | TableB_id | TableA_id | TableC_id | text | TableC_id | text | TableD_id | TableB_id | text |
+-----------+------+-----------+-----------+-----------+------+-----------+------+-----------+-----------+------+
|         1 | A1   |         1 |         1 |         1 | B1   |         1 | C1   |         1 |         1 | D1   |
|         1 | A1   |         2 |         1 |         2 | B2   |         2 | C2   |         2 |         2 | D2   |
|         1 | A1   |         3 |         1 |         3 | B3   |         3 | C3   |         3 |         3 | D3   |
+-----------+------+-----------+-----------+-----------+------+-----------+------+-----------+-----------+------+
```

So, this is of course not about the mysqljs module - it's about my misunderstanding of MySQL JOIN results!

Thank you for helping make it clear!

[debug_with_ON_and_grouped_nest_tables.txt](https://github.com/mysqljs/mysql/files/4137719/debug_with_ON_and_grouped_nest_tables.txt)
[debug_with_USING_and_grouped_nest_tables.txt](https://github.com/mysqljs/mysql/files/4137720/debug_with_USING_and_grouped_nest_tables.txt)
[debug_with_USING_and_prefixed_nest_tables.txt](https://github.com/mysqljs/mysql/files/4137721/debug_with_USING_and_prefixed_nest_tables.txt)
