### ISSUE TITLE
Professional help needed

### ISSUE THREAD

**Issue by telecomsxchange** [mysqljs/mysql#2296]
We are looking for a Node-Mysql expert from the community to help with investigating a strange issue happening between nodejs and mysql using this package.

**Comment by dougwilson** [comment]
Is it possible to write up an issue report on this forum?

**Comment by telecomsxchange** [comment]
mysql query gets stuck in node-mysql sometimes. We do not know how exactly to reproduce it, but last few days it happens really often. We have tried connection pooling, and setting timeouts per query using node-mysql but yet id did not help.
In code sample below we do not make it to "qry complete" step when issue arises. The query itself is very fast and mysql server is OK.

        sql = "SELECT i_account, IF('" + ip + "' = ip_address, 1 , 0) as ipmatch FROM accounts "
                + " WHERE (voip_login = '" + login + "' AND voip_password='" + pass + "' AND ip_address = '" + ip + "') "
                + " OR (voip_login = '" + login + "' AND voip_password='" + pass + "' AND ip_address = '') ORDER BY ipmatch DESC LIMIT 1"
        console.log(sql)
        try {
                console.log("running qry");
                con.query({sql: sql, timeout:200}, function (err, result) {
                        console.log("qry complete")
                        if (err) throw err;
                        console.log("results:", result)
                        if (err && err.code === 'PROTOCOL_SEQUENCE_TIMEOUT') {
                                throw new Error('Dead connection?');
                        }
                        //console.log("Result: ",  result[0].i_account);
                        if(result.length == 0 ) {
                                console.log("account not found for login:" + login + " ip:" + ip);
                                cb(0);
                                return
                        }
                        cb(result[0].i_account)
                });
        } catch (e) {
                console.log("failed query:", sql)
                console.log("error:", e)

        }

**Comment by sidorares** [comment]
@telecomsxchange that `if (err) throw err;` never reaches to `catch (e)` block (because error is thrown from completely different stack to catch block). Try to add some logging when you have error. Best practice for callback-style flow is to call your `cb` function with error and check that error on callback side

**Comment by telecomsxchange** [comment]
there is no err, I don't get that function executed, otherwise there would be "qry completed"

**Comment by dougwilson** [comment]
Hi @telecomsxchange . If you are experiencing this on the regular, it may be worth it to turn on debug mode (https://github.com/mysqljs/mysql#debugging-and-reporting-problems) and then, when it happens again, share the debug output at the time of the issue. The debug logs are printed to STDOUT of the process, and each packet has the connection ID in parenthesis if you want to share just the results from the connection ID that stalled. Ideally the logs should show the Query packet being sent and then whatever came back from the server, if anything.

Depending on what that turns up, there are additional steps we can take.

**Comment by telecomsxchange** [comment]
Thx @dougwilson will try that and update the thread.

**Comment by CovertLeopard** [comment]
@telecomsxchange are you running your function in a Lambda environment on AWS, or is it somewhere else?

**Comment by telecomsxchange** [comment]
We have found the issue and fixed it. It was not a Mysql issue. It was caused by a none asynchronous  NodeJS code. Thanks for all of you who tried to help and collaborate. 

The take a way from all this for us was to use asynchronous code in JS. It makes debugging and troubleshooting similar issues much easier when an issue comes up.  Hope this helps someone. Cheers!
