### ISSUE TITLE
Node Mysql package returns float datatype as whole number

### ISSUE THREAD

**Issue by waleedshabbir1** [mysqljs/mysql#2298]
I am using this package in expressjs.

In database I have a column with float till 2 decimal places

So the values which are in column are 
2.00
2.01
2.02

so on..

When I run a select query 
for value "2.00" I get 2
but for other values like "2.01" I get proper value 2.01

How can I get 2.00 for value "2.00" in query?

However If i run select query on direct database I get the correct results.

**Comment by dougwilson** [comment]
This is a javascript question, as all numbers in javascript are floating point. It sounds like you are asking how to format your javascript numbers like `num.toFixed(2)` method.

**Comment by waleedshabbir1** [comment]
> This is a javascript question, as all numbers in javascript are floating point. It sounds like you are asking how to format your javascript numbers like `num.toFixed(2)` method.

I am making API's and I am quering results from mysql and passing as it is as json. 
in database my column value is saved as 2.00 and when i query it I get 2 only
however for 2.01 I get the value 2.01 which is correct

**Comment by dougwilson** [comment]
What the the colum type?

**Comment by bbito** [comment]
As dougwilson wrote, this has to do with how JavaScript handles numbers, not really with how this mysql module is doing anything. You have the choice of using this module to custom typecast your values into Strings (https://github.com/mysqljs/mysql#custom-type-casting)  or receiving the numbers as you do now and using JavaScript to format the number as needed using `num.toFixed(2)`

**Comment by waleedshabbir1** [comment]
Maybe this picture will explain better

First picture I am running query directly in phpmyadmin

and in the second picture I am running query via mysql node package 

![1](https://user-images.githubusercontent.com/45197387/74114908-eb28d000-4bac-11ea-9253-3b7e36b35ca5.JPG)



![Capture](https://user-images.githubusercontent.com/45197387/74114917-f1b74780-4bac-11ea-824c-961fcafe8906.JPG)

**Comment by waleedshabbir1** [comment]
![Capture](https://user-images.githubusercontent.com/45197387/74114945-0c89bc00-4bad-11ea-8c88-78c75074f0cd.JPG)

**Comment by dougwilson** [comment]
That is because phpmyadmin is formatting your number for display, which you can do with the .toFixed method while this module is lile the programming that is happening behind the scenes in phpmyadmin is just has the raw values. This module is just a programming API and is not comparable with a full UI system with number formatting like phpmyadmin -- you are expected to implement the formatting on top of a module like this to create something like phpmyadmin.
