### ISSUE TITLE
Unable to set minimum TLS version

### ISSUE THREAD

**Issue by alexburley** [mysqljs/mysql#2301]
By default Node12 requires a minimum TLS version of 1.2, it would be nice to override this to resolve compatibility issues with certain MySQL DB versions which only run TLS 1.1 or 1.0.

https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L463

Ideally we could set any https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by dougwilson** [comment]
Are you not able to set it through the existing SSL options? https://github.com/mysqljs/mysql#ssl-options Whatever object you pass in there we just pass directly to Node.js.

**Comment by alexburley** [comment]
I was trying that initially but the only way I can get this to set the minVersion is to assign it directly in https://github.com/mysqljs/mysql/blob/master/lib/Connection.js#L463

**Comment by dougwilson** [comment]
Oh, sorry, I misunderstood your request. You want us to add another property. I was just about to ask which one, but I see you replied that it is `minVersion`.

**Comment by dougwilson** [comment]
> the only way I can get this to set the minVersion is to assign it directly

Well, that or, according to Node.js docs, use https://nodejs.org/api/tls.html#tls_tls_default_min_version , which is not ideal, I get it, but there is at least another way outside of source code modification :)

**Comment by alexburley** [comment]
We can just use Node10 for the moment with our service instead of the cli argument.
Would you be open to me making a PR to allow adding this?

**Comment by dougwilson** [comment]
Yea, absolutely welcome a PR! You can find the basic contribution guidelines at https://github.com/mysqljs/mysql#contributing

For this, I know you linked to just one of the division of environments, so just want to make sure the option works in both of the Node.js version splits and adds the appropriate tests and docs :)

**Comment by alexburley** [comment]
👍 Thanks for the quick replies I'll take a look

**Comment by BrandonNoad** [comment]
Thanks for this @alexburley. I was just about to submit a similar request/PR. 

We want to upgrade to Node v12, but are using MySQL 5.6, which only supports TLSv1.

Let me know if you need any help with the PR.

**Comment by nechama-fel** [comment]
@BrandonNoad 
Hi, I would love to get some help - I have upgraded the node version in my project to v12, but my mySQL only supports TLSv1.
Didn't quit understand how I can overcome this issue.

Thanks!

**Comment by Norah1234** [comment]
@BrandonNoad
Hi, I would love to get some help - I have upgraded the node version in my project to v12, but my mySQL only supports TLSv1.
Didn't quit understand how I can overcome this issue.
Thanks!

**Comment by BrandonNoad** [comment]
@Norah1234 https://github.com/mysqljs/mysql/pull/2304 will fix the issue.

Until it is merged, there is not much you can do unless you want to fork this package and patch it yourself.

**Comment by Norah1234** [comment]
@BrandonNoad , Thanks!
Do you know when it is supposed to be merged?

**Comment by dougwilson** [comment]
Hi guys, I did forget, and of course you posted right at the start of a holiday weekend where I live so cannot attend to it yet. If you can use the command line switch posted above, that is the only solution currently.

**Comment by BrandonNoad** [comment]
No worries @dougwilson. Enjoy your long weekend.

**Comment by nechama-fel** [comment]
@dougwilson 
Thanks for the update! Do you have an ETA when it will be pushed?

**Comment by BrandonNoad** [comment]
@dougwilson Now that the holiday season is over, is there a chance that #2304 will be merged soon? Thanks.

**Comment by brad-bergeron-tm** [comment]
Seconding that we could really use this so we dont run into issues updating from Node 10, which is deprecated in AWS by end of May. Please and thank ya.

**Comment by gilgameshskytrooper** [comment]
Can someone please merge #2304? Thank you

**Comment by dougwilson** [comment]
Oh shoot,I am really sorry. Looks like travis ci went away, even. Let me get the CI fixed here and that merged and released for you. I'm sorry I let it drop like that and thank you for the ping here.

**Comment by JaclynCodes** [comment]
<img width="480" height="480" alt="Image" src="https://github.com/user-attachments/assets/bd9ee805-712c-4f5c-b80f-3142aacc9187" />

**Comment by JaclynCodes** [comment]
.
