### ISSUE TITLE
Getting ER_LOCK_WAIT_TIMEOUT when using pool without transactions

### ISSUE THREAD

**Issue by apoorvans** [mysqljs/mysql#2302]
When running update and insert queries with pool.query I am getting ER_LOCK_WAIT_TIMEOUT. NOT using transactions anywhere.
The queries are small, using indexes, usually take milli seconds to run. 

Creating pool like this:
`const thePool = mysql.createPool({..});`

Using like this:
`export function getDbPool() {
  if (thePool) {
    return thePool;
  } else {
    throw {message: "MySQL pool is not initialized"};
  }
}`

`const db =  getDbPool(); db.query({...}))`

This was working alright for over a year until a month back. Since then occurring regularly & looks like with increasing frequency. Can't figure where to start looking. Any hints appreciated..

**Comment by apoorvans** [comment]
@dougwilson any hint please, this is not going away :(

**Comment by dougwilson** [comment]
If you are using InnoDB storage engine every query is a transaction. This module isn't really doing anything with transactions,  just passing the query commands given to it to the server. Is it possible to make some kind of reproduction steps so I can reproduce the issue?

**Comment by apoorvans** [comment]
> If you are using InnoDB storage engine every query is a transaction. This module isn't really doing anything with transactions, just passing the query commands given to it to the server. Is it possible to make some kind of reproduction steps so I can reproduce the issue?

Thanks for getting back. We are using InnoDB very much. The tables are small ~ half a millions rows & the update queries when they do run normally take 10s of milli seconds. But the number of updates may be large during peak times. Most of these update queries use primary key but there are a couple that may update more than one row and use multiple columns in the where clause.

We figured there is such a thing as transaction isolation level that defaults to "REPEATABLE-READ", we changed it to "READ-COMMITTED" in the hope of fixing this. The guess being that REPEATABLE-READ leads to locking of more rows than those determined by the where clause in the query. So a large number of updates may lead to locks that are waiting for other locks to be released although I can't figure how.

Sorry, don't have much to share by means of reproduction, haven't been able to replicate myself. Please feel free to close the issue.

**Comment by dougwilson** [comment]
Ok. I can always re-open, of course, if the issue is with this library. I have a similar setup on one of my databases and get lock wait timeouts too (using a Java client, not this one) and the solution we ended up with was to manually start a transaction, run `SELECT ... FOR UPDATE`, then run the UPDATE, then commit the transaction (https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html). Not sure if there is a simpler solution or if that will work for you or not. Stackoverflow may be a better place to get generic MySQL usage help as well, better quality than mine at least :)
