### ISSUE TITLE
ssl-mode options is not valid

### ISSUE THREAD

**Issue by Cherviakov** [mysqljs/mysql#2312]
I'm using following command to connect to mysql:
```
mysql -u user -h host -p --ssl-cert client-cert.pem --ssl-mode=REQUIRED --ssl-key client-key.pem
```
In mysql nodejs driver there no ssl-mode option, when I tried to specify just key and cert I got access denied from mysql, and when I tried to put options to connection URL (accodring  to [this](https://dev.mysql.com/doc/refman/8.0/en/connecting-using-uri-or-key-value-pairs.html) ) I got error saying that ssl-mode, ssl-key and ssl-cert options are not valid.

Is there any other way to achieve this? Or any plan to support ssl-mode option?

**Comment by dougwilson** [comment]
Hello! The SSL options that are available are listed here: https://github.com/mysqljs/mysql#ssl-options

Both `ssl-mode=REQUIRED` or using client certificates are not currently implemented in this library, so if that is desired, then a pull request is welcome to add such parameters to the `ssl` option.

**Comment by Cherviakov** [comment]
Thank you for quick response. Understood.

**Comment by sidorares** [comment]
@Cherviakov according to this example client certs work just fine with this library - https://techsparx.com/software-development/docker/damp/mysql-ssl-connection.html

just pass ` cert: fs.readFileSync(__dirname + '/certs/client-cert.pem')` in ssl options

**Comment by dougwilson** [comment]
@sidorares you're right! My mistake. I should add a test to the test suite. So it is just ssl-mode required we don't have an option to do cutting (fail the connection if no ssl).

**Comment by Cherviakov** [comment]
I was thinking to try client certs tomorrow anyway but seems you got here faster @sidorares 
Thanks for update.

**Comment by Cherviakov** [comment]
Even though it was done countless of time around will put here my results. 
This code worked:
```
 25     if (isProd) {
 26       options = {
 27         ...options,
 28         dialectOptions: {
 29           ssl: {
 30             ca,
 31           },
 32         }   
 33       };  
 34     }
```
Adding key and cert properties with ca to dialectOptions.ssl seems has no  effect (can pass any value for those props). Passing key and cert without ca produce self-signed certifcates in certifcate chain error.
Also tried to pass rejectUnauthorized: false, which effectievly make things work even without any certificates, therefore connection established without ssl and everything is wide open to read for everyone.

**Comment by sidorares** [comment]
@Cherviakov is that when used together with ORM? Can you reduce to example using this library directly, otherwise probably better to rise an issue on orm side

**Comment by Cherviakov** [comment]
Oh yes, sorry. Will update code a bit later today.

**Comment by Cherviakov** [comment]
@sidorares updated and checked that same is take place for this library on its own.
