### ISSUE TITLE
Very strange error

### ISSUE THREAD

**Issue by dev-yaris** [mysqljs/mysql#2313]
I am unable to connect to mysql using this lib, but from PHP and CLI everything works fine.

"mysql": "^2.15.0"

![image](https://user-images.githubusercontent.com/61779545/75863017-7d1ca500-5e08-11ea-8403-559c093e64dc.png)

**Comment by dougwilson** [comment]
That is I think the first time I have seen it say firstbyte is undefined. Does it happen every time or only sometimes? Also what version of Node.js are you using?

**Comment by dev-yaris** [comment]
Sorry for delayed answer, it happened on Virtual Machine, after recreating a VM the error disappeared.
