### ISSUE TITLE
how to interpret FieldPacket? 

### ISSUE THREAD

**Issue by mx2323** [mysqljs/mysql#2318]
hi all, im using this node mysql client and im noticing that in the return of the query() callback there is an array of FieldPackets corresponding to each of the columns

![image](https://user-images.githubusercontent.com/528124/77005839-21353e80-6927-11ea-83a7-fcd40042e948.png)
 
Given this information, how do I discern the types of each of the columns? I would like to get to something similar to the **"Type"** column when I use the DESCRIBE table command with the mysql command line tool. 

```code
mysql> DESCRIBE orders
    -> ;
+-----------------+---------------+------+-----+---------+-------+
| Field           | Type          | Null | Key | Default | Extra |
+-----------------+---------------+------+-----+---------+-------+
| ORD_NUM         | decimal(6,0)  | NO   |     | NULL    |       |
| ORD_AMOUNT      | decimal(12,2) | NO   |     | NULL    |       |
| ADVANCE_AMOUNT  | decimal(12,2) | NO   |     | NULL    |       |
| ORD_DATE        | date          | NO   |     | NULL    |       |
| CUST_CODE       | varchar(6)    | NO   |     | NULL    |       |
| AGENT_CODE      | varchar(6)    | NO   |     | NULL    |       |
```

**Comment by dougwilson** [comment]
Hi @mx2323 this is the raw data coming back from your MySQL server. To get the type as an English word, this module provides the `Types` export: `mysql.Types[num]`. As an example, this will return an array of type names given the `fields` array:
```js
fields.map((field) => mysql.Types[field.type])
```
I hope this helps!
