### ISSUE TITLE
Infinite loop possible if external packages modify package functions

### ISSUE THREAD

**Issue by zaveconrad** [mysqljs/mysql#2319]
**Problem:**
Package runs into infinite loops in some cases, causing the application go down

**Replication steps (possible):**
Require the following code before creating a connection.
```
let mysql = require('mysql');
//BEGIN ALTERING APP STATE
var Events           = require('events');
Events.usingDomains = true;
class Domain {
    enter() {
        process.domain = d;
    }
    exit() {
    }
}
let d = new Domain();
let oldCreateConnection = mysql.createConnection.bind(mysql);
//Override the default create connection behavior
mysql.createConnection = (...p) => {
    let conn = oldCreateConnection(...p)
    conn.domain = d;
    return conn;
}
```

The behavior is caused by the logic contained in Connection.js
```
function unwrapFromDomain(fn) {
  return function () {
    var domains = [];
    var ret;

    while (process.domain) {
      domains.shift(process.domain);
      process.domain.exit();
    }

    try {
      ret = fn.apply(this, arguments);
    } finally {
      for (var i = 0; i < domains.length; i++) {
        domains[i].enter();
      }
    }

    return ret;
  };
}
```

**Result:**
The package ends up in an infinite loop.

**Expected Behavior:**
The prototypes and the main exported function should not be modifiable. 
The Domain API is also deprecated.

**Comment by dougwilson** [comment]
Thank you for the report. I guess if you don't want to encounter an infinite loop, you probably don't want to specifically write code that makes one happen.

If you think there are issues with the Node.js domains API, you should report them to the Node.js project.

Yes, it is deprecated, but only on certain versions of Node.js. This module is coded to work with domains if the user is using domain at their choice, especially on the Node.js versions in which domains API is not deprectaed.
