### ISSUE TITLE
How to wait for the first MySQL query to complete - Node.JS

### ISSUE THREAD

**Issue by Rishat7c** [mysqljs/mysql#2329]
Hello

There is module.exports and it has two functions:

First _loadAllRows()_
Second _getRow(id)_

```js
loadAllRows();
getRow(id);
```

The problem is that when the first function is executed, the second does not find anything

As a result, the second function does not find anything

It seems to me that need to use the Promise here, but I can not find an example :-)

If yes, show an example.
thanks

**Comment by Rishat7c** [comment]
Body section query

```
getRow: function (accountId) {
  mode.query('SELECT * FROM `accounts` WHERE `id` = ? LIMIT 1', [accountId], (err, res) => { 
       // body
  });
});
```

**Comment by sidorares** [comment]
@Rishat7c 

you need to pass callback to `loadAllRows` so it knows where to continue when result is available, or you can use Promises - under the hood mechanics is the same as with callback with a bit more standartised api

example with callback:

```js
loadAllRows: function(nextFunctionThatConsumesRows) {
   model.query('SELECT * FROM `accounts`, (error, rows) => {
     nextFunctionThatConsumesRows(error, rows);
   })
})
```
