### ISSUE TITLE
Inserting into and retrieving from binary string column

### ISSUE THREAD

**Issue by sameerjalnapurkar** [mysqljs/mysql#2330]
Hello,

I have a table MyKeys with a column that is a binary string of length 16 bytes:
`CREATE TABLE MyKeys (id INT AUTO_INCREMENT PRIMARY KEY, myKey BINARY(16))`
Now I create an ArrayBuffer of size 16 bytes:
`var myBuffer = new ArrayBuffer(16);`
Now I want to insert it into the table:
`con.query('INSERT INTO MyKeys (myKey) VALUES (?)', [myBuffer],function (err, data) {});`
However that is causing an error:
	ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
	sql: "INSERT INTO MyKeys (myKey) VALUES ()"
So it looks like myBuffer is not being sent to MySQL at all.

Any suggestions would be much appreciated. Thanks!

**Comment by sidorares** [comment]
can you try with `new Buffer(16)`? ( Buffer instead of ArrayBuffer )

**Comment by sidorares** [comment]
See https://github.com/mysqljs/mysql#escaping-query-values

> Buffers are converted to hex strings, e.g. X'0fa5'

I makes sense to treat ArrayBuffer similar to Buffer, but it looks like its treated as string https://github.com/mysqljs/sqlstring/blob/d3cd69ae47e83c610392c276e9e02357e0b740eb/lib/SqlString.js#L56

**Comment by sameerjalnapurkar** [comment]
Thanks very much. Will try Buffer instead and report back shortly.

**Comment by dougwilson** [comment]
An `ArrayBuffer` cannot be read directly, as you need to overlay some kind of view over it to read. The Node.js `Buffer` is a view into an `ArrayBuffer`. You can create a Buffer view of an ArrayBuffer using `Buffer.from(myArrayBuffer)`

**Comment by sameerjalnapurkar** [comment]
Seems to be working now. Thanks a million, @sidorares & @dougwilson
