### ISSUE TITLE
Column of type `SET` are returned with type `STRING`

### ISSUE THREAD

**Issue by indrimuska** [mysqljs/mysql#2331]
Hi All,
I notice that fields for columns of type `SET` are returned with type `STRING`, hence the check below in the connection settings object is never true:

```typescript
const connection = mysql.createPool({
    // ...
    typeCast: (field, next) => {
        if (field.type === mysql.Types.SET) {
            return field.string().split(',');
        }
        return next();
    }
});
```

Could you please check if this is a common problem or suggest a fix? I am on version 2.17.1
Also, what do you think of returning a `string[]` for all SET column values?

Thanks,
Indri

**Comment by dougwilson** [comment]
Hi @indrimuska that is strange, as the type is just whatever the database itself is returning, not controlled by this module. Can you share with us a complete replication case? For example:

1. What version of Node.js are you using
2. What version of MySQL server are you using
3. What is the DDL of your table
4. Can you share a simple INSERT statement that would populate a row in your table
5. Can you share a simple SELECT statement that we can run with this module to see the type

**Comment by indrimuska** [comment]
Hi @dougwilson, thanks for the quick turnaround.

1. Node 10.15.3
2. MySQL 5.7.26
3. ```
   CREATE TABLE `test` (
    `names` set('foo','bar','john','doe') NOT NULL
   ) ENGINE=InnoDB DEFAULT CHARSET=latin1
   ```
4. ```
   INSERT INTO `test` (`names`) VALUES
   ('foo'), ('bar'), ('foo,bar'), ('john,doe');
   ```
5. ```
   SELECT * FROM `test`
   ```

**Comment by dougwilson** [comment]
Thanks so much. From your output above, and my test:
```
FieldPacket { catalog: 'def',
  db: 'test',
  table: 'test',
  orgTable: 'test',
  name: 'names',
  orgName: 'names',
  charsetNr: 33,
  length: 48,
  type: 254,
  flags: 6145,
  decimals: 0,
  default: undefined,
  zeroFill: false,
  protocol41: true }
```

The MySQL server is returning the column type as value 254, which is a string type (https://github.com/mysqljs/mysql/blob/master/lib/protocol/constants/types.js#L38). Unfortunately it seems like the MySQL server considers the returns column value as a string for whatever reason. There isn't a way this module can change that output; it is just how the MySQL server is returning it...

**Comment by indrimuska** [comment]
I am using AWS RDS with a MySQL DB, am I the only one you are aware who experienced this? What do you suggest? Shall I raise forward this to MySQL?

**Comment by dougwilson** [comment]
There could have been precious reports, I don't recall. All I can say is for the scenario above, the mysql server is saying the column is a string; this module is simply reporting what the mysql server saying in a javascript api.
