### ISSUE TITLE
unique value depend in ID

### ISSUE THREAD

**Issue by ashrafalzyoud** [mysqljs/mysql#2335]
HOW I CAN let value enique when ID =2
![id](https://user-images.githubusercontent.com/50211455/79640744-dc0d6200-819b-11ea-9f8a-76166d117fbf.png)

**Comment by ashrafalzyoud** [comment]
if Custom_field_id= 2 the value eneterd must be unique

**Comment by dougwilson** [comment]
Hi, I think you may have opened this in the wrong place. This is the issue tracker for the Node.js mysql driver.
