### ISSUE TITLE
Question: Running SOURCE query

### ISSUE THREAD

**Issue by RipaltaOriol** [mysqljs/mysql#2336]
**This is only a question**
Hello, I am trying to run a SOURCE query, but it gives me a syntax error.
I run the query as `connection.query('SOURCE file.sql', (err) => { })`
My question is to ask if this behaviour of connection is supported.
Thank you.
<img width="1421" alt="Screenshot 2020-04-18 at 17 20 02" src="https://user-images.githubusercontent.com/48039207/79680852-b53f4200-8214-11ea-9fd9-770b9f397ef9.png">

**Comment by dougwilson** [comment]
The `SOURCE` command is not part of the MySQL server dialect, instead is a command specific to the `mysql` command line program. This is a client driver and sends all the commands you provide to your MySQL server, which is responding that it does not understand the `SOURCE` statement.

**Comment by sytana** [comment]
So, how ti SOURCE?
