### ISSUE TITLE
Retrieve Inserted Id

### ISSUE THREAD

**Issue by apissotte** [mysqljs/mysql#2337]
Hi,

I am trying to insert a row into a table which has a `VARCHAR(36) PRIMARY KEY` corresponding to an UUID. It is generated by a trigger before insert.

The code bellow, inserts correctly the row and the uuid is generated by the trigger. Nevertheless, I cannot retrieve the UUID in the callback.
```javascript
this._connection = mysql.createConnection({
            host: 'localhost',
            user: '****',
            password: '****',
            database: '****'
}) // That works fine

const object = {
    UUID: null,
    LNAME: 'DUPONT',
    FNAME: 'Alex',
    EMAIL: 'charles.dupont@gmail.com',
    PHONE: '0608050405'
}

this._connection.query('INSERT INTO PARTNER SET ?', object , (err, results, fields) => {
          console.log(err)
          console.log(results)
          console.log(fields)
}))
```
Attribute InsertId of OkPacket (results variable) is always equals to 0.

Above, you will find the console output:
![image](https://user-images.githubusercontent.com/35975692/79691747-90bd8700-8261-11ea-82a1-c24bda2d7013.png)

When I tried to pass an UUID to the query, I still have the same problem
```javascript
this._connection = mysql.createConnection({
            host: 'localhost',
            user: '****',
            password: '****',
            database: '****'
}) // That works fine

const object = {
    UUID: 'zz9315fc-8252-11ea-b3f6-f05e0602f6ce',
    LNAME: 'DUPONT',
    FNAME: 'Alex',
    EMAIL: 'charles.dupont@gmail.com',
    PHONE: '0608050405'
}

this._connection.query('INSERT INTO PARTNER SET ?', object , (err, results, fields) => {
          console.log(err)
          console.log(results)
          console.log(fields)
}))
```
![image](https://user-images.githubusercontent.com/35975692/79692091-8bf9d280-8263-11ea-82d7-10eda8de4b35.png)

Could you please tell me how to get the inserted row's id?
Thanks

**Comment by dougwilson** [comment]
Hi @apissotte , unfortunately this is a limitation of the MySQL protocol -- the insertId can only be an integer (see protocol definition https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html), so when you define your primary key to be a different type, it will always come back as zero. Even if you try and use `SELECT LAST_INSERT_ID()` (https://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_last-insert-id) it won't work because it also only returns an integer.
