### ISSUE TITLE
transaction containing insert and update yields unexpected ER_NO_REFERENCED_ROW_2

### ISSUE THREAD

**Issue by skidvd** [mysqljs/mysql#2338]
I have a table with a self-referencing foreign key for parent/child style relationships.

I am endeavoring to be able create a new child row and then update the parent row to reflect this addition.

When I manually (via sql console) perform an insert statement to create the new child record and then subsequently perform an update of the parent row, all of this works perfectly.  I assume this is because auto commit makes the child insert permanent before the update statement.

However, I would like to do both of these steps atomically within a transaction.  I would like both the insert and update to either fully succeed or fail as a unit as part of a transaction.

I have had success using transactions for similar purposes at other places in my code.  However, this instance is not working as expected.  I am using the following approach to accomplish this:

```
try {
    connection = await pool.getConnection();

    await connection.beginTransaction();

    await connection.execute(`INSERT into ....`   // This successfully inserts the child record as verified by logging output

    await connection.execute(`UPDATE ....  // This fails with ER_NO_REFERENCED_ROW_2

    await connection.commit();
} catch (err) {
    await connection.rollback();
}
```

The FK is not auto-generated.  It is a separately created UUID.  I have verified both the INSERT and UPDATE statements as well as the parameter values via logging to be as needed and to be in agreement with the manual steps taken in the console.  However, it appears that within the transaction, the effects of the insert statement are not realized causing the ER_NO_REFERENCED_ROW_2

```
"errno": 1452,
    "sqlState": "23000",
    "sqlMessage": "Cannot add or update a child row: a foreign key constraint fails (`test`, CONSTRAINT `fk_test_id` FOREIGN KEY (`reversing_id`) REFERENCES `test` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)"
```

error.

Obviously, inserting another commit statement after the insert would not give me the atomic semantics that I need in this case.

What am I missing or doing incorrectly here as it seems like the above should work?

Thank you kindly in advance!

**Comment by sidorares** [comment]
@skidvd I see you posted to mysql2 as well, do you want to close this issue? Not sure it is specific to prepared statement but your example just won't work with mysqljs/mysql driver

**Comment by skidvd** [comment]
My apologies, it appears that a trigger was interfering with this that I was not aware of.  This is working as expected without it.

**Comment by victorkl400** [comment]
@skidvd Could you share your solved code? I'm facing exactly the same issue
