### ISSUE TITLE
Support mysql versions

### ISSUE THREAD

**Issue by reuu** [mysqljs/mysql#2339]
Hi. I want to know what versions of Mysql / MariaDb support.. im actually have mysql 5.7 on my Godaddy hosting , but i cant access using this library, but i can connect using mysql cli on the same machine to the same hosting, same user and same password... (ER_ACCESS_DENIED_ERROR: Access denied for user...)..
Thanks

**Comment by dougwilson** [comment]
Hi! This module definitely supports mysql 5.7. The support is at the protocol level, which is expansive against all the mysql versions. That error can mean a few things, but you said you could connect with the mysql cli. Your message can occur if your server only allows you to log in over unix domain socket and not via tcp. What command line arguments do you give to the cli?

**Comment by reuu** [comment]
Thanks for your response... with a large revision of my code, i see the problem.. it was on my code... im so sorry for my post.. thanks for your answer...
