### ISSUE TITLE
Installer gets stuck

### ISSUE THREAD

**Issue by SuperSeriousMan** [mysqljs/mysql#2340]
My installer randomly got stuck all the time since today.

Error log:
`119 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Projects\Vextoria\node_modules\mysql\node_modules\readable-stream' -> 'C:\Projects\Vextoria\node_modules\mysql\node_modules\.readable-stream.DELETE'
120 verbose cwd C:\Projects\Vextoria
121 verbose Windows_NT 10.0.18362
122 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
123 verbose node v12.16.2
124 verbose npm  v6.14.4
125 error code ENOENT
126 error syscall rename
127 error path C:\Projects\Vextoria\node_modules\mysql\node_modules\readable-stream
128 error dest C:\Projects\Vextoria\node_modules\mysql\node_modules\.readable-stream.DELETE
129 error errno -4058
130 error enoent ENOENT: no such file or directory, rename 'C:\Projects\Vextoria\node_modules\mysql\node_modules\readable-stream' -> 'C:\Projects\Vextoria\node_modules\mysql\node_modules\.readable-stream.DELETE'
131 error enoent This is related to npm not being able to find a file.
132 verbose exit [ -4058, true ]`

`117 verbose stack Error: ENOENT: no such file or directory, rename 'C:\Projects\Vextoria\node_modules\mysql\node_modules\string_decoder' -> 'C:\Projects\Vextoria\node_modules\mysql\node_modules\.string_decoder.DELETE'
118 verbose cwd C:\Projects\Vextoria
119 verbose Windows_NT 10.0.18362
120 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "mysql"
121 verbose node v12.16.2
122 verbose npm  v6.14.4
123 error code ENOENT
124 error syscall rename
125 error path C:\Projects\Vextoria\node_modules\mysql\node_modules\string_decoder
126 error dest C:\Projects\Vextoria\node_modules\mysql\node_modules\.string_decoder.DELETE
127 error errno -4058
128 error enoent ENOENT: no such file or directory, rename 'C:\Projects\Vextoria\node_modules\mysql\node_modules\string_decoder' -> 'C:\Projects\Vextoria\node_modules\mysql\node_modules\.string_decoder.DELETE'
129 error enoent This is related to npm not being able to find a file.
130 verbose exit [ -4058, true ]`

**Comment by dougwilson** [comment]
For help with npm issues, https://www.npmjs.com/support

**Comment by SuperSeriousMan** [comment]
> For help with npm issues, https://www.npmjs.com/support

Every other package installs fine. This one does not.

**Comment by dougwilson** [comment]
Strange. I just tired on two machine without an issue. I'm not sure if there is something I can do to fix it, especially if I cannot reproduce the issue.

Can you perhaps provide the full reproduction steps? And any suggestions for what we can do to fix?

**Comment by SuperSeriousMan** [comment]
All I did was install it. It worked fine when using Yarn though.

**Comment by bstras21** [comment]
I just had the same issue. I then tried yarn and it worked.
