### ISSUE TITLE
Error while inserting with `execute`

### ISSUE THREAD

**Issue by aggarwaldev** [mysqljs/mysql#2342]
Hey,

I'm receiving the following error when I'm trying to `execute` the following statement:
```js
const [results] = await mysql.execute('INSERT INTO `employee` SET ?', employee);
```
Error: 
```
Bind parameters must be array if namedPlaceholders parameter is not enabled
TypeError: Bind parameters must be array if namedPlaceholders parameter is not enabled
```

If I try the exact statement with `query` method, it gets executed without any errors:
```js
const [results] = await mysql.query('INSERT INTO `employee` SET ?', employee);
```

Can you please help me with this? I prefer to use `execute` for insertion while `query` for everything else.

**Comment by aggarwaldev** [comment]
Invalid issue. Apologies!

**Comment by dougwilson** [comment]
You may have opened this in the wrong place, as this module does not have an .execute method.
