### ISSUE TITLE
Bulk insert is not working with nested array

### ISSUE THREAD

**Issue by arokanto** [mysqljs/mysql#2343]
Hello, I tried to create a bulk insert using a nested array, like what's described in the docs:

> Nested arrays are turned into grouped lists (for bulk inserts), e.g. [['a', 'b'], ['c', 'd']] turns into ('a', 'b'), ('c', 'd')

But if I do this:
```javascript
const insertArray = [[1,2], [1,3], [1,4]]
const insertResults = await db.query(`
    INSERT INTO customer_category(customer_id, category_id)
    VALUES(?)
`, insertArray)
```

Only the first pair ([1, 2]) gets inserted.

I even created a minimal example using just the `sqlstring` package, with the following results:

```javascript
import SqlString from 'sqlstring'

const values = [
  [1,2],
  [3,4],
  [5,6]
]
const query = 'INSERT INTO tbl (a, b) VALUES (?)'

const result = SqlString.format(query, values)
console.log(values) // [ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ] ]
console.log(result) // INSERT INTO tbl (a, b) VALUES (1, 2)
```

Maybe I'm missing something, but I just can't seem to make this work. I tried this with `sqlstring` version 2.3.2 and I have Node 13.10.1 and MySQL 8.0.19 installed.

I'm not sure if I'm just using `mysql` wrong or if this is a real issue in `sqlstring`.

**Comment by dougwilson** [comment]
You're almost there, but the last argument to .query and .format is an array, so you are one array short to make it work.

The second argument is an array of values, where each array element matches to each ? in the query. You want your double array to be the value of the first ? so you need it to be the first element in that array, not the array itself.

**Comment by dougwilson** [comment]
```js
const insertArray = [[1,2], [1,3], [1,4]]
const insertResults = await db.query(`
    INSERT INTO customer_category(customer_id, category_id)
    VALUES(?)
`, [insertArray])
```

**Comment by arokanto** [comment]
Thanks, it all makes sense now!
