### ISSUE TITLE
ER_BAD_FIELD_ERROR with connection.escape() or String Template

### ISSUE THREAD

**Issue by Oasis1819** [mysqljs/mysql#2344]
Language : Typescript
Runtime : NodeJS 6.0

Hi, I have tried make a nodejs app what sends to mysql Server the data.
But my code cause the error.

My INSERT query code :
```
        var records = ["BRABO", "OSCAR"]
        var QueryValues:string[] = records.map((it) => 
        `(${Database.escape(it)}, ${Database.escape(momentJS(new Date()).tz("Asia/CityNAME").format("YYYY-MM-DD"))})`
        )
        Database.query(`INSERT INTO chains(NAME, ContactDayWithoutTime) VALUES ${QueryValues.join(",")};`, (err, rows, fields) => {
        })
```

If this code runs normaly, this SQL query is like this : 
`INSERT INTO chains(NAME, ContactDayWithoutTime) VALUES ("BRABO", "YYYY-MM-DD"), ("OSCAR", "YYYY-MM-DD");`
but this mysql library returns the error "ER_BAD_FIELD_ERROR" with this SQL : 
`INSERT INTO chains(NAME, ContactDayWithoutTime) VALUES (\\'BRABO\\', \\'YYYY-MM-DD\\'),  (\\'OSCAR\\', \\'YYYY-MM-DD\\');`

I may expect about three reason about this error.
1. connection.escape() method is wrong (or library).
2. string template is wrong("``")
3. array.map() method is wrong.

but the other query code that uses array.map() method is working well.
is there anybody who tell me what I made a mistake..?

**Comment by dougwilson** [comment]
Your query error has a second `VALUES` note, which is where the error is I guess. But running your code produces the query you are expecting.

Perhaps, can you provide all the following:

1. Version of Node.js you are using
2. Version of this module you are using
3. Complete source code that I can run without modification (I had to modify you're above to provide values and other unknowns, which may have been why I could not reproduce).
4. Instructions on how to get the same error with the given code.

**Comment by Oasis1819** [comment]
Oh, second `VALUES` are typo.. my code has only one `VALUES`.
NodeJS verson : 6.x(I don't know exactly verson because I use Cloud lambda)
Mysql Module Version : 2.18.1(Typescript 2.15.10)

source code that you can run without modification :
```
    import momentJS from "moment"
    import "moment-timezone"
    import mysql from "mysql"
    var Database = mysql.createConnection(..)

    function InsertRecord(myStaticID:string, records:Array<string>){
        var QueryValues:string[] = records.map((it) => 
        `(${Database.escape(myStaticID)}, ${Database.escape(it)}, ${Database.escape(momentJS(new Date()).tz("Asia/Seoul").format("YYYY-MM-DD"))}, ${Database.escape(0)})`
        )
        Database.query(`INSERT INTO scanchains(ScannerStaticID, ScanedDynamicUUID, ContactDayWithoutTime, Authed) VALUES ${QueryValues.join(",")};`, (err, rows, fields) => {
            console.log(err)
        })
    }

    InsertRecord("OSCAR", ["HELLO", "WORLD"])
```

Error Message : 
```
ER_BAD_FIELD_ERROR
errno: 1054
sqlState: '42S22'
sql: 'INSERT INTO scanchains(ScannerStaticID, ScanedDynamicUUID, ContactDayWithoutTime, Authed) VALUES (\\'OSCAR\\', \\'HELLO\\', \\'2020-04-27\\', 0), (\\'OSCAR\\', \\'WORLD\\', \\'2020-04-27\\', 0);'
```
I think this code changes the sql query `'` to `\\'`.
so I have tried change the `InsertRecord` like this : 
```
function InsertRecord(myStaticID:string, records:Array<string>){
        var QueryValues:string[] = records.map((it) => 
        `(${Database.escape(myStaticID)}, ${Database.escape(it)}, ${Database.escape(momentJS(new Date()).tz("Asia/Seoul").format("YYYY-MM-DD"))}, ${Database.escape(0)})`
        )
        Database.query(`INSERT INTO scanchains(ScannerStaticID, ScanedDynamicUUID, ContactDayWithoutTime, Authed) VALUES ${QueryValues.join(",").replace("\\\\'", "'")};`, (err, rows, fields) => {
            console.log(err)
        })
    }
```
But it doesn't work, too.
so I can guess this library makes the problem.
And I'm going to try more method.

**Comment by Oasis1819** [comment]
Hmm, I found the SQL query(not `string template` but also `plus operator`) hasn't any problem by this code.
```
console.log(`INSERT INTO scanchains(ScannerStaticID, ScanedDynamicUUID, ContactDayWithoutTime, Authed) VALUES ${QueryValues.join(",")};`)
```
This code prints the SQL query same as my argument that I used for connection.query()
And, `console.log()` printed this :
```
INSERT INTO scanchains(ScannerStaticID, ScanedDynamicUUID, ContactDayWithoutTime, Authed) VALUES ('d16509b5-a552-47fc-b71e-e03e63774c0e', 'A9BF6D0160AAAAC63D', '2020-04-28', false),('d16509b5-a552-47fc-b71e-e03e63774c0e', '522C382DFF79FBAAE4', '2020-04-28', false);
```
It didn't print `'` to `\\'`. so I realized that and I tried reinstall mysql library, but It didn't worked too.

In conclusion : 
- connection.escape() method is not problem
- backtick is not problem, too
- This problem happens only this SQL query string.

must I change the mysql Version?

**Comment by kai-koch** [comment]
I am checking this on my phone, so I might be wrong. But the error can
happen when the quotes are not proper escaped, the string then is broken
into more fields than there are in the insert statement. It seems to me
that you are escape the values twice. This library adds outer quotes when
escaping values.

bye, kai

CRUSHU <notifications@github.com> schrieb am Di., 28. Apr. 2020, 15:54:

**Comment by Oasis1819** [comment]
Oh, I found that I wrote wrong SQL field at table.
`Authed` field should be deleted.  I think this library made the strange SQL because of invalid SQL field.
It's too shameful mistake... and sorry at you because of my absurd mistake.
Thanks for everyone :+1:
