### ISSUE TITLE
mysql.createConnection() returns undefined

### ISSUE THREAD

**Issue by Xekso** [mysqljs/mysql#2346]
require('./lib/Connection') returns undefined in index.js and subsequently returns the error:
"undefined is not a constructor (evaluating 'new Connection({config: new ConnectionConfig(config)})')"
when attempting to return back to the main file.

The package has been re-installed several times, and is running on the expo cli with the fs package switched with react-native-fs and crypto rewritten with browserify. While this may not be an issue with the package directly, there seems to be no publicly available information on this issue and any help would be greatly appreciated.

The crypto package was rewritten with the directions from this website: https://hackernoon.com/using-core-node-js-modules-in-react-native-apps-64acd4d07140

The react-native-fs package was installed from this website:https://github.com/hawkingnetwork/node-libs-react-native/tree/fa42818dfcd9ac2003682a33d7009967b037f0e3

From this the require() in every relevant file was updated through the use of throwing errors to the console to find the locations.

Error code:
![image](https://user-images.githubusercontent.com/40378249/80511432-6e450f80-89bf-11ea-9803-4b5a211c425c.png)

Error location:
![image](https://user-images.githubusercontent.com/40378249/80511521-8d43a180-89bf-11ea-9b2c-f0fe21e16dd8.png)

Cause of error:
![image](https://user-images.githubusercontent.com/40378249/80511570-9cc2ea80-89bf-11ea-9048-e9ab9f5da9f8.png)

contactxekso@gmail.com

**Comment by dougwilson** [comment]
Please provide the steps to reproduce the error so we can help & debug.

**Comment by hervegbedji** [comment]
Steps to reproduce error: 
1- install mysql through npm (node -v is 13.11.0 / npm -v is 6.14.6 )
2- `var mysql = require('mysql');
let connection = mysql.createConnection({
    host     : '127.0.0.1',
    user     : 'root',
    password : '',
    database : 'canticles'
});`

3- `let connexionMsg = 'current type is '+x;
//let err = connection.error;

connection.connect((err) => {

    if (err) {
        connexionMsg = `wow error connecting: ${err.stack}`;
        //return;
    } else {
        connexionMsg = `connected as id ${connection.threadId}`;
    }

});`

4- pring out connexionMsg. thread is still null and connection.state is disconnected
5- Go take a look at the mysql's index.js & Connection.js. In the index.js the `var Classes = Object.create(null);` seems obscure and making the func bug especially considering `var Class = Classes[className];

  if (Class !== undefined) {

    return Class;
  }

  // This uses a switch for static require analysis
  switch (className) {
    case 'Connection':
      Class = require('./lib/Connection');`

I just stumbled upon this issue today, i will try to see what adjustment needs to be done to the code to make it work

**Comment by dougwilson** [comment]
Hi @hervegbedji it is difficult to follow your steps. It also seems like you're a different used from the OP. If you are having an issue, I would ask you if you could open a new issue and explain what issue you're having, along with any errors. The OP in this issue has not responded in months, so I'm closing this out.
