### ISSUE TITLE
Async await works with majority of the function.

### ISSUE THREAD

**Issue by aswinpchn** [mysqljs/mysql#2347]
I see that on the API page. Take for example the .qeuery function, it has a callback option. If you want to use async/await we have to write our own promise wrapper. This was the assumption till last week. Last week I tried using await directly with .query(), .beginTransaction(). It worked. Has anything recently changed that allows async/await to work without wrappers?

**Comment by dougwilson** [comment]
No, nothing had changed in this module regarding that.
