### ISSUE TITLE
Check Database Exists

### ISSUE THREAD

**Issue by eurekaindustries** [mysqljs/mysql#2348]
Is it possible to check if a (MySQL) database exists and if it doesn't create it.

I have tried to do

`SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'DBName'
`
But as the connection can not create if the DB doesn't exists, it throws an error. Ideally I would like to add the following command on start up of my nodejs app when it first tries to connect to MySQL

`CREATE DATABASE IF NOT EXISTS DBName;`

Thanks

Libbie

**Comment by dougwilson** [comment]
If you are not sure a database will exist before connecting, you just need to not specify the database in the connection configuration. Then just run those commands upon connecting and then you can run `USE DBName` once it is confirmed to exit or has been created.
