### ISSUE TITLE
sqlMessage: "Incorrect string value: '\\xF0\\x9F\\x8D\\xB5' 

### ISSUE THREAD

**Issue by sclswin** [mysqljs/mysql#2351]
table:
ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

Special characters in string  Throw error “sqlMessage: "Incorrect string value: '\\xF0\\x9F\\x8D\\xB5' ”

example：
![avatar](https://www.xcwmoon.com/static/images/11.png)

**Comment by dougwilson** [comment]
Set the `charset` connection option (https://github.com/mysqljs/mysql#connection-options) to `utf8mb4`.
