### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by Mamagotchi** [mysqljs/mysql#2353]
Hi,

I installed nodejs-module "mysql" (npm install mysql) on my angular (@angular/cli": "^8.3.17") and try a simple code, that should create a connection to my mysql database, clicking on a button.

 ```
mysql_test() {
    var mysql = require('mysql');

    const con = mysql.createConnection({
    host: "localhost",
    user: "admin",
    password: "123456",
    });

    con.connect(function(err) {
    if (err) throw err;
    console.log("Connected!");
    });
  }
```

But if I click on the button, I got this error in my browser console:
![Anmerkung 2020-05-06 073334](https://user-images.githubusercontent.com/64885963/81145411-8942f100-8f76-11ea-8a4c-8fea8789327e.png)

Any idea?

**Comment by dougwilson** [comment]
Unfortunately this is a Node.js module, not a web browser module. Node.js 0.6 or higher is required to run this module.

**Comment by Mamagotchi** [comment]
> Unfortunately this is a Node.js module, not a web browser module. Node.js 0.6 or higher is required to run this module.

Yes, I installed nodejs already.

**Comment by dougwilson** [comment]
Based on your error message, `require('stream').Stream` is `undefined` in your environment. In Node.js that would be the Stream class constructor.

**Comment by dougwilson** [comment]
Yes, but since this is a Node.js module, you have to run it inside Node.js, not inside a web browser. None of the Node.js APIs like streams are available in the web browser, as they are specific to Node.js runtime.
