### ISSUE TITLE
Bad Handshake

### ISSUE THREAD

**Issue by consciousweb** [mysqljs/mysql#2354]
> I20200512-23:02:11.526(-6)? starting query ...
> I20200512-23:02:11.627(-6)? <-- HandshakeInitializationPacket {
> I20200512-23:02:11.628(-6)?   protocolVersion: 10,
> I20200512-23:02:11.628(-6)?   serverVersion: '5.0.95',
> I20200512-23:02:11.628(-6)?   threadId: 251,
> I20200512-23:02:11.628(-6)?   scrambleBuff1: <Buffer 2c 35 65 21 6d 28 79 4c>,
> I20200512-23:02:11.628(-6)?   filler1: <Buffer 00>,
> I20200512-23:02:11.628(-6)?   serverCapabilities1: 41516,
> I20200512-23:02:11.629(-6)?   serverLanguage: 8,
> I20200512-23:02:11.629(-6)?   serverStatus: 2,
> I20200512-23:02:11.629(-6)?   serverCapabilities2: 0,
> I20200512-23:02:11.629(-6)?   scrambleLength: 0,
> I20200512-23:02:11.629(-6)?   filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
> I20200512-23:02:11.629(-6)?   scrambleBuff2: <Buffer 4d 7e 54 6a 38 74 62 6c 78 37 47 41>,
> I20200512-23:02:11.629(-6)?   filler3: <Buffer 00>,
> I20200512-23:02:11.630(-6)?   pluginData: undefined,
> I20200512-23:02:11.630(-6)?   protocol41: true }
> I20200512-23:02:11.630(-6)? 
> I20200512-23:02:11.630(-6)? --> (251) ClientAuthenticationPacket {
> I20200512-23:02:11.630(-6)?   clientFlags: 455631,
> I20200512-23:02:11.631(-6)?   maxPacketSize: 0,
> I20200512-23:02:11.631(-6)?   charsetNumber: 33,
> I20200512-23:02:11.631(-6)?   filler: undefined,
> I20200512-23:02:11.631(-6)?   user: '[redacted]',
> I20200512-23:02:11.631(-6)?   scrambleBuff: <Buffer 89 0d 12 f9 e1 b5 be 63 78 fd b2 30 f0 16 65 99 16 6b fc 77>,
> I20200512-23:02:11.631(-6)?   database: '[redacted]',
> I20200512-23:02:11.631(-6)?   protocol41: true }
> I20200512-23:02:11.631(-6)? 
> I20200512-23:02:11.678(-6)? <-- (251) UseOldPasswordPacket { firstByte: 254 }
> I20200512-23:02:11.678(-6)? 
> I20200512-23:02:11.679(-6)? --> (251) OldPasswordPacket { scrambleBuff: <Buffer 58 41 48 4b 47 4e 58 55> }
> I20200512-23:02:11.679(-6)? 
> I20200512-23:02:11.729(-6)? <-- (251) ErrorPacket {
> I20200512-23:02:11.729(-6)?   fieldCount: 255,
> I20200512-23:02:11.729(-6)?   errno: 1043,
> I20200512-23:02:11.730(-6)?   sqlStateMarker: '#',
> I20200512-23:02:11.730(-6)?   sqlState: '08S01',
> I20200512-23:02:11.730(-6)?   message: 'Bad handshake' }
> I20200512-23:02:11.730(-6)? 
> I20200512-23:02:12.328(-6)? Client connected
> I20200512-23:02:12.330(-6)? Query error: Error: ER_HANDSHAKE_ERROR: Bad handshake
> I20200512-23:02:12.330(-6)? Query finished successfully
> I20200512-23:02:12.330(-6)? 0 rows

**Comment by consciousweb** [comment]
solved. caused by old_password being enabled on the server

**Comment by dougwilson** [comment]
Hi @consciousweb thanks for the update! I wasn't able to look into your issue yet, but with that information, and the log above (very helpful, BTW), I will see if we can get at the very minimum a better error message.
