### ISSUE TITLE
mysql too many connection

### ISSUE THREAD

**Issue by hbhng** [mysqljs/mysql#2356]
a web application , refreshed  many times then  the mysql server come to connection Limit, and the other appliction can't be connect to mysql with startup.  Mysql command "show processlist " shows the connectlist too many, but the application pool._allConnections.length is still under pool.config.connectionLimit.  Shutdown this aplication ,the mysql show processlist will immediately show normal, and the other application can connect mysql again .

**Comment by 716green** [comment]
So during development is it best to increase the maximum limit or is there some other setting that I'm not taking into account? Because I am sometimes refreshing my server and database connection several times a minute while debugging.

**Comment by dougwilson** [comment]
@hbhng can you show your code? If the `_allConnections.length` is less than you see in your process list on the MySQL server, it may be that you are accidentally creating multiple pool objects in the code, which is where all those other connections are hanging out.

**Comment by hbhng** [comment]
@dougwilson ，I have traced the code , no hanging out Pool. And I have changed the code to use only connection not the pool , it's the same state. The mysql extra connections are created in the connection.query(sql). It's not my code problem. If I startup the two applications before the mysql connection limit reached, they all work OK.

**Comment by dougwilson** [comment]
Very strange, I'm not sure what is going on then. I haven't experienced that kind of behavior in my own usage of this module.

Can you help provide a reproduction case by providing all of the following so we can reproduce and fix it?

1. Version of Node.js in use
2. Version of this module in use
3. Full code we can run without modification to reproduce the issue.
4. Instructions for running said code if needed.

Thank you!

**Comment by hbhng** [comment]
@dougwilson, I solved the problem. I sure that the issues are created by the module ' express-mysql-session '.  
Thank you very much!
