### ISSUE TITLE
Options like "enableArithAbort" and "encrypt" are not included in *Connection Options*

### ISSUE THREAD

**Issue by begandroide** [mysqljs/mysql#2366]
Hi! I dont understand why "options" are not included in *[Connection Options](https://github.com/mysqljs/mysql#connection-options)*; these options could has attributes like "enableArithAbort", "encrypt", and other else.

Actually I'm working with Knexjs and the attribute "options" is readOnly, so I cant assign the property to constructor class; and they build the interface based on your definition.

So, why not include it?

**Comment by dougwilson** [comment]
Hi @begandroide I'm really not sure what you are asking exactly. There is nothing even in this module named "enableArithAbort" or "encrypt". What are those? What does it mean to add it here? Would you be willing to make a PR around this?

**Comment by begandroide** [comment]
Sorry @dougwilson, im working with mssql not with Mysql, and i tried to used you library instead of mssql. Bad me.
