### ISSUE TITLE
Nod Js formidable not uploading

### ISSUE THREAD

**Issue by marcebyte** [mysqljs/mysql#2369]
Dear:
I have a Node js program ussing formidable to upload file. Form has a "Adjuntos" file input. But server does not get the file. And file is not coppied.
 My code is:

         let formidable=require('formidable');
         let form=formidable.IncomingForm();
         console.log(form.files);
         form.parse(req, function (err, fields, files) {
           var oldpath = files.Adjuntos.path;
           console.log('Ruta:' + oldpath);

           var newpath = 'c:\Temp\ ' + files.filetoupload.name;
           fs.rename(oldpath, newpath, function (err) {
             if (err) throw err;
             res.write('File uploaded and moved!');
             res.end();
           })
          })

Thanks in advance

**Comment by dougwilson** [comment]
Hello, @marcebyte , I believe you have opened your issue in the wrong location. This is for MySQL-related questions. It seems you are looking for the Node.js formidable module: https://github.com/node-formidable/formidable/issues
