### ISSUE TITLE
[Inquiry] Killing a Node.js frequently while developing

### ISSUE THREAD

**Issue by PolymorphiK** [mysqljs/mysql#2372]
I have a question. While I am developing my node.js server, I will be killing and restarting the server by either a SIGKILL using CTRL+C or via Nodemon which would restart the Node.js server.

Is this safe? I just want to make sure so I don't have problems down the line.

Thanks!

**Comment by dougwilson** [comment]
Hi @PolymorphiK this module is just standard JavaScript and itself doesn't have issues with that.
