### ISSUE TITLE
Connection pool fills up without releasing connections

### ISSUE THREAD

**Issue by paolo-projects** [mysqljs/mysql#2373]
I have an express server written in typescript where I'm providing a global instance of the connection pool through a module:
```typescript
const DB_RECONNECT_TIMEOUT = 10000;

const DbConnection = mysql.createPool(DatabaseConf);

// Ping database to check for common exception errors.
const ConnectionPing = () => DbConnection.getConnection((err, connection) => {
  ...
});

ConnectionPing();

export default DbConnection;
```
I have multiple interfaces that query the database through a `Pool | PoolConnection` object. When the Pool is directly used a single `query` is performed through the whole request/response lifecycle, otherwise a connection is requested and released as shown in this example:
```typescript
return new Promise((resolve, reject) => {
    DbConnection.getConnection((err, connection) => {
        if(err) return reject(new DatabaseError(err));
        AuthDbInterface.getEmailTokenByToken(connection, emailToken)
            .then(token => UserDbInterface.setUserVerifiedByEmail(connection, token.email, 1))
            .then(res => AuthDbInterface.deleteEmailTokenByToken(connection, emailToken))
            .then(res => resolve())
            .catch(reject)
            .finally(connection.release);
    });
});
```
By monitoring the connections on the database side I can see the connection count increase until the connection pool reaches its limit, and at that point every further request to the server that goes through a DB connection will hang indefinitely.

Initially the pool size was of 50 but I also tried 10 and the only difference I found is that it takes only 10 connections to hang up the server.

I suppose the connection pool should reuse the connections when they are released, so if there are 10 concurrent requests then 10 connections are created but when some of them are released, any further request should use one of the free connections in the pool. 

This is not my case though since the connection count will increase even if the requests are spaced in time, and they are never dropped, forcing me to restart the app to get it working again.

**Comment by dougwilson** [comment]
Are you sure you are actually releasing the connections back to the pool? Your code provided so far would not do that, as there is a simple javascript mistake that would keep it from happening:

```js
.finally(connection.release)
```

Needs to be written as either `.finally(connection.release.bind(connection))` or `.finally(() => connection.release())`

**Comment by paolo-projects** [comment]
Omg, I suppose that switching between java and javascript/typescript without reviewing the basics has its (avoidable) consequences! Thank you very much for the heads-up.
