### ISSUE TITLE
Query query, transaction and and queries on the same connection

### ISSUE THREAD

**Issue by zmooky** [mysqljs/mysql#2376]
Using one connection ( pool ) I expect to be able to walk queries results with a cursor and while doing this to run updating queries on rows that where selected "FOR UPDATE" all of this in a transaction. 

Currently the pausing of the query streaming is done using the connection where the pause should be done on a connection query result pointer/cursor. 

From my past experience with oracle databases in Java/Visual basic, this kind of implementation should be possible.

Is this a limitation of mysql ?

Theoretically during a transaction a parallel query should see the inserted rows where a query that is on a separate transactions should not see the records affected in a different currently opened transaction

**Comment by dougwilson** [comment]
> Is this a limitation of mysql ?

Yes, it is a limitation of the MySQL protocol. The connection and queries are 1-to-1, as in once you start to receive result rows for a query, you cannot send any further commands (like another query) until all results have been sent by the MySQL server and received by the client (this module).

**Comment by zmooky** [comment]
I did not expect that.I thought that Mysql is able to do this. I will
perform some tests in different environments.

**Comment by dougwilson** [comment]
It's no problem. That's also why I didn't close this. As far as I'm aware it's not possible, and I've been down at the protocol/wire level for some time. But I am happy to be proven wrong, especially in the form of a pull request to add such functionality, if it is truly possible.

**Comment by zmooky** [comment]
I will return as soon as I have results on this topic.

**Comment by dougwilson** [comment]
Closing due to no response.
