### ISSUE TITLE
Placeholder for JSON_PATH in JSON_SET

### ISSUE THREAD

**Issue by vnikolay** [mysqljs/mysql#2381]
Hi, I tried different combinations:
```
SET `data`= JSON_SET(`data`, ?, ?) , [name, value]
SET `data`= JSON_SET(`data`, ??, ?) , [name, value]
SET `data`= JSON_SET(`data`, ?, ?) , ['"$.' + name + '"', value]
SET `data`= JSON_SET(`data`, ??, ?) , ['"$.' + name + '"', value]
```
And nothing is working, getting error.

How can I escape JSON_PATH in JSON functions?

**Comment by dougwilson** [comment]
I'm assuming your `name` variable does not start with the `$.` based on your last two examples. If so, your issue is you are including extra quotes on the second two. The following should work:
```js
conn.query('SET `data`= JSON_SET(`data`, ?, ?)', ['$.' + name, value])
```
