### ISSUE TITLE
ER_BAD_FIELD_ERROR: Unknown column 'student_name' in 'field list'

### ISSUE THREAD

**Issue by jjoel1630** [mysqljs/mysql#2387]
```sql
CREATE TABLE student (
    student_id INT PRIMARY KEY, 
    student_name VARCHAR(20),
    major VARCHAR(20)
);
SELECT * FROM student;


INSERT INTO student(student_id, student_name) VALUES(3, 'Bob');
```
Every time I run this, it throws me an error. I would appreciate if someone could please help. 
Thanks!

**Comment by ar-ushi** [comment]
To the best of my knowledge,when you want to insert/update a string value onto the database,use single quotes or backslash. As of right now,the value is being read as student_name = Bob.

Using 
`INSERT INTO
 student(student_id, student_name) 
VALUES(3, " 'Bob' ");`
or 
`INSERT INTO 
student(student_id, student_name)
 VALUES(3, ' \ 'Bob\' ');`

should work.

**Comment by dougwilson** [comment]
I'm going to close as there was a response and seem to be a MySQL question unrelated to this module.
