### ISSUE TITLE
How to use AS clause when specifying multiple columns

### ISSUE THREAD

**Issue by secmin** [mysqljs/mysql#2388]
Example.
```js
const sql = SELECT ? FROM messages

const columns = [
  'id',
  'body',
  'accesses_count.total',
  'messages_count.total'
]

const [rows] = pool.query(sql, [columns])
```
When you get a column in columns as shown in the example, the total will be grouped together.
```
[
  TextRow {
    id: 1,
    body: ~,
    total: 0 
  }
]
```
So I tried not to cover it with an AS clause as shown below, but I got an error.
```js
const columns = [
  'id',
  'body',
  'accesses_count.total AS access_count',
  'messages_count.total AS message_count'
]
```
Is there a solution to this problem?
Or '?' Should I stop the placeholders and type one word at a time?

**Comment by dougwilson** [comment]
Yes, the placeholders for thus module are meant for very simple use cases. A more full featured SQL string builder like https://hiddentao.github.io/squel/ will allow you to build a SQL string like you are trying to do with a rich API 👍
