### ISSUE TITLE
Incorrect unescaping of column names

### ISSUE THREAD

**Issue by KrofDrakula** [mysqljs/mysql#2391]
Consider the following table:

```sql
CREATE TABLE example (
  `from` DATE NOT NULL
);
```

`from` is a reserved SQL keyword. If you try to insert a row into that table using named columns, the `from` column is not escaped, which causes a syntax error. I haven't found a way to force the library to not remove escapes for this column name even after forcing it to insert a raw value:

```js
// this query unescapes "`from`" into "from"
connection.query(
  "INSERT INTO example (`from`) VALUES (?)",
  ["2020-01-01"]
);

// this query does the same
connection.query(
  "INSERT INTO example (?) VALUES (?)",
  [mysql.raw('`from`'), "2020-01-01"]
);
```

This also affects exports from MySQL that contain backtick-escaped column names that are reserved keywords when being passed to the `query` function after reading from a file.

Is there something I'm missing? Is there a way to force identifiers to always be escaped in the final query?

**Comment by dougwilson** [comment]
Hi @KrofDrakula I ran the code you provided and have no issues. This library does not do any kind of unescaping, so I'm not sure why you would be having issues. I know you only gave a piece of code, so maybe there is some kind of things happening in code that is not provided.

For reference, here is a complete, stand alone file I used to try and reproduce. Perhaps you can run this and see if it reproduces for you? Just change the connection options:
```js
const mysql = require('mysql')
const conn = mysql.createConnection({ /* your conn options */ })

conn.query('CREATE TEMPORARY TABLE `from` (`col1` DATE)', function (e) {
  console.log('create table 1: ' + (e ? e.message : 'OK'))
})

conn.query('CREATE TEMPORARY TABLE `example` (`from` DATE)', function (e) {
  console.log('create table 2: ' + (e ? e.message : 'OK'))
})

conn.query('INSERT INTO example (`from`) VALUES (?)', ["2020-01-01"], function (e) {
  console.log('insert 1: ' + (e ? e.message : 'OK'))
})

conn.query('INSERT INTO example (?) VALUES (?)', [mysql.raw('`from`'), "2020-01-01"], function (e) {
  console.log('insert 2: ' + (e ? e.message : 'OK'))
})

conn.end()
```

Running this for me results in the following:
```
create table 1: OK
create table 2: OK
insert 1: OK
insert 2: OK
```

**Comment by KrofDrakula** [comment]
@dougwilson Sorry for the late response; this might be a problem with `node-mysql2`, as we're currently using that version of the library, not the base `mysql`. Not sure if it has anything to do with the specific setup there, but I'll move the conversation to the relevant repo.

Thanks!
