### ISSUE TITLE
Support to import RowDataPacket object 

### ISSUE THREAD

**Issue by lx-mn** [mysqljs/mysql#2394]
When post processing knex response, I want to check if some nested value of the result is an instance of RowDataPacket. I am looking for importing it similar to 

`const { RowDataPacket } = require("knex");`. 

So, that i can do something like,

```
const processKnexResponse = (result, queryContext) => {
  // ....
  if ( result[0] instanceof RowDataPacket) {
    // process RowDataPacket
  }
};
```

**Comment by dougwilson** [comment]
In order to import from Knex, you need to open the issue with the Knex library.

**Comment by lx-mn** [comment]
@dougwilson this is strange I don't how I stepped into this library when I was looking to go to knex. Anyways thanks.
