### ISSUE TITLE
Save Data in database properly but showing error

### ISSUE THREAD

**Issue by SabiulSabit** [mysqljs/mysql#2404]
When i run this code:
data = " INSERT INTO `shopinfo`(`businessMail`, `haircut`, `salon`, `nailCutter`, `beautySalon`) " +
                            "VALUES ('" + ownerEmail + "','" + checkboxHaircut + "','" + checkboxSalon + "','" + checkboxNailCutter + "','" + checkboxBeautySalon + "')"

                     
                        connectDB.query(data, (result, err1) => {
                            if (err1) {
                                console.log("shopinfo query err");
                                //throw err;
                                console.log(err1)
                            }
                        })

it is saving data in my database but showing error in the console like this:
OkPacket {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0
}
Can any one help me how to solve this?

**Comment by dougwilson** [comment]
The callback signature of `.query` is `(err, result)` (see https://github.com/mysqljs/mysql#performing-queries) -- you just have your variable backwards so are interpreting the result as an error.

**Comment by SabiulSabit** [comment]
ohhh my god... thanks a lot dear
