### ISSUE TITLE
TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by xMuffionex** [mysqljs/mysql#2406]
i have code in coinGain.js:

`const { client } = require("../index");
let { con } = require("./message.js");

client.on('message', async(msg) => {
    let sql;
    let boosts;
    let coins;
    sql = `SELECT * FROM eco WHERE id = ${msg.author.id}`;
    con.query(sql, (err, rows) => {
        if(rows.length< 1) {
            sql = `INSERT INTO eco(id, coins, boosts) VALUES(${msg.author.id}, 0, 0)`
        }else{
            let ran = Math.floor(Math.random() * 15);
            sql = `UPDATE eco SET coins = ${rows[0].coins+=ran} WHERE id = ${msg.author.id}`;
            con.query(sql);
        }
    })
})`

and this in message.js:

`
const { client} = require('../index.js')
const { MessageEmbed } = require('discord.js');
const chalk = require("chalk")
const mysql = require("mysql");

let con;

client.on("ready", () => {
    console.log(chalk.green(`Zalogowano jako ${client.user.tag}.`));
    con = mysql.createConnection({
        host: 'xyz.pro',
        database: 'xyz',
        user: 'xyz',
        password: 'xyz'
    })
    console.log(chalk.green("Połączono z serwerem bazy danych!"))
    setInterval(function(){
        con.ping();
    }, 18000)
})

client.on("message", async message => {
    if (message.author.bot) return;
    con.query(`SELECT * FROM guilds WHERE id = ${message.guild.id}`, (err, res) => {
    let prefix = null;
        if(err) throw err;
        prefix = res[0].prefix;
        if (!message.content.startsWith(prefix)) return;
        
        const args = message.content.slice(prefix.length).trim().split(/ +/g);
        const cmd = args.shift().toLowerCase();
        
        if (cmd.length === 0) return;
        
        let command = client.commands.get(cmd);
        if (!command) command = client.commands.get(client.aliases.get(cmd));
        if (command) command.run(client, message, args, con);
    })
});

module.exports = {
    con: con
}`

And i'm getting this:
node:25684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'query' of undefined
    at Client.<anonymous> (C:\Users\Kamilek\Desktop\rewrite\events\coinGain.js:9:9)

**Comment by mbaumgartl** [comment]
```require``` works synchronously while the connection is established asynchronously. ```con``` is not initialized when it's exported.

It's broken as intended.
