### ISSUE TITLE
MySQL hijacking Express' error handler and re-throwing errors

### ISSUE THREAD

**Issue by maulikvora** [mysqljs/mysql#2408]
I am using mysql with expressjs.

I have an app wide error handler, which catches any runtime-logical errors and don't let node-server crash.
```
app.use(function (err, req, res, next) {
    log.error(err);
    res.status(500).send({"message": "Internal Server Error"});
});
```

Problem here is whenever mysql is interacted in any of my function, MySQL rethrow-nonmysql errors and at that time, expressjs-handler is not able to catch it and my nodejs-app crashes.

```
/node_modules/mysql/lib/protocol/Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read property 'id' of undefined
```

I know why that `id` is undefined and I can fix it. but my problem here is MySQL library is hijacking my app-wide error handler, bypasses that error-handler and my nodejs-app crashes.

If mysql is not interacted in any method and such error happens, its get caught by my app-wide error handler.

Does anyone know how to fix this?

**Comment by dougwilson** [comment]
This is just an underlying issue with Node.js itself. You cannot throw in a callback function of an async operation if you want to have the error propagated. This is why Express provides the `next` function with an error argument.

You can see a demonstration by adding this to your app:
```js
app.use((req, res) => {
  setImmediate(() > {
    throw new Error('this is not handled'))
  })
})
```

You can read more about asynchronous error handling in the Express docs http://expressjs.com/en/guide/error-handling.html
