### ISSUE TITLE
Error invoking quit and not ending connection.

### ISSUE THREAD

**Issue by otkashix** [mysqljs/mysql#2414]
I'm using this package for a Discord Bot. The things is if I use a query inside a query, but a connection.end() is out of the first query, the code will stop and will give me this error: "Error: Cannot enqueue Query after invoking quit.". This happen if there are results. If there are not results, will not give the error but, instead, will not close the connection to the database, ending with another error after a lot of time of: too many connections.

Code: https://pastebin.com/Bc8yDC0Z
Error picture: https://imgur.com/uNoo4Z2

**Comment by mbaumgartl** [comment]
The code doesn't work the way you might think. You should definitely learn what asynchronous code is and how it works.

Hint: the problem is not in this package :wink:
