### ISSUE TITLE
Distributed transaction with XA.

### ISSUE THREAD

**Issue by bermudezc** [mysqljs/mysql#2424]
Hello somebody could show me some example off XA transaction, 

I try:    **myConnection.query("xa start 'a';" ...)**  and found perfect, but when continued with 
           **myConnection.query("xa end 'a';" ...)**  throw me    XA_error the transaccion is not started.

Thanks in advance.

**Comment by dougwilson** [comment]
Can you provide more details around reproduction? For example a small script that runs and produces that error. There are many options and such and it is difficult to assist as to why you are getting that without understanding things like what the myConnection object is and how it was constructed.

**Comment by bermudezc** [comment]
var mysql = require('mysql');
var myConn = mysql.createPool({
    host: 'localhost',
    user: 'user',
    port: '3306',
    password: 'user',
    database: 'test'
});

Banco_a.query("xa start 'a';", function(err, result, fields) {
    if (err) throw err;
    
    myConn.query("xa end 'a';", function(err, result, fields) {
        if (err) throw err;
        
        myConn.query("xa prepare 'a';", function(err, result, fields) {
            if (err) throw err;
   
        });
    });

});

**Comment by dougwilson** [comment]
The issue is that you are using the .query helper of a pool, which changes the connections. You either need to change you code to use createConnection instead of createPool or use the getConnection method on the pool and perform your transactions off that single connection.

**Comment by bermudezc** [comment]
yes, i tried with createConnection too and is the same error. 
I thought of something specific like **myConn.beginXAtransaction**

**Comment by dougwilson** [comment]
So I was assuming in your code that `Banco_a` was a typo of `myConn`, but perhaps not. Here is the code I have that works with no issue:
```js
var mysql = require('mysql');
var myConn = mysql.createConnection({
    host: 'localhost',
    user: 'user',
    port: '3306',
    password: 'user',
    database: 'test'
});

myConn.query("xa start 'a';", function(err, result, fields) {
    if (err) throw err;
    
    myConn.query("xa end 'a';", function(err, result, fields) {
        if (err) throw err;
        
        myConn.query("xa prepare 'a';", function(err, result, fields) {
            if (err) throw err;
   
        });
    });

});
```

**Comment by bermudezc** [comment]
I don't understand i had already try that and trow: **'XAER_RMFAIL: The command cannot be executed when global transaction is in the  NON-EXISTING state'**
Thanks a lot Douglas

**Comment by dougwilson** [comment]
Can you include the stack trace so I can see which of those three queries is the one that has that issue?
