### ISSUE TITLE
promisified pool.query wont release/destroy connection

### ISSUE THREAD

**Issue by montanaolive** [mysqljs/mysql#2426]
lets say you use pool.query inside a promise like this

```
()=>{
     return new Promise((resolve,reject) => {
           pool.query(a query,values,(error,results,fields) => {
                if(!results.length) reject()
                else resolve()
           })
     })
}
```

the connection to the pool wont close, since the pool.query function finished its work with the call of reject of resolve.
Using the long way like this

```
()=>{
      return new Promise((resolve,reject) => {
           pool.getConnection((err,connection)=>{
                  connection.query(a query,values,(error,results,fields) => {
                       if (!results.length) reject()
                       else resolve()
                       connection.destroy()
                  })
            })
      })
}
```
seems to do the work. I know its not that much of a difference for a solution in this type of problem. But promisified queries are a way to retrieve the data if you have your queries in a different file.

**Comment by dougwilson** [comment]
The behavior you are describing has nothing to do with promises. When you use a pool, the whole point is that the connection is _not_ closed when you finished your query. You can read more about the concept of connection pooling on Wikipedia, amongst other places: https://en.wikipedia.org/wiki/Connection_pool

**Comment by montanaolive** [comment]
I am new in this area. I just wanted to mention the differences in the behavior of these 2 type of connections to a pool when they are promisified.
