### ISSUE TITLE
how do i use "?" as variables for my values so that i don't get hacked?

### ISSUE THREAD

**Issue by AntoCrasher** [mysqljs/mysql#2430]
I was wondering how do I use question marks so that I don't get hacked because when I use this:
`SQL = "INSERT INTO users (id, username) VALUES ( " + message.author.id + ", " + message.author.username + ")"`
it gives me an error: `Unknown column '(my username)' in 'field list'`
I know you will say that there is already a post like this, but I am kinda a beginner still so I don't understand what they are saying

**Comment by dougwilson** [comment]
https://github.com/mysqljs/mysql#escaping-query-values

**Comment by AntoCrasher** [comment]
thnakss
