### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by emmansun** [mysqljs/mysql#2433]
We used loopback 3 and mysql in our project, detail packages are as below:
      
     "loopback": "^3.27.0",
     "loopback-boot": "^3.3.1",
     "loopback-component-explorer": "^6.5.1",
     "loopback-connector-mysql": "^6.0.0",
 
Our deployment environment is Azure K8S
    **NodeJs 12.18.3**

and our Mysql tables also have no special data types expect **MEDIUMTEXT** and **TEXT**, and the table columns are no more than 20.

We also integrated Azure Application Insights in our application/service as APM/Distribution Trace service.

We found the performance degradation after several days:
- Sometimes, there are some slow queries from application view but we can't find slow query at server side; and the slow queries happened frequently over time.
- Event loop CPU time became higher (This metrics is collected by [ApplicationInsights nodejs native](https://github.com/microsoft/ApplicationInsights-node.js-native-metrics))
![image](https://user-images.githubusercontent.com/7235232/98186488-c8fc8c80-1f49-11eb-897b-e540b469b07e.png)
- From Azure K8S, the average CPU time is normal, did NOT find high CPU issue
- Request performance degradation, we can find it's NOT related to loading/TPS, but the operation time was rising day by day.
![image](https://user-images.githubusercontent.com/7235232/98186946-d9613700-1f4a-11eb-8207-5ea1a9cb7760.png)

We tried to increase **UV_THREADPOOL_SIZE** to **16** (mysql connection pool size is default: 10), but it seems it just postponed the degradation, but it can't resolve this issue fundamentally. We had to restart our application/service regularly as short-term solution now.

In fact, we also has other services used **loopback 3** + **Mongodb**, we did NOT find similar issue.

**Comment by dougwilson** [comment]
Based on even your version numbers, you are not using this module directly, so it would make it even harder to track down. I use this module in various applications with a lot of usage and don't have any issue, but perhaps I am not using the module in the same way.

Unfortunately, though you are having issues, there is just not enough information provided here to actually look into the problem. Perhaps could you provide a reduced test case that just uses this module that reproduces the issue? Or maybe memory dumps from your application for the duration of the issue, or flame graphs of where the time is being spent during the slow queries?

**Comment by emmansun** [comment]
Thx @dougwilson 's quick answer, "loopback-connector-mysql": "^6.0.0" depends on "mysql": "^2.11.1", and the real used mysql version is "2.18.1".

Due to we just find this issue in our production environment now, we still tried to reproduce it in non-prod env.

**Comment by sidorares** [comment]
@emmansun I'd check memory usage as a first suspect, GC pauses might cause increase in latency and CPU load
Try to log regularly [process.memoryUsage()](https://nodejs.org/api/process.html#process_process_memoryusage), if you see strong signal that your application heap grows over time (unproportional to the load) then start your app with `node --trace_gc`

**Comment by emmansun** [comment]
Thx @sidorares , the used heap grows over time, we used local memory cache, and start nodejs with --max-semi-space-size=64.

We redeployed it after Oct 23 11:00 AM, and also redeployed it after Nov 03 11:00 PM.
**Avg Memory Usage (Heap)** :
![image](https://user-images.githubusercontent.com/7235232/98191658-a58b0f00-1f54-11eb-8aa5-c808bfada71e.png)
**Max Memory Usage (Heap)** :
![image](https://user-images.githubusercontent.com/7235232/98191716-c18eb080-1f54-11eb-8e76-c6e771dceb41.png)

**Avg IncrementalMarking Garbage Collection Duration:**
![image](https://user-images.githubusercontent.com/7235232/98192103-5beef400-1f55-11eb-8721-972a5b4dfcec.png)
**Max IncrementalMarking Garbage Collection Duration:**
![image](https://user-images.githubusercontent.com/7235232/98192208-96589100-1f55-11eb-9735-34ff645c993b.png)

**Avg MarkSweepCompact Garbage Collection Duration**
![image](https://user-images.githubusercontent.com/7235232/98192246-abcdbb00-1f55-11eb-880e-e985579abf13.png)
**Max MarkSweepCompact Garbage Collection Duration**
![image](https://user-images.githubusercontent.com/7235232/98192301-c43dd580-1f55-11eb-99e7-77841a0809a8.png)

**Comment by Zikoel** [comment]
@emmansun what is the conclusion of this discussion? The decreased performance are caused by mysql driver or some other issue (like memory leak suggest) inside your application ?

**Comment by emmansun** [comment]
@Zikoel , we still do not have conclusion for it, we had upgraded nodejs to 12.22.x , and will upgrade it to 14.16.x soon. We will disable azure application insights mysql auto-collect soon, to check if it's impacted by it.

**Comment by emmansun** [comment]
I think this issue's root cause is NOT related to this package, after we upgraded/changed crypto and uuid related implementation, this issue disappeared .
