### ISSUE TITLE
Just another UNKNOWN_CODE_PLEASE_REPORT

### ISSUE THREAD

**Issue by bardouni** [mysqljs/mysql#2437]
![image](https://user-images.githubusercontent.com/11160251/99992522-bc37bf80-2db6-11eb-8718-03f29065f4df.png)
I get this with this query "select * from payments for share lock in share mode".
Thank you.

**Comment by dougwilson** [comment]
Thank you! Looks like this is code 3568 added in 8.0.1; it will be resolved with PR #2386
