### ISSUE TITLE
pool.releaseConnection is not a function

### ISSUE THREAD

**Issue by move-zig** [mysqljs/mysql#2441]
A pool created from createPool() works fine, but the pools returned from poolCluster.of() do not have a releaseConnection function.

Works:
```
const pool = createPool(options);
pool.getConnection((err, connnection) => {
  pool.releaseConnection(connection);
});
```

Doesn't work:
```
const poolCluster = createPoolCluster();
poolCluster.add(options);
const pool = poolCluster.of('*');
pool.getConnection((err, connnection) => {
  pool.releaseConnection(connection); // TypeError: pool.releaseConnection is not a function
});
```

Is this intentional? The typescript types given in @types/mysql imply that releaseConnection should be available. If this is intentional, then I will open an issue with @types/mysql.

In the meantime, we can use connection.release() instead.

**Comment by dougwilson** [comment]
pool.releaseConnection is not a publicly documented function, as it is for internal usage. The cluster pools are internally different. You should not be using undocumented methods or properties at all :)

**Comment by dougwilson** [comment]
It sounds like whoever is managing the types is including non public methods, it seems. I'm not sure if that is right or not, as I don't use typescript.
