### ISSUE TITLE
Is mysql_stmt_send_long_data supported ?

### ISSUE THREAD

**Issue by ortegarenzy** [mysqljs/mysql#2444]
I am trying to insert large blobs into MySQL but fails because of ER_NET_PACKET_TOO_LARGE. I don't want to change the setting of the MySQL that's why I was hoping if this approach is supported here ?

**Comment by dougwilson** [comment]
Hi @ortegarenzy this module does not  (currently) support prepared statements functionality (https://github.com/mysqljs/mysql#todo).

**Comment by ortegarenzy** [comment]
@dougwilson Thank you for the info!
