### ISSUE TITLE
Error with esplugin_mysql and es_admin2 at FiveM server

### ISSUE THREAD

**Issue by MGZBright** [mysqljs/mysql#2445]
Hi!
I've got a problem with my esplugin_mysql and es_admin2. I'm trying to make a GTA5 FiveM RP server for my friends. Now i was trying to make a database and run essentialmode. Below is link with my issue. I can upload more screenshots if you want. Looking forward for help, thanks.
Imma really sorry for my language, I'm from Eu.

https://imgur.com/xScOGDF

**Comment by dougwilson** [comment]
Hi @MGZBright what you are showing in your screenshots don't seem to have anything to do with this Node.js module.
