### ISSUE TITLE
Question about RowDataPacket

### ISSUE THREAD

**Issue by sqllyw** [mysqljs/mysql#2452]
Hi,
try out this:
````
connection.connect();

connection.query('select *  from user', function (error, results, fields) {
  if (error) throw error;
  let data = results[0]
  console.log(data) 
});
````
and got this:
````
RowDataPacket {
  Host: '%',
  User: 'root',
  Password: '*',
  Select_priv: 'Y',
  Insert_priv: 'Y',
  Update_priv: 'Y
}
````
just curious what data type of results[0]? and RowDataPacket seems not a json property, and yet I can access it like this:
````
console.log(data.Host)
````
without referencing to RowDataPacket, can anybody enlighten me on this? Thanks

**Comment by dougwilson** [comment]
Hi @sqllyw this is just how Node.js formats objects when using `console.log`. If you want to see it as the standard JavaScript object that it is, you can use `console.log(JSON.stringify(results, null, 2))`.

**Comment by sqllyw** [comment]
wow, so far the fastest response I ever got in github, thanks!
