### ISSUE TITLE
mysql pool - Looping through multiple queries

### ISSUE THREAD

**Issue by dharmeshnayer** [mysqljs/mysql#2455]
Hey, I'm trying to insert data into 3 tables simultaneously in mySQL DB. Each of the tables have a foreign key to the next ie table one to two and two to three.  How do I insert multiple rows of data into the 3 tables using mysql pool. Currently I loop through the data I have , insert it into the first table, get the unique key which is a foreign key in table 2. Use this key to insert multiple rows of data into table 2. Get the unique keys of all the rows inserted into table 2 and use them to insert data into table 3. Is there a simpler or efficient way to do this ?

**Comment by mbaumgartl** [comment]
You could write a stored procedure.

**Comment by dougwilson** [comment]
This is just how MySQL works, unfortunately. You'll need to use a stored procedure to prevent round trips if that is what you want.
