### ISSUE TITLE
dataGrip连接报错Error encountered when performing Introspect schema information_schema: Unknown column 'generation_expression' in 'field list'. Unknown column 'generation_expression' in 'field list'

### ISSUE THREAD

**Issue by zhushuaiCoding** [mysqljs/mysql#2470]
Now I check the introspect using jdbc metadata option on the datagrip, which can cause the presentation information of the table to not be seen.
![image](https://user-images.githubusercontent.com/38322565/110732150-8f70c080-825e-11eb-832d-967ad200f39d.png)
![image](https://user-images.githubusercontent.com/38322565/110732164-94ce0b00-825e-11eb-9c74-c811cf610434.png)

**Comment by dougwilson** [comment]
This repository is for the Node.js module to connect to MySQL, not for the MySQL server itself.

**Comment by zhushuaiCoding** [comment]
Ask me where I can solve this problem. If you know, please attach a link













At 2021-03-11 11:43:08, "Douglas Wilson" <notifications@github.com> wrote:

This repository is for the Node.js module to connect to MySQL, not for the MySQL server itself.
