### ISSUE TITLE
Is option to connect to DB through SSH ?

### ISSUE THREAD

**Issue by Amrkamel1** [mysqljs/mysql#2473]
Is there any feature through which i can connect to the server through SSH then initiate a connection to the running DB on that server.?

**Comment by dougwilson** [comment]
Hi @Amrkamel1 yes, this module just makes a TCP connection to the server like most programs. If you want to connect to something over a SSH connection, just set up SSH port forwarding as usual and then point this module at the local port and localhost. I hope that helps!

**Comment by Amrkamel1** [comment]
Definetly it helps, could provide any reference that could work with mysql.

I have tried many node packages but failed to do so always getting timeout

**Comment by dougwilson** [comment]
Hi @Amrkamel1 no problem! Here is an example for how to set up a tunnel with the SSH program (the most common way): https://www.ssh.com/ssh/tunneling/example

**Comment by Amrkamel1** [comment]
@dougwilson 

I have managed to connect through ssh thanks so much.

but i have another question how i can disable all meta data like the highlighted part below 

![image](https://user-images.githubusercontent.com/32042806/112466745-77bd3000-8d66-11eb-96c5-4446a3c19f3e.png)
