### ISSUE TITLE
Connect mysql ER_ACCESS_DENIED_ERROR, but after connect through workbench, try sequelize again success!

### ISSUE THREAD

**Issue by grapewheel** [mysqljs/mysql#2474]
Node: 14.16
sequelize: 6.5.1
mysql2: 2.2.5
mysql server: 8.0.4 docker
mysql server password strategy: caching_sha2_password

**Normal**: I can connect to mysql throw cli, workbench, and **other node module**
**Weird**: When I connect to mysql through sequelize, it always throws **ER_ACCESS_DENIED_ERROR**, BUT after I try **workbench** success, I come back try sequelize again, it was success indeed!~

It was said that if I didn't connect success throught other method, I can NOT connect it through sequelize!

```
sequelizeOptions: {
			database: 'repair',
			dialect: 'mysql',
			host: '127.0.0.1',
			port: 3306,
			username: 'root',
			password: 'root',
			logging: false
		},
```

![微信截图_20210325104441](https://user-images.githubusercontent.com/490426/112411112-4e48d800-8d57-11eb-9b72-e40c828c8e92.png)

**Comment by dougwilson** [comment]
I think you posted this in the wrong repo, seeing as you listed mysql2 as the driver.
