### ISSUE TITLE
Renaming 

### ISSUE THREAD

**Issue by sschell1** [mysqljs/mysql#2476]
https://github.com/mysqljs/mysql#poolcluster
Please make use of provider/consumer or a more neutral naming pair when describing pool cluster configurations. 
Thank you.

**Comment by dougwilson** [comment]
Hi @searraschell thank you for your issue report. The PoolCluster was a contribution from a few users and I'm not very familiar with it, including what you mean by your issue. Can you ellaborate more on what you mean? Or perhaps submit a PR for the change you are looking for?

**Comment by Zikoel** [comment]
I think this is a question of don't use `master` or `slave`! To accomplish this is sufficient to rename some words on the readme no code need to be touched.

**Comment by dougwilson** [comment]
Oh, I see. These are the direct terms used by the MySQL server itself (https://dev.mysql.com/doc/internals/en/replication.html). If they can provide new terms to use in their literature, we can update them here to match. If they don't match, then we would need to add somewhere in here the mapping, which I think would defeat the purpose as they would still end up in the readme.
