### ISSUE TITLE
Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by 178900PRITAM** [mysqljs/mysql#2487]
im using 
```
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : '1.0.1',
  port     : '3306',
  user     : 'us',
  password : "pwd",
  database : 'db'
});

```
for my discord bot but when this error apears the bot crashes 
because of this error
Error: Connection lost: The server closed the connection.

**Comment by aratnamirasugab** [comment]
@178900PRITAM  Hi you can add code to make handle when the mysql disconnects

**Comment by dougwilson** [comment]
Closing due to no response.
