### ISSUE TITLE
Employee id fetching issue

### ISSUE THREAD

**Issue by ashishsme14** [mysqljs/mysql#2493]
Our task is

![Employee Issue 1](https://user-images.githubusercontent.com/61864865/122250868-aa02a780-cee7-11eb-8381-906bbf79a5a9.JPG)

We written

select  x.DEPTNO from department x where x.DEPTNO not in 
(select d.DEPTNO from department d join
employee e where e.deptid=d.DEPTNO)

Not working , please help us on it.

**Comment by dougwilson** [comment]
Hello, I'm sorry you are having issues. Are you having an issue actually formulating your MySQL query, or with the usage of this JavaScript library?

**Comment by ashishsme14** [comment]
formulating your MySQL query,

**Comment by dougwilson** [comment]
Hi @ashishsme14 thanks for clarifying. This is the issue tracking for the JavaScript library that is contained in the repository. I would suggest posting on somewhere more generic, like Stackoverflow.
