### ISSUE TITLE
mysql error with cronjob (node-cron)

### ISSUE THREAD

**Issue by segun-flexible** [mysqljs/mysql#2494]
Am using node-cron to run a cron job every 12 Oclock Midnight, the job am running is to increment some data on the user table,
the issue now is that, the job will run twice.

e.g i wanna increment 15, after 12 o'clock, it will turn to 17 instead of 16.

have tried my possible best to detect the issue ,am unable.

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble. Your issue is unrelated to this module, unfortunately; you will likely want to seek help from the corn stuff.
