### ISSUE TITLE
Error: Cannot enqueue Query after fatal

### ISSUE THREAD

**Issue by devsabai** [mysqljs/mysql#2497]
Hi I am new to nodejs and trying the connect the Mysql.
I am really troubled with the error Cannot enqueue Query after fatal error.

My code :

```
let mysql = require('mysql');
let connection = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "",
    database: "api_db"
})

connection.connect((error) => {
    if (!!error) {
        console.log(error);
    } else {
        console.log("Connceted .....................................");
    }
})

module.exports = connection;
```
My code : 

```
let dbCon = require('../lib/db')

exports.index = async (req, res, next) => {
    dbCon.query(`SELECT id, po_no, pr_no, quote_no, customer_name, contact_name, description, category_name, po_date, approve FROM po_view`, (err, rows) => {
        if (err) {
            console.log('error', err)
        } else {
            res.status(200).json(rows)
        }
    })
}
```

**Comment by dougwilson** [comment]
Hello, and welcome! The error means that a fatal error has occurred on the given connection and you cannot enqueue queries on the connection any longer. Fatal errors are things like the tcp connection is lost and other things that cannot be recovered and require you to make a new connection. 

You can find more in the error handling docs https://github.com/mysqljs/mysql#error-handling

**Comment by devsabai** [comment]
> Hello, and welcome! The error means that a fatal error has occurred on the given connection and you cannot enqueue queries on the connection any longer. Fatal errors are things like the tcp connection is lost and other things that cannot be recovered and require you to make a new connection.
> 
> You can find more in the error handling docs https://github.com/mysqljs/mysql#error-handling

Thank you so much @dougwilson my error like this, can you recommend
![Screen Shot 2021-06-30 at 05 34 28](https://user-images.githubusercontent.com/74530969/123876512-a8b09080-d965-11eb-8e87-13abec5b7c8d.png)

**Comment by dougwilson** [comment]
Hi, yes, that error you posed means you got an error previously but did not handle it. If you can provide the error that came before it I may be better able to assist. Looking at your code, you just log out any error, but do not take any action to do anything, like create a new connection if needed. This is why you are getting the error you posted.
