### ISSUE TITLE
Convert Field columnType to human readable format

### ISSUE THREAD

**Issue by UserSina** [mysqljs/mysql#2504]
I have a simple use case where I want to display the types of the fields:

```JAVASCRIPT
let [rows, fields] = await conn.execute("SELECT * FROM users");
var typesArray = fields.map((field) => {
    return field['columnType'];
  });
```
However the output is:
```
[3, 252, 252]
```

I want to ultimately get `['int', 'string', 'string']`  or something similar.

**Comment by dougwilson** [comment]
Hi @UserSina you may have opened this in the wrong repository. This module does not support the `await` syntax, does not have an `.execute` method, and does not have a `columnType` property on the field objects.
