### ISSUE TITLE
DatabaseMetaData.getTypeInfo() Method not return json data type

### ISSUE THREAD

**Issue by zjcnb** [mysqljs/mysql#2508]
Hi everyone，

 I used mysql driver 5.x and 8.x， use jdbc through java, not return  json data type, executing the sql command also did not find, such as: ? data types;

 AUTO_INCREMENT
   BIGINT
   BINARY
   BIT
   BLOB
   BLOB DATA TYPE
   BOOLEAN
   CHAR
   CHAR BYTE
   DATE
   DATETIME
   DEC
   DECIMAL
   DOUBLE
   DOUBLE PRECISION
   ENUM
   FLOAT
   INT
   INTEGER
   LONGBLOB
   LONGTEXT
   MEDIUMBLOB
   MEDIUMINT
   MEDIUMTEXT
   SET DATA TYPE
   SMALLINT
   TEXT
   TIME
   TIMESTAMP
   TINYBLOB
   TINYINT
   TINYTEXT
   VARBINARY
   VARCHAR
   YEAR DATA TYPE

**Comment by dougwilson** [comment]
Hello, sorry you are having trouble. Unfortunately this is the wrong repository for your question, as this is a driver for Node.js
