### ISSUE TITLE
Pool and Workers

### ISSUE THREAD

**Issue by BronislavKlucka** [mysqljs/mysql#2512]
Hi, 
I have a question about pool and worker threads, when creating pool of e.g. 5 connections in e.g. 3 workers, will there be 15 max connections (5 per every worker) or only 5 (shared across workers?)
I would assume 15, but I'd like to make sure....
Thanks for the answer

**Comment by dougwilson** [comment]
Yes, that ia correct. You could even do that within the same worker, as the limit is per the pool instance you create.
