### ISSUE TITLE
表新增一个时间字段使用current_timestamp()和使用null为默认值是否影响性能

### ISSUE THREAD

**Issue by hudongdong129** [mysqljs/mysql#2537]
比如现在一张表有100万数据 这个时候需要新增一个datetime类型的时间字段，默认为current_timestamp()或null是否性能不一致

**Comment by dougwilson** [comment]
Hello, and sorry you are having any issues. Unfortunately your question is unrelated to this Node.js module and is just a generic MySQL question. You may want to ask Oracle or on a forum like StackOverflow.
