### ISSUE TITLE
How to catch ER_BAD_FIELD_ERROR

### ISSUE THREAD

**Issue by lz000** [mysqljs/mysql#2542]
I have this code
```
const connection = mysql.createConnection(dbConfig);

connection.query(
        'INSERT INTO ...',
        [...],
        (e) => {
          if (e) {
            console.log(e)
          };
        }
);
```
When ER_BAD_FIELD_ERROR happens, It is not handled by the callback, thus the `if (e)` conditional is not invoked. Instead it causes the program to terminate with uncaught error. I also tried adding `try catch` around the `connection.query` but same issue. Is there a way to catch this error so that program will not stop?

**Comment by dougwilson** [comment]
Hi, very sorry that happened. Can you provide a complete reproduction result? A quick try did work as you expected, but there is so little information provided so far.

**Comment by lz000** [comment]
sorry my bad, it is actually a different error causing the program to stop
