### ISSUE TITLE
Prevent unexpected SQL Injections by changing the default stringifyObjects option

### ISSUE THREAD

**Issue by stypr** [mysqljs/mysql#2554]
## Description

`stringifyObjects` option has been implemented by https://github.com/mysqljs/mysql/issues/501, but there are a lot of web frameworks such as `express` that allows Objects to be passed over, making the project potentially vulnerable to SQL injections when mysql package is used with the project.

A lot of online resources are also misleading, and I strongly think this needs to be fixed from the package itself, and shouldn't be manually fixed by the end-user developers. so I think it is better to make the default value of `stringifyObjects` to be `true` instead of `false`.

https://github.com/mysqljs/mysql/blob/3430c513d6b0ca279fb7c79b210c9301e9315658/lib/ConnectionConfig.js#L28

For example, such code written could be vulnerable to SQL injection, but it is really hard to even detect and recognize what could be a problem.

```js
app.post("/auth", function (request, response) {
  var username = request.body.username;
  var password = request.body.password;
  if (username && password) {
    connection.query(
      "SELECT * FROM accounts WHERE username = ? AND password = ?",
      [username, password],
      function (error, results, fields) {
        if (results.length > 0) {
          request.session.loggedin = true;
          request.session.username = username;
          response.redirect("/home");
        } else {
          response.send("Incorrect Username and/or Password!");
        }
        response.end();
      }
    );
  } else {
    response.send("Please enter Username and Password!");
    response.end();
  }
});
```

Please consider reading this article for more information.

English: https://flattsecurity.medium.com/finding-an-unseen-sql-injection-by-bypassing-escape-functions-in-mysqljs-mysql-90b27f6542b4

**Comment by dougwilson** [comment]
Hello, and thank you for your report. It seems you may be reporting a security issue. I have received your report above and will review in ASAP, but in the meantime I have removed it to provide time to review the content. You can reach out using the security procedure outlined at https://github.com/mysqljs/mysql#security-issues if you would like to be kept in the loop or discuss further. Thanks again and I will be looking in to this shortly.

**Comment by stypr** [comment]
@dougwilson 

There doesn't seem to be your e-mail address on your profile and the repo itself.
Please confirm if your email address is doug < at > something doug ( dot ) com

My e-mail address is h.kim ( at  ) flatt [dot] tech . I will reach out to you once the email address is confirmed

**Comment by dougwilson** [comment]
Hi @stypr yes, you can find emails through `package.json` or the `npm owner ls` command as is typical with npm packages.

**Comment by dougwilson** [comment]
It looks like changing the title does not remove it from the github interface, so I'll be deleting this issue shortly to clean it up, in case you see it disappear.
