### ISSUE TITLE
The correct table name when creating the table, with an error: ER_WRONG_TABLE_NAME.

### ISSUE THREAD

**Issue by liushuai05** [mysqljs/mysql#2558]
When creating a table, "Error: ER_WRONG_TABLE_NAME: incorrect table name' XXX'" will be mentioned when the table name is underlined.

- The above information comes from sogou Translate.

![1646125794981](https://user-images.githubusercontent.com/26994692/156139552-50251653-877a-4e10-a56f-e5a3ce6ba335.png)

**Comment by mbaumgartl** [comment]
Creating tables with underscores works perfectly fine. The whitespaces (before and after) in the table name are the problem:
```
mysql> create database foo;
Query OK, 1 row affected (0.00 sec)

mysql> use foo;
Database changed

mysql> create table `foo_bar` (id int);
Query OK, 0 rows affected (0.03 sec)

mysql> create table ` foobar ` (id int);
ERROR 1103 (42000): Incorrect table name ' foobar '
```

**Comment by liushuai05** [comment]
> 

Thank you very much for your patient answer. How to solve this problem? The same sql runs very well in phpmyadmin.

**Comment by mbaumgartl** [comment]
Just trim (remove whitespaces) the table name:

```sql
CREATE TABLE ` a_b `
```
should become
```sql
CREATE TABLE `a_b`
```

**Comment by liushuai05** [comment]
> Just trim (remove whitespaces) the table name:
> 
> ```sql
> CREATE TABLE ` a_b `
> ```
> 
> should become
> 
> ```sql
> CREATE TABLE `a_b`
> ```

Thank you very much. This problem has been solved. I used another library, which resulted in the automatic addition of spaces between`a_b`
