### ISSUE TITLE
Error: getaddrinfo ENOENT

### ISSUE THREAD

**Issue by mattwkelly** [mysqljs/mysql#262]
I'm using the sample code from the README, but I'm getting "Error: getaddrinfo ENOENT".

var mysql      = require('mysql'); var connection = mysql.createConnection({user     : '****_',password : '**_**',database : '****',}); connection.connect();

Thoughts? I've Googled around a bit, but haven't found anything pertinent.  Thanks!

**Comment by msingh025** [comment]
Error: getaddrinfo ENOENT issue come in different case.
steps .1 create connection using 
var pool      =    mysql.createPool({
    connectionLimit : 100, //important
    host     : 'localhost',
    user     : 'me',
    password : 'me',
    database : 'test',
    debug    :  false
});
2: connect network cable it is work fine. while my database is my local machine.
3: after disconnect network cable and start node server. 
it is throwing exception as "Error: getaddrinfo ENOENT".
I can not understand , what is decency on network..

**Comment by dougwilson** [comment]
This is an issue with Node.js itself, not this module. Please file the issue there.

**Comment by dougwilson** [comment]
FYI until Node.js fixes this, the work around is to use 127.0.0.1 instead of localhost

**Comment by dougwilson** [comment]
Here is a very recent Node.js issue about this: https://github.com/joyent/node/issues/25338
