### ISSUE TITLE
Error: getaddrinfo ENOENT with a lot of connection

### ISSUE THREAD

**Issue by bbcelly** [mysqljs/mysql#284]
I'm getting this error, when service that uses this module has a lot of hits from users.

Any thoughts? I've Googled, but nothing usable found. Thanks.

**Comment by julesmoretti** [comment]
@bbcelly I am encountering the same problem. Could you walk me through finding those file descriptors and what to change? I am running an Ubuntu server with node mysql and... same issues :)

Thank you for the help.

**Comment by bbcelly** [comment]
@julesmoretti As I wrote, you need to set allowed number of file descriptors (and/or) use only few active connections. I made a pool of connections, that is permanetly connected to mysql, and any request just reuse them.
