### ISSUE TITLE
Return affected rows

### ISSUE THREAD

**Issue by TehShrike** [mysqljs/mysql#363]
Giving some way to access the "affected rows" value for queries, similar to how last insert id is handled, would be quite spiffy.

**Comment by eaholt06** [comment]
So at the moment, there isn't a way to access the 'affected_row' directly when you make an update? I am trying to update a field in a row (accessed with its ID) and then get other field values from that row after the UPDATE. Is there a way to do this without 2 separate queries? (1 for update, 1 for select)

**Comment by TehShrike** [comment]
The [example code maltzj posted](https://github.com/felixge/node-mysql/issues/363#issuecomment-11724676) worked fine for me without needing to run a second query.
