### ISSUE TITLE
Please review documentation and give feedback

### ISSUE THREAD

**Issue by kai-koch** [mysqljs/mysql#370]
Please review the documentation I have started at:
https://github.com/kai-koch/node-mysql/wiki

This is only a draft and consists mainly of the `readme.md` broken down into an sections sorted by (subjective) importance.

For the examples given I increased indentation from 2 to 4 spaces, because it is more readable IMO .

If the draft meets your approval I would like to continue working on:
- more in depth examples from practical use-cases
- in the API section, I would like to add descriptions like on php.net for methods and objects the end-user has to deal with

Please give feedback and, of course, suggestions on how to improve the structure of this draft.

**Comment by dougwilson** [comment]
I'm going through old issues in preparation for a major release. I'm going to close this as clean up, as I think perhaps this was already completed, but at least the link no longer works 😂
