### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by raxitsheth** [mysqljs/mysql#372]
Hi

I am writing simple user sign-up form.
Id,Name,Email,mobilenumber

email=unique
mobilenumber=unique.

On duplicate vaue, i am getting proper error message, but i am not sure how to identify which field is duplicate (and accordingly instruct the user!)  

Currently, node-mysql error is mapped to mysql, but Is it meaningful to set few more extra stuff in Error  object ?  

PS : i know it is tough to break compatibility as many other projects uses node-mysql internally.

**Comment by ZaidPathan** [comment]
@felixge IMHO, It should at-least throw which fields are causing issue.
