### ISSUE TITLE
Add custom query format to entire connection pool

### ISSUE THREAD

**Issue by ShimShamSam** [mysqljs/mysql#401]
Currently you allow connections to have a custom queryFormat function which allows custom argument parsing. If you're using a connection pool, however, you have to specify it on every new connection. Perhaps there should be a way to apply the default queryFormat for an entire pool?

**Comment by azaiter** [comment]
Apparently, queryFormat is not passed, a workaround to this would be the following code:

```javascript
pool.on('connection', function (connection) {
    connection.config.queryFormat = function (query, values) {
        if (!values) return query;
        return query.replace(/\:(\w+)/g, function (txt, key) {
            if (values.hasOwnProperty(key)) {
                return this.escape(values[key]);
            }
            return txt;
        }.bind(this));
    };
});
```
