### ISSUE TITLE
pool default timeout

### ISSUE THREAD

**Issue by sapkal-manish** [mysqljs/mysql#424]
I have used pool with node-mysql.

I want to know, When is the time for connection destroy? means when my connection object is getting destroyed and my resource is freed. 

thanks.

**Comment by lroal** [comment]
I think idle connetions in the pool should be closed after a while.There also should be a max number of connections in a pool. This could be a default value of something, but could be set explicitly. If there are too few connections available at the time, requests must wait for a connection to be idle. Node-postgres seems to handle it this way.
