### ISSUE TITLE
Charsets problem

### ISSUE THREAD

**Issue by tomasikp** [mysqljs/mysql#441]
I recently ran into an interesting problem with my node-mysql setup.  In the past I was using a combination of [generic-pool](https://github.com/coopernurse/node-pool) and node-mysql to accomplish connection pooling.  Each connection was being created in the following way:

```
var connection = mysql.createConnection({
            host     : config.host,
            user     : config.user,
            password : config.password,
            database:  config.database,
            charset: 'utf8mb4'
});
```

Everything worked beautifully, emoji were being saved nicely in my tables with utf8mb4 columns.

However, when I recently decided to upgrade from alpha4 to alpha7 I noticed that emoji were not coming back or saving into the db correctly any longer.  Upon further investigation the charset configuration I was using above was horribly wrong, considering there was:
- No mapping for utf8mb4 in the lib/protocol/constants/charsets.js file (Added a pull request with fresh charsets in #440)
- this.charsetNumber is set to **undefined** in [ConnectionConfig.js](https://github.com/felixge/node-mysql/blob/master/lib/ConnectionConfig.js#L37-L39) when an invalid charset is input as an option.

I tried adding the proper charset to my local node-mysql charsets.js file adding:

```
exports.UTF8MB4_UNICODE_CI   = 224;
```

and changing the config to {charset: 'UTF8MB4_UNICODE_CI'} : Success!

Then I noticed that there was a problem with subsequent pooled connections reverting to unwanted behavior.  

added a fix to pull request #440 

I wonder why the undefined charsets worked with utf8mb4?

**Comment by Nedudi** [comment]
`charset: 'utf8mb4'`

save me a day, awesome!    
thanks!
