### ISSUE TITLE
Connection lost. The server closed the connection

### ISSUE THREAD

**Issue by sapkal-manish** [mysqljs/mysql#532]
I am using mysql@2.0.0-alpha7 with node.js.

I have written code as follows: 

``` javascript
var mysql = require('mysql');
var pool  = mysql.createPool({
  host     : 'example.org',
  user     : 'bob',
  password : 'secret',
});

pool.getConnection(function(err, connection) {
   connection.query(query, function (err, rows, fields) {
        connection.end();

        if (err) {
           //Return Error
        };
        //Return result
   });
});
```

But Now a days, I am getting error "Connection lost. The server closed the connection."  
Detailed error is like this:

```
 Thu Jul 04 2013 00:40:47 GMT+0000 (Coordinated Universal Time) - uncaughtException : Error: Connection lost: The server closed the connection. stack Error: Connection lost: The server closed the connection.
    at Protocol.end (C:\inetpub\wwwroot\NodeJs\node_modules\mysql\lib\protocol\Protocol.js:72:13)
    at Socket.onend (stream.js:66:10)
    at Socket.EventEmitter.emit (events.js:126:20)
    at TCP.onread (net.js:418:51) 
```

What is the solution for the problem.

Thanks.

**Comment by swapnilaryan** [comment]
you can use this code 
`var db_config = {
  host: 'localhost',
    user: 'root',
    password: '',
    database: 'example'
};

var connection;

function handleDisconnect() {
  connection = mysql.createConnection(db_config); // Recreate the connection, since
                                                  // the old one cannot be reused.

  connection.connect(function(err) {              // The server is either down
    if(err) {                                     // or restarting (takes a while sometimes).
      console.log('error when connecting to db:', err);
      setTimeout(handleDisconnect, 2000); // We introduce a delay before attempting to reconnect,
    }                                     // to avoid a hot loop, and to allow our node script to
  });                                     // process asynchronous requests in the meantime.
                                          // If you're also serving http, display a 503 error.
  connection.on('error', function(err) {
    console.log('db error', err);
    if(err.code === 'PROTOCOL_CONNECTION_LOST') { // Connection to the MySQL server is usually
      handleDisconnect();                         // lost due to either server restart, or a
    } else {                                      // connnection idle timeout (the wait_timeout
      throw err;                                  // server variable configures this)
    }
  });
}

handleDisconnect();`

**Comment by yashgt** [comment]
Same issue here.
