### ISSUE TITLE
Return values query

### ISSUE THREAD

**Issue by TWEESTY** [mysqljs/mysql#554]
Hello all,

I have several problems with return of queries.

Here, what I would like to do : 

---

```
//If the email hasn't a good format
if(email_not_good_format())
   //I do something
else if(email_already_exists_in_mysql(email))
  //I do something


function email_already_exists_in_mysql(email){
connection.query('SELECT COUNT(*) AS nb FROM user WHERE emailUser = ' + connection.escape(email), function(err, rows, fields) {
        if (err) throw err;
        if(rows[0].nb == 0)
            return false;
        else
            return true;
    });
}
```

---

I saw on different posts callback function but it doesn't work for what I want to do.

Thanks for your help!

Regards

**Comment by challapruthvi** [comment]
Hello I am new to Nodejs and i was working with some similar example which was stated above (working with mysql too). I couldnt return the values in the callback functions. 

How can I use the callback to get a particular value out of that function to another place ??
Here is my code:

connection.query('CREATE TABLE sampletest'+
						'(id INT(11) AUTO_INCREMENT, '+
						'Testname VARCHAR(255), '+
						'Attributename VARCHAR(255), '+
						'PRIMARY KEY (id));', function(err, rows){
							if (err) {
								console.log("ERROR: "+ err.message);
								throw err;
							}
							console.log('dsmtest table has been created');
							return true;
						});
						
can you elaborate with any example. That would help me a lot.
Thanks in advance.
