### ISSUE TITLE
ER_ACCESS_DENIED_ERROR: 

### ISSUE THREAD

**Issue by sushantchavan** [mysqljs/mysql#591]
Am sure this has already been sorted out but couldn't find anything conclusive.

I am specifying the database credentials when I create the mysql.createConnection

While connecting to the db it gives with this error Access denied for user \'root\'@\'triband**********.mtnl.net.in\' (using password: YES)'

I am 100 % sure these are not the credentials for the database. How do I solve this ?

**Comment by thegreatmichael** [comment]
hey team, i know it's been a while on this issue, but i'm seeing a problem like this. I'm getting:

`Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'myuser '@'localhost' (using password: YES)`

when i run my node script from root (`su sudo` on ubuntu 14.04) the script works when i run as `myuser` (anyway it explicitly tells node-mysql to use `myuser`)

**Comment by sidorares** [comment]
Hi @thegreatmichael 

grant entries are separate for local domain socket and tcp connections, when you connect from command line you are likely do it via domain socket ( you can locate it with `mysql_config --socket` command ) so the solution is to either 1) add grant entry for 'localhost' or 2) connect using socket - see `socketPath`  [connection option](https://github.com/felixge/node-mysql#connection-options)

**Comment by thegreatmichael** [comment]
thanks for the quick response @sidorares ! I'm slightly confused, probably because I provided too little info.  see below:

    mysql> mysqlgrants;
    +---------------------------------------------------------------------------+
    | Grants for myuser@localhost                                               |
    +---------------------------------------------------------------------------+
    | GRANT USAGE ON *.* TO 'myuser'@'localhost' IDENTIFIED BY PASSWORD <secret>|
    | GRANT ALL PRIVILEGES ON `somedbdev`.* TO 'myuser'@'localhost'             |
    | GRANT ALL PRIVILEGES ON `somedbprod`.* TO 'myuser'@'localhost'            |
    +---------------------------------------------------------------------------+

So, I think i have allowed the user the permission on localhost, should that work?

To be clear:

    myuser@mymachine:~somepath$ node myscript.js 

^works! (-: ^

    myuser@mymachine:~somepath$ sudo su
    root@mymachine:/home/myuser/somepath# node myscript.js 

    /home/myuser/somepath/myscript.js:462
          if(err) throw err;
                        ^
    Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'myuser '@'localhost' (using password: YES)

^ doesn't work )-: ^

**Comment by dougwilson** [comment]
Hi @thegreatmichael, perhaps when you run it as root, it is accessing some different configuration file or something? The error is that the login failed for the user `'myuser '`, where there is a space character at the end of the username. I assume you user does not actually have a space, so there is some kind of thing happening in your code adding a space at the end of your username it seems. Try attaching a debugger to your code to see where it is coming from.

**Comment by thegreatmichael** [comment]
thanks @dougwilson YOU GLORIOUS CHAMPION! you are a golden god. indeed, i was originally running with env vars on the command line

    env1=something env2=else node script.js

but when i copied that to change it into individual lines, i didn't remove the (not so visible in my editor) trailing spaces!

(It's working)

**Comment by mytharcher** [comment]
Upgrade the package version to `^2.1.x` solved my problem.

**Comment by ClarenceL** [comment]
Ya my issue was with one particular version 2.1.0 I think I was on had an issue, 2.13.0 was fine

**Comment by SURESHA2** [comment]
any buddy can help????????

Details:  Error: Could not connect to MySQL:
Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

**Comment by isabellachen** [comment]
Had trouble until I found out I was using the root user. My config:
`var connection = mysql.createConnection({
  host: 'localhost',
  user: 'root',
  password: '',
  database: 'someExistingDb'
});`
