### ISSUE TITLE
LOAD LOCAL DATA INFILE works, but doesn't call callback

### ISSUE THREAD

**Issue by issacg** [mysqljs/mysql#593]
I've encountered a problem lately with LOAD LOCAL DATA INFILE

The functionality works, and rows are added fine to MySQL, but the callback never gets called, and the code hangs.  This doesn't seem to always reproduce, but rather "comes and goes", mostly based on the dataset.

A wireshark trace shows that MySQL responds with an OK packet after the LOAD command, but for some reason I'm not getting the callback from mysql.query

This is happening with a connectionPool of 5-7 active connections.

I'm not quite sure what the call path for that should look like (and really don't have @work's grace to spend enough time diving deeply into the module from scratch), so reaching out for help - I'd be happy to help troubleshoot further, as long as my time permits, but wondering where a good place to start would be.

Thanks!

**Comment by chacent** [comment]
> I've encountered a problem lately with LOAD LOCAL DATA INFILE
> 
> The functionality works, and rows are added fine to MySQL, but the callback never gets called, and the code hangs. This doesn't seem to always reproduce, but rather "comes and goes", mostly based on the dataset.
> 
> A wireshark trace shows that MySQL responds with an OK packet after the LOAD command, but for some reason I'm not getting the callback from mysql.query
> 
> This is happening with a connectionPool of 5-7 active connections.
> 
> I'm not quite sure what the call path for that should look like (and really don't have @work's grace to spend enough time diving deeply into the module from scratch), so reaching out for help - I'd be happy to help troubleshoot further, as long as my time permits, but wondering where a good place to start would be.
> 
> Thanks!

me too,i'll track this problem.but it's hardly to reproduce
