### ISSUE TITLE
Using connection.escape adds single quotes around my value?

### ISSUE THREAD

**Issue by Broham** [mysqljs/mysql#594]
If I do the following:

```
console.log(value);
```

I get the expected output of:  `tmp/myValue`

But the following code:

```
console.log(connection.escape(value));
```

It outputs `'tmp/myValue'`. Notice the single quotes that are now around the value.

Is there a reason for this or is it a bug?

**Comment by tarwin** [comment]
This is great, although it does cause problems when trying to do things like:

```
console.log(`SELECT * FROM book where name LIKE '%${connection.escape(searchName)}%'`)
// SELECT * FROM book where name LIKE '%'SEARCH_NAME'%'

// You get those extra quotes inside the LIKE ...
```

**Comment by kai-koch** [comment]
@tarwin See https://github.com/mysqljs/mysql/issues/1386 about escaping Values for LIKE.
The example should be in the Docs. There will be someone taking care of that soon(tm), I guess.

**Comment by tarwin** [comment]
@kai-koch I realized I could simply do:

```
let searchName = 'SEARCH_NAME'
let searchLike = `%${searchName}%`
console.log(`SELECT * FROM book where name LIKE ${connection.escape(searchLike)}`)
// SELECT * FROM book where name LIKE '%SEARCH_NAME%'
```
