### ISSUE TITLE
connect takes at least 5 seconds

### ISSUE THREAD

**Issue by bhasis** [mysqljs/mysql#617]
i've got mysql@2.0.0-alpha9 and node v0.10.18
and i make a connection like this:

var mysql = require('mysql');
var start = Date.now();
var connection = mysql.createConnection({
    host     : 'ip',
    user     : 'root',
    password : 'root'
});

connection.connect(function(err) {
    console.log((Date.now() - start));

});

it will takes nearly every time 5s (+/- 10ms). 
Its no problem of network/mysql because with other mysql extension the connection will be established immediately.
Also on every pool.getConnection(), if they have to be established a new connection , it will take 5s (+/- 10ms).

**Comment by anurat** [comment]
hi @bhasis  
I also have the same problem. Could you share how you solve the DNS problem you have?
