### ISSUE TITLE
MySql Error when connecting to a remote host

### ISSUE THREAD

**Issue by rutaihwa** [mysqljs/mysql#648]
error when connecting to db { [Error: MySQL server is requesting the old and insecure pre-4.1 auth mechanism.Upgrade the user password or use the {insecureAuth: true} option.] code: 'HANDSHAKE_INSECURE_AUTH', fatal: true }

The host has old_password configured, I am not sure how to deal with this error...

**Comment by tiagosiebler** [comment]
@sidorares isn't `insecureAuth` just a workaround? Any info on what needs to be done on the DB side to handle this properly?
