### ISSUE TITLE
express node js mysql connection issue

### ISSUE THREAD

**Issue by nikhiltuteja** [mysqljs/mysql#653]
I am just beginner on express. I have found issue when connecting with mysql.
my directory structure:-
 app.js
 controller
     ---------index.js
     --------- foo 
             ------index.js
  node_modules
  package.json
  public
  ------images
  ------stylesheet
  ------javascripts
  routes
  -----index.js
  views

app.js 

var express = require('express')
, http = require('http')
, path = require('path');
var app = express();
app.use("/foo", require("./controller/foo"));
//var controller =  require('./controller')({app: app});
// all environments
app.configure(function() {

```
    app.set('port', process.env.PORT || 8888);
    app.use(express.json());
    app.use(express.urlencoded());
    app.use(express.methodOverride());
    app.use(app.router);
    app.use(express.static(path.join(__dirname, 'public')));
    app.set('view engine', 'jade');
    app.set('views', __dirname + '/views');
    app.use(app.router);
    app.get('/', function( req, res) {
    res.render('index');
```

});

});
http.createServer(app).listen(app.get('port'), function(){
console.log('Express server listening on port ' + app.get('port'));
});
~

config.js

module.exports = {
  db: {
    user:     'root',
    password: 'hack007',
    host:     'localhost',
  },
};

controller/foo/index.js
var express = require("express"),
    mysql   = require("mysql"),
    config  = require("../../config.js")
    db      = connection.connect();
var app = module.exports = express();

app.get("/:id", function(res, req) {
  var id = req.param("id");
  // fetch
});

**Comment by Jamison-skip** [comment]
> Closing due to lack of response. Please feel free to re-open if you still need help.





https://netbeans-81.github.io/D1BkWwgXYGCbbsvJQAtXi4MzeC6SFcAiSp7Y2x7tBbodiw/
