### ISSUE TITLE
Possible memory leak in pooled connections

### ISSUE THREAD

**Issue by shaishf** [mysqljs/mysql#697]
Hi,

I'm experiencing a (slow) memory leak when working with a pooled connection.

my code is as follows (simplified for this example):

at the beginning i'm creating the pool:

```
this.db_config =  {host: app.settings.DB_HOST,
    user: app.settings.DB_USERNAME,
    password: app.settings.DB_PASSWORD,
    database: app.settings.DB_SCHEMA,
    connectionLimit: 10,
    supportBigNumbers: false};


this.pool = mysql.createPool(this.db_config);
```

and then inside requests:

```
 this.pool.getConnection(function (err, connection) {

    // Use the connection
    connection.query("select 1", parameters, function (err, rows) {
        connection.release();
        res.json(200,{});
        return;
    });
});
```

when using apache-bench,and "top", i can see the memory footprint of the app slowly getting bigger (and if i remove the query code, it doesn't).

i've made sure no other parts of the application are leaking memory.

Thanks!!!

**Comment by vujovicigor** [comment]
Same here, only in my case nodejs memory footprint is ok,
but mysqld memory is increasing until server stops.
If I change connection.release() to connection.destroy() mysqld memory is ok 
(but that defeats pool connections purpose)

**Comment by tangnan526** [comment]
I have the same problem with the latest version ,too. Is there any solution to solve this problem?

**Comment by Fuck-You-GFW** [comment]
I have the same issue with the latest version, too. I have to restart application regularly to "resolve" it.

**Comment by guruprasad211** [comment]
i am facing the sam problem did any one solve this issue

**Comment by philpoore** [comment]
facing the same using pooled mysql connections.

**Comment by dougwilson** [comment]
Nothing can be done if there is no provided reproduction case. Please open a new issue with all information for us to reproduce and diagnose the issue.

**Comment by kai-koch** [comment]
One additional note:
If your mysqld memory is growing, likely your mysql-server is to slow. (Especially with the DEFAULT configuration.)
Give it more RAM, if the indexes of your tables won't fit into the allocated memory for mysqld. (Else you have lot of disc-I/O for JOIN-operations.)

If you have many INSERTs/UPDATEs to handle, think of rewriting your queries/logic to use transactions and bulk INSERT/UPDATE queries. That would minimize the Disk-Operations needed to write the data and take of the back-pressure the DB needs to handle.
