### ISSUE TITLE
Increasing number of connections to mysql

### ISSUE THREAD

**Issue by nareshbhatia** [mysqljs/mysql#712]
I am trying to performance tune a small sample app. I started with 100 connections and hitting the node server as fast as possible. I got a throughput of ~1200 request/second. Now I tried to increase the number of db connections to 400 (by setting the connectionLimit). However, when I do this and start hitting the server hard, I get the following error:

```
ER_CON_COUNT_ERROR: Too many connections
```

How can I increase the number of connections? I don't think this is an issue on the MySQL end because I am easily able to run the same test using a Java server on the same MySQL instance.

Here's my node.js code:

```
var Mysql = require('mysql');

var pool = Mysql.createPool({
    host: 'localhost',
    user: 'bfoms_javaee',
    password: 'bfoms_javaee',
    database: 'bfoms_javaee',
    connectionLimit: 400
});

exports.findAll = function(req, res) {

    pool.getConnection(function(err, connection) {
        if (err) throw err;

        connection.query('SELECT * FROM orders WHERE symbol="GOOG"', function(err, rows, fields) {
            if (err) throw err;

            res.send(rows);
        });

        connection.release();
    });
};
```

**Comment by mhbernheim** [comment]
question... so I also stumbled by this using connection.release(); in the wrong place... thanks for that, but for learning purposes... why is it in the wrong place?

**Comment by nawlbergs** [comment]
@mhbernheim 

connection.query is asynchronous call... meaning the code below it will most likely run before its done.
I put letters next to how it was executing incorrectly.
```
A - pool.getConnection(function(err, connection) {
    B - connection.query('SELECT * ...    //  <--- this is async and might take a long
        D - res.send(rows); //  <-- code run after query response.
    });
    C - connection.release(); // <-- this code does not wait for sql response... and was releasing connection before connection was done..
});
```

**Comment by mitulparmar21696** [comment]
var q = connection.query(strQuery, queryParams, function (error, results, fields) {
                
                connection.release();
                if (error) {
                    console.log(q.sql);
                    console.log(error);
                    console.log(results);
                    console.log(strQuery);
                }
                callback(req, res, error, results, fields);
            });

I put connection.release(); like this still getting error of too many connection. 
Is there any other way?

**Comment by antontsvil** [comment]
@mitulparmar21696 try checking the max_connections variable in your mysql server.

``
show variables like "max_connections";
``

This variable will determine the max amount of connections your mysql server will allow at one time. You can modify it like so 

``
set global max_connections = 200;
``
I referenced [this link](https://www.morpheusdata.com/blog/2014-12-11-too-many-connections-how-to-increase-the-mysql-connection-count-to-avoid-this-problem) for this info
