### ISSUE TITLE
replace createCredentials + createSecurePair with tls.connect

### ISSUE THREAD

**Issue by sidorares** [mysqljs/mysql#737]
See https://github.com/felixge/node-mysql/commit/4b59612666b04483d4eec0b26fbf99b6be0e094f#commitcomment-5445205

createSecurePair is [deprecated](http://nodejs.org/dist/v0.11.6/docs/api/tls.html#tls_tls_createsecurepair_credentials_isserver_requestcert_rejectunauthorized) in v0.11.x. and should be replaced with `tls.connect`

**Comment by dougwilson** [comment]
Replaced with `tls.createSecureContext`
