### ISSUE TITLE
.query(...).stream().pipe(process.stdout) throws TypeError: invalid data

### ISSUE THREAD

**Issue by JHKennedy4** [mysqljs/mysql#741]
I'm using the following code to test out the functionality of .stream().pipe() and I'm getting an error when I pass fairly typical stream outputs I've seem used elsewhere to .pipe(). I'm wondering if I'm totally off base or if this functionality is no longer supported.

```
pool.getConnection(function (err, connection) {
    connection.query('SELECT * FROM wp_users WHERE ID = ?', [req.params.id])
    .stream({highWaterMark: 5})
    .pipe(process.stdout);
});
```

I get "TypeError: first argument must be a string or Buffer" when I call .pipe(res).

**Comment by waylonflinn** [comment]
You can also use the [`csv-stringify`](https://www.npmjs.com/package/csv-stringify) module.

at the command line in the root of your project, run:

`npm install csv-stringify`

then, in your file:

```node
var stringify = require('csv-stringify');

var stringifier = stringify();

pool.getConnection(function (err, connection) {
    connection.query('SELECT * FROM wp_users WHERE ID = ?', [req.params.id])
    .stream({highWaterMark: 5})
    .pipe(stringifier).pipe(process.stdout);
});
```

notice the extra `.pipe(stringifier)` before the `.pipe(process.stdout)`

**Comment by gentunian** [comment]
Excellent examples and documentation. I've tried this for piping to stdout and works ok. The only issue I'm having is that I wan't to pipe large datasets. For some reason, `highWaterMark` option will only pipe the specified amount of objects, as the nodejs documentations states:

From [buffering](https://nodejs.org/api/stream.html#stream_buffering)

> For streams operating in object mode, the highWaterMark specifies a total number of objects.

From [stream options](https://nodejs.org/api/stream.html#stream_constructor_new_stream_writable_options)
> highWaterMark <number> Buffer level when stream.write() starts returning false. Defaults to 16384 (16kb), or 16 for objectMode streams.

Saying that and without knowing how many rows should I return (most than 1.000), how could I pipe this into another process?

**Comment by germansokolov13** [comment]
@sidorares I think you should write this fact in here:
https://github.com/mysqljs/mysql#piping-results-with-streams
In this paragraph it doesn't say what becomes `data` in the data event of streams, a row, a collection of rows, a byte or what. It becomes clear only with your comment in here.
