### ISSUE TITLE
What does serverStatus mean?

### ISSUE THREAD

**Issue by euglv** [mysqljs/mysql#745]
Hello, i am executing the following code:

```
    var sql = 'DELETE FROM ....';

    pool.query(sql, params, function(err, rows){
        if (err)
            throw err;

        res.write(JSON.stringify(rows));
        res.end();
    });
```

And I get the following result:
{"fieldCount":0,"affectedRows":0,"insertId":0,"serverStatus":2,"warningStatus":0}
I can't find documentation about what field serverStatus and warningStatus mean.

**Comment by HarryPehkonen** [comment]
I see "warningStatus:"

https://github.com/sidorares/node-mysql2/blob/272009923bdb18708eec172c42e1290fadbbfbca/lib/packets/resultset_header.js#L14

```
[...]
this.warningStatus = packet.readInt16();
[...]
```

After execute()ing, here is what I received:

```
{"fieldCount":0,"affectedRows":1,"insertId":0,"serverStatus":2,"warningStatus":0}
```

@dougwilson I concur that I see "warnings" and the description "number of warnings" at https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html, but I don't know if I'm looking at the correct documentation.

I see two tests with warningStatus:

https://github.com/sidorares/node-mysql2/blob/272009923bdb18708eec172c42e1290fadbbfbca/test/integration/connection/test-binary-multiple-results.js#L16

https://github.com/sidorares/node-mysql2/blob/272009923bdb18708eec172c42e1290fadbbfbca/test/integration/connection/test-multiple-results.js#L16

These files refer to warningCount (good):

https://github.com/sidorares/node-mysql2/blob/272009923bdb18708eec172c42e1290fadbbfbca/lib/packets/prepared_statement_header.js#L10

https://github.com/sidorares/node-mysql2/blob/272009923bdb18708eec172c42e1290fadbbfbca/lib/packets/index.js#L29

While I'm here:  Thanks very much for this library!

**Comment by dougwilson** [comment]
@HarryPehkonen, every link you posted there was to a different module, not this module. Are you sure you are posting to the correct repository? Also, please try to open new issue, rather than posting back on over 2 year old issues :) Things change over the years that can make older posts irrelevant.

**Comment by HarryPehkonen** [comment]
My apologies.  I have a slight fever today.  I'll blame it on that.
