### ISSUE TITLE
Close Stream

### ISSUE THREAD

**Issue by momohuri** [mysqljs/mysql#768]
Hey,
I am streaming the result of a huge select.
But Sometime I want to close the stream before the end. Is there any way of doing that? Thanks

**Comment by akirattii** [comment]
Why not use `conn.emit("end")`:

```js
conn.query("SELECT * FROM hugetable")
  .on("result", result => {
    ...
    if (needCloseConnectionOnTheWay) {
      // Close this connection!
      return conn.emit("end");
    }
  })
```

**Comment by dougwilson** [comment]
Closing, as implementation of this requires a higher-level extraction, with multiple connections to MySQL server, which is outside the scope of this module.
