### ISSUE TITLE
Bulk inserting array of objects

### ISSUE THREAD

**Issue by alexcroox** [mysqljs/mysql#814]
In the example it shows you can do

``` js
var post  = {id: 1, title: 'Hello MySQL'};
var query = connection.query('INSERT INTO posts SET ?', post, function(err, result) {
  // Neat!
});
```

I am trying to add an array of objects, is this possible?

``` js
var currentLogs = [ { socket_id: 'Server',
    message: 'Socketio online',
    data: 'Port 3333',
    logged: '2014-05-14 14:41:11' },
  { socket_id: 'Server',
    message: 'Waiting for Pi to connect...',
    data: 'Port: 8082',
    logged: '2014-05-14 14:41:11' }];

connection.query('INSERT INTO logs_debug SET ?', currentLogs, function(err, rows) {
    connection.release();
```

Only inserts the first object

**Comment by Vinyl3** [comment]
var mysql = require('mysql');
 
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'mydb',
    debug: false,
});
 
connection.connect();
 
console.log("Connected to Mysql");
 
var records = [
                [1, 'Vinyl', 'Singh'],
                [2, 'Piyush', 'Sinha'],
                [3, 'Sunny', 'Singh']
];
 
var sql = "INSERT INTO employee (employee_id, first_name, last_name) VALUES ?";
 
var query = connection.query(sql, [records], function(err, result) {
    console.log(result);
});
 
connection.end();

**Comment by elvinaze** [comment]
I wish you pasted console.log(result); here as well, so we could see what type of result comes back

**Comment by enjunear** [comment]
@elvinaze 
I did this with some of my data, and this is the output of console.log(result) on a small bulk insert:
```js
OkPacket {
  fieldCount: 0,
  affectedRows: 2,
  insertId: 14,
  serverStatus: 2,
  warningCount: 0,
  message: '&Records: 2  Duplicates: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0 }
```

**Comment by lakshaygaur** [comment]
Why does it only return single **insertId** ?

**Comment by kai-koch** [comment]
MySQL reports only the last of the inserted IDs from an  AUTO_INCREMENT column.
See https://dev.mysql.com/doc/refman/5.7/en/getting-unique-id.html

**Comment by lakshaygaur** [comment]
@kai-koch you're right , thanks for sharing the link.

**Comment by Mouradif** [comment]
@lakshaygaur If you want all insert Ids you'd have to run separate queries

**Comment by DaltonHarvey** [comment]
@alexcroox you can use the arry map prototype

`currentLogs = [ { socket_id: 'Server',
    message: 'Socketio online',
    data: 'Port 3333',
    logged: '2014-05-14 14:41:11' },
  { socket_id: 'Server',
    message: 'Waiting for Pi to connect...',
    data: 'Port: 8082',
    logged: '2014-05-14 14:41:11' }];`

You can do something like this:

`connection.query('INSERT INTO logs_debug SET ?'[currentLogs.map(logs.socket_id,logs.message,logs.data,logs.logged)], function(err, rows) {
    connection.release();`

**Comment by M0nzer** [comment]
@DaltonHarvey 
```
currentLogs = [
 { socket_id: 'Server', message: 'Socketio online', data: 'Port  3333', logged: '2014-05-14 14:41:11' },
 { socket_id: 'Server', message: 'Waiting for Pi to connect...', data: 'Port: 8082', logged: '2014-05-14 14:41:11' }
];

console.warn(currentLogs.map(logs=>[ logs.socket_id , logs.message , logs.data , logs.logged ]));
```

***

**Comment by saltsucker** [comment]
I know it's not bulk inserting, as in, using mysql's bulk ability, exactly, but in case anyone comes across this while searching "how to insert an array of objects into mysql using nodejs", you can do basically do it using `Promise.all`
**Data:**
`    "flow": [
        {
            "flowStep": "Board Assembly"
        },
        {
            "flowStep": "Power"
        },
        {
            "flowStep": "Boundary Scan"
        }
    ],`

**Code:**
```javascript
// in route.js under '/create' api call
db = new Database()
Promise.all(flow.map((step) => {
    db.insert(db.flow, step).then((result) => {
    console.log('flowstep insert result', result);
  });
}));
```

```javascript
// in my custom Database class
  insert(table, data) {
    const sql = 'insert into ?? set ?';
    return this.query(sql, [table, data]);
  }

  query(sql, data) {
    return new Promise((resolve, reject) => {
      this.pool.query(sql, data, (error, result, fields) => {
        if (error) {
          console.log('query with data failed');
          console.log(error);
          return reject(error);
        } else {
          console.log('query with data success');
          console.log(result);
          resolve(result);
        }
      });
    });
  }
```
