### ISSUE TITLE
pool keep-alive

### ISSUE THREAD

**Issue by gjohnson** [mysqljs/mysql#835]
While https://github.com/felixge/node-mysql/commit/5ea649d6d94f1dde7e28dff73d04ec188582a86d addresses the issue of getting a connection that has timed out from being idle too long. Why not also have some type of keep-alive behavior to prevent them from becoming idle too long in the first place? Something to the effect of:

``` js
Pool.prototype._startKeepAlive = function(){
  var pool = this;
  this._keepalive = setInterval(function(){
    pool._freeConnections.forEach(function(connection){
      connection.ping(function(err){
        if (err) {
          connection.destroy();
          pool._removeConnection(connection);
        }
      });
    });
  }, this.config.keepalive);
};
```

**Comment by stian-sandvold** [comment]
What is the status on this? :)

**Comment by E88** [comment]
I think it it not necessary to do keep alive.
As long the wait_timeout from the DB server is not reached, my connections keep alive.
After the wait_timeout the DB server disconnects this connection.
Then the client closes this connection [on 'end'](https://github.com/mysqljs/mysql/blob/master/lib/PoolConnection.js#L20).
If you need longer inactive connections, set "wait_timeout" on the server.
