### ISSUE TITLE
transaction not committed after error occurs (specifically, DEADLOCK)

### ISSUE THREAD

**Issue by sa-0001** [mysqljs/mysql#853]
The issue I am having is fairly simple to explain:
1. start transaction on connection from pool
2. run a number of queries using this connection
3. somewhere in the middle, an error occurs ( DEADLOCK)
4. the failed query is retried after a short timeout, and now succeeds
5. run a number of additional queries using this connection
6. commit transaction
After this happens, I select the newly created row(s) and they do not exist.

I would appreciate if someone could help pinpoint what the problem is.  Does a transaction automatically rollback if _any_ error occurs?  Does the setTimeout() somehow cause an issue?

I can confirm that none of the queries done in this transaction cause an implicit commit (only SEL/UPD/INS/DEL).  I also have no evidence that the transaction fails when there is no error, or when there was an error other than DEADLOCK.

Looking through the source of this module, it doesn't seem like rollback() and commit() are used anywhere, rather that they must always be explicitly called by me.  So, maybe the error or the timeout mean that the queries from #4 and #5 above are actually running on a _different_ connection from the one with the open transaction?

Edit: I have always understood that rollbacks are explicit even when an error occurs - am I wrong about this or are there some settings in node-mysql I have forgotten to set?

**Comment by SHaluArya** [comment]
the same in oracle...with code please
