### ISSUE TITLE
getConnection()'s callback never called when I got disconnect from the NET (using pools)

### ISSUE THREAD

**Issue by paulintrognon** [mysqljs/mysql#854]
Hi,
I am running locally a very simple script that creates a node webserver, connects to MySQL using pools, runs a simple query and returns the result to the client. It's working well, but if I unplug my Internet cable to manually to stop the connection to the remote MySQL server, no error is thrown the first time... The callback in `pool.getConnection(function(err, connection) {});` is never called. But if I run the query again, I get a `ENETUNREACH` error, as expected.

So what I don't understand is why is the expected error `ENETUNREACH` is not thrown the first time I run the query after I disconnect the cable? The result of this issue is that after a disconnect, the server never returns a response (not even a 500 error) and the client has to wait 30 seconds before a timeout, which is really not good...

I don't know what I'm doing wrong, i'm using [the sample code displayed here](https://github.com/felixge/node-mysql#pooling-connections) without any changes...

PS: using the debug mode, the "ComPingPacket" is never answered...

PPS: thank you very much for this library, apart from this issue (which I believe the problem is on my side) , i'm very appreciating the effort made here =)

**Comment by qx** [comment]
What's your problem ? @paulintrognon ,the same +1
