### ISSUE TITLE
Keep getting timeout after a few minutes of idle on google cloud sql

### ISSUE THREAD

**Issue by badoet** [mysqljs/mysql#878]
is there any compatiblity issue of this driver with the google cloud sql ?
https://developers.google.com/cloud-sql/
it seems that we keep getting time out after a few minutes of idle time.
do anyone in the community face the same issue?

thx

**Comment by lokeshwebmobi** [comment]
Hi dougwilson

I'm getting the following error when i tried to connect after some 15minutes

{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"read","fatal":true}

**Comment by dougwilson** [comment]
Hi @lokeshwebmobi , can you post the stack trace for that error as well? The error itself is saying "Node.js tried to read from a TCP socket that was previously established, but timed out attempting to do so".

**Comment by tzmartin** [comment]
Just following up for posterity..

Referring to Cloud SQL docs: [https://cloud.google.com/sql/docs/compute-engine-access](https://cloud.google.com/sql/docs/compute-engine-access)

> To keep long-lived unused connections alive, you can set the TCP keepalive. The following commands set the TCP keepalive value to one minute and make the configuration permanent across instance reboots.

    # Display the current tcp_keepalive_time value.
    $ cat /proc/sys/net/ipv4/tcp_keepalive_time
    
    # Set tcp_keepalive_time to 60 seconds and make it permanent across reboots.
    $ echo 'net.ipv4.tcp_keepalive_time = 60' | sudo tee -a /etc/sysctl.conf
    
    # Apply the change.
    $ sudo /sbin/sysctl --load=/etc/sysctl.conf
    
    # Display the tcp_keepalive_time value to verify the change was applied.
    $ cat /proc/sys/net/ipv4/tcp_keepalive_time

**Comment by q42jaap** [comment]
@tzmartin setting the keepalive values is not enough, node-mysql should enable keepalive on the socket it uses:
https://nodejs.org/api/net.html#net_socket_setkeepalive_enable_initialdelay

You can see whether the keepalive is active with `netstat -o`, it will tell you in the last column called `Timer`.
