### ISSUE TITLE
too many connections - not pooling?

### ISSUE THREAD

**Issue by gotmikhail** [mysqljs/mysql#889]
I've read through multiple issues / threads, but can't seem to find a solution.

I regularly get a the error, `ER_CON_COUNT_ERROR: Too many connections`, but from my understanding pooling should take care of that by queuing, correct?

The max connection on the server is low, only 32, but again, queuing ... ?

Note that I'm relying on default values. (10 connections, unlimited queue, etc)

Here's my code:

``` javascript
var dbPool = mysql.createPool({
    "host": appConfig.db.ip,
    "user": appConfig.db.user,
    "password": appConfig.db.pw,
    "database": appConfig.db.database,
    "dateStrings": true,
    "multipleStatements": true
});
```

``` javascript
exports.dbQuery = function (queryString, callback, nested, preserveObject) {
    if (nested !== false) {
        nested = true;
    }
    dbPool.getConnection(function (err, connection) {
        var queryOptions = {
            "sql": queryString,
            "nestTables": nested
        };
        connection.query(queryOptions, function (err, results) {
            // Recycle db connection
            connection.release();
            if (err) {
                console.log(err);
                // Report error to callback()
                if (typeof(callback) === 'function') {
                    callback(true);
                }
            }
            if (typeof(callback) === 'function') {
                callback(false, camelize(snakeize(results)), preserveObject);
            }
        });
    });
};
```

**Comment by RameshRM** [comment]
@dougwilson I am experiencing `too many connections` with default of `10` in a connection pool, but my load is very small, my code looks like this

> ```pool.query(query, options, callback)```

As you can see , I don't manage connections letting the `pool` take care of acquiring & releasing. Trying to figure out how to solve this, let me know if any pointers.

**Comment by ericuldall** [comment]
We're experiencing this issue too. One thing unique about our setup is we have 2 different connection pools created for the same mysql host...Is there any known issues with that type of setup?

**Comment by germansokolov13** [comment]
I also use just `pool.query` and I get this error over time after several dozens requests to server even with the `connectionLimit` set to `1`

**Comment by germansokolov13** [comment]
My bad. It seems my pool itself is initialized many  times. Chances are @RameshRM could experience the same thing. I was using `express-di` and was not aware that its factories would execute on each request.

**Comment by dougwilson** [comment]
Instead of
```js
app.use(function(req, res, next){
    res.locals.connectionPool = connectionPool
    next();
});
```

Just use `app.locals` (http://expressjs.com/en/4x/api.html#app.locals):
```js
app.locals.connectionPool = mysql.createPool({
    connectionLimit : 10,
    host : 'localhost',
    user : 'user',
    password : 'password',
    database : 'database'
});
```

**Comment by Rootmars** [comment]
Still new at using nodejs. Thanks for the advice!

**Comment by skemb321** [comment]
I have to share the same experience when initializing the pool. 
I had the same "Too many connections" error because I initialized the pool on every route. (SMH).

Cheer to everyone who also solved by via `app.locals` ! :clinking_glasses:

**Comment by kai-koch** [comment]
Problem seems to be resolved with using ```app.locals```.
Re-open, if needed.
