### ISSUE TITLE
I have a "Connection lost: The server closed the connection." error, please help!

### ISSUE THREAD

**Issue by DmitriySheludko** [mysqljs/mysql#897]
Hello!

I have an application that use ActionHeroJS + ah-sequelize-plugin + Sequelize ORM + node-mysql.

Sometimes, in realy random times, i see this error:

```
{"level":"error","message":"! uncaught error from task: Cannot read property 'class' of null on queue default","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"! Error: Connection lost: The server closed the connection.","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"!     at Protocol.end (/var/soft/kidguard-api/node_modules/mysql/lib/protocol/Protocol.js:103:13)","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"!     at Socket.<anonymous> (/var/soft/kidguard-api/node_modules/mysql/lib/Connection.js:88:28)","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"!     at Socket.emit (events.js:117:20)","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"!     at _stream_readable.js:929:16","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"!     at process._tickDomainCallback (node.js:463:13)","timestamp":"2014-08-28T00:29:28.572Z"}
{"level":"error","message":"*","timestamp":"2014-08-28T00:29:28.572Z"}
```

And after this error my system stops sending requests to mysql at all. If i request any method that uses mysql - request freezes.

Please help to fix this!

**Comment by VishalWaman** [comment]
{"date":"Sun Feb 11 2018 05:44:20 GMT+0000 (UTC)","process":{"pid":12367,"uid":500,"gid":500,
"cwd":"/home/ec2-user/iagonApi","execPath":"/home/ec2-user/.nvm/versions/node/v6.11.5/bin/node",
"version":"v6.11.5","argv":["/home/ec2-user/.nvm/versions/node/v6.11.5/bin/node",
"/home/ec2-user/.nvm/versions/node/v6.11.5/lib/node_modules/pm2/lib/ProcessContainerFork.js"],
"memoryUsage":{"rss":58814464,"heapTotal":29392896,"heapUsed":25094520,"external":436435}},"os"
:{"loadavg":[0,0,0],"uptime":4301814},"trace":[{"column":13,"file":"/home/ec2-user/iagonApi/node_modules/mysql/lib/protocol/Protocol.js",
"function":"Protocol.end","line":113,"method":"end","native":false},{"column":28,"file":"/home/ec2-user/iagonApi/node_modules/mysql/lib/Connection.js",
"function":null,"line":109,"method":null,"native":false},{"column":20,"file":"events.js","function":"emitNone","line":91,"method":null,"native":false},
{"column":7,"file":"events.js","function":"Socket.emit","line":185,"method":"emit","native":false},{"column":12,"file":"_stream_readable.js",
"function":"endReadableNT","line":974,"method":null,"native":false},{"column":11,"file":"internal/process/next_tick.js",
"function":"_combinedTickCallback","line":80,"method":null,"native":false},{"column":9,"file":"internal/process/next_tick.js
function":"process._tickDomainCallback","line":128,"method":"_tickDomainCallback","native":false}],
"stack":["Error: Connection lost: The server closed the connection.","   
 at Protocol.end (/home/ec2-user/iagonApi/node_modules/mysql/lib/protocol/Protocol.js:113:13)"," 
 at Socket.<anonymous> (/home/ec2-user/iagonApi/node_modules/mysql/lib/Connection.js:109:28)","  
 at emitNone (events.js:91:20)","    at Socket.emit (events.js:185:7)","    at endReadableNT (_stream_readable.js:974:12)","  
 at _combinedTickCallback (internal/process/next_tick.js:80:11)","    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"],
 "level":"error","message":"uncaughtException: Connection lost: The server closed the connection.","timestamp":"2018-02-11T05:44:20.336Z"}
 

`Connection lost: The server closed the connection.`

Can you please help?
