### ISSUE TITLE
Insert 1,000,000 rows into a table, got "out of memory" error

### ISSUE THREAD

**Issue by hellomaya** [mysqljs/mysql#899]
I have tried to insert 1,000,000 rows into a table, and I got this error : 

```
*FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Aborted*
```

And I also tried the same thing in PHP, it worked. Do you think this is an issue?
Here is the test code, https://github.com/hellomaya/db-performance

**Comment by Watchvirulent** [comment]
i met the same problem and created a strategy to resolve it https://skyler-passenger.github.io/ade/
