### ISSUE TITLE
How much overhead is there in node-mysql?

### ISSUE THREAD

**Issue by Redsandro** [mysqljs/mysql#919]
Some huge query in **phpMyAdmin** reports for example:

```
Showing rows 0 - 29 (154 total, Query took 0.1439 sec)
```

In `node-mysql` from query to callback takes about 1.5 seconds for this query.

The actual query-time is approximately 10-fold. For less results it's less overhead, for more results the overhead is more.

Where does this come from? These timings are pretty much the same in `mysql2`. Is there something I can do?

**Comment by sidorares** [comment]
@Redsandro this issue is 2.5 years old and probably lots changed since, I'm closing it

**Comment by Redsandro** [comment]
@sidorares :+1: 

I admid I forgot about this issue. Apologies. A lot has changed since.
