### ISSUE TITLE
Using node-mysql with promises

### ISSUE THREAD

**Issue by chrisveness** [mysqljs/mysql#929]
Can node-mysql be used with promises, or only with callbacks? If it can't, can you suggest how best to use it within a promises structure? (I'm a bit lost with promisify, bluebird, Q, ...)

**Comment by gajus** [comment]
What advantage do generators have over promises in this scenario?

**Comment by chrisveness** [comment]
Using Koa at least, it seems that programs can be written almost as traditional synchronous code, just prefixing would-be blocking calls with 'yield', making for far more readable (hence supportable) code. I find promises avoid 'callback-hell', but still break up code flow in unnatural ways. I believe error handling is also simpler and more robust with Koa. There's a decent illustration here: www.strongloop.com/strongblog/node-js-express-introduction-koa-js-zone.

**Comment by dougwilson** [comment]
The whole Koa/yield thing is a hack because JavaScript doesn't support stuff. ES7 will give us `async` and `await` keywords, which will make promises look exactly like Koa and Koa plans to use promises as soon as this happens.

**Comment by chrisveness** [comment]
ES6 will give us generators/yield. ES6 is available in Node v0.11, and will be available for production use if Node v0.12 ever arrives. Koa uses generators ("through leveraging generators Koa allows you to ditch callbacks"). No need to wait for ES7.

**Comment by dougwilson** [comment]
I'm just explaining why Koa uses generators; besides, even the Koa generators (powered by `co`) actually use promises, so you can `yield function_returning_a_promise()` just fine.

**Comment by gajus** [comment]
Have a go at http://gajus.com/blog/2/the-definitive-guide-to-the-javascript-generators to understand better the generators. Generators are not a good candidate for MySQL abstraction.

**Comment by dougwilson** [comment]
Correct. generators have nothing to do with async programming: they just generate a list of values. The `co` library hacks generators such that it provides a trampoline. The section about Lisp in https://en.wikipedia.org/wiki/Trampoline_%28computing%29 literally describes what `co` does and when you put on the other side of `yield` is a thunk-returning function (`co` also accepts promises, not only thunks, though, but a promise is sort of line a fancy thunk).

If you look at the source for `mysql-co`, you'll see it returns thunks.

**Comment by chrisveness** [comment]
@gajus - that *definitive guide* is really clear and helpful, and the references at the end make good reading also. But why are generators (as used by Koa) not a good candidate for MySQL abstraction?

**Comment by petkaantonov** [comment]
> https://www.npmjs.org/package/promise-mysql ( bluebird )

FWIW that wrapper uses much more inefficient wrapping than simply using bluebird's promisifyAll - using  that properly will give same performance as equal callback code.

**Comment by dougwilson** [comment]
> I don't even understand why people make these modules - the bluebird docs provide an example how to promisify the mysql module with literally 2 lines 

Exactly :) This is one of the reasons I haven't pushed very hard to convert callback-style modules into promises at all, since it's so easy to just wrap them.

**Comment by gajus** [comment]
> Promise-mysql is a wrapper for node-mysql that wraps function calls with Bluebird promises. Usually this would be done with Bluebird's .promisifyAll() method, but node-mysql's footprint is different to that of what Bluebird expects.

https://www.npmjs.com/package/promise-mysql

**Comment by petkaantonov** [comment]
@gajus the api docs show an example how to promisify it:

```js
Promise.promisifyAll(require("mysql/lib/Connection").prototype);
Promise.promisifyAll(require("mysql/lib/Pool").prototype);
```

Typically modules can be promisified with `Promise.promisifyAll(require("module"))` because they expose classes as properties of the main export, but the above isn't too bad either.

**Comment by gajus** [comment]
Thats true, though `promise-mysql` also does other things, viz., handle disconnections (https://github.com/lukeb-uk/node-promise-mysql/blob/master/lib/connection.js#L8-L35). I am not arguing about the greatness of the specific implementation. I would simply like to see `mysql` package having a better integration with Promise(s).

**Comment by dougwilson** [comment]
@gajus the files you referenced, where it tries to re-establish a dropped connection, is something you should _never_ use anyway; session state can become reset any any moment with that kind of code and you'll never know and queries like `SELECT LAST_INSERT_ID()` will return bizarre results.

**Comment by petkaantonov** [comment]
@dougwilson btw is exposing the classes as properties of the main export something you would consider for even easier promisification? basically in index.js you would just say `exports.Connection = Connection; exports.Pool = Pool;` etc

**Comment by gajus** [comment]
Thats a good example. But it is even worse if a promise that gave an active connection suddenly changes its state, because by convention promise state must not change after it has been set. Therefore, as a user I would prefer whatever magic behind the scenes to ensure that mysql connection is not lost.

My suggestion to the said issue, while it is a workaround, it would prevent session state reset, https://github.com/lukeb-uk/node-promise-mysql/issues/2.

**Comment by dougwilson** [comment]
> @dougwilson btw is exposing the classes as properties of the main export something you would consider for even easier promisification? basically in index.js you would just say exports.Connection = Connection; exports.Pool = Pool; etc

Sorry I took so long; I lost this issue in the large amount. I'm going to make this change for sure.

**Comment by bucaran** [comment]
Just in case someone is wondering how to build an example without `promisifyAll` (as I couldn't really make it work exactly like I wanted and you know people have to work also...)

This is a ES7-like example of how things would go:

```js

let mysql = require("mysql")

let database_query = function (options, query) {
 return new Promise(function(resolve, reject) {
  let {host, user, password, database} = options
  let conn = mysql.createConnection({
    host     : host,
    user     : user,
    password : password,
    database : database
  })
  conn.connect()
  conn.query(query, function(err, data) {
    return (err ? reject(err) : resolve(data));
  });
  conn.end()
 })
}

let options = {
  host     : process.ENV_HOST || "localhost",
  user     : process.ENV_USER || "root",
  // ...
}

async function () { 
  try {
    let rows = await database_query( options, queryString )
    rows.forEach((row) => row_view( row ))
  } catch (err) {
    handleError( err )
  }
}
``

**Comment by AdriVanHoudt** [comment]
@sidorares I'm interested in an update on the benchmarks, do they still hold valid? Also why is node-mysql2 so much faster?

**Comment by sidorares** [comment]
@AdriVanHoudt  mysql2 core is completely different, it compiles row parsers dynamically at runtime + other perf optimisations. I'll try to make new benchmarks against latest versions, but expect similar results

**Comment by AdriVanHoudt** [comment]
@sidorares cool thanks, are there use cases as to when to use mysql2 and when not to?

**Comment by sidorares** [comment]
mysql2
pros: 
   - faster ( especially on big resultsets )
   - prepared statements ( note that almost no ORMs support them, probably only one is knex.js so kurrently only useful if you use library directly )
   - IMO source code is simpler to read and change. mysql protocol parser partially trying to guess packets looking at packet content and partially state machine, while mysql2 commands present state machine explicitly ( result of command consuming packet is next state of command )
   - binlog protocol support
   - server part of the protocol

cons:
   - some new functionality might me missing or buggy ( PoolCluster, latest fixes to pool etc )
  
mysql
pros
 - stability. More users, more tests, @dougwilson 


So probably short answer is "use mysql2 if you really need to have a little bit of extra performance ( and have benchmarks to prove where is bottleneck) or hacking on mysql protocol and tools. In all other cases use mysql"

**Comment by AdriVanHoudt** [comment]
@sidorares thanks! I was looking for a clear statement like that for a while!

**Comment by chrisveness** [comment]
I've also found mysql2 works very well with Koa, using [mysql-co](https://github.com/sidorares/mysql-co) (following on the original theme of this issue); there's an example in my [Koa Sample App](https://github.com/chrisveness/koa-sample-web-app-api-mysql). Thanks @sidorares!

**Comment by sidorares** [comment]
@chrisveness this is not specific to mysql2, mysql-co should probably accept driver instance as a parameter instead of requiring it internally

**Comment by chrisveness** [comment]
Good point – though works fine for me as is :)

**Comment by Redsandro** [comment]
@gajus 
> It would be interesting to test it using the native (0.11.13) promises

@bucaran
> Just in case someone is wondering how to build an example without promisifyAll

Using the `new` keyword is unnecessary overhead and a big no-no in `node`. `Bluebird` promises are much more optimized than the native `Promise` implementation. 

For example, you can `Promise.resolve('something')` and chain from there, never having to use the `new` keyword.

The author spent a lot of time optimizing things. You can read his own explanation here:

[StackExchange: Why are native ES6 promises slower and more memory-intensive than bluebird?](http://programmers.stackexchange.com/questions/278778#279003)

**Comment by robertleeplummerjr** [comment]
I'm trying to do:
```js
import mysql from 'mysql';
import Promise from 'bluebird';
import { co } from 'bluebird-co';
import config from 'config';

co(function* () {
  const pool = mysql.createPool(config.mysql);
  const connection = yield Promise.promisify(pool.getConnection)();
  const query = Promise.promisify(connection.query);
  query('select * from table');
});
```

but keep getting an error thrown:
```js
Unhandled rejection TypeError: this._implyConnect is not a function scripts/node
```

What am I doing wrong?

**Comment by chrisveness** [comment]
My suggestion would be to use mysql2, which now comes complete with a promises wrapper.

You can then do something like:

    const koa = require('koa'); // koa v1
    const mysql = require('mysql2/promise');
    const router = require('koa-router')();
    
    const app = koa();
    const config - require('./config.json');
    const pool = mysql.createPool(config.db); // create pool on app startup
    
    app.use(function* mysqlConnection(next) { // get connection for this request
        this.state.db = yield pool.getConnection();
        yield next;
        this.state.db.release();
    });
    
    router.get('/', function*(next) {
        const [results] = yield this.state.db.query('select * from table');
        console.log(results);
    });
    
    app.use(router.routes());
    
    app.listen(3000);

There is a fuller example on my sample app https://github.com/chrisveness/koa-sample-web-app-api-mysql

**Comment by Redsandro** [comment]
@chrisveness what's your opinion on `mysql2` vs `mysqljs`?

**Comment by chrisveness** [comment]
@Redsandro I think both are very solid, but I've actually only ever used `mysql2` myself. 

For me, `mysql2` coming with a promise wrapper makes it far more convenient (I love async/await) – that may or may not matter to you. If you are focused on performance, you can use bluebird, or stick to callbacks, though I would be surprised if performance of promises was remotely significant against performance of the database library itself – I'd love to see any benchmarks.

I think @sidorares' [summary](https://github.com/mysqljs/mysql/issues/929#issuecomment-95054386) is pretty good.

**Comment by Redsandro** [comment]
@chrisveness thanks for the quick response. I've been using `mysqljs` with `bluebird` anyway, and I have been waiting for prepared statements, which `mysql2` seems to implement. So it sounds good.

I see `mysql2` is in the process of being merged with `mysqljs`. I might take the completion of that as proof of being production ready, for no clear reason.

**Comment by Xstoudi** [comment]
>Using the new keyword is unnecessary overhead and a big no-no in node. Bluebird promises are much more optimized than the native Promise implementation.
For example, you can Promise.resolve('something') and chain from there, never having to use the new keyword.
The author spent a lot of time optimizing things. You can read his own explanation here:
StackExchange: Why are native ES6 promises slower and more memory-intensive than bluebird?`

As you can see on [the V8 project bug reporting](https://bugs.chromium.org/p/v8/issues/detail?id=5343), native promises are on the way.
